### ISSUE TITLE
BlazePose Full Body

### ISSUE THREAD

**Issue by ljmkimqx** [google/mediapipe#1066]
Why does Mediapipe only support the upper body and not the full body? When does Mediapipe support the full body? I know the full body function of ML kit, but I prefer mediapipe to support the full body（I think Mediapipe is very practical and convenient ）

**Comment by mgyong** [comment]
@ljmkimqx I would encourage you to use MLKit if you need the full body for now. Releasing something in MediaPipe might be something we will consider. Thks

**Comment by vpenades** [comment]
@mgyong in our case we're glad to support MLKit on Android and iOS, but our project needs to be available on windows and linux too, for which MLKit is not available. Right now we're considering alternatives.

**Comment by mgyong** [comment]
Windows support is experimental for us. Could you share with me what your project is about?

**Comment by vpenades** [comment]
We've been able to successfully run the upper body model in windows, and it just runs fine.

Our project is for a potential client that wants a virtual coach app. For most use cases, 10fps on mobile is fine, but there's a few specialised cases that might require 30fps, for which we think a PC is better suited (for example, boxing)

**Comment by jiuqiant** [comment]
@vpenades, I assume that you already solved [this Windows issue](https://github.com/google/mediapipe/issues/908#issuecomment-659565309) and ran the upper body model on Windows. Can you post your change in "mediapipe/mediapipe/framework/packet.h" to benefit the other Windows users? Thanks.

**Comment by jiuqiant** [comment]
@vpenades, I assume that you already solved [this Windows issue](https://github.com/google/mediapipe/issues/908#issuecomment-659565309) and ran the upper body model on Windows. Can you post your fix of "mediapipe/mediapipe/framework/packet.h" to benefit the other Windows users? Thanks.

**Comment by vpenades** [comment]
@jiuqiant I'm afraid I cannot help in that issue;  I am developing in C# and using [Emgu.TF](https://github.com/emgucv/emgutf) for TensorFlow Lite inferences. It took me a while to understand how to use the model, I also had a lot of good luck; in the past I was able to run the BlazeFace model in Emgu.TF, but I was not able to run the hand landmarks model.

Certainly, I would have liked to use MediaPipe directly, but since there's no c# bindings for it, it's no use for me.

On Android and iOs, I hope to use the MLkit library through Xamarin c# bindings when they're available.

Regarding your windows issue; if it's compiling on gcc but failing with MS BuildTools... I would file an issue to Microsoft. Maybe it's a bug on their side... or maybe it's yet another STL inconsistency;  Microsoft is notorious when implementing STL in its own way, sometimes with good reasons.

**Comment by PINTO0309** [comment]
Tensorflow.js + BlazePose Full Body
https://www.youtube.com/watch?v=UaWX-nz5gnI

CoreML, TFLite, TF-TRT, OpenVINO
https://github.com/PINTO0309/PINTO_model_zoo

**Comment by sgowroji** [comment]
We are closing this feature request as this is fixed and available in our MediaPipe solutions.
