### ISSUE TITLE
Instantmotiontracking cannot use obj format files，How to make uuu file format ？

### ISSUE THREAD

**Issue by mmm2016** [google/mediapipe#1074]

**Comment by tyrmullen** [comment]
The .uuu format is a simple custom binary format designed to be trivially rendered using OpenGL, so sequenced .obj animations/files (or any other asset format) will need to be parsed into this format in order to be used by MediaPipe.  The LoadAnimation and LoadAnimationAndroid functions in gl_animation_overlay_calculator.cc can be used as reference for how the .uuu format is expected to be loaded.  In brief, the format expects an arbitrary number of animation frames, concatenated directly together, with each animation frame looking like:
HEADER
VERTICES
TEXTURE_COORDS
INDICES
The header consists of 3 int32 lengths, the sizes of the vertex data, the texcoord data, and the index data, respectively.  Let us call those N1, N2, and N3.  Then we expect N1 float32's for vertex information (x1,y1,z1,x2,y2,z2,etc.), followed by N2 float32's for texcoord information (u1,v1,u2,v2,u3,v3,etc.), followed by N3 shorts/int16's for triangle indices (a1,b1,c1,a2,b2,c2,etc.).  This is precisely the data that a glDrawElements call expects, when drawing triangles.

**Comment by mmm2016** [comment]
If I want to use my own obj file, just add the file header?

**Comment by tyrmullen** [comment]
Unfortunately, no-- you'll need to use a script or program to parse the .obj file for the necessary information, and output it into the format above.

**Comment by mmm2016** [comment]
Therefore, we cannot modify the effect we want in this project. Can you open source the script?

**Comment by Whisperd130** [comment]
@tyrmullen  ` followed by N3 shorts/int16's for triangle indices (a1,b1,c1,a2,b2,c2,etc.).`
I found this line to say the uuu model got vertex indices. Which format did obj file used to show indices?

f 1/1/1 2/2/2 4/4/3 3/3/4  
f 3/3/5 4/4/6 6/6/7 5/5/8

f 1/1 2/2 3/3 4/4 
f 5/4 6/1 7/2 8/3 
f 1/4 4/1 6/2 5/3 

These two kind of indices format is what I met. I‘m not sure which I need to use. 

I think maybe is the second one because the uuu format caculate normal information by code not load from uuu file.

Am I right?

**Comment by tyrmullen** [comment]
With the next update of MediaPipe, we're hoping to release our internal obj --> uuu processing tools; so hopefully this will clarify the precise nature of our formats in full detail.

**Comment by sgowroji** [comment]
Hi @mmm2016, Could you please respond if you still looking resolution for the above query. Thanks!
