### ISSUE TITLE
Extracting Output Landmark Coordinate Data and Inputting Non-Live Video on iOS

### ISSUE THREAD

**Issue by js-0528** [google/mediapipe#1096]
Hello! 

I managed to get mediapipe running on iOS. I am able to see the landmarks on my hand live. However, is there a way to extract the landmark coordinates?   Additionally, is there a way to input my own video (not live), and get output coordinates for those?

I know that there is code included in mediapipe iOS that calculates the coordinates, but I do no know where it is stored on the phone or how to access it.  Can anyone help me with this please?

Thank you so much!

**Comment by Gauraviiitian** [comment]
I also have a similar question, I'm trying to build filters using face mesh landmarks and I can also see where the landmarks are processed but just couldn't get how can we use those landmarks in a coordinate system. I'm hoping for someone to come up with its solution.

**Comment by mgyong** [comment]
@js-0528 Can you share what method did you get MediaPipe running in iOS? Did you use tulsi or the bazel build method documented [here](https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/docs/getting_started/building_examples.md#ios)

Regarding accessing the detected hand landmarks, refer to https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/handtrackinggpu/HandTrackingViewController.mm#L43-L48

As for how to use video file as input instead of live video, you can call `[CommonViewController](https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/common/CommonViewController.mm#L107-L115) ` We do not have an example of how to use `self.sourceMode` yet and may release something using it later. However, if you manage to get call` CommonViewController` We love to get example from you

**Comment by js-0528** [comment]
Thank you so much for the reply! We used the bazel method! Regarding accessing the landmarks, we used that code to build the app and run it. Is there anything more specific we should do with it?

**Comment by ahmedAlmasri** [comment]
+1

**Comment by js-0528** [comment]
@mgyong Sorry to bother you again! We were still wondering whether you could help with outputting solely the landmarks from the iOS app instead of the landmark overlay live video on the hand. We used tulsi, and then used the bazel build command line and not XCode to compile the app on an iPhone, and aren't exactly sure where we should edit the code to output just the landmarks. Thank you!

**Comment by sgowroji** [comment]
Hi @js-0528, Could you please respond if you are still looking resolution for the above query. Thanks!

**Comment by js-0528** [comment]
Hello! We ended up extracting the landmarks for our project without using the iOS app, so we are not looking for a solution anymore! Thank you so much for your help though!

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this  issue now.
