### ISSUE TITLE
reinstall Android SDK and NDK using setup_android_sdk_and_ndk.sh on Ubuntu 20.04

### ISSUE THREAD

**Issue by chriswallenwein** [google/mediapipe#1108]
I installed the Android SDK and NDK using setup_android_sdk_and_ndk.sh on my Ubuntu 20.04. I realized that I did a mistake. How do I cleanly uninstall Android SDK and NDK including path variables and everything?

**Comment by jiuqiant** [comment]
They are in your ~/Android/Sdk and ~/Android/Sdk/ndk-bundle. Just delete them. 
The script only sets the path field at https://github.com/google/mediapipe/blob/master/WORKSPACE#L242 and https://github.com/google/mediapipe/blob/master/WORKSPACE#L246. Please remove them.
 Since the script doesn't touch your env variables, you don't need to do anything.
