### ISSUE TITLE
Do you have plan to bring other DL inference engine support to this ?

### ISSUE THREAD

**Issue by sagarsahu27** [google/mediapipe#111]
Are you planning to include support for ONNX, pytorch etc support to this framework or it will be tightly coupled with tf or tflite only ?

**Comment by mgyong** [comment]
@sagarsahu27 MediaPipe TF & TFlite support is due to the support [tf inference calculators](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc) 
 & [tflite inference calculators](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc)Given the limited resources we have, we don't have plans to support other inference engines. We welcome open source community to create inference calculators for other DL inference engines

**Comment by sagarsahu27** [comment]
> @sagarsahu27 MediaPipe TF & TFlite support is due to the support [tf inference calculators](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc)
> & [tflite inference calculators](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc) Given the limited resources we have, we don't have plans to support other inference engines. We welcome open source community to create inference calculators for other DL inference engines

Thanks @mgyong for the information, I just started looking into this and was curious to know. I would like to contribute to this. This looks really promising.
