### ISSUE TITLE
Why the CPU load factor does not reach about 100% on Raspberry Pi 4?

### ISSUE THREAD

**Issue by UchiyKei1320** [google/mediapipe#1115]
Hello.

I'm running a Hand Tracking with CPU-build on my Pi 4.

Looking at the `top` command, the CPU load factor is not approaching 100%. What is the reason?

Maybe it's because the Pi OS is 32bit? But I think there are other reasons.

<img width="638" alt="topコマンド" src="https://user-images.githubusercontent.com/58416528/93038646-8375be80-f680-11ea-88bd-1104cc919adc.png">

**Comment by jiuqiant** [comment]
I apologize that we doesn't have a good answer for your question since MediaPipe doesn't officially support Raspberry Pi yet and we also don't have Raspberry PI devices to reproduce this issue.

**Comment by jiuqiant** [comment]
I apologize that we doesn't have a good answer for your question since MediaPipe doesn't officially support Raspberry Pi yet and we don't have any Raspberry PI devices to reproduce this issue.

I will keep your issue open and hope someone in the oss community who knows this issue better can help you soon.

**Comment by TheBricktop** [comment]
well we could definitely buy You some its cheap and kinda ubiquitous here.
