### ISSUE TITLE
How to add opacity for texture drawn using AnnotationRenderer

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1170]
Hi, 
    I wish to do Iris Coloring.  As of now. I am able to do Iris fill coloring.  But i wish to have some opacity. 
I tried changing shader program in AnnotationRendererCalculator but It is not working.  After setting  
   ```
glEnable( GL_BLEND );
   glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
```  

before GIRender(cc) call in RenderToGpu
and changed gl_FragColor to value less than 1
Output video frame seems broken.  

in Drawing Part (opencv) i tried to add opacity using addWeighted method but it's not working

Can anyone help?

**Comment by mcclanahoochie** [comment]
Unfortunately, opencv (used in annotation calc) doesn't support transparency drawing.

You will have to use another overlay, like the [MaskOverlayCalculator](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/calculators/image/mask_overlay_calculator.cc) , with some constant mask .

This would blend the current annotated image (no transparency) with the original, based on some alpha blend; this should have the same effect as having opacity inside the annotator.

Example graph:
<img width="847" alt="Screen Shot 2020-09-30 at 2 48 19 PM" src="https://user-images.githubusercontent.com/1004136/94743592-7ddcd180-032c-11eb-8cde-514cf7edcbdd.png">

The "All Other Calculators" box is a placeholder for the rest of your graph.

Then **global** opacity is adjusted by 
```
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:opacity_side_packet"
  options {
    [ConstantSidePacketCalculatorOptions] {
      packet { float_value: 0.5 }
    }
  }
}
```

(Different opacity per annotation would require a mask, instead of a const float.)

**Comment by Nvelu048** [comment]
Thanks with check and get back

**Comment by Nvelu048** [comment]
I have updated ConstantSidePacketCalculator to 

```
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:0:num_faces"
  output_side_packet: "PACKET:1:opacity_side_packet"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 1 }
      packet { float_value: 0.5} 
    }
  }
}

```

and added 

```
node {
  calculator: "SidePacketToStreamCalculator"
  input_stream: "TICK:input_video"
  input_side_packet: "opacity_side_packet"
  output_stream: "AT_TICK:opacity_packet"
}

node {
  calculator: "MaskOverlayCalculator"
  input_stream:"VIDEO:0:input_video"
  input_stream:"VIDEO:1:output_video_" // output of IrisAndDepthRendererGpu i.e AnnotationCalculator
  input_stream:"CONST_MASK:opacity_packet"
  output_stream:"IMAGE:output_video" // Final output
}
```

After this changes, my app crashes 
 
What to do

**Comment by Nvelu048** [comment]
@mcclanahoochie 

I have named MaskOverlayCalculator output_stream TAG as per code.

And updated Build file to include Maskoverlay Calculator. 

And app working as expected

So i am closing this issue

Thanks for the support 🙇‍♂️
