### ISSUE TITLE
System.loadLibrary("mediapipe_jni") fails and crashes application

### ISSUE THREAD

**Issue by WaldHabets** [google/mediapipe#1224]
I have followed the steps on the [MediaPipe website](https://google.github.io/mediapipe/getting_started/android_archive_library.html) to build an Android Archive for use with Android Studio and Gradle. Next I followed the steps for the [Hello World! on Android](https://google.github.io/mediapipe/getting_started/hello_world_android.html) tutorial.

However the application crashes without an error when calling the line `System.loadLibrary("mediapipe_jni");` in
```
public class MainActivity extends AppCompatActivity {
    static {
        // Load all native libraries needed by the app.
        System.loadLibrary("opencv_java3");
        System.loadLibrary("mediapipe_jni");
    }

    // Rest of code for MainActivity
    // ....
}
```
The line `System.loadLibrary("mediapipe_jni");` seems to pass without issue. I've also tried to build the AAR with the flag `--fat_apk_cpu=arm64-v8a,armeabi-v7a,x86,x86_64` instead of just `--fat_apk_cpu=arm64-v8a,armeabi-v7a` without success. Additionally, I've cloned and build the [multi-hand tracking example](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example), but it also crashes when calling `System.loadLibrary("mediapipe_jni")`.

I am testing with a Honor 6 device running android 6.0. When I test on virtual device the app throws the following error:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv3Mat20updateContinuityFlagEv" referenced by "/data/app/be.waldhabets.handhab-2/base.apk!/lib/x86/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at be.waldhabets.handhab.MainActivity.<clinit>(MainActivity.java:20)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by FubukiRandeZvous** [comment]
I've encountered the same question.
`
12/13 14:17:26: Launching 'ZERO' on asus ASUS_Z01KD.
Install successfully finished in 9 s 713 ms.
$ adb shell am start -n "com.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 12279 on device 'asus-asus_z01kd-H8AZCY02X9554TH'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/zygote: Late-enabling -Xcheck:jni
V/Monotype: SetAppTypeFace- try to flip, app = com.google.mediapipe.apps.handtrackinggpu
V/Monotype:     Typeface getFontPathFlipFont - systemFont = /data/mt_fonts/0/MYuppyHK-Medium#優皮體
I/zygote: Do partial code cache collection, code=30KB, data=23KB
I/zygote: After code cache collection, code=30KB, data=23KB
I/zygote: Increasing code cache capacity to 128KB
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.handtrackinggpu, PID: 12279
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.handtrackinggpu-QV-YbyYAvU-fIur9_mhEkg==/lib/arm/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6585)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by joeshow79** [comment]
Face the same issue with the android examples, tried several demo apps, all are crashed due to the lack of "aligned_alloc" symbol

$ adb logcat -b crash
12-14 05:31:49.203 20512 20512 E AndroidRuntime: FATAL EXCEPTION: main
12-14 05:31:49.203 20512 20512 E AndroidRuntime: Process: com.google.mediapipe.apps.handtrackinggpu, PID: 20512
12-14 05:31:49.203 20512 20512 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so"...
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1562)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-14 05:31:49.203 20512 20512 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

12-14 05:38:33.575 20581 20581 E AndroidRuntime: FATAL EXCEPTION: main
12-14 05:38:33.575 20581 20581 E AndroidRuntime: Process: com.google.mediapipe.apps.facedetectioncpu, PID: 20581
12-14 05:38:33.575 20581 20581 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.facedetectioncpu-1/lib/arm64/libmediapipe_jni.so"...
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1562)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-14 05:38:33.575 20581 20581 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)


12-14 05:38:49.055 20607 20607 E AndroidRuntime: FATAL EXCEPTION: main
12-14 05:38:49.055 20607 20607 E AndroidRuntime: Process: com.google.mediapipe.apps.holistictrackinggpu, PID: 20607
12-14 05:38:49.055 20607 20607 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.holistictrackinggpu-1/lib/arm64/libmediapipe_jni.so"...
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1562)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-14 05:38:49.055 20607 20607 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)


12-14 05:39:00.784 20633 20633 E AndroidRuntime: FATAL EXCEPTION: main
12-14 05:39:00.784 20633 20633 E AndroidRuntime: Process: com.google.mediapipe.apps.handdetectiongpu, PID: 20633
12-14 05:39:00.784 20633 20633 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.handdetectiongpu-1/lib/arm64/libmediapipe_jni.so"...
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1562)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-14 05:39:00.784 20633 20633 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)


12-14 05:39:07.299 20655 20655 E AndroidRuntime: FATAL EXCEPTION: main
12-14 05:39:07.299 20655 20655 E AndroidRuntime: Process: com.google.mediapipe.apps.iristrackinggpu, PID: 20655
12-14 05:39:07.299 20655 20655 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.iristrackinggpu-1/lib/arm64/libmediapipe_jni.so"...
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1562)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-14 05:39:07.299 20655 20655 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by jizhu1023** [comment]
Hi @jiuqiant  We also encountered the same problem when replacing the AAR file in this project (https://github.com/jiuqiant/mediapipe_face_detection_aar_example) by the AAR file built with the latest version of Mediapipe and run it on the RK3399 platform (Android 8.1): 
  

>   --------- beginning of crash
2020-12-15 16:10:36.897 2692-2692/com.example.myfacedetectionapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myfacedetectionapp, PID: 2692
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.example.myfacedetectionapp-ZrZsB9WLF5P696bhjIeA1w==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.example.myfacedetectionapp.MainActivity.<clinit>(MainActivity.java:50)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2020-12-15 16:10:36.907 2692-2692/com.example.myfacedetectionapp I/Process: Sending signal. PID: 2692 SIG: 9

However, when we run this apk on HUAWEI Kirin 985 (Android 10), everything is fine. When we downgraded Mediapipe to v0.7.5 to build the AAR file (which is the version used in https://github.com/jiuqiant/mediapipe_face_detection_aar_example) and run the built apk on the aforementioned RK3399 platform, it was OK. So this seems to be a new bug introduced in recent versions. @jiuqiant could you figure out this issue? Many thanks in advance!

**Comment by joeshow79** [comment]
> Hi @jiuqiant We also encountered the same problem when replacing the AAR file in this project (https://github.com/jiuqiant/mediapipe_face_detection_aar_example) by the AAR file built with the latest version of Mediapipe (0.8.1) and run it on the RK3399 platform (Android 8.1):
> 
> > --------- beginning of crash
> > 2020-12-15 16:10:36.897 2692-2692/com.example.myfacedetectionapp E/AndroidRuntime: FATAL EXCEPTION: main
> > Process: com.example.myfacedetectionapp, PID: 2692
> > java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.example.myfacedetectionapp-ZrZsB9WLF5P696bhjIeA1w==/lib/arm64/libmediapipe_jni.so"...
> > at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> > at java.lang.System.loadLibrary(System.java:1657)
> > at com.example.myfacedetectionapp.MainActivity.(MainActivity.java:50)
> > at java.lang.Class.newInstance(Native Method)
> > at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
> > at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
> > at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
> > at android.app.ActivityThread.-wrap11(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:164)
> > at android.app.ActivityThread.main(ActivityThread.java:6494)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> > 2020-12-15 16:10:36.907 2692-2692/com.example.myfacedetectionapp I/Process: Sending signal. PID: 2692 SIG: 9
> 
> However, when we run this apk on HUAWEI Kirin 985 (Android 10), everything is fine. When we downgraded Mediapipe to v0.7.5 to build the AAR file (which is the version used in https://github.com/jiuqiant/mediapipe_face_detection_aar_example) and run the built apk on the aforementioned RK3399 platform, it was OK. So this seems to be a new bug introduced in recent versions. @jiuqiant could you figure out this issue? Many thanks in advance!

Yes, I observed the same. Older version mediapipe built multihandtracker runs on android7.1, when I update mediapipe to latest, the apk crash due to the issue discussed in this topic. I tried another huawei Android10.0 phone whith the most latest apk, everything works fine.

**Comment by WaldHabets** [comment]
I was able to solve my original issue by defining the api-level for the NDK in the workspace folder.
`
android_ndk_repository(
    name = "androidndk",
    api_level = 21, <-- add this
 )
`
As was mentioned in [this comment](https://github.com/google/mediapipe/issues/178#issuecomment-547619564)
My appologies, I forgot to update the issue. Can you guys see if this solution works for you?

**Comment by jizhu1023** [comment]
@WaldHabets Yes, adding "api_level=21" solved my problem. Many thanks!

**Comment by mczha** [comment]
> Hi @jiuqiant We also encountered the same problem when replacing the AAR file in this project (https://github.com/jiuqiant/mediapipe_face_detection_aar_example) by the AAR file built with the latest version of Mediapipe (0.8.1) and run it on the RK3399 platform (Android 8.1):
> 
> > --------- beginning of crash
> > 2020-12-15 16:10:36.897 2692-2692/com.example.myfacedetectionapp E/AndroidRuntime: FATAL EXCEPTION: main
> > Process: com.example.myfacedetectionapp, PID: 2692
> > java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.example.myfacedetectionapp-ZrZsB9WLF5P696bhjIeA1w==/lib/arm64/libmediapipe_jni.so"...
> > at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> > at java.lang.System.loadLibrary(System.java:1657)
> > at com.example.myfacedetectionapp.MainActivity.(MainActivity.java:50)
> > at java.lang.Class.newInstance(Native Method)
> > at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
> > at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
> > at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
> > at android.app.ActivityThread.-wrap11(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:164)
> > at android.app.ActivityThread.main(ActivityThread.java:6494)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> > 2020-12-15 16:10:36.907 2692-2692/com.example.myfacedetectionapp I/Process: Sending signal. PID: 2692 SIG: 9
> 
> However, when we run this apk on HUAWEI Kirin 985 (Android 10), everything is fine. When we downgraded Mediapipe to v0.7.5 to build the AAR file (which is the version used in https://github.com/jiuqiant/mediapipe_face_detection_aar_example) and run the built apk on the aforementioned RK3399 platform, it was OK. So this seems to be a new bug introduced in recent versions. @jiuqiant could you figure out this issue? Many thanks in advance!

你怎么解决的，在哪里添加api 21 需要重新编译aar吗

**Comment by liufsd** [comment]
+1

**Comment by mauricewells** [comment]
Hi, @WaldHabets 
can you please tell me where I can find workspace folder
as you know, i can't fnid any workspace folder in my android studio project

**Comment by vietnt-uet** [comment]
Does anyone still face the issue even adding api_level = 21 to the android_ndk_repository?

**Comment by merthankavak** [comment]
> > 
> 
> Where should I place this code?

Did you find?
