### ISSUE TITLE
Switch the graphic renderer on/off programmatically.

### ISSUE THREAD

**Issue by salvadorld0** [google/mediapipe#1247]
Hi!
I am working in a project that uses the multihand-tracking calculator.  It is working fine, but now I need to sometimes switch “on” and “off” the graphic renderer. I mean, I need the video to sometimes highlighting my hand, and sometimes to only show the video without processing, but still keep the detecting process active the whole time. I was wondering if there is a way to do this programmatically.
Any help would be appreciated.

**Comment by aaaron7** [comment]
Maybe you could do it in this way:

1. Add an input stream to your graph which represents the on/off signal.
2. Create a new calculator and place it between Detection and AnnotationRender calculator, the calculator should takes two input: step1 signal and detection result  stream, 1 output: detection result.
3. Every time the calculator received detection result, check the step1 signal(on/off) to decide whether it need be pass to next calculator(AnnotationRender)
4. Do not forget configure your calculator's input stream policy, use ImmediateStreamHandler instead of default one to prevent unexpected sync in this scenario.
5. Then you could switch annotation render on/off by send according signal packet to graph.

**Comment by sgowroji** [comment]
Hi @salvadorld0, Could you please reply whether you're still looking for the above query. Thanks!
