### ISSUE TITLE
Getting the size of Sneakers using Objectron

### ISSUE THREAD

**Issue by ReqWrecker** [google/mediapipe#1264]
I need to figure out how to calculate the size of Sneakers (length/width), as mentioned in the Objectron documentation. Is there any way to get these output directly or I have to write any specific calculators to extract the relevant bounding box coordinates and then need to perform scaling to get correct measurement? Any kind of help would be appreciated.
Happy coding :)

**Comment by ahmadyan** [comment]
We compute the scale of the box (from the 3D vertices) in the [AnnotationToModelMatrices calculator](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.cc#L179), but it is not directly exported to the user level via any API (only the orientation and position are). You can export it by adding new output streams to that calculator and subsequently to your graph. 

Since there are some interest, we might expose the size via a public API in the future.

**Comment by ReqWrecker** [comment]
Thanks for great explanation. I would like to know more about this like, how I can access that output stream at android end by using AAR. Do I need to create separate proto buff or it is possible to access with existing one. One more thing, How I can access other proto buff present inside the Objectron calculators using AAR only. Any code snippet would be helpful for me.

**Comment by sgowroji** [comment]
Hi @ReqWrecker, We don't have any direct code. you can try creating Android AAr for objectron from here https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive
