### ISSUE TITLE
node execution parallel not working

### ISSUE THREAD

**Issue by liyuming1978** [google/mediapipe#131]
I am in modify the facedetection_cpu example,  I need a fast render but a slow facedetection (for low cpu cost as most as possible), I change the pbtxt as:
I add RoundRobinDemuxCalculator to demux two, and add usleep(200*1000) in TfLiteTensorsToDetectionsCalculator process.

but the render is slow too!!!
as doc says: even no RoundRobinDemuxCalculator , the node will be parallel executing, so how to fix this ?

any one knows ,  thx! so much

--------------------------------------------------------------------------
node {
  calculator: "RoundRobinDemuxCalculator"
  input_stream: "input_video"
  output_stream: "OUTPUT:0:input_video_second"
}

# Crops the rectangle that contains a hand from the input image.
node {
  calculator: "ImageCroppingCalculator"
  input_stream: "IMAGE_GPU:input_video"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageCroppingCalculatorOptions] {
      width: 300
      height: 300
    }
  }  
}

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_second"
  input_stream: "FINISHED:detections"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

**Comment by hadon** [comment]
Hi Li,

It sounds like you want to run the tensorflow-model for face-detection twice in parallel in order to process twice as many frames per second.  Please confirm that this is your goal.  

The RoundRobinDemuxCalculator can indeed be used for this purpose.  In face_detection_mobile_cpu.pbtxt , one detail to be aware of is that the FlowLimiterCalculator limits the number of frames that can be processed in parallel.  The default options for FlowLimiterCalculator limit the graph to one frame at a time.  In order to process two frames at a time you would need to: 

(1) on the FlowLimiterCalculator set the option "MAX_IN_FLIGHT" to "2".  
(2) add a second copy of the TfLiteInferenceCalculator and its associated calculators.
(3) add a RoundRobinDemuxCalculator sending frames to the two TfLiteInferenceCalculators.
(4) add a MuxCalculator combining the output streams from the two TfLiteInferenceCalculators.

It is best to sequence the RoundRobinDemuxCalculator after the FlowLimiterCalculator in order to accept one additional input frame when each TfLiteInferenceCalculator finishes processing.  

-- Best Wishes, /-/adon

**Comment by liyuming1978** [comment]
sorry for long delay, too many works. 
I have a requirement that draw camera image ASAP,  but it can has slow face detection output (since 3399 gpu-cpu buffer copy is slow). so I change the pbtxt as below, the RoundRobinDemuxCalculator  not meet my requirement.
A:
input_video->gpu crop-> output_video
output_video->flowlimit->facedetecion->output float vector for face detection result.
it will crash in gsync point release

B:
input_video->flowlimit->gpu_crop->detection
gpu_crop->output_video
it will crash for 5~6 hours in externel_render , I think it's because when output-video render , the flowlimt change the input buffer since it only waits detection.

c:
input_video->flowlimit (wait output_video)->gpu_crop->output_video
gpu_crop->flowlimit->gpu_crop->detection
in testing...

so I want to know how to get the right to split gpu_render with cpu_detection?   3399 gpu limitation, can not use gpu version

**Comment by liyuming1978** [comment]
@mgyong sorry for long delay, my purpose is split gpu_render with cpu_detection, to make the render ASAP in rockchip 3399.  hope your kindly reponse.
and  I find mediapipe seems has memory leak in android (rockchip 3399 and Qalcomm 660)

**Comment by liyuming1978** [comment]
@hadon  hope your kindly response

**Comment by Bakashaka** [comment]
Hello!! I want to make my custom calculator execute parallelly. I found "[max_in_flight](https://github.com/google/mediapipe/tree/master/mediapipe/framework/calculator.proto)" that can make it work in the doc,
so I changed my calculator graph content like this:
original:
input_stream: "text"
output_stream: "bs"

node {
calculator: "Text2SpeechCalculator"
input_stream: "text"
output_stream: "speech"
}

node {
calculator: "Audio2BsCalculator"
input_stream: "speech"
output_stream: "bs"
}

now:

input_stream: "text"
output_stream: "bs"

node {
calculator: "Text2SpeechCalculator"
input_stream: "text"
output_stream: "speech"
max_in_flight: 2
}

node {
calculator: "Audio2BsCalculator"
input_stream: "speech"
output_stream: "bs"
max_in_flight: 2
}

But it didn't work, I don't know why,
When I input text twice, the workflow in the log is "Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process()" rather than my expected result that "Text2SpeechCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Audio2BsCalculator::Process()" .

**Comment by LiuYi-Up** [comment]
> Hello!! I want to make my custom calculator execute parallelly. I found "[max_in_flight](https://github.com/google/mediapipe/tree/master/mediapipe/framework/calculator.proto)" that can make it work in the doc, so I changed my calculator graph content like this: original: input_stream: "text" output_stream: "bs"
> 
> node { calculator: "Text2SpeechCalculator" input_stream: "text" output_stream: "speech" }
> 
> node { calculator: "Audio2BsCalculator" input_stream: "speech" output_stream: "bs" }
> 
> now:
> 
> input_stream: "text" output_stream: "bs"
> 
> node { calculator: "Text2SpeechCalculator" input_stream: "text" output_stream: "speech" max_in_flight: 2 }
> 
> node { calculator: "Audio2BsCalculator" input_stream: "speech" output_stream: "bs" max_in_flight: 2 }
> 
> But it didn't work, I don't know why, When I input text twice, the workflow in the log is "Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process()" rather than my expected result that "Text2SpeechCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Audio2BsCalculator::Process()" .

Hi, did you solve this problem yet?

**Comment by LiuYi-Up** [comment]
> face_detection_mobile_cpu

Hi, excuse me. I want to make hand_tracking_desktop_live.pbtxt in multi threads so that I can detect two or more cameras in parallel. This is very hard to me to understand what I should fix it and how to use it. Could you give some advices to me?

It's thankfull very much if I can get your reply.

Best wishes!
