### ISSUE TITLE
Mediapipe HandTrackingGpu iOS build fails

### ISSUE THREAD

**Issue by bushixingan** [google/mediapipe#135]
hello, when I learn Hand Tracking with Gpu,i got some questions .Firstly,when I use tulsi to generate MediaPipe,an error occurred
ERROR: An error occurred during the fetch of repository 'local_config_git':
ERROR: /private/var/tmp/_bazel_shenming/0f5d0daefd6f87499857aa68c4ad73ed/external/org_tensorflow/tensorflow/core/BUILD:2785:1: @org_tensorflow//tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):

And then when I run the HandTrackingGpu demo ,an error occurred /mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: no such package 'mediapipe/mediapipe/examples/ios': BUILD file not found in any of the following directories.
Could u help me to solve them?

**Comment by yujie-tao** [comment]
I have the same problem, are you able to fix it?

**Comment by yujie-tao** [comment]
I fixed the issue, it's out of the problem of the invalid provision file for my case.

**Comment by mgyong** [comment]
@bushixingan This might be a network connection issue. Can u ensure you have VPN turned on the ensure no network interference issue for China?

**Comment by norman452003** [comment]
I meet the same problem when i use tulsi to generate the project.It toast ERROR: An error occurred during the fetch of repository 'local_config_git':ERROR:  .
Then i start to research bazel tool and i download the simple of bazel.I try to run the simple but failure because my python version is 2.7. I update my python.Then i found i can build HandTrackingGpu.ipa by the common line.Then I find I can use tulsi to build the project success.
