### ISSUE TITLE
Integrating CoreML Model With Mediapipe IOS

### ISSUE THREAD

**Issue by sarvnazale** [google/mediapipe#1350]
Hi!

I'm trying to import my own CoreML Model onto the Mediapipe Xcode project, specifically to feed the landmarks generated in HandTrackingViewController.mm to the model. When I import the model, it asks me to choose a target. However, none of the actual targets are available for me to choose, and so I am not able to generate a model class. Would anyone know how to solve this issue? I'm not sure why I can't just check off HandTrackingGpuApp as an option. 

Thank you so much! 

The targets on top are all grey/unavailable: 
![Screen Shot 2020-11-29 at 11 16 38 AM](https://user-images.githubusercontent.com/55462526/100547362-5c1c9f80-3234-11eb-8af6-8b96e1451cfc.png)

I am unable to generate a model class because I can't choose a target: 
![Screen Shot 2020-11-29 at 11 18 13 AM](https://user-images.githubusercontent.com/55462526/100547410-9423e280-3234-11eb-948e-b24dc25a3b27.png)

**Comment by danhd123** [comment]
You might be able to add the .mlmodel file to the BUILD file for one of the example projects, and then regenerate the .xcodeproj. Otherwise, I would suggest building mediapipe as a framework and adding it to your own project along with the .mlmodel. You could also try adding the .mlmodel to another project, and copy the generated classes into one of these projects, same as you would any other class.

**Comment by sarvnazale** [comment]
@danhd123 thank you for your response! I am very new to this, so I'm not sure how I would go about trying some of the things you recommended. How would adding it to a BUILD file be different? Thank you!

**Comment by sgowroji** [comment]
Hi @sarvnazale, Could you please respond if you are still looking resolution for the above query. Thanks!
