### ISSUE TITLE
error when using python inference

### ISSUE THREAD

**Issue by flynnamy** [google/mediapipe#1368]
How to solve like this? I build from source of master branch. 
ImportError: /usr/local/lib/python3.6/dist-packages/mediapipe/python/_framework_bindings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: ippicviNormRel_L1_16u_C1R

**Comment by jiuqiant** [comment]
Looks like it's an opencv issue that is similar to https://stackoverflow.com/questions/27491041/opencv-unresolved-external-symbol. 

The error is related to the missing Intel IPP supporting library, which is needed by OpenCV. How do you install OpenCV and link it to mediapipe?

**Comment by flynnamy** [comment]
I execute setup_opencv.sh this file to install opencv. @jiuqiant

**Comment by jiuqiant** [comment]
Seems like the set_opencv.sh script doesn't work well on your machine. You can try to add `-DWITH_IPP=OFF` at https://github.com/google/mediapipe/blob/master/setup_opencv.sh#L67 to disable IPP and rebuild the opencv library to see if it helps. Otherwise, you can use package manager to install opencv to your system directly.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
