### ISSUE TITLE
Poorly Documented and vague code

### ISSUE THREAD

**Issue by Zumbalamambo** [google/mediapipe#1375]
The documentation is too poor and unusable. There are many issues where there is a demand for the documentation but no proper documentation at all thus far.

**Comment by mgyong** [comment]
Appreciate if you could be more precise with the comment. Thanks

**Comment by AntonioDomenech** [comment]
I don't think that @Zumbalamambo explained the issue in a proper maner, so I'll try to elavorate:

It's true that, although MediaPipe's documentation has improved largely since release 8.0.0, it still lacks many things. I now speak for the python documentation which is the one I'm currently using. It's true there is an example posted for each solution but there is now information regarding each internal function. For example, how does hands.process work? (also applyes to pose.process or holistic.process) to get the landmarks you have to keep figuring out how they are stored. For example in the case of Holistic, if I want to extract just the left hand thumb landmarks, what do I do? I know there is a way, but there is no documentation at all and I have to use the method try and error until I understand how the code works. This happens with other thinks.

In general the examples you provide are very good, but we need more information of how the internal functions of MediaPipe work and how can we use them properly

I hope I made myself clear,

Thank you very much and keep rocking!!!

**Comment by sgowroji** [comment]
Hi @Zumbalamambo  & @AntonioDomenech, Thank you for bringing this to our notice. We are improving our documentation  much better with every release. Please reach us with any suggestions you wanted us to add in the latest  documentation, we will be happy to consider and we also encourage your contribution in PR.
