### ISSUE TITLE
From face mesh landmarks, via face geometry to metric landmarks, to world model 

### ISSUE THREAD

**Issue by Rassibassi** [google/mediapipe#1379]
Hi,

thanks for mediapipe and all the hard work that has been put in. I'm working on a little project where I'd like to get the face mesh landmarks into a world model via the intrinsic/extrinsic camera calibration. 

From the cv2 camera calibration, I have obtained intrinsic `camera_matrix`, `dist_coeff` and extrinsic `rvecs`, `tvecs` numerical values. [As described here](https://nikatsanka.github.io/camera-calibration-using-opencv-and-python.html) and [here](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#calibrationmatrixvalues)

From the [Python solution of the face mesh mediapipe](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_mesh.py), I have obtained the landmarks of a face and am planning on plugging them into the face geometry module. The face geometry module then provides metrics landmark values. From these metric values, I think I should somehow be able to get to my world model via the extrinsic camera values.

I'm still working on getting the metric landmark values out of the face geometry module. However, I'm confused about the role of the virtual `PerspectiveCameraFrustum` and how it relates to the real camera (which was calibrated above).

The `PerspectiveCameraFrustum` requires 4 properties, the `perspective_camera.near()`, `perspective_camera.vertical_fov_degrees()`, `frame_width` and `frame_height`, as found in [here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc)

From the `camera_matrix`, I am able to calculate the `vertical_fov_degrees`, as found [here](https://stackoverflow.com/questions/39992968/how-to-calculate-field-of-view-of-the-camera-from-camera-intrinsic-matrix), and in Python:

```python
rad2deg = 180 / np.pi
fov_y = 2 * np.arctan(frame_height / (2 * camera_matrix[1,1])) * rad2deg
```

However, I am puzzled what to choose for `perspective_camera.near()`. Also, do `frame_width` and `frame_height` refer to the frame of the camera (1920 x 1080) or to the frame passed into the face mesh DNN (192 x 192).

Next, when `PerspectiveCameraFrustum` is defined, I understood the steps to obtain the metric landmark values, but how to get to the world model. Is the virtual camera of the metric landmark values assumed to be centered in the middle of the frame and pointing along the -Z axis, as shown [here](https://google.github.io/mediapipe/images/face_geometry_metric_3d_space.gif)? Does this mean, one has to apply a camera motion to the virtual camera according to the extrinsic camera calibration (`rvecs`, `tvecs`) to get to the world model?

Any light shed on my problems, or links where I can read more about these topics are highly appreciated! If this is a feature other people might be interested in, I'm happy to build a mediapipe module after solving it.

Thanks <3,
Rasmus

**Comment by kostyaby** [comment]
Hey @Rassibassi,

Thanks for reaching out! I'll try to address your questions this reply

> However, I'm confused about the role of the virtual `PerspectiveCameraFrustum` and how it relates to the real camera

I'll try to explain help you with the internals, but overall - `PerspectiveCameraFrustum` (or anything that you find in the anonymous namespace of a `.cc` file) is not a part of the public API and thus it's by design less documented, not guaranteed to stay the same over time and can generally be more "fuzzy"

> I am puzzled what to choose for perspective_camera.near()

The public API of the Face Geometry module requires to establish the so-called *environment* upon initialization ([proto format](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/environment.proto)), which includes parameters for the virtual camera. 

Real-world physical camera don't "clip" objects, but virtual cameras do ([good overview](http://www.songho.ca/opengl/gl_projectionmatrix.html)). Thus, you need to provide *some* reasonable arguments for the near and far clipping planes; I'd expect you to define them once and then just keep using the same values all the time.

Given that the face geometry space is metric (in centimeters), using the current default params from the face effect demo ([link](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_effect/face_effect_gpu.pbtxt#L54-L55)) will clip anything which is closer than 1cm and further than 100m. These values ensure internal math to be numerically stable + I don't think face landmark detection will even work for a person 100m away from the camera. If that's not true in your case, consider updating `far: 10000.0` to some bigger number, but beware of the possible Z-fighting (also described in that good virtual camera overview)

> do frame_width and frame_height refer to the frame of the camera (1920 x 1080)

**Comment by kostyaby** [comment]
Hey @Rassibassi,

Thanks for reaching out! I'll try to address your questions in this reply

---

> However, I'm confused about the role of the virtual `PerspectiveCameraFrustum` and how it relates to the real camera

I'll try to help you with the internals, however please keep in mind that `PerspectiveCameraFrustum` (or anything that you find in the anonymous namespace of a `.cc` file) is not a part of the public API and thus it's by design less documented, not guaranteed to stay the same over time and can generally be more "fuzzy"

> I am puzzled what to choose for perspective_camera.near()

The public API of the Face Geometry module requires to establish the so-called *environment* upon initialization ([proto format](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/environment.proto)), which includes parameters for the virtual camera. 

Real-world physical camera don't "clip" objects, but virtual cameras do ([good overview](http://www.songho.ca/opengl/gl_projectionmatrix.html)). Thus, you need to provide *some* reasonable arguments for the near and far clipping planes; I'd expect you to define them once and then just keep using the same values all the time.

Given that the face geometry space is metric (in centimeters), using the current default params from the face effect demo ([link](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_effect/face_effect_gpu.pbtxt#L54-L55)) will clip anything which is closer than 1cm and further than 100m. These values ensure internal math to be numerically stable + I don't think face landmark detection will even work for a person 100m away from the camera - thus I encourage you to give them a try as-is. If those won't work in your case, consider updating `far: 10000.0` to some bigger number, but beware of the possible Z-fighting (also described in that good virtual camera overview)

> ...do frame_width and frame_height refer to the frame of the camera (1920 x 1080) or to the frame passed into the face mesh DNN (192 x 192)

Those are taken from the input image dimensions (not the DNN input dims) that you pass into the calculator / geometry pipeline. Again, in the public API you don't need to worry about that as it's done automatically via graph configuration 

> Is the virtual camera of the metric landmark values assumed to be centered in the middle of the frame and pointing along the -Z axis, as shown here? 

Yes

On a related note, our matrix model doesn't cover [principal points](https://en.wikipedia.org/wiki/Pinhole_camera_model#The_geometry_and_mathematics_of_the_pinhole_camera) of the camera. From my experience, those principal points are usually *very close* to the frame center, i.e. most cameras are centered well; you can rarely come across a camera whose principal point is far from the frame center. Having said that, I'd encourage you to simply ignore the principal points for now assuming those are `(0, 0)`. If the precision will be a bottleneck, please comment here and we'll plan adding principal points to our virtual camera model

> Does this mean, one has to apply a camera motion to the virtual camera according to the extrinsic camera calibration (rvecs, tvecs) to get to the world model?

Yes. Apply whatever extrinsics you have to the matrix & to the metric landmarks as well

**Comment by Rassibassi** [comment]
Thank you very much for all your comments. It already helps a lot. 

I still have 2-3 more questions while I also made progress on plugging the screen landmarks into the face geometry module.

So, if one sets `camera_perspective.near()` to 1cm, then the metric landmark values are projected on a plane with the distance of 1cm away from the virtual camera. If one assumes the person is 60cm away from the camera, one has to project that near plane to the plane at 60cm before applying any extrinsic camera rotation/translation to obtain the world model. Is my thinking correct here?

I understand the problem regarding Z-fighting, however, the application I have in mind, assumes the person to be max ~80cm away from the camera. The `.far()` property of the virtual camera is never actually used while calculating the metric landmarks, but only in the `effect_renderer.cc`. So my guess is that `.far()` somehow has to play a role when I project the near plane to the plane at 60cm as desribed in the previous paragraph.

We can actually get more explicit, I have implemented the face geometry pipeline in numpy and tested it against the cpp code. All can be found in this repository [here](https://github.com/Rassibassi/mediapipeFacegeometryPython). [This iPython notebook](https://github.com/Rassibassi/mediapipeFacegeometryPython/blob/main/metric_landmarks_to_world_model.ipynb) is basically where I am stuck. I have the metric landmarks and my camera calibration and what now? How to get to the world model :(

I still have to read the "[good overview](https://www.songho.ca/opengl/gl_projectionmatrix.html)" in detail, so maybe the answer is in there. If so, just say so and I'll crack on with that.

Thanks again, big help! Highly appreciated.

**Comment by kostyaby** [comment]
> So, if one sets camera_perspective.near() to 1cm, then the metric landmark values are projected on a plane with the distance of 1cm away from the virtual camera. If one assumes the person is 60cm away from the camera, one has to project that near plane to the plane at 60cm before applying any extrinsic camera rotation/translation to obtain the world model. Is my thinking correct here?

`camera_perspective.near()` affects face depth estimation within the face geometry module in a very small, insignificant way. I can confirm that inside the pipeline values are multiplied / divided by `camera_perspective.near()` equal number of times - meaning, that does not affect the final result directly

Two major factors that affect the face depth estimation within the face geometry module are 1) canonical face model and 2) predicted face landmark locations. Camera FOV does affect the result in a significant way as well, but not as much as the canonical face model

Having said that, it doesn't matter if one assumes the person is 60cm away from the camera - just apply your extrinsics to the world model and it should be fine

> I understand the problem regarding Z-fighting, however, the application I have in mind, assumes the person to be max ~80cm away from the camera. The .far() property of the virtual camera is never actually used while calculating the metric landmarks, but only in the effect_renderer.cc. So my guess is that .far() somehow has to play a role when I project the near plane to the plane at 60cm as desribed in the previous paragraph.

You are correct that `far` is never used in the geometry estimation pipeline is only needed to set up a virtual perspective projection camera in the effect renderer

> We can actually get more explicit, I have implemented the face geometry pipeline in numpy and tested it against the cpp code. All can be found in this repository here. This iPython notebook is basically where I am stuck. I have the metric landmarks and my camera calibration and what now? How to get to the world model :(

I skimmed through the repo / notebook; there's quite a lot of code there, so I won't get a chance to familiarize myself with all of it - sorry about that. One thing I noticed so far: I don't think that passing the `fy = np.array(data['camera_matrix'])[1,1]` as-is a good idea as long as as `fx = np.array(data['camera_matrix'])[0,0]` is not equal to 1. I'd say you need some sort of normalization

**Comment by Rassibassi** [comment]
Hi again,

thanks a bunch. I think it all works now. At least the numpy face geometry implementation. If it helps anyone in the future, for an example [see here](https://github.com/Rassibassi/mediapipeFacegeometryPython/blob/main/head_posture_rt.py).

One last question:
When comparing the rotation part of the `pose_transform_mat` obtained from the face geometry implementation with the pose rotation calculated by cv2.solvePnP, the bottom two rows have their sign flipped. Any idea why they are not identical?
```
pose_transform_mat[:3,:3]:
[[ 0.87025447  0.0039611   0.49258651]
 [ 0.03988128  0.99611855 -0.07846862]
 [-0.49098538  0.08793265  0.86671864]]
```

```
cv2.Rodrigues(rotation_vector)[0]:
[[ 0.87025447  0.0039611   0.49258651]
 [-0.03988128 -0.99611855  0.07846862]
 [ 0.49098538 -0.08793265 -0.86671864]]
```
where
```
_, rotation_vector, translation_vector = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeff, flags=cv2.cv2.SOLVEPNP_ITERATIVE)
```
Thanks again, and feel free to close this issue :)

**Comment by kostyaby** [comment]
I'm glad it worked out for you!

On the matrix rows being "flipped": hard to tell, but it might one of the following reasons:

- `cv2.solvePnP` could allow mirroring along some of the axis to find a better fit in L2 error terms, while MediaPipe's `ProcrustesSolver` bans this sort of possibility explicitly
- `cv2.solvePnP` could find you a rotation group in the left-handed 3D space, while MediaPipe's `ProcrustesSolver` is explicitly finding a rotation group in the right-handed 3D space
- Input landmarks could be flipped along some of the axis between your approach and the original FaceGeometry approach

It's really hard to tell what exactly causes the discrepancy; I guess it's only up to you to try different ideas that might help to shed light on what's really going on

**Comment by ianni67** [comment]
...
> One last question:
> When comparing the rotation part of the `pose_transform_mat` obtained from the face geometry implementation with the pose rotation calculated by cv2.solvePnP, the bottom two rows have their sign flipped. Any idea why they are not identical?
> 
> ```
> pose_transform_mat[:3,:3]:
> [[ 0.87025447  0.0039611   0.49258651]
>  [ 0.03988128  0.99611855 -0.07846862]
>  [-0.49098538  0.08793265  0.86671864]]
> ```
> 
> ```
> cv2.Rodrigues(rotation_vector)[0]:
> [[ 0.87025447  0.0039611   0.49258651]
>  [-0.03988128 -0.99611855  0.07846862]
>  [ 0.49098538 -0.08793265 -0.86671864]]
> ```
> 
> where
> 
> ```
> _, rotation_vector, translation_vector = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeff, flags=cv2.cv2.SOLVEPNP_ITERATIVE)
> ```
> 
> Thanks again, and feel free to close this issue :)
Sorry for resuming a closed post, but I felt this might help.
I might be completely wrong here, but it seems that in mediapipe x and y axes are flipped w.r.t. opencv, consequently, both rotation vector and translation vector have some signs flipped as well.
