### ISSUE TITLE
Mediapipe Javascript - Is there a way to pass canvas object instead of a video tag element?

### ISSUE THREAD

**Issue by Saltb0xApps** [google/mediapipe#1388]
https://google.github.io/mediapipe/solutions/hands

It's more easier for all developers to pass a canvas object to the ml model instead of a video element. Specifically talking about this function -
`hands.send({image: videoElement});`

Canvas object can be used to represent a static image, or the data being received in real time from the camera.
Any ideas on how this can be done?

**Comment by mhays-google** [comment]
Thank you!  We definitely need more ways to pass inputs.  Will add this
very soon.

**Comment by mhays-google** [comment]
I wrote a quick test to add support for HTMLImageElement,
HTMLCanvasElement, and HTMLVideoElement as inputs with success.  I need to
do some diligence around this, but I'll have that functionality to the
public soon.  I think MediaStream will be a thing soon, as well, so let me
check with some folks to see what we want to do.

Thank you for bringing this up!

**Comment by datvm** [comment]
Currently how do you use a single image as input? I can't seem to load an image file or canvas to a video element. The `Camera` part is quite mysterious, I cannot find their source code to see how.

**Comment by Saltb0xApps** [comment]
@mhays-google thank you for the quick response. Looking forward to some sample code or steps on how to make it work! :) 

Based on personal experience, the earlier hand tracking version running on tfjs (https://github.com/tensorflow/tfjs-models/tree/master/handpose) also used canvas as a parameter, so supporting that will make it easy for developers to switch over to this far more superior mediapipe version easily!

**Comment by Jorres** [comment]
Hey, @mgyong, I was wondering how is it going with that piece of functionality? It just so happens that mediapipe hands recognition is a superior solution to the one I use in my work right now, but I desperately need a way to supply single picture to the framework. Is there any estimate on how close the implementation is?)

**Comment by datvm** [comment]
Currently I am using this workaround: Use a renderer like ffmpeg (a bit big and slow) or [Whammy](https://github.com/antimatter15/whammy) to render a single picture into webm video to put it in as input. It's not desirable and quite slow, but at least it works for now.

**Comment by mhays-google** [comment]
Hey everyone, thanks for the patience.

I have staged a new version of hands that has this capability.  I will be
staging the other apis very soon.  For the moment, HTMLImageElement,
HTMLCanvasElement, and HTMLVideoElement are all supported for the hands
API.  You should not need to do _anything_ other than point 'image' to the
element reference.

```
    await solution.send({'image': image});
```

I'm not done with this issue yet.  I still need to stage the other
solutions, and I kind of need to make an example that actually demonstrates
exactly what you are trying to do.

--Michael

**Comment by DrhF** [comment]
@mhays-google Hello!
Thank you for the new version of mediapipe hands for js! I've tried to use it in my project, installed the version from npm, but got several issues:
```Uncaught SyntaxError: Unexpected identifier
hands_solution_wasm_bin.js:1 Uncaught SyntaxError: Unexpected identifier
./node_modules/@mediapipe/hands/hands.js:28 Uncaught (in promise) TypeError: g is not a function
    at ja.h (./node_modules/@mediapipe/hands/hands.js:28)
    at U (./node_modules/@mediapipe/hands/hands.js:10)
    at na.next (./node_modules/@mediapipe/hands/hands.js:11)
    at k (./node_modules/@mediapipe/hands/hands.js:22)
(anonymous) @ /./node_modules/@mediapipe/hands/hands.js:28
U @ /./node_modules/@mediapipe/hands/hands.js:10
next @ /./node_modules/@mediapipe/hands/hands.js:11
k @ /./node_modules/@mediapipe/hands/hands.js:22
Promise.then (async)
g @ /./node_modules/@mediapipe/hands/hands.js:22
(anonymous) @ /./node_modules/@mediapipe/hands/hands.js:22
X @ /./node_modules/@mediapipe/hands/hands.js:22
Z.send @ /./node_modules/@mediapipe/hands/hands.js:45
predict @ test_mediapipe.js? [sm]:98
(anonymous) @ test_mediapipe.js? [sm]:90
sentryWrapped @ helpers.ts:87
load (async)
(anonymous) @ trycatch.ts:185
(anonymous) @ instrument.ts:421
putImageOnCanvas @ test_mediapipe.js? [sm]:86
(anonymous) @ test_mediapipe.js? [sm]:80
emit @ events.js:182
EventEmitter.emit @ domain.js:442
topLevelDomainCallback @ domain.js:121```

Due to obfuscation of the source code it's nearly impossible to get where is the error without your help. 
I'm ready to provide any extra information needed. Thank you once again!

**Comment by Jorres** [comment]
Hello @mhays-google! I'm experiencing issues quite different to @DrhF's issues. I'm instantiating hands object as follows:
```typescript
import {Hands} from "@mediapipe/hands/hands";
const hands = new Hands({locateFile: (file: string) => {
    return "file:///my_node_prefix/node_modules/@mediapipe/hands/" + file;
}});
```
I've attached a handler to hands.onResults:
```typescript
hands.onResults(console.log);
```
And then I'm calling `send`:
```typescript
    hands.send({'image': canvas /* HTMLCanvasElement */ });
```

However, there seems to be trouble locating files:
```
RuntimeError: abort(Error: ENOENT: no such file or directory, open 'file:/my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.wasm') at Error
   at jsStackTrace (file:///my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:68157)
   at stackTrace (file:///my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:68333)
   at abort (file:///my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:42224)
   at getBinary (file:///my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:43496)
   at file:///my_node_prefix/node_modules/@mediapipe/hands/hands_solution_wasm_bin.js:9:44108
```

The file `hands_solution_wasm_bin.wasm` is clearly in place, I double checked it. 

Maybe it is due to lack of understanding on how to instantiate Hands object? Could you provide some information on what am I doing wrong? I'm currently using `0.1.1613506466` version.

**Comment by mhays-google** [comment]
I had sort of hacked a solution in to expose images and canvases

While I've been distracted, I'm back, and I'm formally adding image support
within the next week or so.  The issue you are seeing looks like I've not
properly protected some of the name mangling from the obfuscator.

Since this is destined to be open source, I may be able to help you with
troubleshooting. I'll see if it's okay for me to release a
non-minified/obfuscated script.  I can't promise right now, but I'm heavily
in favor of giving you all the help you need.

**Comment by akyeww** [comment]
Hello @mhays-google, many thanks for the hardwork! I've encountered following error on both Android / PC Chrome browser when running the [example](https://google.github.io/mediapipe/solutions/hands#javascript-solution-api) given.
This only happens when no hands are detected from the frame, and it would cause the canvas to not draw that particular frame from video. I would like the canvas to keep drawing even if no hands are detected, can you help to resolve this issue?
```
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at Object.transform (hands.js:44)
    at ja.h (hands.js:42)
    at U (hands.js:10)
    at ma.next (hands.js:11)
    at hands.js:22
    at new Promise (<anonymous>)
    at X (hands.js:22)
    at Object.onResults (hands.js:39)
    at methodCaller_void_$vector$ResultData$$ (eval at new_ (hands_solution_wasm_bin.js:9), <anonymous>:5:26)
    at __emval_call_void_method (hands_solution_wasm_bin.js:9)
```

**Comment by Jorres** [comment]
Hello @mhays-google! Thank you for your great work! I've tried to use a new version, `@mediapipe/hands 0.1.1614621970`, and it seems to give the same error as described in my previous commentary, the `ENOENT` one. But I'm seriously thinking it's because I'm doing something wrong. It would be a great help to my business process if you had a look through 7 lines of code I sent there: https://github.com/google/mediapipe/issues/1388#issuecomment-782866041 

The best way will be if you would just add the supposed way to instantiate `Hands` object into some part of the documentation, so it would help everybody, not just me. Unfortunately, I failed to understand what I'm doing wrong with current documentation. 

Eagerly waiting for your reply!

**Comment by sgowroji** [comment]
We have improved our Javascript solutions and documentation here https://google.github.io/mediapipe/getting_started/javascript.html. We are closing this issue now, Please reach us with a new issue or reopen the above issue if you are looking answer from the above query. Thanks!

**Comment by pauldubois98** [comment]
I'm not very sure to understand how to use mediapipe with a canvas instead of a videoelement...
In particular, I am willing to pass single image(s), instead of the camera.
Could you explain a little futher how to do that?

Thank you for your time!

**Comment by ainanicolau** [comment]
Hello, I also wanted to use a canvas element as input for the holistic model. Is this currently supported?
