### ISSUE TITLE
TensorToFloat and TensorToLandmark seem to take far far longer than inference (Holistic example)

### ISSUE THREAD

**Issue by PoseAI** [google/mediapipe#1414]
Hi, I have been testing out what appears to be the new pipeline (i.e. tensor instead of tflitetensor) and I get unexpected behavior:

1. I use the new holistic example in Linux on the GPU (mobile models run blistering fast), 
2. Only modification is  I turned on mediapipe profiling by including the standard lines at the top of the graph
3. I use the web based mediapipe profiling tool to analyze the log (screenshot attached)
=> over 65% of the time is spent on the various TensorToFloat and TensorToLandmark calculator calls.

While I understand crossing from the GPU to the CPU is expensive, I am a little surprised by the magnitude.  Under the previous way of doing things inference and sometimes rendering were always the biggest bottlenecks by a longshot.

Is this expected behavior? Is it a quirk in the profilier?  

Thanks
![Screenshot_2020-12-20 MediaPipe](https://user-images.githubusercontent.com/59567884/102725698-98fa2480-4310-11eb-9c62-1e03a4740756.png)

**Comment by mcclanahoochie** [comment]
profiling gpu graphs is a bit tricky, because the gpu runs in a separate runtime in its own thread. 
the gpu is forced to sync to cpu in these calculators ( ex: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/tensors_to_landmarks_calculator.cc#L146 ) so likely we are just seeing the GL command queue being flushed at this point (since the GL queue runs asynchronously) . 
unfortunately, there isn't a clean way to measure gpu performance per calculator, without forcing a sync in each calculator (say, by creating a simple calculator that just calls glFinish() and inserting that before and after each gpu calculator you want to measure).

**Comment by PoseAI** [comment]
ok thanks that makes sense!
