### ISSUE TITLE
how to get face pose transformation matrix ?

### ISSUE THREAD

**Issue by Choons** [google/mediapipe#1457]
I have been experimenting with the Face Mesh solutions in python and javascript and want to get the pose transformation matrix and 3D mesh from the bundled Face Geometry module, but can't figure out how. I think the process is to get the face landmarks first and then pass them to Face Geometry methods, but I get lost trying to understand the C bindings. Can someone give me a snippet of code that shows how?

**Comment by kostyaby** [comment]
Hey @Choons,

Thanks for reaching out!

What you want is currently not available as Face Geometry is not exposed through Python or Javascript Solution APIs. This issue is really a feature request, so I added @chuoling to comment on whether this is something on the radar to build in the near future

For Python, you might benefit from a solution @Rassibassi built as a part of #1379. Feel free to explore the code or contact the author: https://github.com/Rassibassi/mediapipeFacegeometryPython/blob/main/head_posture_rt.py

**Comment by Choons** [comment]
Hi @kostyaby, thanks for the reply! That code from @Rassibassi is exactly what I need. I was trying to import the face_geometry_pb2 as geom and then instantiate a class object with fae_geom = geom.FaceGeometry(). I could see in PyCharm that I need to pass in some parameters, but it just showed as 'self:type,*args,**keywds' so I never could figure out what it wanted. I *think* it should just require image_size as a tuple, and the landmarks_list. If I didn't pass anything it would run fine and I could do face_matrix = face_geom.pose_transform_matrix without any errors, but it had no values in it. Anyway, that was my thought process if it helps in adding the feature. It's quite close to working already-- just needs a bit more.

**Comment by mhays-google** [comment]
We recognize how useful this is, and it will be added eventually.   Just a matter of priorities at the moment.  Thank you for reaching out!

**Comment by Choons** [comment]
I'll leave this here. https://github.com/spite/FaceMeshFaceGeometry

maybe people will find it useful

**Comment by Rassibassi** [comment]
Check out my demo here: https://github.com/Rassibassi/mediapipeDemos/blob/main/head_posture.py

many more demos under https://github.com/Rassibassi/mediapipeDemos

**Comment by sgowroji** [comment]
Above added contributions are really useful for the community. We are closing this issue now. Feel free to reach us if you still have any further queries on top of it.Thanks!
