### ISSUE TITLE
How to use the pre-downloaded dependency repository

### ISSUE THREAD

**Issue by lrjbdss** [google/mediapipe#1489]
When run 
`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`
Downloading org_tensorflow will time out.
I want use the pre-downloaded org_tensorflow by putting the tar.gz file in the .cache corresponding directory, but it didn't work.How should I operate it correctly?

**Comment by DandyLorenz** [comment]
Since the V0.8.2 version, I cannot use handtrackinggpu aar normally, through the following command:

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
    name = "mp_face_detection_aar",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)
I even tried the following commands:

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
        name = "my_handtrackinggpu_aar",
        calculators = [
        "//mediapipe/graphs/hand_tracking:mobile_calculators",
        "//mediapipe/calculators/core:pass_through_calculator"
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_gpu",
        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_gpu",
       ],
)
I imported the generated aar into my Android project, and it prompted that the calculation unit could not be found: This is a common error, I spent a lot of time for it, I don’t know how to solve it, please help me, thank you, you can Refer to my detailed description:

**Comment by DandyLorenz** [comment]
The best way for you to use a VPN. Another way is to:
IN WORKSPACE　file.

mediapipe will download libyuv:You can download and replace the file path by yourself


```

# libyuv　　
#http_archive(
#    name = "libyuv",
#    urls = ["https://chromium.googlesource.com/libyuv/libyuv/+archive/refs/heads/master.tar.gz"],
#    build_file = "@//third_party:libyuv.BUILD",
#)
 
new_local_repository(
	name= "libyuv",
	path = "/home/work/Downloads/libyuv-refs_heads_master",
	build_file = "@//third_party:libyuv.BUILD",
)
```

**Comment by eknight7** [comment]
@lrjbdss were you able to get it working?

**Comment by BestUkpai** [comment]
@lrjbdss were you able to get it working?

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.

**Comment by Lr-2002** [comment]
So,Did the problem fixed ever?
In need of your help ,plz

**Comment by sgowroji** [comment]
Hi @Lr-2002, Did you try with the latest MediaPipe version?. If you still face the same issue, could you please raise as a new issue with complete details in it. Thanks!
