### ISSUE TITLE
modifying face landmark subgraph problem

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1512]
Hello, I want to modify facemesh example and implement another face_landmark model. I've explored face_landmark module, in face_landmark_gpu subgraph there are some node that made me confused.
As far as I know, face_landmark_gpu is responsible for getting image and faces ROIs(obtained from face detection model) and putting landmark points on it.
in this subgraph, there is a node for spliting output vector of inference calculator to 2 vector. first for landmark tensor and second for **face_flag_tensor** . the next node Converts the **face_flag tensor** into a float that represents the **confidence**. what confidence mean here? I believe face detection is responsile for face presence not landmark model. 

my model gives a tensor of landmark points as output and no other output for confidence or face presence score. 
how can I use my model instead of default mediapipe ladmark?
Any help is appreciated.

**Comment by danhd123** [comment]
There's a face presence score and a detection confidence. I believe the detection confidence comes from the BlazeFace detector -- how sure is the system that there *is* a face, from 0-1 -- and the face presence score is a sum of confidences for individual landmarks --how sure is the system that *this* is where the face landmarks are. Individual landmarks being offscreen (either because the face is near the edge of the frame or because the face is partially or completely in profile or because it's too dark to see them) drags down the face presence score. 

Confidences and face presence scores are just possible outputs which might or might not be used by a renderer. They don't have any inherent meaning for the mediapipe framework itself. Go wild with your model without them, you'll just need to edit the graphs, and possibly use your own renderer.

**Comment by milad-4274** [comment]
thank you very much. It seems I should design a seperate subgraph(instead of FaceLandmarkGPU) for landmark detection based on my tflite model. 
do you have any idea for designing a graph? I mean how can I debug my graph.
now my approach is changing graph, building android app and see device logs for error and warnings that is so time consuming and tedious.

**Comment by hadon** [comment]
There is an API function to see the subgraph "expanded" within the enclosing graph.  After calling CalculatorGraph::Initialize(), you can call my_calculator_graph.Config().DebugString() to see the complete graph with subgraphs replaced by their nested calculators.  

For debugging mediapipe graphs generally, you can add LOG(INFO) diagnostics to various calculators, and you can use CalculatorGraph::ObserverOutputStream() to monitor the packets along any stream in the running graph.  There is also a profiling interface at CalculatorGraph::profiler().

**Comment by hadon** [comment]
Closing this issue for now.  Feel free to re-open it if more responses are needed.

**Comment by zeina-abuaisheh** [comment]
how to get the face presence please? I am searching for a way to get the landmarks presence score?
