### ISSUE TITLE
Issue on getting proper Face Landmarks using Mediapipe AAR

### ISSUE THREAD

**Issue by PravinChill** [google/mediapipe#1535]
I am trying to implement [FaceMesh](https://google.github.io/mediapipe/solutions/face_mesh.html) in Android using [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html).

The landmark I am getting using AAR is different from the Bazel Mediapipe application.

PFA

Face Mesh using Mediapipe Application (BAZEL)
![Screenshot_20210121-140407](https://user-images.githubusercontent.com/77655317/105336990-e8798c00-5bff-11eb-98d1-0229b6b16f33.jpg)

Face Mesh using Mediapipe AAR Application (GRADLE)
![Screenshot_20210121-140759_FaceMesh](https://user-images.githubusercontent.com/77655317/105337109-0646f100-5c00-11eb-90b9-31d54114ceee.jpg)

How to fix this issue ?

**Comment by jiuqiant** [comment]
I think it's due to the repo reorganization -- the Bazel one uses the models in mediapipe/modules while the AAR one uses the old models in mediapipe/models. You can replace the old models with new models in your assets dir.

|  Old ｜ New |
| ----------- | ----------- |
| mediapipe/models/face_detection_front.tflite | mediapipe/modules/face_detection/face_detection_front.tflite |
| mediapipe/models/face_landmark.tflite | mediapipe/modules/face_landmark/face_landmark.tflite |

**Comment by PravinChill** [comment]
@jiuqiant,

Issue got resolved after changing to new model.

Thank you for the support :)
