### ISSUE TITLE
bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_cpu --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt

### ISSUE THREAD

**Issue by jingruhou** [google/mediapipe#159]
select timeout
select timeout
select timeout
select timeout
select timeout

why???

**Comment by mcclanahoochie** [comment]
this error is coming from opencv's video capture module, and usually happens when there is an issue with opencv initializing the camera.

can you make sure your camera works with another application? can you unplug the camera and reconnect? are you on osx or linux?  on linux make sure you can use the camera via the program 'cheese' (may have to install it)

**Comment by jingruhou** [comment]
Solved, thank you. 

My virtual machine camera is not connected successfully.
