### ISSUE TITLE
Pip install 3.8 or 3.7 not working

### ISSUE THREAD

**Issue by chrisdoyleIE** [google/mediapipe#1597]
Attempting to install on macOS Mojave

<img width="524" alt="Screenshot 2021-02-08 at 12 05 04" src="https://user-images.githubusercontent.com/44365591/107217432-11728d00-6a06-11eb-8ac6-7f5381195afb.png">

<img width="741" alt="Screenshot 2021-02-08 at 12 53 55" src="https://user-images.githubusercontent.com/44365591/107222385-bee89f00-6a0c-11eb-900a-fa542043dbd7.png">

**Comment by jiuqiant** [comment]
Mojave is 10.14 and the python wheel file is mediapipe-0.8.2-cp38-cp38-macosx_10_15_x86_64.whl, which requires 10.15 and above. 

You may download it from https://pypi.org/project/mediapipe/#files and rename it to be mediapipe-0.8.2-cp38-cp38-macosx_10_14_x86_64.whl to see if it works. Otherwise, you also can build it locally by following https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package.

**Comment by mayank10j** [comment]
Facing same issue with macOS Mojave on executing command: 
pip install mediapipe
```
ERROR: Could not find a version that satisfies the requirement mediapipe
ERROR: No matching distribution found for mediapipe
```

**Comment by jiuqiant** [comment]
> Facing same issue with macOS Mojave on executing command:
> pip install mediapipe
> 
> ```
> ERROR: Could not find a version that satisfies the requirement mediapipe
> ERROR: No matching distribution found for mediapipe
> ```

Can you report your os info (whether with apple m1 chip or not) and your python version.

**Comment by jiuqiant** [comment]
It works on my MacBook Pro with macOS Mojave. See https://github.com/google/mediapipe/issues/1622#issuecomment-781545043.

Also, Mojave has python 3.9 as default and the new mediapipe python wheel for python 3.9 is coming. But, for now, you still need python 3.6 to python 3.8 to install mediapipe.

**Comment by mayank10j** [comment]
I am using MacOS Mojave version 10.14.16 
Using Anaconda python distribution and tried with conda env with Python version 3.6, 3.7, 3.8 and 3.9 
pip install mediapipe not working with any of these.

**Comment by chrisdoyleIE** [comment]
I couldn't fix it, ended up wiping my mac and installing Catalina which worked fine.

**Comment by jiuqiant** [comment]
> I couldn't fix it, ended up wiping my mac and installing Catalina which worked fine.



> I am using MacOS Mojave version 10.14.16
> Using Anaconda python distribution and tried with conda env with Python version 3.6, 3.7, 3.8 and 3.9
> pip install mediapipe not working with any of these.
> I am using Intel Based MacBook Pro 15 inch 2018 Model

The macOS Python packages are fro MacOS 10.15+. You can find this from the whl file name such as "mediapipe-0.8.3-cp39-cp39-macosx_10_15_x86_64.whl". So, it's required to have Catalina at least.

**Comment by chrisdoyleIE** [comment]
> > I couldn't fix it, ended up wiping my mac and installing Catalina which worked fine.
> 
> 
> 
> 
> 
> 
> 
> > I am using MacOS Mojave version 10.14.16
> 
> > Using Anaconda python distribution and tried with conda env with Python version 3.6, 3.7, 3.8 and 3.9
> 
> > pip install mediapipe not working with any of these.
> 
> > I am using Intel Based MacBook Pro 15 inch 2018 Model
> 
> 
> 
> The macOS Python packages are fro MacOS 10.15+. You can find this from the whl file name such as "mediapipe-0.8.3-cp39-cp39-macosx_10_15_x86_64.whl". So, it's required to have Catalina at least.

This isn't closed surely? I had Mojave and had to reset to an OLDER os. Mediapipe did not work for Mojave or multiple python versions on Mac

**Comment by chrisdoyleIE** [comment]
@jiuqiant

**Comment by jiuqiant** [comment]
> > > I couldn't fix it, ended up wiping my mac and installing Catalina which worked fine.
> > 
> > 
> > > I am using MacOS Mojave version 10.14.16
> > 
> > 
> > > Using Anaconda python distribution and tried with conda env with Python version 3.6, 3.7, 3.8 and 3.9
> > 
> > 
> > > pip install mediapipe not working with any of these.
> > 
> > 
> > > I am using Intel Based MacBook Pro 15 inch 2018 Model
> > 
> > 
> > The macOS Python packages are fro MacOS 10.15+. You can find this from the whl file name such as "mediapipe-0.8.3-cp39-cp39-macosx_10_15_x86_64.whl". So, it's required to have Catalina at least.
> 
> This isn't closed surely? I had Mojave and had to reset to an OLDER os. Mediapipe did not work for Mojave or multiple python versions on Mac

MediaPipe Python packages support macOS 10.15+. If you need this to work on Mojave, you can build the package on your local machine by following https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package. Another solution is you can download the wheel package and rename it to be mediapipe-0.8.3-cp39-cp39-macosx_10_14_x86_64.whl to see if it works.

**Comment by PhanThanhTrung** [comment]
I'm getting the same error. Here is my error code:
```
ERROR: Could not find a version that satisfies the requirement mediapipe
ERROR: No matching distribution found for mediapipe
```
I'm using MacOS 10.14.6 with python 3.7 (conda).

**Comment by jiuqiant** [comment]
> I'm getting the same error. Here is my error code:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement mediapipe
> ERROR: No matching distribution found for mediapipe
> ```
> 
> I'm using MacOS 10.14.6 with python 3.7 (conda).

This is expected. MediapPipe Python macOS supports 10.15+ for now.

**Comment by KeygenLLC** [comment]
Trying to build this locally in Mojave is a cluster$%#&. Maybe someone with more know-how can do it, but it's a mess.

I tried it just for the hell of it. Installing the dependencies takes a while with homebrew (especially opencv). Following the instructions to build for Mojave has problems and fails upon the last few tasks. It can't find libjpeg even though it has been installed with homebrew and even has paths set in `.bash_profile`. Bazel also seems to be looking for broken google links.

Using this code fails: `python3 setup.py install --link-opencv`
Using this code gets 99% complete and fails with a few tasks left: `python3 setup.py bdist_wheel`

```bash
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 14157 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
Target //mediapipe/python:_framework_bindings.so failed to build
```

> Mojave is 10.14 and the python wheel file is mediapipe-0.8.2-cp38-cp38-macosx_10_15_x86_64.whl, which requires 10.15 and above.
> 
> You may download it from https://pypi.org/project/mediapipe/#files and rename it to be mediapipe-0.8.2-cp38-cp38-macosx_10_14_x86_64.whl to see if it works. Otherwise, you also can build it locally by following https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package.

This doesn't work. It might be related to [this StackOverflow post →](https://stackoverflow.com/a/39519008/3927293)

- Download the wheel [from this link →](https://files.pythonhosted.org/packages/03/c8/ec54b88bb7136a4de5dbaeb9bdac843ddb0fa2c3d6a91ea95bc45e9bf63f/mediapipe-0.8.9.1-cp310-cp310-macosx_10_15_x86_64.whl)
- Rename the file to `mediapipe-0.8.2-cp38-cp38-macosx_10_14_x86_64.whl`
- Activate your ENV in terminal (I'm using Anaconda) `conda activate MYENVNAME`
- Then install with `pip install /path/to/mediapipe-0.8.2-cp38-cp38-macosx_10_14_x86_64.whl`

Installed fast with no errors and imported into my script fine. When running the script, it can't find the `.so`. Only if renaming it to `_framework_bindings.so` will it find it, however then you get errors that symbols are missing.

Here is what did work for me:
---
The only way I've gotten this to work so far is to install via pip in Big Sur, then I copied the folders over to my main machine that runs Mojave into my `~/opt/anaconda3/envs/MYENV/lib/python3.8/site-packages/` folder. Recognized in vscode, works when running the scripts in Terminal. I don't know if trying to install the wrong way helped or not, so YMMV. It's not the first time I've had to do this with python packages that don't provide Mojave versions.

If anyone still needs the this for Mojave, I zipped the library. I had to split it up into 3 zips due to size, but you can open with [Keka](https://www.keka.io/en/) (I made them with Keka). Install in the correct place and it should work, though I can't guarantee this and provide no warranty. It wouldn't let me upload them here, so you can grab them from the public repo I made below if you'd like to test it out.

[Download from Keygen Public Files on Github  →](https://github.com/KeygenLLC/Public-Files)

@chrisdoyleIE @PhanThanhTrung @mayank10j
