### ISSUE TITLE
how to de-normalize the Z-axis in the hand tracking keypoints.

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#1654]
Hello, Please give me some guidance on how to de-normalize the Z-value in the hand tracking .

Example(the below value is for left hand):

X: 0.6740323305130005  Y: 0.7470104694366455 Z: -0.000010861454029509332
X: 0.7135494351387024  Y: 0.7020353078842163 Z: 0.046364061534404755
X: 0.7387958765029907  Y: 0.6469143629074097 Z: 0.062905453145504
X: 0.7581880688667297  Y: 0.5938120484352112 Z: 0.07525277882814407
X: 0.780859112739563  Y: 0.5642832517623901 Z: 0.08842882513999939

**Comment by vasanthhr** [comment]
@mcclanahoochie @mgyong @mhays-google 

Could you please guide on the above request about logic to de-normalize the Z-axis value of handtracking .

**Comment by prabhavnegi** [comment]
@vasanthhr Did you find a solution. If yes can you pls share.

**Comment by victorC97** [comment]
Is it really relevant de-normalizing the Z axis here ? I'm facing the same issue (on estimation pose of the whole body). 

It seems that in order to denormalize X and Y, you take the height and width of the image, but there is no such equivalent for Z (as an image is in 2-D), is it ?

I guess we need to find, if it has a relevance, the profundity of the image.

I've found that Mediapipe uses shades of gray differences to find the profundity of the image, maybe we have to take the real profundity of the room ?

It could also be a combination of X and Y ?

I don't know if I really helped the debate, please, tell me if you find a suitable solution in the future.
Have a good day everyone,

Victor

**Comment by sgowroji** [comment]
Hi @vasanthhr, Could you please respond if your still looking answer for the above query. Thanks!

**Comment by mhays-google** [comment]
The z coordinate is unfortunately not a metric coordinate, it truly is a
normalized, relative coordinate.

Pose has recently introduced metric coordinates into its landmarks, and
since the same model is used in our holistic solution which also includes
hands, it's possible that this will become a thing.  But no timetable on
this right now.
