### ISSUE TITLE
Building C++ command-line example apps - getting error while running on mac

### ISSUE THREAD

**Issue by KanzaSheikh** [google/mediapipe#1664]
I am trying to use mediapipe for a university project and have installed it, even successfully ran the Hello World! in C++ bit but when I am trying to build the C++ example, it is giving me errors.

I ran this:
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

and the result I got is this:
DEBUG: /private/var/tmp/_bazel_kanzashaikh/c191ae13e9137350b50f6a19ce94bf21/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
INFO: Build option --compilation_mode has changed, discarding analysis cache.
ERROR: Error fetching repository: java.io.IOException: The repository's path is "/usr/local/opt/opencv@3" (absolute: "/usr/local/opt/opencv@3") but this directory does not exist.
ERROR: /Users/kanzashaikh/development/mediapipe/third_party/BUILD:178:6: //third_party:opencv_binary depends on @macos_opencv//:opencv in repository @macos_opencv which failed to fetch. no such package '@macos_opencv//': The repository's path is "/usr/local/opt/opencv@3" (absolute: "/usr/local/opt/opencv@3") but this directory does not exist.
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.194s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 237 targets co\
nfigured)

How do I solve it?

**Comment by miscounting** [comment]
I commented on your StackOverflow question https://stackoverflow.com/questions/66376720/getting-error-while-running-mediapipe-on-macos-building-c-command-line-exampl/66383865#66383865?newreg=eb92f4ae2f7d422fb878d18755ea3dbf , but wanted to comment here as well w/more details, because the Mac installation instructions aren't detailed enough currently!

Gotchas: install opencv@3 via brew; if you have failures, look at dependencies like openSSL that might not have been installed via brew.
Edit WORKSPACE so the path is set to "/usr/local/Cellar/opencv@3/"
Note that /usr/local/Cellar/opencv@3 has a version folder in it; third_party/opencv.BUILD doesn't account for this.  Edit third_party/opencv.BUILD so that `hdrs = glob(["**/include/opencv2/**/*.h*"]),` and `includes = ["**/include/"],`

Good luck!

**Comment by KanzaSheikh** [comment]
@miscounting Thank you so much for your answer, I was finally able to run the build. For some reason, I didn’t have to edit the WORKSPACE file or anything else either but nonetheless your answer is much appreciated!!

**Comment by sgowroji** [comment]
@KanzaSheikh From above comment is see your issue is resolved. So closing this issue.
