### ISSUE TITLE
Pose Detection for Cyclist

### ISSUE THREAD

**Issue by nickharmening** [google/mediapipe#1666]
Dear Community, 

i am using mediapipe for detecting the body pose of a cyclist. Compared to mediapipes performance in other contexts, the offset of the predicted and the true leg-landmarks is quite high. Is there any plan to improve the model in this context?

Best regards
Nick
![IMG 2 annotated](https://user-images.githubusercontent.com/49647389/109304059-fabc9a80-783b-11eb-88c1-6e93c2629c34.png)
<img width="512" alt="IMG 1 annotated" src="https://user-images.githubusercontent.com/49647389/109304106-0f992e00-783c-11eb-9060-6bff3161a300.png">

**Comment by sgowroji** [comment]
Hi @nickharmening Could you provide more details about platform.

**Comment by nickharmening** [comment]
Sure, i ran it with the colab notebook you provided: https://mediapipe.page.link/pose_py_colab

**Comment by flobaader** [comment]
Hello @mgyong,
I am a team member of @nickharmening and can help here. :)
Our use case is that we want to analyze how well a bike is set up, in which we analyze for example the knee angles.
We have been able to get very good results with Mediapipe when a body is seen from the front, but from the side, the results are then worse.

Are there any tips on how we could possibly improve the detection?

**Comment by verilog15** [comment]
Hi @flobaader, were you able to resolve it or did you use another tool instead? Having a similar situation here.

**Comment by ayushgdev** [comment]
@nickharmening Please consider using the Heavy pose detection model for this use case, since it looks like the model is able to determine the pose almost accurately. By default, pose detection solution uses [full model](https://github.com/google/mediapipe/blob/56552dbfb5818b6926d5b1c23f1f0e718a624623/mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt#L50) enumerated as ["1"](https://github.com/google/mediapipe/blob/56552dbfb5818b6926d5b1c23f1f0e718a624623/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt#L37). You can find all models in [this section](https://github.com/google/mediapipe/blob/56552dbfb5818b6926d5b1c23f1f0e718a624623/docs/solutions/models.md#pose) of the pose model documentation.
Since the details of the language you are using is not available, in Python, you can provide model complexity as 
```
with mp_pose.Pose(static_image_mode=True, model_complexity=2) as pose:
...
```
In Javascript, it is done as:
```
pose.setOptions({modelComplexity: 1})
```
In C++, you can provide model_complexity as `input_side_packet` to the [PoseLandmarkGpu](https://github.com/google/mediapipe/blob/56552dbfb5818b6926d5b1c23f1f0e718a624623/mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt#L45) calculator
```
input_side_packet: "MODEL_COMPLEXITY:model_complexity"
```
