### ISSUE TITLE
DeadLock occured  when i get face_detections  packet  in the Face Detection Samples 

### ISSUE THREAD

**Issue by lizhanping** [google/mediapipe#1709]
i want to get the face number in the image, so i change the code in Face Detection Sample. and i change the graph outputstreampoller to face_detections like below. so i  output the face_detections info but not reander image data.
ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller,face_detect_graph.AddOutputStreamPoller("face_detections"));
![image](https://user-images.githubusercontent.com/24273982/110109210-14d01d00-7de8-11eb-851b-e541b62789de.png)

when the input image has >= 1 face num,that's working,but when the input image does not have a one face, application will dead but not crashed.
so i track the code,i find the code is dead in poller.Next(&packet)   --- >>     handler_condvar_.Wait(&mutex_);   
Is it the wrong way I use it, or is there really a problem? I need help. Thank you

**Comment by hadon** [comment]
OutputStreamPoller will block indefinitely waiting for a non-empty output packet, so if on any iteration the graph produces no output packet, poller.Next() will block indefinitely. Depending on the application, this may block the next input and result in a deadlock.  To avoid this sort of deadlock, I usually change from AddOutputStreamPoller() to ObserveOutputStream(), which doesn't block any thread.  

AddOutputStreamPoller() is designed for convenience by enabling synchronous graph input and output, all from a single application thread.  However, because some MediaPipe calculators occasionally produce no output, AddOutputStreamPoller() is prone to deadlocks.  ObserveOutputStream() has recently been updated with the option "observe_timestamp_bounds" to accept timestamp updates with empty packets as well as non-empty packets, but this option has not yet been added to AddOutputStreamPoller(), where it would make polling less prone to deadlocks.

**Comment by sgowroji** [comment]
Hi @lizhanping, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/1709#issuecomment-859778697).  Thanks!

**Comment by lizhanping** [comment]
> OutputStreamPoller will block indefinitely waiting for a non-empty output packet, so if on any iteration the graph produces no output packet, poller.Next() will block indefinitely. Depending on the application, this may block the next input and result in a deadlock. To avoid this sort of deadlock, I usually change from AddOutputStreamPoller() to ObserveOutputStream(), which doesn't block any thread.
> 
> AddOutputStreamPoller() is designed for convenience by enabling synchronous graph input and output, all from a single application thread. However, because some MediaPipe calculators occasionally produce no output, AddOutputStreamPoller() is prone to deadlocks. ObserveOutputStream() has recently been updated with the option "observe_timestamp_bounds" to accept timestamp updates with empty packets as well as non-empty packets, but this option has not yet been added to AddOutputStreamPoller(), where it would make polling less prone to deadlocks.

thank you for your reply,i will try later and reply here 。

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now. Feel free to reach if you have any further relevant queries.
