### ISSUE TITLE
mediapipe.autoFlip error - Segmentation Fault : 11 when running the autoflip example multiple times.

### ISSUE THREAD

**Issue by nitinkatyal1314** [google/mediapipe#1726]
I've followed the installation steps for autoflip and build it using the following command:

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip`

 I ran the autoflip example by specifying the input & output file locations using command:

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \
  --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \
  --input_side_packets=input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/absolute/path/to/save/the/output/video/file,aspect_ratio=1:1`

and I get the following error:

<img width="1790" alt="Screenshot 2021-03-10 at 5 32 48 PM" src="https://user-images.githubusercontent.com/23167810/110626401-ad8ae200-81c6-11eb-9d18-726a3fd92cc9.png">

This issue appears more often when the you try to run the example multiple times. For this, I created a bash script which runs the example 5 times (which is why you see the error in above image referring to the bash script line where it failed).

Here is the link to the video file I used when running the example : https://github.com/keplerlab/katna/blob/master/tests/data/pos_video.mp4 

Below are the system details:
OS : MacOS Catalina (v 10.15.7),
Memory : 16 GB,
openCV & bazel version -  OpenCV @ 3, bazel 4.0.0-homebrew

**Comment by sgowroji** [comment]
Hi @nitinkatyal1314 , Could you please go through this [issue](https://github.com/google/mediapipe/issues/497),  I assume this will resolve your error

**Comment by nitinkatyal1314** [comment]
> Hi @nitinkatyal1314 , Could you please go through this [issue](https://github.com/google/mediapipe/issues/497), I assume this will resolve your error

That issue was closed in Sept 2020. Has the issue been fixed but note released yet?

**Comment by jiuqiant** [comment]
@ndimension, can you take a look at this issue when you have time. I believe the fix to https://github.com/google/mediapipe/issues/497 was fixed. This can be a new corner case?

**Comment by sgowroji** [comment]
@nitinkatyal1314 Assuming you are resolved, we are closing this issue. Please feel free to open, if the issue still persists and share the latest update.

**Comment by nitinkatyal1314** [comment]
> @nitinkatyal1314 Assuming you are resolved, we are closing this issue. Please feel free to open, if the issue still persists and share the latest update.

The main issue is still there. As a workaround, I have added a configurable parameter (currently set to 3) in my code. If segmentation fault is encountered, the code re-runs the pipeline. 

Opening the issue so it can be fixed.

**Comment by sgowroji** [comment]
Hi @nitinkatyal1314, Are you still looking resolution for the above query, Thanks!

**Comment by anandvaishnao** [comment]
i am also facing the same "segmentation fault" error. Any resolution yet ? This looks like same issue as well: https://githubmemory.com/repo/google/mediapipe/issues/2585

**Comment by TsainGra** [comment]
Hi, I am facing the same issue with Autoflip on Ubuntu 20.04

**Comment by Somyaa10** [comment]
Facing the same issue on a few videos. The code works on some videos but throws "segmentation fault" for other videos. Is there any resolve for this issue?

**Comment by AlverGant** [comment]
I have found that reducing the number of threads reduces the probability of the problem to occur.

Running autoflip on linux with the following code appears to solve the problem but also reduces performance:
GLOG_logtostderr=1 taskset --cpu-list 0 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip .....

**Comment by jiuqiant** [comment]
I find that the segfault is caused by the cv2::kmeans method call at  https://github.com/google/mediapipe/blob/cc6a2f7af65977248b2a15f471503da2832f583a/mediapipe/examples/desktop/autoflip/calculators/border_detection_calculator.cc#L193

Other users also reported similar issues such as https://github.com/opencv/opencv_contrib/issues/2351. Updating the OpenCV dependency to a more recent version might be a valid workaround.

**Comment by nathanfrey-google** [comment]
Thank you @jiuqiant for finding the location of the crash.  In the short term, another workaround is to not use the BorderDetectionCalculator since it is an optional input to SceneCroppingSalculator.  Removing it from the graph may stop the crash, however if the video has black bars on the top/bottom they will not be removed by autoflip as this is handled  by the border_detection_calculator.cc.  

Some older video content has black bars burned directly into the video but it is not typical to do this with modern videos.  You may consider weather you need the BorderDetectionCalculator for your specific use case.

**Comment by senpo** [comment]
This may address your issue. Please take a look.
https://github.com/google/mediapipe/issues/2822#issuecomment-1098249400
