### ISSUE TITLE
Densify

### ISSUE THREAD

**Issue by alecda573** [google/mediapipe#1768]
What is the operation densify seen in the tflite graph for the hand_landmark_sparse model? 

Do you guys or have you guys published this network architecture and corresponding weights in any other format?

**Comment by sgowroji** [comment]
Hi @alecda573, Could you please elaborate with complete details to understand the query much better. Thank you!

**Comment by alecda573** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/60713416/111798828-71c3dc80-8898-11eb-8fe6-bccaeb3e30f7.png)

Using netron I was viewing the hand_landmark_sparse model graph and it is showing these layers/ops called densify it is unclear what they are? 

Also, I was wondering if the model was available in native tensorflow or another format as this densify layer makes it impossible to convert to onnx via package tflite2onnx (its unrecognized)

**Comment by alecda573** [comment]
@sgowroji I am interested in updating the weights of your model on my own dataset that is why I am wondering if the weights are available in another format, like .pb or hdf5

**Comment by alecda573** [comment]
@sgowroji and @mgyong any updates on this?

**Comment by mgyong** [comment]
@ablavatski Can you answer?

**Comment by ablavatski** [comment]
Sure. Densify op has been introduced into TFLite (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs#L358) in order to convert the sparse weights into dense one that can be further used in other ops of TensorFlow Lite graph like regular or depthwise convolutions. The op helps to store the sparse weights in optimized format what reduces the size (on the disk) of the sparse model. As for `tflite2onnx` the best option is to provide a conversion implementation for DENSIFY op here (https://github.com/jackwish/tflite2onnx/tree/master/tflite2onnx/op) similar to C++ implementation (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/densify.cc) and replace it to the identity in the graph. Does that helps you?
