### ISSUE TITLE
Hair Segmentation on web app

### ISSUE THREAD

**Issue by probator1059** [google/mediapipe#1780]
Hello.
Currently, I am trying to build web app that uses many mediapipe solutions, since it is mobile-friendly.
My issue is that I cannot figure out how to use hair segmentation solution in web app(using js).
As far as I know, hair segmentation does not provide js solution. It only has web demo.
How can I achieve what I want? 
Hair segmentation would have js solution? 
Somewhere, I read that it was converted to wasm for the web demo.
Then, where can I get that wasm file and make use in web app?
Thanks.

**Comment by sgowroji** [comment]
Hi @probator1059  Present we are not supporting Hair segmentation in Javascript. See [here](https://google.github.io/mediapipe/#mediapipe-on-the-web).  May be you can share your exact need so that i can check with the team and let you know if there are any workaround, But not sure this will be addressable as per your requirement.

**Comment by rmothukuru** [comment]
@probator1059,
Marking it as a Feature Request. Thanks!

**Comment by arianatri** [comment]
so will the hair segmentation come out for js?
