### ISSUE TITLE
MediaPipe JS custom build

### ISSUE THREAD

**Issue by futuyao** [google/mediapipe#1818]
We'd like to have a custom built JS solution to use, but the [documentation](https://google.github.io/mediapipe/getting_started/javascript.html) only includes ready-to-use solutions without any information on how to build for JavaScript. Specifically, we're wondering if the following could be made available:
- Instructions and files to build mediapipe js
- If we can’t get that, can we get a custom build of mediapipe js that targets openGL ES 2.0 or webGL 1.0

Related issues:
- https://github.com/google/mediapipe/issues/1427
- https://github.com/google/mediapipe/issues/877
- https://github.com/google/mediapipe/issues/1741

Thank you very much.

**Comment by mgyong** [comment]
see related issue #877

**Comment by tyrmullen** [comment]
This issue is a multi-part request with a lot of smaller pieces, so for the sake of completeness, detailing the subpieces here for future reference:
- WebGL1/OpenGLES2.0 compatibility
- Open-sourcing the JS Solutions build process

With fixes like those in #1427, JS Solutions should all be WebGL1/GLES2.0-compatible now, so the first part of the request is fulfilled.

However, the JS Solutions build process can be further broken into:
(1) C++ MediaPipe --> Wasm binaries
(2) Internal C++ and BUILD rule web helper code (asset handling macros, for example)
(3) The Solutions API framework code (mostly TS; built on top of the MediaPipe wasm binary)
(4) The GPU-based ML inference engine used for several of our demos

With current status as follows:
(1) Progress tracked in issue #877
(2+3) Not yet open-sourced, but not as high priority (can be worked around)
(4) Not part of regular MediaPipe, no ETA on open-sourcing

**Comment by eulercat** [comment]
I'm curious about any updates for "Open-sourcing the JS Solutions build process".
+ @tyrmullen, @futuyao
