### ISSUE TITLE
Any chance of non tflite models or training data for hands?

### ISSUE THREAD

**Issue by martinlyons** [google/mediapipe#186]
Hi,

I really like the potential of Blazepalm and the landmark extractor. There's so much that could be done with them. My potential issue is that TFlite models aren't the most useful since - correct me if I'm wrong - they can't be converted from tensorflow and are only GPU accelerated on mobile. I'd love to work with them on desktop or in Unity as part of a game.

Is there any chance of a release of the original tensorflow models? Even better the training dataset and pipeline mentioned in the blog would allow further experimentation and improvement, though I guess you might want to keep that proprietary.

Thanks!

**Comment by mgyong** [comment]
@martinlyons We have [hand tracking with desktop example with both GPU & CPU](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md) You can use the model with MediaPipe as it is. As mentioned in #13, we will not be releasing training dataset or pipeline due to privacy concerns.
