### ISSUE TITLE
Python Face Mesh landmarks for inverted faces gives wrong results yet Holistic gives correct result

### ISSUE THREAD

**Issue by quickgrid** [google/mediapipe#1915]
I used the python sample codes provided, but [face mesh](https://google.github.io/mediapipe/solutions/face_mesh.html) landmarks are not correct for inverted faces. It works correctly with holistic sample code provided here, https://google.github.io/mediapipe/solutions/holistic.

![download (3)](https://user-images.githubusercontent.com/1857293/115518084-9fda7900-a2a9-11eb-86e2-2e85b2d34c03.png)
![download (2)](https://user-images.githubusercontent.com/1857293/115518098-a4069680-a2a9-11eb-92f6-93e93c1ad4ec.png)

This notebook shows the problem,

https://nbviewer.jupyter.org/github/quickgrid/CodeLab/blob/master/computer_vision/Mediapipe_Python_Holistic_and_Face_Mesh.ipynb?flush_cache=true

Added this link in case of 404 error with nbviewer,

https://github.com/quickgrid/CodeLab/blob/master/computer_vision/Mediapipe_Python_Holistic_and_Face_Mesh.ipynb

**Comment by Anonymous7code** [comment]
I am too facing the same issue while running on rotated cideo frame :
![Screenshot (16)](https://user-images.githubusercontent.com/63298113/115698949-cc15f880-a382-11eb-8a10-701758eccb27.png)
![Screenshot (17)](https://user-images.githubusercontent.com/63298113/115698971-d1734300-a382-11eb-8ac2-4e5c47f84c29.png)
 

and in addition while converting image from BGR2RGB it throws the error mentioned below and still locates the landmark for non-rotated video clip.

`Traceback (most recent call last):
  File "E:\Github\Ml\OpenCV\FaceMesh.py", line 16, in <module>
    frame = cv.cvtColor(frame,cv.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wvn_it83\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in 
function 'cv::cvtColor'`

**Comment by ivan-grishchenko** [comment]
These pipelines use different detection models and that's why the result differs.
Face detector used in Face Mesh pipeline has more strict requirements for face to be positioned vertically.
Pose detector used in Holistic is more robust as it should work for complex use cases like yoga. And it actually detects poses rather than face, and face region is later extracted from pose landmarks.
So if you have prior knowledge about face orientation - use it. If not - run on flipped image as well.
