### ISSUE TITLE
Is Mediapipe using Tflite + GPU delegate on Web ?

### ISSUE THREAD

**Issue by jtg-gg** [google/mediapipe#1934]
I've successfully built mediapipe examples CPU version (using bazel + emscripten, tflite + xnndelegate)
since mediapipe web samples can use GPU, I am trying to do the same. 
TfLite GPU delegate is using EGL initiation, which some how I can pass. 
Currently I am stuck at binding GL_SHADER_STORAGE_BUFFER which is not supported with OpenGL ES 3.0

So If Mediapipe is using Tflite + GPU delegate on Web platform, I am just wondering how much more work is needed ?

**Comment by tyrmullen** [comment]
It's quite a lot of work.  Most GPU delegates use compute shaders, which don't exist for earlier versions of OpenGL ES (and therefore don't exist for WebGL1/WebGL2).  Which is why all our initial demos run the ML CPU-side.  Effectively those GPU ML backends are fundamentally incompatible with web at the moment.  To run ML on the GPU web-side, therefore, you'd need to write an entirely new ML backend (or somehow port over the old one) using only existing GPU technologies for the web (e.g. WebGL).

**Comment by jtg-gg** [comment]
Thank yo @tyrmullen for fast reply
so I just want to confirm
1. Yes mediapipe is using tflite with GPU delegate
2. Mediapipe team has created tflite GPU delegate that is compatible with WebGL

so wondering when the code will be released? any timeline estimate ?

**Comment by tyrmullen** [comment]
To answer your questions, yes, we're using a GPU-based inference engine, which is often compatible with WebGL and always compatible with WebGL2.  However, the engine we're using in MediaPipe JS Solutions is not part of the MediaPipe codebase, and it is unclear if/when it will be released as open-source.
