### ISSUE TITLE
AttributeError: module 'mediapipe' has no attribute 'solutions' problem remained

### ISSUE THREAD

**Issue by xialuoke4062** [google/mediapipe#1959]
Python 3.7.9
macOS 10.14.6

I ran into the same issue. Both #1466 and #1349 recommended to install using `pip install mediapipe`, but after trying with multiple python versions inside/outside different env it still failed with:
`ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)`
`ERROR: No matching distribution found for mediapipe`

So I built the package from source successfully. But the same error was raised when running the sample code:
`AttributeError: module 'mediapipe' has no attribute 'solutions'`
I also made sure #1928 does not happen in my code.

Any suggestions would be greatly appreciated!

**Comment by sgowroji** [comment]
Hi @xialuoke4062, Could you provide the steps to reproduce the above issue. Thanks!

**Comment by xialuoke4062** [comment]
Hi @sgowroji 
I built the package from source within a conda environment, adjusted the python version to 3.7.9, and moved the `mediapipe` directory source code into this environment's `site-packages` directory `(/Users/***/anaconda3/envs/***/lib/python3.7/site-packages').`
Then from the root directory I ran 

> import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands`

from the [sample script](https://google.github.io/mediapipe/solutions/hands#python), and it produced `AttributeError: module 'mediapipe' has no attribute 'solutions'`

**Comment by jiuqiant** [comment]
First of all, mediapipe python macos support 10.15+ if you need to install it from pip.
If you successfully built it from source, please leave your local mediapipe repo directory and run the python demo code. Otherwise, the python source code in the mediapipe local repo will confuse the python interpreter with the mediapipe library search path.

**Comment by jiuqiant** [comment]
First of all, mediapipe python macos supports 10.15+ if you need to install it from pip.
If you successfully built it from source, please leave your local mediapipe repo directory and run the python demo code. Otherwise, the python source code in the mediapipe local repo will confuse the python interpreter with the mediapipe library search path.

**Comment by xialuoke4062** [comment]
Thanks for the reply! So mediapipe does not support anything below 10.15 anymore? 
I did notice your previous comments about leaving the local mediapipe repo and I have already tried that by running the demo code at root, but it still has the `AttributeError: module 'mediapipe' has no attribute 'solutions'` problem

**Comment by sgowroji** [comment]
Hi @xialuoke4062, Did you try/follow the solution mentioned in the above comment from @jiuqiant.

**Comment by xialuoke4062** [comment]
> Hi @xialuoke4062, Did you try/follow the solution mentioned in the above comment from @jiuqiant.

Hi @sgowroji Sorry for the delayed response. Leaving the local mediapipe repo directory did not resolve the problem with the package built from the source.

However, I updated the macOS to Big Sur Version 11.3 and the pip install worked.
