### ISSUE TITLE
Hand Landmarks Estimation on Input Video 

### ISSUE THREAD

**Issue by jameel-malik** [google/mediapipe#1964]
I used the following command to run hand tracking on an input video: 
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt   --input_video_path=/my_path/input1.mp4 --output_video_path=/my_path/output1.mp4

However, I am getting the following error;
![Screenshot from 2021-04-30 16-44-49](https://user-images.githubusercontent.com/19156400/116711899-9650bf80-a9d3-11eb-8b0e-d47e07ac7c1e.png)

The path to the video was correct. 
Could you pl. help to resolve the issue ? thanks

**Comment by mcclanahoochie** [comment]
Try building and running [hand_tracking_tflite](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/desktop/hand_tracking/BUILD#L20) instead,
and then include the input_video_path and output_video_path inside input_side_packets, as such
`--input_side_packets=input_video_path=<input video path>,output_video_path=<output video path>`

The reason is, the `simple_run_graph_main.cc` is for self-contained graphs and can handle side packets, while the `demo_run_graph_main.cc` can run graphs that have input/output streams (and no side packets)

**Comment by jameel-malik** [comment]
Thankyou @mcclanahoochie . 
It works with TensorFlow Lite on CPU. 

Is there a support provided with TensorFlow Lite on GPU that can handle side packets ?

**Comment by mcclanahoochie** [comment]
The code to initialize the GPU from [demo_run_graph_main_gpu](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc#L62) can be added to the simple_run_graph_main.cc in a similar way
