### ISSUE TITLE
Where did upper-body pose landmark go?

### ISSUE THREAD

**Issue by danielbraun89** [google/mediapipe#1995]
25 points upper-body pose landmark disappeared from the docs,  and from the modules.
I can see the commits which removed them, but they contain no description or explanation, just the  "copybara" message.

1. Is the upper-body landmark solution dead for good?
2. Where can we get updates for these kind of changes? is there a changelog somewhere?  

Obviously, it would have been nice if future deprecations will be explained, rather than just pulling the code from under our feet.

**Comment by vpenades** [comment]
I agree, the upper body pose landmark is also useful on its own.

The upper body model only needs to crop the upper body from the input image, which results in enhanced precission, which is required in our use case.

**Comment by txf-** [comment]
There is a description in the tag for v.0.8.4 here : https://github.com/google/mediapipe/releases/tag/v0.8.4

> Removed the upper_body_only option in MediaPipe Pose and MediaPipe Holistic, as the standard model now already handles upper-body-only use cases well

**Comment by chuoling** [comment]
> 25 points upper-body pose landmark disappeared from the docs, and from the modules.
> I can see the commits which removed them, but they contain no description or explanation, just the "copybara" message.
> 
> 1. Is the upper-body landmark solution dead for good?

We previously included an upper-body-only model because the full-body model didn't handle well the cases where the lower body is not visible. However, we've improved the full-body model (across all model complexities: lite, full, heavy) such that it now handles those cases well and a special upper-body-only model is no longer needed.

Going forward, we plan to only maintain the full-body model (which also comes in various versions with different complexities). Note that if desired you could simply ignore the pose landmarks that correspond to the lower body (i.e., index 25~32 in https://google.github.io/mediapipe/solutions/pose.html#pose-landmark-model-blazepose-ghum-3d).

> 2. Where can we get updates for these kind of changes? is there a changelog somewhere?

Unfortunately our open-source release is set up in a way that commits in the upstream codebase get squashed into a single one in the downstream GitHub repo, and the individual commit logs no longer get preserved. We have plans to revisit the set up, but if/when we can adjust it is TBD.

> Obviously, it would have been nice if future deprecations will be explained, rather than just pulling the code from under our feet.

Acknowledged, and appreciate the feedback.

**Comment by sgowroji** [comment]
Hi @danielbraun89, Could you please respond to the above [comments](https://github.com/google/mediapipe/issues/1995#issuecomment-877970342).
