### ISSUE TITLE
Could you provide the original tflite model before quantization?

### ISSUE THREAD

**Issue by jizhu1023** [google/mediapipe#2016]
Hi @jiuqiant @chuoling ,

Mediapipe is really efficient and powerful for developing Mobile AI applications. Many thanks for your great work! 
We recently tested the pose detection and landmark models released just a few days ago which performed very well for our application. But the problem is that the models are quantized so it is not flexible to refine the network structure and retrain the model for our application. Could you send me the original tflite model before quantization for pose detection and landmark?  Thanks in advance : )  My email: jizhu1023@gmail.com

**Comment by jizhu1023** [comment]
Hi @ivan-grishchenko , any comment?

**Comment by sgowroji** [comment]
Hi @jizhu1023,  Please find the github [code](https://github.com/google/mediapipe).

**Comment by PINTO0309** [comment]
There are two ways to convert a Float16 or INT8 quantization model back to Float32.

1. tensorflow-onnx https://github.com/onnx/tensorflow-onnx Support: Float16 / INT8, tflite->ONNX
2. tflite2tensorflow https://github.com/PINTO0309/tflite2tensorflow Support: Float16, tflite->ONNX,tflite float32/16/INT8, TFJS, TFTRT, OpenVINO, Myriad Blob, CoreML

However, the problem is that even if both methods can generate saved_model and onnx, they cannot bring them back to a state where they can be retrained. It is just a model format conversion.

I am a little concerned that this work might antagonize the great developers of MediaPipe. :crying_cat_face:
