### ISSUE TITLE
Multiple textures on the model

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#2076]
Hello, I would like to ask if the UUU file format can support multiple textures? Since many models require multiple textures to merge into one complete texture image, if there is such a way, can you tell me how to do it? thank you

**Comment by sgowroji** [comment]
Hi @z7212819 Adding [information](https://github.com/google/mediapipe/issues/1074#issuecomment-685129974) about UUU file

**Comment by z7212819** [comment]
@sgowroji Thank you very much for your reply. Now I can convert any OBJ model to UUU format, and the rendering effect can be achieved through a single texture. However, if the OBJ model has multiple textures and is converted to UUU, how can I read these textures? Since there seems to be only one definition of texture in the chart and calculator, my idea is how to modify the chart or calculator to read multiple textures at the same time.

**Comment by hadon** [comment]
It looks like GlAnimationOverlayCalculator renders only one texture across all of the texture coordinates in the animation.  I assume that all of the texture coordinates in the UUU files refer to a single texture, and that the UUU format and the GlAnimationOverlayCalculator do not currently support rendering multiple textures in one animation.  Maybe @tyrmullen can let us know if there is any recommended approach for rendering multiple textures.

**Comment by tyrmullen** [comment]
The GlAnimationOverlayCalculator is pretty simplistic and low-level, and multiple textures was not something we intended to support.  However, I can see two paths forwards:
(1) For a quick workaround, you can combine all textures into one (this can be done before the .obj is even converted to .uuu, or else this can be made a part of the .uuu conversion code).  Software can help do this automatically, but it wouldn't be too hard to just concatenate multiple textures together into a new one, and offset the tex-coords of the appended textures accordingly.  Then the rest of the pipeline can be kept the same.
(2) To actually support multiple textures, you would need to do what you were suggesting: modify the graph and calculator to optionally read multiple texture streams (basically shadowing all the places where one texture is used with a second texture).  You'd also need to either:
     (a) add in code to allow the .uuu parsing to read in two(or more) different TriangleMesh structures for each animation frame, effectively treating each texture as defining its own object, and rending two objects at a time
     (b) add in code to tie each vertex to one of the two textures (when reading the .uuu file), and then also editing the shader code to render each vertex with the appropriate texture

My recommendation would be (1) since it's the easiest.

**Comment by sgowroji** [comment]
Hi @z7212819, Could you please respond to the above comments. Thanks!

**Comment by z7212819** [comment]
@tyrmullen Thank you very much for your reply. Now I have adopted the first scheme, which has achieved the effect. However, the smoothness of my model is not as good as yours.

**Comment by tyrmullen** [comment]
Glad to hear that the approach seems to be working for you!

I'm not quite sure what you mean by "smoothness" in this context (i.e. is this smoothness of animation, model geometry, or texturing?).  If it's not a multi-texturing issue, but rather a different bug, then let's close this issue and create a new one dedicated to that problem.  If it's a multi-texturing issue, then please add more specifics and details here.

**Comment by sgowroji** [comment]
Hi @z7212819, Please go through the above comment and raise a new issue with complete observation regarding smoothness as you mentioned in this [comment](https://github.com/google/mediapipe/issues/2076#issuecomment-861201867) with any video or error logs to understand it much better for further investigation.  We are closing this issue as the main thread was addressed in it.
