### ISSUE TITLE
Facing issues while working on JS examples mediapipe.

### ISSUE THREAD

**Issue by bhargav-sudo** [google/mediapipe#2134]
HI,

I am working on Face detection mediapipe JS example..
It is not detecting anything.
I used code from this [https://google.github.io/mediapipe/solutions/face_detection#javascript-solution-api](url)
I am getting the following error.

![Screenshot from 2021-06-07 11-29-40](https://user-images.githubusercontent.com/57169077/120966778-53c59400-c784-11eb-96ec-9322b3857d96.png)

Thanks,
Bhargav.K.

**Comment by sgowroji** [comment]
Hi @bhargav-sudo, Could you please provide your code changes if there are any. Have you tried doing the same in [codepen](https://codepen.io/mediapipe/full/dyOzvZM)?

**Comment by bhargav-sudo** [comment]
HI @sgowroji This is my js and html code

Js code : 

const videoElement = document.getElementsByClassName('input_video')[0];
console.log(videoElement);
const canvasElement = document.getElementsByClassName('output_canvas')[0];
const canvasCtx = canvasElement.getContext('2d');
console.log(canvasCtx);


function onResults(results) {
  // Draw the overlays.
  canvasCtx.save();
  canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
  canvasCtx.drawImage(
      results.image, 0, 0, canvasElement.width, canvasElement.height);
  if (results.detections.length > 0) {
    drawingUtils.drawRectangle(
        canvasCtx, results.detections[0].boundingBox,
        {color: 'blue', lineWidth: 4, fillColor: '#00000000'});
    drawingUtils.drawLandmarks(canvasCtx, results.detections[0].landmarks, {
      color: 'red',
      radius: 5,
    });
  }
  canvasCtx.restore();
}

const faceDetection = new FaceDetection({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.0/${file}`;
}});

// faceDetection.setOptions({
//  minDetectionConfidence: 0.5
// });

faceDetection.onResults(onResults);

const camera = new Camera(videoElement, {
  onFrame: async () => {
    await faceDetection.send({image: videoElement});
  },
  width: 1280,
  height: 720
});
camera.start();


HTML : 

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js" crossorigin="anonymous"></script>

  
</head>

<body>
  <div class="container">
    <video class="input_video">
        <source src="/home/local/ZOHOCORP/bhargav-10476/Downloads/Detection-Video.mp4">
        </source>
    </video>
    <canvas class="output_canvas" width="1280px" height="720px"></canvas>
  </div>


</body>
<script type="text/javascript" src="/mediapipejsexamples/facedetection.js"></script>
</html>



Thanks.

**Comment by tyrmullen** [comment]
Have you checked (using Chrome's built-in "Network" tab, for example) that all fetches are succeeding and not returning 404 errors?  I'm not sure 'face_detection@0.0' would work... maybe try face_detection@0.3 or face_detection@0.1?

**Comment by bhargav-sudo** [comment]
Hi @tyrmullen I will check that and let you know..

Thanks.

**Comment by bhargav-sudo** [comment]
Hi @tyrmullen I had tried like you said ..
I gave 'face_detection@0.1' and face_detection@0.3 and it shows errors like below

**face_detection@0.1 :**
![Screenshot from 2021-06-08 11-05-05](https://user-images.githubusercontent.com/57169077/121128875-b6cd2e80-c849-11eb-82af-e7578c4e8517.png)


face_detection@0.3 : 
![Screenshot from 2021-06-08 11-05-23](https://user-images.githubusercontent.com/57169077/121128930-cfd5df80-c849-11eb-9029-dc0c46c43f0f.png)

Thanks.

**Comment by tyrmullen** [comment]
You can also just navigate to those pages directly if you want to check whether they exist.  (Although I'd really recommend the "Network" tab in the Chrome Dev Tools; it's great for showing all of your loading successes and errors at the same time).  When I do, I can verify that:
https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.0/face_detection.js - EXISTS
https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.3/face_detection.js - EXISTS
And all other versions do NOT exist.

You can also use unversioned (https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js) but then you may get broken if the API updates out from under you.

So I think the first error you had in your last post (face_detection@0.1) is because that face_detection version doesn't exist.  While the second error you had (face_detection@0.3) means it succeeded in loading "face_detection", but something went wrong when trying to load "drawing_utils".  Note that you'll probably want to target a version for EACH of those scripts (face_detection, camera_utils, drawing_utils, and control_utils), and ALSO the loading redirect (that "locateFile" function's URL path).  In fact, looking again, I suspect your initial error might be because you had a mismatch-- you had "face_detection@0.0" for the redirect, but just "face_detection" for the actual script, which will point to a later version by default.

The CodePen is not the most up-to-date, but you can use that to make sure you have some versions which should at least work: http://mediapipe.dev/demo/face_detection.  It uses @0.0 for the face_detection.js (and the loading redirect), while it uses @0.1 for all of the other utility scripts.

**Comment by bhargav-sudo** [comment]
Hi @tyrmullen thanks for response.

I did not installed any npm packages ..
Do I need to install anything before trying the JS samples...?

Thanks.

**Comment by tyrmullen** [comment]
I did-- @0.1 for those should be fine.  But I think it's already basically working for you-- I see it printing out ResultData and boundingBox data.  The error is now pointing to drawingUtils never being defined-- those lines of code look like TypeScript demo code accidentally got copied to a pure JavaScript demo.  For your demo, I think you can just remove the "drawingUtils." and it will work (so just call "drawLandmarks" or "drawRectangle" directly instead).  The CodePens will show working versions (or else it's much more obvious when they're broken), so I'd recommend checking there first in the future.

**Comment by bhargav-sudo** [comment]
Hi @tyrmullen 

I removed drawingUtils ..

It works for me ..
But is is showing two outputs Instead of one..

One is getting a detected face..
and other one is webcam input.


Any Idea about this .?

Thanks for the help.
Bhargav.K.
