### ISSUE TITLE
Error while compiling python project with pyinstaller

### ISSUE THREAD

**Issue by Fqlox** [google/mediapipe#2162]
I have issues compilling a project with mediapipe python on mac, it's using selfie augmentation's solution.
I tried to compile an .app from a .py file using pyinstaller.

so far I tried 
```
pyinstaller  --windowed --noconsole pose_edge.py

pyinstaller  --onefile --windowed --noconsole pose_edge.py

pyinstaller --noconsole pose_edge.py
```

The .app does not open, and if I try the unix exec, I get

```
  Traceback (most recent call last):
  File "pose_edge.py", line 26, in <module>
  File "mediapipe/python/solutions/selfie_segmentation.py", line 54, in __init__
  File "mediapipe/python/solution_base.py", line 229, in __init__
FileNotFoundError: The path does not exist.
[36342] Failed to execute script pose_edge

```

**System information** 
- Mac OS : 10.15
- Python 3.8
- Installed using pip on conda env
- Mediapipe 0.8.5
- opencv-contrib-python 4.5
- pyinstaller 4.3

**Comment by AXH312** [comment]
I also have the same problem but i am using a windows 10 OS. with the following: 
Python 3.9
Mediapipe 0.8.4
opencv-contrib-python 4.5
pyinstaller 4.3

**Comment by nemwiz** [comment]
Mediapipe library requires certain files to run (these are mainly TensorFlow files with `.tflite` extension.)
Since these are loaded dynamically, PyInstaller doesn't know about these and during the compilation phase you need to copy them over to the `dist` directory.

This can be achieved via `datas` property in PyInstaller spec file.
You can read more about it in the [PyInstaller docs](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle)

Here is my spec file. See under `datas` property and ensure that path is correct since directories under `venv` are OS specific.

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['.'],
             binaries=[],
             datas=[('venv\\Lib\\site-packages\\mediapipe\\modules', 'mediapipe\\modules'),],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')
```

**Comment by RohitSingh1226** [comment]
The rest of the arguments inside 'exe' and 'coll' are going to be the same?

**Comment by ElectroCoderEC** [comment]
For anyone who wants a fast solution meanwhile someone fixs this error. It works for me, Just get module path from meadiapipe or the module what you get error and in python console:

import mediapipe
print(mediapipe.__file__)

once you get path folder, just copy all mediapipe folder and paste in your folder where you have your exe file and that is all!. Luck

**Comment by jiuqiant** [comment]
> For anyone who wants a fast solution meanwhile someone fixs this error. It works for me, Just get module path from meadiapipe or the module what you get error and write in python console:
> 
> import mediapipe print(mediapipe . __ file __ ) (without black spaces)
> 
> once you get path folder, just copy all mediapipe folder and paste in your folder where you have your exe file and that is all!. Luck

Thanks for providing the solution! I am going to close this issue now.

**Comment by JoraSN** [comment]
> For anyone who wants a fast solution meanwhile someone fixs this error. It works for me, Just get module path from meadiapipe or the module what you get error and write in python console:
> 
> import mediapipe print(mediapipe . __ file __ ) (without black spaces)
> 
> once you get path folder, just copy all mediapipe folder and paste in your folder where you have your exe file and that is all!. Luck

For me, when I was compiling my .py script that imported mediapipe using pyinstaller I couldn't use the --onefile command or I would get the same error. I haven't found a solution for this other than not using --onefile.

**Comment by miimzyu** [comment]
Since the solutions described here didn't work for me I want to add what I found out.

I used [Auto PY to EXE](https://pypi.org/project/auto-py-to-exe/) and used the option _Additional Files_ > _Add Folder_to add my entire mediapipe folder
`C:\Users\[YOUR NAME]\AppData\Local\Programs\Python\Python310\Lib\site-packages\mediapipe`

I left all the other setting as default except for Onefile and Console Window.
Both _One Directory_ + _Console Based_ and _One File_ + _Window Based (hide the console)_ worked for me.

In my case I also had a problem with cvzone which gave the same error as mediapipe so I added the folder the same way as mediapipe.

**Comment by ITSAIDI** [comment]
@miimzyu Thanks It's working  properly for me

**Comment by wulf11** [comment]
I got it working with:

pyinstaller --add-data "C:\Users\USER\AppData\Local\Programs\Python\Python310\Lib\site-packages\mediapipe;mediapipe/" YOURSCRIPT.py

so just trace back your mediapipe module path and modify the command above..
you can also add "--onefile" if you want to just deploy one .exe
