### ISSUE TITLE
HandTracking precision

### ISSUE THREAD

**Issue by SuzieSzn** [google/mediapipe#217]
I have been developing gesture recognition function. 
But I find when I'm moving hand, sometimes the landmarks don't track the hand.
Specially  gesture 'One',  when I move 'One' to the front of my face, the index finger always is missing, Mediapipe landmarks represent it as 'fist' not 'one'. when the fingers have crossed or overlapped, the tracking precision is lower.

Do you plan to improve the precision in that case? and did you also meet the problem when you developed the gesture? if there is some advice?
Thank you

**Comment by pablovela5620** [comment]
Just out of curiosity, do you start with a closed fist and then make the one gesture? If so then most likely this has to do with the fact that it retrieves bounding boxes based on the previous landmark. It has a belief that the bounding box is much smaller and because of this, the entire hand is not fed into the network making it look like the landmark detector is less accurate than it actually is at least for this specific case.

A naive solution would be to have the palm detector run on every frame and this would improve the accuracy but at the great cost of inference time since the palm detector seems to be way more computationally expensive.

Try seeing if you still have a problem with the one gesture starting from an open hand position.

**Comment by SuzieSzn** [comment]
@pablovela5620 
I have the palm detector run on every frame on your suggestion.
The palm rect was right on every frame, and the landmarks still didn't track the hand pose.

**Comment by Momohanfeng** [comment]
![111](https://user-images.githubusercontent.com/4652023/68441790-39bf7a80-020a-11ea-9069-4aa231452135.png)

**Comment by Momohanfeng** [comment]
![222](https://user-images.githubusercontent.com/4652023/68442612-85732380-020c-11ea-8d2e-a7ca4a51333e.png)

**Comment by mgyong** [comment]
This is something we will address in future versions of hand tracking model
