### ISSUE TITLE
Loading holistic 0.3 in the browser fails

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#2181]
**System information** (Please provide as much relevant information as possible)

- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: **Chrome**
- Solution ( e.g. FaceMesh, Pose, Holistic ): **Holistic**

**Describe the current behavior:**
I have an Angular app using Holistic. With using `v0.1`, my build process would copy: `node_modules/@mediapipe/holistic/` to `assets/models/holistic/` to when I load holistic, all the files are loaded localy:
```js
new holistic.Holistic({
      locateFile: (file) => {
        console.log('Holistic', 'loading', file);
        return `assets/models/holistic/${file}`;
      }
    });
```

For `v0.1`, this worked fine.
Now I upgraded to the latest, `v0.3.1620694839`, and this no longer works.

Console log:
![image](https://user-images.githubusercontent.com/5757359/122179509-e4d4f300-ce87-11eb-9390-e5d0fa594d30.png)

Notice it is saying "Holistic loading" for the files, and all of them are indeed found:
![image](https://user-images.githubusercontent.com/5757359/122179966-4bf2a780-ce88-11eb-8b46-58af6bdfe051.png)

But then the log says it is looking for a file under `third_party` path, which (a) doesn't exist and (b) there is no network request going out to such path.
> Calculator::Open() for node "holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite. [type.googleapis.com/mediapipe.StatusList='\n\xf6\x01\x08\x02\x12\xf1\x01\x43\x61lculator::Open() for node \"holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator\" failed: Failed to read file third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite.']

You can see the files under the latest distribution here:
https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.3.1620694839/

**Describe the expected behavior:**
Loading new version should work.

**Comment by tyrmullen** [comment]
The specific file "pose_landmark_full.tflite" seems to be included in that distribution, but isn't being found at the expected location in the wasm runtime.  I don't see that in the list of 200's, so perhaps there's a fetch failing still?

I don't think there's an issue with the new version, though, since the CodePen appears to have been already updated to 0.3.1620694839 (https://codepen.io/mediapipe/pen/LYRRYEw) and is functioning properly for me.

Don't worry too much about the "third_party" reference-- the path being printed out is the internal wasm-runtime directory structure, and does not reflect where files are expected to be found outside of the .wasm.  To be explicit, the network request should still be "https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.3.1620694839/pose_landmark_full.tflite".

One other thing to double-check is that all the different script versions have been updated fully; you can use the CodePen as a reference for those version numbers (in the "HTML Settings").

**Comment by AmitMY** [comment]
Thanks @tyrmullen 
The list of network requests I attached is the full list, there is no additional request going out and failing.

And these are the files I'm hosting locally: (automatically copied using angular build system)
![image](https://user-images.githubusercontent.com/5757359/122350830-d94bff80-cf4d-11eb-8252-cacb0238212d.png)

**Comment by tyrmullen** [comment]
Then that's definitely the issue.  It looks like the file fetching code for the .tflite models was changed to now be triggered in the optionsConfig onChange() callback for 'modelComplexity'.  So if you change the 'modelComplexity' setting (valid values of 1, 2, or 3, I believe) using setOptions(), that should cause a network fetch to be initiated to the locateFile() path you specified, looking for pose_landmark_xxxx.tflite, which should resolve the problem.

If that works, then I think perhaps there is a bug still to be fixed here, since it sounds like we might only load the model when the settings are changed, and do not load the initial model specified at construction time...  But let me know if this workaround fixes the problem for you first!

**Comment by AmitMY** [comment]
Thanks @tyrmullen, this works.

Full code:
```ts
this.model = new holistic.Holistic({
      locateFile: (file) => {
        console.log('Holistic', 'loading', file);
        return `assets/models/holistic/${file}`;
      }
    });

    this.model.setOptions({
      modelComplexity: 1
    });
```

I agree - it should default to some complexity and not spaz out.

**Comment by UrielJavier** [comment]
@tyrmullen @AmitMY thnks, thats works!

**Comment by mhays-google** [comment]
Will add default values for modelcomplexity -- will be available this week.

**Comment by AmitMY** [comment]
Commenting so not stale

**Comment by mhays-google** [comment]
This is a caching issue on behalf of jsnotify.  I am making it a habit now to purge URLs that use the default/major/minor versions to load our solutions.  Those who use the specific timestamped solution will probably not encounter these issues.  I'm weighing different options to make this less of a problem in the future.

**Comment by tyrmullen** [comment]
Default values for modelcomplexity have been added in, so the workaround above should hopefully no longer be necessary on newer versions of the APIs.  Closing as fixed, but please reopen if the issue pops up again.

**Comment by ben-xD** [comment]
Thanks for letting me know. 

I tried the latest version [`0.4.1628005088`](https://www.npmjs.com/package/@mediapipe/holistic), and couldn't find `VERSION` by using `import {Holistic, Results, VERSION} from "@mediapipe/holistic";`. 

Typescript said: `Module '"@mediapipe/holistic"' has no exported member 'VERSION'.`
