### ISSUE TITLE
Getting "Memory access out of bounds" error on Chrome 91.0.4472.101

### ISSUE THREAD

**Issue by apcjs** [google/mediapipe#2188]
The following pen, which is the demo code for Holistic, works fine in the desktop, but on Chrome Mobile for Android ver 91.0.4472.101, I get a "Memory access out of bounds". I tried this on multiple devices with the above version of Chrome, and seeing the same error. It works good with previous versions of Chrome for Android (including Chrome for Android 92 Beta).

https://codepen.io/arunitc/pen/mdWomyz

**Comment by sgowroji** [comment]
Hi @apcjs, Could you please go through this https://github.com/google/mediapipe/issues/2082#issuecomment-852470806.

**Comment by apcjs** [comment]
Hi @sgowroji, thanks for the reply. The demo works fine in other versions of Android Mobile including 92 beta. It fails only in the mobile version of 91.

**Comment by tyrmullen** [comment]
Unfortunately, I believe this is due to a Chromium regression (https://bugs.chromium.org/p/v8/issues/detail?id=11863).  There are some potential workarounds, and there's more related discussion in the Emscripten issues (see https://github.com/emscripten-core/emscripten/issues/14538).  For now, we're waiting to see if only 91 stable will be affected before committing resources to fixing it; if on the other hand the problem looks like it will persist in following Chrome versions then we'll have to investigate further workarounds on our end.

**Comment by tyrmullen** [comment]
@apcjs As Android Chrome Stable is now past M92, do you mind testing to see if the issue still repros?  If not, let's close this issue out with a note to avoid the problem M91 versions on Android Chrome.

**Comment by apcjs** [comment]
@tyrmullen, I do not experience this issue in Chrome 92 anymore. Closing this issue. Thanks
