### ISSUE TITLE
Open model source for custom training

### ISSUE THREAD

**Issue by whatisor** [google/mediapipe#2195]
I as well as many AR developer  realized hand-tracking model is not good for use-case of AR camera( such as grayscale, non-selfie).
Can Mediapipe open Model source for fork?
In deep learning, without model source, it is NOT an open source project.
Thank you.

**Comment by sgowroji** [comment]
Hi @whatisor, Could you please elaborate your use case with complete details.

**Comment by whatisor** [comment]
I am using  mediapipe for HTC VIVE Focus Plus (android) to develop a hand tracking solution.
It gets very low accuracy in comparison with  web demo of mediapipe.
Similar to this, but I think it is even worse
https://github.com/google/mediapipe/issues/1014

**Comment by sgowroji** [comment]
Hi @whatisor, Can you provide a recorded video to understand it much better. Thanks

**Comment by yolo-1111** [comment]
I COMPLETELY AGREE with @whatisor. Im having MASSIVE problem with particularly with mediapipe's landmarks outputs. It is disaster if there is a small head turn (even over 30 degree) that is simply useless.  What is the purpose of releasing mediapipe without releasing model source for custom training when its current outputs are just do bad and highly inaccurate that they are rendered useless? Its not that it is only x% accurate....i mean it has problem with almost every output. We cant create meaningful visual content when these tracking outputs are just plain bad.  

I agree with the whatisor on two major points - 
1) outputs are more highly inaccurate than those shown in demo - STARK difference
2)  "In deep learning, without model source, it is NOT an open source project. " especially if outputs are so highly inaccurate almost all the time.

Let me ask - What is Google mediapipe trying to accomplish with this release of models that generate inaccurate outputs?
What do you want us to do with it? 

Google Mediapipe is wasting everyone's time. It has not respect for the users. Why doesn't Mediapipe open Model source for fork and let users add more data, try to improve the model and  share the improve the outputs/model and knowledge with everyone else? Facebook and others do it all the time. They basically provide an ecosystem where developers will improve and expand on it. Otherwise it is simply waste of time.
And i think you have gotten ENOUGHHHHH feedback from github users that mediapipe HAS SO MANY PROBLEMs that it simply isnt usable in the real world. Hope you don't ask me to describe use case.

**Comment by doduythao** [comment]
Same, tried on other hand gesture datasets and the result was really bad. They should change this

**Comment by kuaashish** [comment]
Hello @whatisor,
We are adding new feature into our new solutions [model maker](https://developers.google.com/mediapipe/solutions/model_maker) which hold capability to input your own datasets with minimal datapoints and predict as per your required use case. 

However, We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
