### ISSUE TITLE
Help!  Where is the path of the source code file which the images read from  OpenCV to send to  neural network for the c++ vesion?

### ISSUE THREAD

**Issue by sewage1213** [google/mediapipe#2210]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):Linux Ubuntu 18.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):gcc 7.5
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): C++ 11
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):3

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

We  want to change the size of the images  sent to the  network. However, the whole  mediapipe project is so big.  Can you tell us  where is the codes for images reading and how to change the image size  for the c++ version ?

**Comment by sgowroji** [comment]
Hi @sewage1213, Could you please elaborate your use case with more details. Thanks!

**Comment by sewage1213** [comment]
I'm trying to compile and modify the source code. Now I want to check whether the image resolution is a fixed size when the video image read from opencv is sent to the mediapipe network, and whether it will be consistent with the resolution of my video source. In addition, I want to know where the code for sending the video stream to the mediapipe network is.Thanks!

**Comment by ayushgdev** [comment]
Hello @sewage1213 
The information about the image resolution accepted by the MediaPipe framework is available in the [Model cards](https://github.com/google/mediapipe/blob/c31a4681e5aa833bd53b7001969905efa1d826fb/docs/solutions/models.md) of respective solutions. MediaPipe framework can internally convert the input video stream to the dimensions required by the solution TfLite models so no extra conversion is required. This is done in the `ImageToTensorCalculator`. 
For example, in pose detection solution, [ImageToTensorCalculator](https://github.com/google/mediapipe/blob/c31a4681e5aa833bd53b7001969905efa1d826fb/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L118) converts the input image frame into a tensor of 256x256x3 since that is the required dimension by the model (check model card). 
Hence the dimensions depend on the solution so you can explore the solution of your preference in a similar fashion.

About the entry point for MediaPipe solution, the graphs (.pbtxt files) are used to start processing images/videos. This is given when you[ run the application](https://github.com/google/mediapipe/blob/c31a4681e5aa833bd53b7001969905efa1d826fb/docs/getting_started/cpp.md#option-1-running-on-cpu) by providing the `--calculator_graph_config_file=` arg . For example, the graph file for pose is [mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt](https://github.com/google/mediapipe/tree/master/mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt)
