### ISSUE TITLE
FaceMesh jawline moves significantly when (partly) occluded

### ISSUE THREAD

**Issue by Grieverheart** [google/mediapipe#2223]
![animated](https://user-images.githubusercontent.com/1652929/123758246-063dd200-d8bf-11eb-9779-2873b7bb8bf5.gif)
**System information**
- OS Platform and Distribution: Mac OS 10.15.7
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.5
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Python 3.8.10

**Describe the expected behaviour:**
Ideally, the face landmarks should be stable when (partly) occluded, while tracking. Unfortunately, if an occlusion is introduced, the landmark positions jump around. This is especially evident close to the jawline.

**Standalone code you may have used to try to get what you need :**

Just used the Python code available [here](https://google.github.io/mediapipe/solutions/face_mesh.html)

**Other info / Complete Logs :**
If more information is needed, I can attach pictures.

**Comment by sgowroji** [comment]
Hi @Grieverheart, Could you please record a video while reproducing the above behavior to understand the issue.

**Comment by Grieverheart** [comment]
@sgowroji I updated the original post with an animated gif showing the issue.

**Comment by zwfcrazy** [comment]
There are many situations that may increase the error of face landmarks. Occlusion is definitely one of them. Others like some strange behaviour may also increase the error. For example, open your mouth like a 0, not an O. This face landmark model also does not recognize eye closure.
I think this is mainly caused by the shortage of corner samples in the training dataset. It will take a lot of time to refine the model as it is very hard to cover every corner situation in the training dataset.
Meanwhile, I don't think accurate landmark localization is a major target of mediapipe.
