### ISSUE TITLE
Need support ImageData in Javascript Pose Detection

### ISSUE THREAD

**Issue by z0y1** [google/mediapipe#2241]
pose > javascript:

```
export type InputImage = HTMLVideoElement | HTMLImageElement | HTMLCanvasElement;
...
send(inputs: InputMap, at?: number): Promise<void>;
```

cause ```POSE``` only support one person, i pre split the source Image into serverl rectangles( by face detect), those sub rect images come from arraybuffer, if pose.send support ImageData, i can directly send pixel data into POSE detection. now i have to draw into Canvas first ,then put the Canvas into POSE detection, I think it's a waste of time..

**Comment by sgowroji** [comment]
Hi @z0y1, Could you share your use case with complete details. Thanks!

**Comment by z0y1** [comment]
> Hi @z0y1, Could you share your use case with complete details. Thanks!

Hi, here is my process pipeline, (to get the whole three person‘s pose landmarks)，if pose.send support ImageData，**step2**  will be not needed anymore，and code run faster。ImageData contains buffer,width,height, it seems more convenient to use.
![image](https://user-images.githubusercontent.com/1248666/124294601-7633ad00-db8a-11eb-951b-7d1c060a2bf1.png)

**Comment by tyrmullen** [comment]
Just so this issue has some response-- yes, there's no reason we can't support ImageData, ImageBitmap, and several other input types while we're at it.  In fact, we're generally just using it directly in a call to [gl.texImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D), so any of those listed sources should work.  Until we update our InputImage type in the TS defines, you can just cast whatever type you want to one of the existing types (say HTMLCanvasElement, since that has .width and .height just like ImageData)-- for example: `await pose.send({image: imageData as unknown as HTMLCanvasElement});`

On an unrelated note, for your pipeline, I'd recommend *not* using ImageData if you can help it, since that will pull all the data back to the CPU from the GPU, which can be relatively slow/expensive.  If you're on Chrome, then perhaps using an ImageBitmap instead could help, as it keeps the resources GPU-side (but creating one is a bit trickier than using ImageData).

Eventually for input, we'll probably want to allow for direct WebGL texture inputs as well, so that users can have complete control of their input if desired (for potential maximum efficiency as well)-- but that would require some system refactoring, so it likely won't happen for a while.

**Comment by z0y1** [comment]
Thank you for your reply,and the advice! i'm so glad to hear ImageData, ImageBitmap will be support as input source.

**Comment by sgowroji** [comment]
Glad to know you resolved. We are closing this issue now. Reach us back if you have any relevant query on it.
