### ISSUE TITLE
Pose tracking spine information

### ISSUE THREAD

**Issue by NathanielEssenberg** [google/mediapipe#2358]
**System information** (Please provide as much relevant information as possible)
I am running MediaPipeUnity, and for now target platforms are Android, iOS, and PC

- MediaPipe Solution (you are using): [MediaPipeUnity](https://github.com/homuler/MediaPipeUnityPlugin) version based on MediaPipe 0.8.6
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No): Willing, but I don't have enough in-depth experience with MediaPipe, unfortunately

**Describe the feature and the current behavior/state:**
I want to ask if there is any way to detect somehow landmarks along the spine for the Pose detection, so that it's possible to see the shape of the spine to some degree. Even just 1 or 2 points would help.

**Will this change the current api? How?**
Yes. It will change the number/list of landmarks for Pose and Holistic tracking and any code using those

**Who will benefit with this feature?**
Anyone interested in the shape of the spine

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by remag2069** [comment]
well well well, I might have just the thing. Although it is not a direct solution, it is a workaround. but it works, that's all that matters right, idk.

So, in order to detect the bend in the spine, I utilize the torso lengths. The theory is that, when I bend my spine, I effectively shorten the distance between my shoulder and my hip. And since the media pipe detects these two points, I can get the distance between them. So at the start of the program, if u save the original torso length (without any bends), and use it as a reference.

all i m saying is green (no bend) big and red (with bend) small. This gives u the magnitude of bend
straight spine:
![image](https://user-images.githubusercontent.com/51650745/129665029-9a4dc36f-8e2c-4814-88f6-7a5886a74f38.png)


bent spine:
![image](https://user-images.githubusercontent.com/51650745/129664892-9b3f1cb8-6ae2-4733-af75-36a2b92d3cfb.png)

Now with this basic idea, u cld plot both the torso lengths and also find the direction of bend.
![image](https://user-images.githubusercontent.com/51650745/129664268-3630de48-0602-4820-8dda-8a90e7b86fb8.png)

**Comment by ROBYER1** [comment]
Has anyone applied this in a project? Thinking of using a similar solution to identify pelvic/postural tilt of the hips/shoulders, however, Mediapipe tracked points for the shoulders and hips barely move in relation to any tilt of the hips or shoulder - especially in a side on view like this diagram.
![image](https://user-images.githubusercontent.com/10745594/137762435-79e125ce-57ed-49f9-ab84-f60ea41e7362.png)

**Comment by aerarslan** [comment]
@ROBYER1 I am trying exactly the same thing. Right now I am trying to understand how Z points are calculated but it seems like it is a bit hard to understand looking to Z axes because they are flickering a lot depending on all the things. Have you found any solution to apply something to detect postural assessment? I am working with frontal view

**Comment by ROBYER1** [comment]
I have not been successful yet in this, I am hoping for a reply from Google staff here to acknowledge this improvement to the pose tracking. I also mentioned this issue on the Mediapipe Slack channel where a lot of other developers mentioned having the same issue. Without additional tracking data it is very difficult to assess posture using Mediapipe currently.
