### ISSUE TITLE
Pose example application has very low performance on a Honor View 10 (Android 9) smartphone

### ISSUE THREAD

**Issue by alien190** [google/mediapipe#2395]
**System information**
- Stock example script provided in Mediapipe: 
https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu

The APK  was built by command:

`bazel build -c opt --config=android_arm64 //mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu`

- OS Platform and Distribution: the APK was built on Ubuntu 20.04 and tested on Android 9
- MediaPipe version:  0.8.6
- Bazel version: 4.1.0
- Solution: Pose
- Programming Language and version: Java

The Pose solution has been tested on Honor View 10 smartphone (https://www.gsmarena.com/honor_view_10-8938.php). 
OS: Android 9
Chipset: Kirin 970 (10 nm)
CPU: Octa-core (4x2.4 GHz Cortex-A73 & 4x1.8 GHz Cortex-A53)
GPU: Mali-G72 MP12

The performance looks like around 10 FPS or low. 

The same build has the well performance (around 30 FPS) on Sony Xperia XZ1 Compact (https://www.gsmarena.com/sony_xperia_xz1_compact-8610.php)
OS: Android 9
Chipset: Qualcomm MSM8998 Snapdragon 835 (10 nm)
CPU: Octa-core (4x2.45 GHz Kryo & 4x1.9 GHz Kryo)
GPU: Adreno 540

**Comment by sgowroji** [comment]
Hi @alien190, Could you please attach a video or screenshot with the  above observation. Thanks!

**Comment by alien190** [comment]
Hi @sgowroji, thanks for your reply.

Please have a look at the two videos of testing Pose example application:
* Honor View 10 (low performance) https://drive.google.com/file/d/1bwxQFNNtiDTe4twXY2tG8XOmU7rkLbU7/view?usp=sharing
* Sony Xperia XZ1 Compact (well performance) https://drive.google.com/file/d/11jzOovXA9ZyNB30h32l-g0B-McP_q3Xo/view?usp=sharing

Thank you.

**Comment by alien190** [comment]
Hi @sgowroji,

Are these videos enough or maybe some additional information is required?

Thank you.

**Comment by sgowroji** [comment]
Hi @alien190, We have assigned it to the engineer who can assist you well on your query. Please subscribe to thread to get the latest updates on it. Thanks!

**Comment by kuaashish** [comment]
Hi @alien190,
We are revisiting the older issues, this issue must be happening due to the device using, It is possible that on the other devices, xnnpack doesn't support the same OP(mediapipe use default xxnpack delegate), but instead of failing, it silently runs on CPU, which would hurt performance. All our mediapipe solutions have been tested in the device chips Snapdragon, Tensor. However, we recommend to try out with delegate NNAPI and this can be done by changing the delegate to NNAPI https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L144. Thank you!

**Comment by fchen09** [comment]
@alien190 
Hi~Sir,
I am running the same apk on Samsung Note 8 and Note 10+. It can only run 15 fps. Could you share your apk to me, so I can check if it can run 30 fps on my devices. Thank you! My email is fchen09@syr.edu
