### ISSUE TITLE
Why the ObjectronGpuSubgraph's input image is assumed to have aspect ratio 3:4?

### ISSUE THREAD

**Issue by homuler** [google/mediapipe#2535]
I'm not sure if this is the right place to ask this, but I have a question.

Objectron internally requires the aspect ratio of the input image to be 3:4.
https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/graphs/object_detection_3d/object_occlusion_tracking.pbtxt#L52-L58
https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/modules/objectron/objectron_gpu.pbtxt#L5

Why is this?

At least, this value is hard-coded as a `GlAnimationOverlayCalculator`'s option value, 
https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/graphs/object_detection_3d/object_occlusion_tracking.pbtxt#L115-L121
so I understand the image is cropped in `object_occlusion_tracking`, but I don't know why `ObjectronGpuSubgraph` assumes that the input image to have aspect ratio 3:4.

**Comment by ahmadyan** [comment]
This is due to the combination of legacy code (backward compatibility) as well as device support in rendering. 

Previously our single-stage models would pass the entire image to the model, and they required the image to be 3:4 aspect ratio (the same aspect ratio as our Objectron dataset). However, in the updated versions, we opted to use two stage detector and pass the crop to the model, so we don't need that any more. If you use two-stage pipeline, you can pass any image to the network (similar to our web and python graphs)

Secondly, we ran models on variety of devices, which would capture images (Android CameraX) at different aspect ratio, and also have different display ratio. For renderer to work correctly and simplify the pipeline, we fixed both at 3:4. If you don't need the renderer, you can ignore the crop and use your own aspect ratio.

**Comment by homuler** [comment]
Thank you for explaining in detail!
