### ISSUE TITLE
shaky face mesh

### ISSUE THREAD

**Issue by dragonballa** [google/mediapipe#2563]
In the [codpen ](https://codepen.io/mediapipe/pen/LYRRYEw) web demo for face mesh tracking. I notice it is extremely shaky/jumpy. Like the mesh seems to quiver and not stay fixed in one place. I need to use to control 3d mesh objects, how can I "smoothen" the face mesh tracking on webcam? because otherwise my 3d avatar character also starts to shake lol

**Comment by sgowroji** [comment]
Hi @dragonballa, Could you please provide a reference video to illustrate the above error. Thanks!

**Comment by mattrossman** [comment]
I experience the same issue. Here is a reference video @sgowroji, even though I am sitting still with a clear view of my face, the predicted mesh shakes a lot:

https://user-images.githubusercontent.com/22670878/134246342-7141fda4-485c-427c-be32-847b9cfee8fb.mp4

I can smooth it out by lerping the predictions, but I would rather have cleaner data in the first place to improve responsiveness.

I experience some shaking with the [TF.js demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html) as well though, so I'm not sure if this is something the Mediapipe team can fix versus a limitation of the model.

**Comment by mhays-google** [comment]
I hear you. I get the same results of course.  We sometimes fix this by adding a bit of momentum in the graph to smooth the output data, and I'm sending an email to folks providing the graph and we'll see if there's some plumbing I can take advantage of.

I suspect that lerping will work, but that you'll need to only lerp when the delta is already tiny (in order to not lag the tracking when the face is legitimately moving around).  I'm interested in how much it improves the final output.

**Comment by opchronatron** [comment]
@mhays-google I would be interested in seeing the graph as well.

**Comment by borhi** [comment]
@mhays-google, do you have some progress with this problem?

**Comment by sureshdagooglecom** [comment]
Hi @dragonballa .
Are you still looking for the resolution on this issue.
