### ISSUE TITLE
How to catch internal exceptions from solutions?

### ISSUE THREAD

**Issue by vavilovm** [google/mediapipe#2577]
I am using Selfie Segmentation library. There was an unreproducible WebAssembly exception. How can I catch exceptions inside the api? Is it thrown from SelfieSegmentation.send() function?

**Comment by tyrmullen** [comment]
We do not yet have any exception catching or wrapping ourselves, so everything will be thrown as-is/in-place.  Which means that yes, generally this will be from the .send() function, since that's what directly triggers the WebAssembly calls when processing a given frame (I'm assuming the exceptions are thrown while processing, and not during initialization-- otherwise you'll have to look to the initialization calls instead).  In fact, although the API makes .send() appear asynchronous, the internal WebAssembly processing is fully synchronous and single-threaded, so you don't have to worry about any asynchonous behavior when catching Wasm exceptions from .send().

**Comment by vavilovm** [comment]
@tyrmullen, thank you for the fast answer!
