### ISSUE TITLE
Why not use stable version of abseil?

### ISSUE THREAD

**Issue by zjuturtle** [google/mediapipe#264]
I notice in WORKSPACE, there is a TODO

```
# Head commit on 2019-04-12.
# TODO: Switch to the latest absl version when the problem gets
# fixed.
```

What is the problem exactly?

**Comment by jiuqiant** [comment]
There is an inconsistent Bazel config setting between mediapipe and abseil. Does the current abseil dependency cause any problem to you?  

Moreover, [abseil](https://github.com/abseil/abseil-cpp/tree/master/absl) has three LTS versions (lts_2018_06_20, lts_2018_12_18, and lts_2019_08_08). Do you suggest that MediaPipe needs to depend on abseil's lts_2019_08_08? We avoid depending on the master branch of abseil since any changes in the master branch invalid the build cache and everything needs to be rebuilt again.

**Comment by zjuturtle** [comment]
Currently I have not encountered any problem, it is just a little wired to use a snapshot version dependency. I think I'll suggest to use lts_2019_08_08 version.
Thank you!

**Comment by jiuqiant** [comment]
Fixed in https://github.com/google/mediapipe/commit/137867d0888a7e5a02089829360b3d32857cdad9.
