### ISSUE TITLE
Android solution get texture id

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2650]
How can i get texture id on funtion , i want to custom effect 

`
public void renderResult(FaceMeshResult result, ResultGlBoundary boundary)
`

**Comment by sgowroji** [comment]
Hi @zhoujingheng, Could you please elaborate your query with more details. What do you mean by texture id? TextureFrame is an interface here. Are you trying to access **TextureFrame**

**Comment by zhoujingheng** [comment]
yes, i want to get texture and do more effect

**Comment by jiuqiant** [comment]
Each solution result object has an [acquireInputTextureFrame()](https://github.com/google/mediapipe/blob/33d683c67100ef3db37d9752fcf65d30bea440c4/mediapipe/java/com/google/mediapipe/solutioncore/ImageSolutionResult.java#L61) method and the TextureFrame object has a [getTextureName()](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/java/com/google/mediapipe/framework/TextureFrame.java#L39) method. You can obtain the underlying texture id by doing `solutionResult.acquireInputTextureFrame().getTextureName()`. Note that since you plan to do more advanced customization with the underlying texture directly, you need to interact with the solution result object in the ResultListener and probably can't use the provided MediaPipe GlRender.

**Comment by jiuqiant** [comment]
Each solution result object has an [acquireInputTextureFrame()](https://github.com/google/mediapipe/blob/33d683c67100ef3db37d9752fcf65d30bea440c4/mediapipe/java/com/google/mediapipe/solutioncore/ImageSolutionResult.java#L61) method and the TextureFrame object has a [getTextureName()](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/java/com/google/mediapipe/framework/TextureFrame.java#L39) method. You can obtain the underlying texture id by doing `solutionResult.acquireInputTextureFrame().getTextureName()`. Note that since you plan to do more advanced customization with the underlying texture directly, you need to interact with the solution result object in the ResultListener and probably can't use the provided MediaPipe SolutionGlSurfaceViewRenderer.
