### ISSUE TITLE
Failed to run mediapipe with gpu support for Facemesh solution with refine landmarks

### ISSUE THREAD

**Issue by Dreadlocke1984** [google/mediapipe#2678]
I built mediapipe facemesh example with gpu support on jetson platform using the reference of the markdown file provided in the following link -
[https://forums.developer.nvidia.com/t/mediapipe/121120/36](url)
and also with reference to this git repository - 
[https://github.com/jiuqiant/mediapipe_python_aarch64](url)

The example is working fine on GPU without setting the refine_landmarks parameter as True.
And it is working fine on CPU with and without setting refine_landmarks parameter as True.

**Error on running mediapipe facemesh example on gpu with refine_landmarks set as True**
![Screenshot from 2021-10-18 10-30-25](https://user-images.githubusercontent.com/67857441/137673910-760df951-8abe-48fb-a861-32153594cbf1.png)
![Screenshot from 2021-10-18 10-31-14](https://user-images.githubusercontent.com/67857441/137673942-cd12226c-d148-4e22-b161-4b89870920b3.png)

**System information** 
- Jetson Xavier AGX
- Jetpack version - 4.5
- Mediapipe version - 0.8
- Programming language - Python (3.6.9)
- Bazel version - 3.7.2

**Comment by mcclanahoochie** [comment]
it's good that the GPU path works for facemesh when refine_landmarks is false, that means the mediapipe GPU configuration/setup is fine.

the `refine_landmarks = true` option actually runs a different ML model ([here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite))

it seems that model has some op that isn't compatible with the tensorflow gpu delegate.

since https://github.com/google/mediapipe/issues/2797 has the same issue and seems to be using only c++, it is unlikely a python issue.

i'm suspecting some mismatch with the model file and tensorflow version.  it may be that a newer tflite runtime is needed (changed [here](https://github.com/google/mediapipe/issues/2797 seems to be using c++,)). 
maybe you can try using a snapshot of tensorflow that is closer to the release date of [refine_landmarks](https://github.com/google/mediapipe/releases/tag/v0.8.8) (Oct 06, 2021)..?

**Comment by sgowroji** [comment]
Hi @Dreadlocke1984, Could you please respond on this https://github.com/google/mediapipe/issues/2678#issuecomment-989348636. if the issue still persists

**Comment by mcclanahoochie** [comment]
if there is a 
`use_advanced_gpu_api: true`
in the graph, try setting it to false.
see https://github.com/google/mediapipe/pull/2463

**Comment by adnan6336** [comment]
> if there is a `use_advanced_gpu_api: true` in any of the graphs, try setting it to false. see #2463

Thanks for the reply brother @mcclanahoochie 
there is no ``` use_advanced_gpu_api: true``` in any graph, I assume this option is in the inference calculator right?

for the reference.
face_landmark_gpu.pbtxt

```
# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of GPU tensors representing, for instance, detection boxes/keypoints
# and scores.
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  input_side_packet: "MODEL:model"
  input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      # Do not remove. Used for generation of XNNPACK/NNAPI graphs.
    }
  }
}
```

can you suggest any other solution?
