### ISSUE TITLE
How to get embeddings from 468 landmarks (x,y,z)

### ISSUE THREAD

**Issue by Ram-Godavarthi** [google/mediapipe#2755]
Hi,

I have used mediapipe facenet landmarks model.
I got 468 points with x, y, z values.

How to compare these with the stored image/ database image to perform verification. ??

Should I convert these 468 points (x,y,z) to embeddings (468 floats in the range [0,1]) and then perform verification ?? If yes, How to convert them to embeddings. ??

Any help would be really appreciated.

Thank you

**Comment by ablavatski** [comment]
Hi Ramalingesh,

There are many approaches you can try but the one that is supported right now is to use k-nearest neighbors algorithm (k-NN) similar to the [pose classification in MediaPipe](https://google.github.io/mediapipe/solutions/pose_classification.html). You can create similar classification for the face mesh but instead of using 468 points you can pick a subset and verify only the subset of the points.

Also, refer to @ivan-grishchenko - the original author of pose classification for more details on the approach.
