### ISSUE TITLE
CPU usage criteria

### ISSUE THREAD

**Issue by gb2111** [google/mediapipe#2784]
I am using a media pipe demo on PC/Windows with Python and on different PCs it uses about 20-30 ms and no more than 10% of CPU. would it be possible that it uses much more of CPU? and work with better performance? If not what are the 'rules' behind that?
Thank you

**Comment by sgowroji** [comment]
Hi @gb2111, Could you be able to provide your use case with complete details. Thanks!

**Comment by gb2111** [comment]
I am using pose tracking from mediapipe. I have 60fps camera and when I run mediapipe it can do max 45fps on my PC.
In same time it uses about 8% of CPU. Why it doesn't compute faster if there is lot of CPU? Is this due to single thread processing? Is there way to make it compute faster?

Thank you.

**Comment by hadon** [comment]
Hi @gb2111,
I think you are using the MediaPipe "holistic" Python solution, which invokes the MediaPipe "holistic_landmark" calculator-graph.   The python solution API "Holistic.Process" makes a series of synchronous calls to the calculator-graph.  These synchronous calls wait for the results from the previous frame to return before sending in the next frame, which reduces the parallelism of the calculator graph and reduces the CPU utilization.  

The same "holistic_landmark" calculator-graph can be run using the MediaPipe Python framework, using functions like "add_packet_to_input_stream()", rather than using the MediaPipe "holistic" Python solution.  When the calculator-graph is run in this way, it can begin processing each input frame sooner, which can increase CPU utilization and throughput.
