### ISSUE TITLE
Selfie Segmentation Freezes in PWA but works fine in Chrome Browser without Installing

### ISSUE THREAD

**Issue by djaffer** [google/mediapipe#2808]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2XL
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome PWA Install
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.1
- Bazel version (if compiling from source): 0
- Solution ( e.g. FaceMesh, Pose, Holistic ): SelfieSemgentation
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): 
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
Selfie Segmentation freezes when used as PWA installed but works fine in native Chrome Browser for Android.

**Describe the expected behavior:**
It should work the same whether installed as PWA or used in browser.

**Standalone code to reproduce the issue:**
N/A

**Other info / Complete Logs :**
N/A

**Comment by sgowroji** [comment]
Hi @djaffer, Could you please provide the steps to reproduce the above issue with a screen recording, error logs to understand the error.

**Comment by berkon** [comment]
@sgowroji , I have the same issue with Electron. I'd guess that indeed the issue is identical thus I thought it would make sense to re-open this one. Please let me know if you'd rather want me to open a new one.

I've created a GitHub repo which should reproduce the issue: [https://github.com/berkon/background-removal](https://github.com/berkon/background-removal)

After cloning, just execute **npm install** and then **npm start**.

I does not always happen. I'd say in 50% of the cases the app starts and then shows a frozen image. Nevertheless on this image the background is correctly replaced. Let me know if you need any additional information.

**Comment by berkon** [comment]
I'm not sure but I think I fixed it. I've added this line:

`await selfieSegmentation.initialize()`

which unfortunately is not present in the codepen Web-demo. I saw it here: https://github.com/google/mediapipe/issues/2823
