### ISSUE TITLE
dataset used in hand tracking.

### ISSUE THREAD

**Issue by Rakeshvcr** [google/mediapipe#284]
Hello,
I have a few questions regarding the hand dataset. I hope you would help me with this.

1. Is the annotated dataset available for public use?
2. How to annotate 3D points for the hand dataset?

**Comment by mgyong** [comment]
@Rakeshvcr 1) unfortunately due to privacy reasons. We are unable to release annotated dataset for public use
2) We have 2 tflite models: one for 2d and one for 3d. For the 2d model, We trained only on 2D annotation (x,y) leaving z empty. For 3d model training, we used synthetic dataset that includes xyz ground truth.
