### ISSUE TITLE
Depth estimation is failing in Mediapipe 0.8.9 Hand Tracking 

### ISSUE THREAD

**Issue by yiusay** [google/mediapipe#2845]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution: Windows 10
- MediaPipe version: 0.8.9
- Bazel version: N/A
- Solution: Hands
- Programming Language and version: Python 3.9.5

**Describe the expected behavior:**

Depth estimation is failing in Mediapipe 0.8.9 Hand Tracking when model_complexity=1 (hand_landmark_full.tflite). 

It was working fine in 0.8.7 and is also working when model_complexity=0 (hand_landmark_lite.tflite is used). See the following image. 

![issue2](https://user-images.githubusercontent.com/9548004/144323265-8ae4fa58-ed11-4e6d-b4ea-f55a0acd6dd7.png)

In general, the depth estimation of Mediapipe 0.8.9's models is a little tight compared to the one of 0.8.7. 

I am moving 3d avatar's fingers using Mediapipe Hand and, because of this problem, the fingers are intersecting with the palm when I make my fist. This problem did not occur in 0.8.7.

![issue1](https://user-images.githubusercontent.com/9548004/144323628-c7dde7f5-573e-41d8-8bb0-fb7ccbb7c5f8.png)

This is the video showing this problem interactively.

https://user-images.githubusercontent.com/9548004/144323666-45d01389-77be-49f4-a9a8-7c29989fb3a7.mp4

**Standalone code you may have used to try to get what you need :**

[hand_tracking_issue.zip](https://github.com/google/mediapipe/files/7637495/hand_tracking_issue.zip)
I have attached the script used in this experiment. By running this, you can reproduce the same images using Mediapipe 0.8.7, Mediapipe 0.8.9 with model_complexity = 0, and Mediapipe 0.8.9 with model_complexity = 1, respectively.

Please let me know anytime if you have questions. 

Thanks for your great work so far! I am very impressed and enjoying using Mediapipe :)

**Comment by yiusay** [comment]
If this is not easy to fix, it would be great if you could restore the hand model in 0.8.7 and allow us to select the model, for example, by setting MODEL_COMPLEXITY to 2.

For now, 2 hand models (hand_landmark_lite and hand_landmark_full) are provided. Is it difficult to restore the hand model in 0.8.7 (which was working great!) as a 3rd one?

**Comment by bazarevsky** [comment]
Both Full and Lite models are different only by architecture, loss and dataset are the same. 
Also, I suppose you use an obsolete way of depth estimation, which has significant limitations due to: limited hand articulations, only synthetic data used for its training. 

We recommend to use newly introduced world coordinates for xyz in meters (recent feature based on GHUM model), which we plan to improve in future. 
Some details related new 3D can be found here: https://blog.tensorflow.org/2021/11/3D-handpose.html

**Comment by matanster** [comment]
Dear @bazarevsky only seeing your comments now ―

>  with the origin in (an) auxiliary keypoint formed as an average between the first knuckles of index, middle, ring and pinky fingers

I would assume that by knuckles you mean the metacarpal landmarks predicted, so that for each input image after predicting the landmarks this origin is calculated and then all landmarks are "normalized", though I don't recall seeing a calculator for this in the computation graph.
