### ISSUE TITLE
are the landmarks skipped when both minDetectCoeff < 0.5 & minTrackCoeff < 0.5 ??

### ISSUE THREAD

**Issue by ssoumyajit** [google/mediapipe#2880]
The documentation is pretty clean.
Just wanted to be a little sure about something;

Let's say we are doing a holistic full body pose estimation with 'min_detection_coeff = 0.5 and min_tracking_coeff =0.5'.

---case 1---
The first frame kicks off the detection and somehow min_detection_coeff < 0.5, in this case there will be no landmarks for that specific frame, am I correct ?

---case 2---
min_detection_coeff >= 0.5 for the 1st frame, and it starts to happily track the subsequent frames until a frame comes where min_track_coeff < 0.5; so it triggers the detection again. what if min_detect_coeff < 0.5 for this frame, again this frame will have no landmarks, is it so ?

all in all, depending upon the parameters (min_detect and min_track) some frames will have no landmark and just skipped , then go to process the next frame ??

Thank you.

**Comment by sgowroji** [comment]
Explained it here https://google.github.io/mediapipe/solutions/pose.html#min_detection_confidence, https://google.github.io/mediapipe/solutions/pose.html#min_tracking_confidence

**Comment by ssoumyajit** [comment]
Thanks @sgowroji for your reply.
yes, I read the above mentioned note.

may be there is something very clear that I don't understand. pardon me.
so let me make the question a little simple yes or no type.

if both the parameters ( min_detect_coeff & min_track_coeff ) less that the set value, will there be any landmarks for that particular frame ?  Yes or NO.

Thank you.

**Comment by Alex7Li** [comment]
I'm also confused by the documentation and would like to know exactly what these parameters do. Based on my experimentation, if we set either the min detection confidence or min tracking confidence to 1 or more, the function returns empty lists every single time. I actually thought it would never return an empty list from the documentation. I'm especially surprised by the behavior when the min tracking confidence is set high - that means that even though the points were detected, nothing was returned due to low detection confidence.

Could someone who knows the code validate what I said and update the documentation to be more clear?

**Comment by ssoumyajit** [comment]
I spent some time with different videos and their per frame landmarks; and it looks like some frames will have no landmarks when both the min_detect_coeff and min_track_coeff are less than the set values.
