### ISSUE TITLE
Lower fps in IOS Mediapip hands JS solution, ( FPS issues).

### ISSUE THREAD

**Issue by vKrypto** [google/mediapipe#2894]
Hi, team
I was trying mediapipe hands-js-solution, had a problem with fps count in iPhone X.

so I tried this on my linux-chrome.

when I am changing user-agent to iPhone, the FPS count decreases from 30 to 5.

is there anything we can do ??

checkout this two screen-shot.

case 1: using responsive mode.

![Screenshot from 2021-12-16 16-04-01](https://user-images.githubusercontent.com/25729859/146361977-a3642b89-897e-42f2-ab5a-9397fe6837b6.png)

case 2: using iphoneX mode.

![Screenshot from 2021-12-16 16-04-38](https://user-images.githubusercontent.com/25729859/146361992-fbc71d8c-7fcd-4a15-b27e-a0c2dcda06d0.png)

**Comment by tyrmullen** [comment]
This is a known issue.  iOS traditionally has not supported WebGL2, so we were unable to run our faster GPU-side machine learning on these devices.  As a result, we intentionally fall back to (often much slower) CPU-side machine learning for iOS.  The latest iOS (15+) versions are supposed to support WebGL2, but we've been encountering issues there, which is why the fallback is still enabled by default.  So closing this issue as a duplicate, but please follow along the discussion for the WebGL2-on-iOS15+ issues for updates!  (See issues #2660, #2675, and #2536)

**Comment by vKrypto** [comment]
> This is a known issue. iOS traditionally has not supported WebGL2, so we were unable to run our faster GPU-side machine learning on these devices. As a result, we intentionally fall back to (often much slower) CPU-side machine learning for iOS. The latest iOS (15+) versions are supposed to support WebGL2, but we've been encountering issues there, which is why the fallback is still enabled by default. So closing this issue as a duplicate, but please follow along the discussion for the WebGL2-on-iOS15+ issues for updates! (See issues #2660, #2675, and #2536)


I am using  habds@0.4.1635986972.js and I just removed 1 line.. from my code, and forced it to use GPU. 

    // default: "iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";").includes(navigator.platform) || navigator.userAgent.includes("Mac") && "ontouchend" in document
    
 and it luckily works..with FPS (~30), tested in (XR, MacBook-pro-intel), maybe they started WebGL support in IOS-15.

**Comment by vKrypto** [comment]
if you got time to look, please check out this link [https://www.ornaz.com/realtime-tryon-v9/](REAL-TIME-TRYON) ( initial load slow, as using a below-average server to serve files..) 

and let me know the device name, if it's not working or slow FPS(< 15) In your device.
