### ISSUE TITLE
Mediapipe is providing two pairs of bounding box coordinates for single hand in a frame, how to resolve it?

### ISSUE THREAD

**Issue by amitbohra1234** [google/mediapipe#2928]
- I have written out the code for getting "hand_rects" from Mediapipe python implementation:
- Ubuntu OS18.04:
- Python 3:
- Solution "Hand":

**While getting the bounding box coordinates from the images passed to mediapipe, sometimes for single hand present in the frame, it would predict out 2 sets of bounding box coordinates. I have updated the mediapipe package for providing out 'hand_rects' after pip install mediapipe**

**It should predict only 1 set of bounding box coordinates for 1 hand present per frame.**

**How to resolve this issue?**

**Comment by sgowroji** [comment]
Hi @amitbohra1234, Can you provide issue details or screenshots to understand the issue and investigate further.  Thanks!

**Comment by amitbohra1234** [comment]
![mediapipe_amit_double_bounding_box](https://user-images.githubusercontent.com/96728697/147537316-00a8885c-7965-49ca-8a3b-6fb10fc909f4.jpg)

Hi @sgowroji, This is one of the screenshot, I cannot share the rest of the data and code due to privacy issues. Please help in resolving this issue. It cannot be differentiated are these two sets of bounding box coordinates per frame, of single hand or 2 hands visible, i.e cannot eliminate the 2nd set of bounding box coordinates as there could be either 1 or 2 hands visible per frame.

**Comment by amitbohra1234** [comment]
Any updates, what could be the potential issue?

**Comment by bazarevsky** [comment]
That can happen due to prediction inaccuracy. Also you can specify how many hands you would like to track. So for single hand - it would be sorted out automatically.

For the case with 2 and more hands tracked, we filter out duplicates by iou threshold between bounding boxes. If two different hands have IOU bigger than certain threshold, we filter out one of them as duplicate. So, you can update this threshold in the graph. Or implement such filtering on your end. 

Alternatively, if you prefer to do this on your end, you can filter out duplicates not only on the basis of bounding box, but on the basis of hand pose similarity metric (If hand key points similarity is bigger than certain threshold- probably this is the same hand).
