### ISSUE TITLE
Any plan to generate an SDK (headers, static & dynamic libs) so that mediapipe can be used without  bazel

### ISSUE THREAD

**Issue by ksachdeva** [google/mediapipe#294]
Hi,

A lot (dare I say almost all) of the C/C++ projects in the world are CMake based however it is understandable that the scale of all things google require a build system like Bazel. 

In near future, do you guys by any chance plan to generate an SDK ( a directory with header files and lib files of media pipe) that one could import/include in their custom project based on other build systems (like CMake) ?

Thanks for this great work

Regards
Kapil

**Comment by zjuturtle** [comment]
I have the same request #236

**Comment by schumy** [comment]
I have the same request... I'm having some issues compiling the library for iOS. Currently when using the project of the library, the static .a that I get after it can't be included in my project because it seems that bitcode is not enabled. I checked the target(I'm using the hand tracking library) and bitcode seems enabled but for some reason, the outcome has not bitcode. Anybody else facing the same issue?

**Comment by gaborpapp** [comment]
I would be also interested in this

**Comment by gaborpapp** [comment]
I would be also interested in this.
I'm trying to build a library to be able to use it in C++ project.
Made the following for desktop OSX, built the static lib, searched for all the required headers and copied them to the project, which is a copy of `hello_world`, but with the static lib.

```
apple_static_library(
    name = "mediapipe",
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:commandlineflags",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:map_util",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:ret_check",
        "//mediapipe/framework/port:status",
        "//mediapipe/framework/port:statusor",
        "@com_google_absl//absl/strings",
        "//mediapipe/calculators/core:pass_through_calculator",
    ],
)
```

When I run the executable I get these errors:
```
Not found: ValidatedGraphConfig Initialization failed.
No registered object with name: PassThroughCalculator; Unable to find Calculator "PassThroughCalculator"
No registered object with name: PassThroughCalculator; Unable to find Calculator "PassThroughCalculator"
```

Do you have any suggestions to fix this?

**Comment by mgyong** [comment]
This is something we are looking at. However, we do not have a timeline on this

**Comment by mapleyuan** [comment]
Same problem

**Comment by samsieber** [comment]
I'm also interested in this for integrating with Rust.

**Comment by Tectu** [comment]
I'm also looking for this.
Proper cmake support would of course be preferred but I guess that's off the table anyway? :p

**Comment by DandyLorenz** [comment]
Same problem。Can you help me see how to solve this problem?Thanks. https://github.com/google/mediapipe/issues/1450

**Comment by shubhamvad** [comment]
Has anyone found the solution to this ? if yes please share . 
Looking for the solution of this.
Thanks .

**Comment by Tectu** [comment]
Building a shared library is easy. You can afterwards include that in your application using whatever build system you like.

**Comment by matrixreload** [comment]
Has anyone found the solution to this ？🤔️

**Comment by yshuolu** [comment]
I want to integrate mediapipe with iOS projects with build systems of BUCK/Cocoapods. However, right now mediapipe seems tightly coupled with Bazel/Tulsi for iOS workflow, while I am struggling to make Tulsi work with the example projects, with all kinds of vague errors. Even though building into static library by bazel could be the way around, but we lose the opportunity to play and hack with the mediapipe source code while debugging things.

**Comment by dibet** [comment]
> Building a shared library is easy. You can afterwa

But how?

**Comment by ArnaubHie** [comment]
How?

**Comment by dibet** [comment]
How ???

**Comment by willstott101** [comment]
I've found problems [like this](https://github.com/google/mediapipe/issues/294#issuecomment-574201789) can sometimes be resolved by setting [`linkshared=1`](https://stackoverflow.com/questions/67542605/bazel-shared-library-does-not-include-all-symbols) on the target you're depending on which forces the linker to include _all_ symbols rather than filtering to only the used ones.

**Comment by rajkundu** [comment]
Same question. It's such a shame because MP seems to be one of the best facial landmark detection models available, but it is practically unusable in C++. :(

**Comment by Tectu** [comment]
> [...] but it is practically unusable in C++. :(

What makes you say that?
It is very usable in C++. It runs notably more smoothly than via Python or Javascript bindings too.

**Comment by dibet** [comment]
We want to use cmake tools.


A sexta, 28/10/2022, 15:19, Joel Bodenmann ***@***.***>
escreveu:

**Comment by rajkundu** [comment]
> Building a shared library is easy. You can afterwards include that in your application using whatever build system you like.

Can you expand on this at all? I am extremely interested in building MP as a library (static would be preferable, but shared is fine too) for use with CMake. How did you do this?

**Comment by rajkundu** [comment]
If anyone is looking to use MediaPipe without Bazel, I've created a generalized shared/dynamic library for the purpose of doing so. Please see https://github.com/google/mediapipe/issues/1162#issuecomment-1306678037, and please feel free to ask any questions! It has been tested on Windows and Linux, but not macOS (yet).

Like many others, I just want to use MediaPipe - not Bazel. This shared library allows me to run MediaPipe examples from my own application, which I can build using CMake. An extremely simple example is [here](https://github.com/rajkundu/libmp-example). I run MP FaceMesh on a picture of my face, access the raw output landmark coordinates, then manually draw each of them as a small, green square on top of the input image.

**Comment by Chnoblouch** [comment]
For those who want to use MediaPipe in other languages (like Rust or Zig), we've created a [plain C API](https://github.com/cpvrlab/libmediapipe) for the framework consisting of a shared object and a single header. After building the library, these files can be used in any build system without Bazel being involved. Currently there are build scripts for Linux, Windows, macOS and Android. Since this is a C library, it should be possible to create bindings for other languages on top of it. [Here](https://github.com/google/mediapipe/issues/1162#issuecomment-1450386045)'s my previous comment about it.

Thanks to @rajkundu for creating [LibMP](https://github.com/rajkundu/mediapipe), it was a huge help in getting started on this thing!
