### ISSUE TITLE
How would I run FaceMesh in two different videos on the same page in javascript?

### ISSUE THREAD

**Issue by cindyloo** [google/mediapipe#2953]
https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#models

I would like to know how (assuming the API allows) I can use FaceMesh with to two different video streams (one local, one remote streaming) *on the same web page*. The demos just seem to assume if the assigned video class is "input_video", that one and only one video element is to be found or to be passed into `SourcePicker`? Results just pops back with any landmarks associated with that one video stream...

**Comment by cindyloo** [comment]
eg: testing by adding another video element to the demo html code does not work
  ```
<div class="container">
    <video class="input_video"></video>
    <div class="canvas-container">
    <canvas class="output_canvas" width="1280px" height="720px">
    </canvas>
    </div>
    <div class="loading">
      <div class="spinner"></div>
      <div class="message">
        Loading
      </div>
    </div>
    

  </div>
  <div class="control-panel">
  </div>

  <div class="container">
    <video class="anothervideo"></video>
    <div class="canvas-container">
    <canvas class="output_canvas" width="1280px" height="720px">
    </canvas>
    </div>
    <div class="loading">
      <div class="spinner"></div>
      <div class="message">
        Loading
      </div>
    </div>
</div>
```

**Comment by sgowroji** [comment]
Hi @cindyloo, Have you tried executing multiple videos one by one dynamically in a loop. Its more javascript implementation and you can find more examples in stack overflow or javascript communities.

**Comment by cindyloo** [comment]
@sgowroji could you be a little more specific? Mapping through videos within the SourcePicker? I spent a good amount of time looking yesterday and didn't find anything. Plus the demo breaks when I add another <video> element on the html section, so I'd like to be clear on how this should work

**Comment by tyrmullen** [comment]
The SourcePicker (and our Camera utilities in general) are only there to make it easier for us to put together a suite of simple demos.  They're not really supposed to be a fully-fledged camera API in any sense.  So for any more advanced usage, it's recommended to bypass those helper utilities and just call FaceMesh API directly.  There are two ways of attempting this for your use case:
(1) Just alternate which frames are getting passed into a single FaceMesh instance, i.e.
```
await faceMesh.send(videoOrImageOne);
await faceMesh.send(videoOrImageTwo);
```
OR
(2) Maintain two separate FaceMesh instances, i.e.
```
await faceMeshOne.send(videoOrImageOne);
await faceMeshTwo.send(videoOrImageTwo);
```

Option (1) will use less memory, since it only uses a single MediaPipe graph runner.  However, for MediaPipe WebAssembly Solutions, we use a single backing Canvas object (in order to perform WebGL operations), so depending on your video input, it may be tricky to ensure that all your frames are processed nicely using that same canvas (if you're playing two video streams, they'll need to be played into the same canvas without "stomping" on each other).  If you are using Chrome and can use ImageBitmaps for passing around your video frame inputs, then you should be fine.  But if you run into any troubles, then option (2) might perhaps be able to avoid some of these issues.

**Comment by Raahmaa99** [comment]
Systems

**Comment by Raahmaa99** [comment]
#1894

**Comment by cindyloo** [comment]
thank you - that helped. The demo was only useful for playing around with.
For others looking to do this in Javascript AND React here's my code:

```
const MediaPipeVisualiser = (params) => {
  const {
    mode,
    maskedParticipant,

  } = params;

  const maskParticipant = async (
    mode: string,
    maskedParticipant: Array
  ) => {
    try {
      // there will be only one local, actually

      
canvasName = <yourcanvasname>
videoEl = <yourvideoelementid>
      canvasOverlayBuff = document.querySelector(
        `#${canvasName}`
      ) as HTMLCanvasElement;

      cOverlay = canvasOverlayBuff.getContext("2d");
      videoEl = document.querySelector(
        `#${videoElementName}`
      ) as HTMLCanvasElement;
    } catch (e) {
      console.log("error in mediapipe vis");
    }
  };


  useEffect(() => {
    if (faceMesh == null || faceMesh == undefined) {
      faceMesh = new FaceMesh({
        locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`;
        },
      });

      faceMesh.setOptions({
        maxNumFaces: 1,
        refineLandmarks: true,
        minDetectionConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });
    }
    faceMesh.onResults(onResults);
    console.log("videoEl is " + videoEl);
    if (videoEl !== null) {
      camera = new Camera(videoEl, {
        onFrame: async () => {
          await faceMesh.send({ image: videoEl });
        },
        width: 1280,
        height: 720,
      });
      camera.start();
    }
  }, [videoEl, maskedParticipant]);

  return <div />;
};

```

**Comment by tyrmullen** [comment]
To answer your question, yes, I believe two separate MP instances should be able to render two different videos to two different canvases, although I'm not sure how much this has actually been tested yet.

Sounds like this immediate issue is resolved, and the remaining issues already have corresponding bugs, so closing this one for consolidation purposes.
