### ISSUE TITLE
Selfie Segmentation drops fps when i switch to another browser

### ISSUE THREAD

**Issue by dattt117** [google/mediapipe#2955]
**System information**
- OS Platform and Distribution (Win10)
- Programming Language : JavaScript

**Describe the problem**:
When I switch to another browser tab or open another app window in full screen, the fps will drop
I use console.log in the onFrame function of the Camera , but it won't log when I switch to another browser tab

Code: https://google.github.io/mediapipe/solutions/selfie_segmentation.html#javascript-solution-api

**Comment by sgowroji** [comment]
Hi @dattt117, Can you provide any references with the above behaviour to investigate further. Thanks!

**Comment by dattt117** [comment]
> 

I use log in the onFrame function of the Camera. 
Code:
![image](https://user-images.githubusercontent.com/55450933/148319711-d392db4d-457b-4e73-b1c3-8bab104f462a.png)
Result: 
![image](https://user-images.githubusercontent.com/55450933/148319874-9c77e4f1-1c16-4d1a-a2a8-63ece8468645.png)
There are about 7 log/sec
But when I switch to another browser tab or open another app window in full screen, no log shows up

**Comment by tyrmullen** [comment]
This sounds like standard browser behavior.  Our simple Camera helper uses `requestAnimationFrame` in order to register for new video frames, and also checks to make sure it's receiving a new video frame.  However, if the user backgrounds the tab, then to save power/resources, the browser will automatically stop updating the video frames as frequently (or will stop updating them at all).  From the browser's point of view, it usually doesn't want to spend lots of power and CPU/GPU cycles if the animation isn't even visible.  So if you need to keep this alive in the background for some reason, you'd have to write something custom and more complex than our simple for-demo Camera helper utility (and you'd need to use something else besides `requestAnimationFrame`).
