### ISSUE TITLE
About face effect virtual model, anyone know the max number of faces and vertices is supported ? 

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#2978]
Like this Helmet with Tengu Mask and Crows,  anyone know the max number of faces and vertices is supported ? 

<img width="574" alt="截屏2022-01-11 下午5 37 27" src="https://user-images.githubusercontent.com/25787391/148918062-c0228b43-5eda-41d4-bf92-ff22fd9c830f.png">

**Comment by sgowroji** [comment]
Hi @wingdi, Which MediaPipe solution are you referring above?

**Comment by wingdi** [comment]
Hi  @sgowroji ,There are no solution about this,  it's come from mediapipe/graphs/face_effect and mediapipe/modules/face_geometry.

**Comment by sgowroji** [comment]
Face effect supports now only for single face  as mentioned here https://google.github.io/mediapipe/solutions/face_mesh#face-effect-example

**Comment by kostyaby** [comment]
Hey @wingdi,

If you're referring to [FaceGeometryEffectRendererCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc), then I believe I didn't set any explicit limits for the number of vertices / faces of the 3D meshes. Your only limits are OpenGL ES 3.0 limits and, of course, performance considerations.

For OpenGL ES limits: use [glGet](https://docs.gl/es3/glGet) to learn values of `GL_MAX_ELEMENT_INDEX`, `GL_MAX_ELEMENTS_INDICES` and `GL_MAX_ELEMENTS_VERTICES` on a specific device. The standard guarantees that `GL_MAX_ELEMENT_INDEX` is at least "2 ^ 24" (=16,777,216). From my personal experience, you should totally be able to render tens of thousands of vertices / faces on a mid-tier mobile GPU

**Comment by wingdi** [comment]
Hi @kostyaby 
I test , the vertex number need less than 65536, it comes from effect_renderer.cc : `RET_CHECK_LE(index_element, std::numeric_limits<uint16_t>::max())`  , if exceed 65536, it will report errors.

**Comment by kostyaby** [comment]
Oh right, sorry about that! Totally forgot. Yeah, I made index buffer a `uint16_t` array. It should be easy to un-hardcode, please go ahead and give it a try: 

- [Lines 85-87](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L85-L87): remove entirely
- [Lines 89-90](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L89-L90): remove `static_cast<uint16_t>`
- [Line 399](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L399): replace `GL_UNSIGNED_SHORT` with `GL_UNSIGNED_INT`
- [Line 669](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L669): add `static_cast<uint16_t>` around `kQuadMesh3dIndexBuffer[i]`

I avoided going with `GL_UNSIGNED_INT` in the first place because on some devices `GL_MAX_ELEMENT_INDEX` can be as low as `2 ^ 24` (=16,777,216), so I'd have to support chunk-by-chunk rendering for large meshes and that's already turn it into a non-trivial renderer. In general, rendering large meshes comes with all sorts of challenges so I wanted to avoid those kind of problems altogether by limiting indices to `GL_UNSIGNED_SHORT`. Looking back on it, I'd say I should have went with `GL_UNSIGNED_INT` and set a limit smth like `2 ^ 20` (=1,048,576); that would have prevented any large-mesh problems but allow larger meshes to be supported

**Comment by wingdi** [comment]
Ok, very thanks for your detailed explination.

**Comment by shiv-u** [comment]
@wingdi Did these changes worked for you ?

**Comment by shiv-u** [comment]
@kostyaby I tried these changes, but all I'm getting are black frames, I can't see any errors in the logcat.

**Comment by shiv-u** [comment]
I'm not able to render normal glasses either with these changes

**Comment by shiv-u** [comment]
@kostyaby  getting this error on Android
`I20220601 11:35:41.380790 30961 gl_context.cc:863] Found unchecked GL error: GL_INVALID_ENUM `

**Comment by Gojo1729** [comment]
The device do support OpenglES 3.2

**Comment by Gojo1729** [comment]
@sgowroji @kostyaby  Any updates on this ?

**Comment by wingdi** [comment]
> @wingdi Did these changes worked for you ?
Yes, it works for me,  but i have not check that part code for a  long time , i remember the most import is [glDrawElements(param...)](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L398) ,the params need to have the same data type.  hope it help, man.

**Comment by Gojo1729** [comment]
@wingdi so the mesh_3d.primitive_type should be unsigned_int ?
Can you provide me the modified `effect_renderer.cc ` file which worked for you ?

**Comment by Gojo1729** [comment]
I resolved the issue,
we need to do some more changes to the `effec_renderer.cc`
1) [line 104](https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L104) change the data type from `uint16_t` to `uint32_t` .
2) [line 655](https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L655) and  [line 660](https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L660) update the data type to `uint32_t` instead of `uint16_t` .

3) [Line 669](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L669): add `static_cast<uint32_t>` around `kQuadMesh3dIndexBuffer[i]` .
