### ISSUE TITLE
Autoflip error when bazel build

### ISSUE THREAD

**Issue by john6402** [google/mediapipe#2985]
**Describe the problem**
I have followed the installation tutorial of Mediapipe on windows10 platform. My bazel version is 4.2.2 currently. Most solutions in Mediapipe could be built and executed smoothly. Ex: Face、Object、Iris module Demo. 

But there was a confusing error when I wanted to build the Autoflip solution.

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//a004234//AppData//Local//Programs//Python//Python365//python.exe" mediapipe/examples/desktop/autoflip:run_autoflip`

For this problem, I have tried to clean the bazel file through "bazel clean --expunge", and updat latest Bazel version. This issue still happened. What detail am I missing? 
Thanks!

**Bazel report via "--verbose_failures":**

ERROR: C:/users/a004234/_bazel_a004234/kwxb47zi/external/ceres_solver/BUILD:36:14: Compiling internal/ceres/dense_sparse_matrix.cc failed: (Exit 2): cl.exe failed: error executing command
  cd C:/users/a004234/_bazel_a004234/kwxb47zi/execroot/mediapipe
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Users//a004234//AppData//Local//Programs//Python//Python365//python.exe
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\a004234\AppData\Local\Temp
    SET TMP=C:\Users\a004234\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/ceres_solver /Ibazel-out/x64_windows-opt/bin/external/ceres_solver /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/com_github_glog_glog /Ibazel-out/x64_windows-opt/bin/external/com_github_glog_glog /Iexternal/com_github_gflags_gflags /Ibazel-out/x64_windows-opt/bin/external/com_github_gflags_gflags /Ibazel-out/x64_windows-opt/bin/external/com_github_glog_glog/_virtual_includes/windows_glog_headers /Ibazel-out/x64_windows-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags /Iexternal/ceres_solver/config /Ibazel-out/x64_windows-opt/bin/external/ceres_solver/config /Iexternal/ceres_solver/include /Ibazel-out/x64_windows-opt/bin/external/ceres_solver/include /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DGOOGLE_GLOG_DLL_DECL=__declspec(dllexport) /DCERES_NO_SUITESPARSE /DCERES_NO_CXSPARSE /DCERES_NO_ACCELERATE_SPARSE /DCERES_NO_LAPACK /DCERES_USE_EIGEN_SPARSE /DCERES_USE_CXX_THREADS /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /w /D_USE_MATH_DEFINES /std:c++17 -Iexternal/ceres_solver/internal -Wno-sign-compare /Fobazel-out/x64_windows-opt/bin/external/ceres_solver/_objs/ceres/dense_sparse_matrix.obj /c external/ceres_solver/internal/ceres/dense_sparse_matrix.cc
Execution platform: @local_execution_config_platform//:platform
cl : Command line error D8021 : invalid numeric argument '/Wno-sign-compare'
Target //mediapipe/examples/desktop/autoflip:run_autoflip failed to build
INFO: Elapsed time: 71.979s, Critical Path: 68.58s
INFO: 171 processes: 129 internal, 42 local.
FAILED: Build did NOT complete successfully

**System information**
- MediaPipe version: on 14 Dec 2021
- Bazel version: 4.2.2
- OpenCV version: 3.4.10
- BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
- BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
- BAZEL_VC_FULL_VERSION=14.28.29333
- BAZEL_WINSDK_FULL_VERSION=10.0.18362.0

**Comment by yuwade** [comment]
me too

**Comment by yuwade** [comment]
how to remove argument  Wno-sign-compare?

**Comment by yuwade** [comment]
进入这个目录 C:/users/a004234/bazel_a004234/3dig75rt\external\ceres_solver\bazel
打开ceres.bzl文件
删除Wno-sign-compare关键字 就可以build成功了

**Comment by john6402** [comment]
Before I asked this issue, I have tried the modification of ceres.bzl (C:\..\_bazel_xxx\..\external\ceres_solver\bazel\ceres.bzl).
Ex: Comment out or Delete the line
        copts = [
            "-I" + internal,
            #"-Wno-sign-compare",
        ] + schur_eliminator_copts,
or
        copts = [
            "-I" + internal,
        ] + schur_eliminator_copts,

The above step is invalid.

However, you give me a timely warning. Try another way.
Mod:
        copts = [
            "-I" + internal,
            "",
        ] + schur_eliminator_copts,

It works. Haha! Thank yuwade. 感謝你呀~

**Comment by xxqwf** [comment]
> 进入这个目录 C:/users/a004234/bazel_a004234/3dig75rt\external\ceres_solver\bazel 打开ceres.bzl文件 删除Wno-sign-compare关键字 就可以build成功了

你好，在windows上你编译成功了吗？我的报错
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'

**Comment by yuwade** [comment]
你的错误信息不完整，
只能看出来是找不到　/ｗ　/D_USE_MATH_DEFINES　等路径

**Comment by xxqwf** [comment]
> 你的错误信息不完整， 只能看出来是找不到　/ｗ　/D_USE_MATH_DEFINES　等路径

D:\resource\demo\CV\mediapipe>bazel build -c opt --config=android_arm64 --action_env PYTHON_BIN_PATH=D://ProjectApplication/py
thon/content/python.exe
mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/11418/_bazel_11418/cyflpetp/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
WARNING: D:/resource/demo/cv/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc
_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos'
: Only for backward compatibility. Do not use.
WARNING: D:/resource/demo/cv/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:fi
eld_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf/
/:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (195 pac
kages loaded, 14932 targets configured).
INFO: Found 1 target...
ERROR: D:/resource/demo/cv/mediapipe/mediapipe/framework/tool/BUILD:184:24: Compiling mediapipe/framework/tool/field_data.pb.c
c failed: (Exit 1): clang failed: error executing command external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin
clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target ... (remaini
ng 57 arguments skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 111.712s, Critical Path: 103.14s
INFO: 364 processes: 131 internal, 232 local, 1 worker.
FAILED: Build did NOT complete successfully

这是我执行命令后的日志

**Comment by xxqwf** [comment]
> 你的错误信息不完整， 只能看出来是找不到　/ｗ　/D_USE_MATH_DEFINES　等路径

方便加一下你的qq吗，向您请教些问题
