### ISSUE TITLE
Allow all media constraints when create Camera

### ISSUE THREAD

**Issue by delmohf** [google/mediapipe#2996]
I am using `@mediapipe/camera_utils`. The Camera creation is quite restrictive about the constraints passed to `navigator.mediaDevices.getUserMedia` so I think it would be useful to be able to create the Camera passing all possible media constraints.

Current allowed parameters
```
export declare interface CameraOptions {
  onFrame: () => Promise<void>| null;
  facingMode?: 'user'|'environment';
  width?: number;
  height?: number;
}
```

My vague proposal according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia):

```
export declare interface CameraOptions {
  onFrame: () => Promise<void>| null;
  video?: object | boolean;
  audio?: object | boolean;
}
```

Thanks!

**Comment by tyrmullen** [comment]
`camera_utils` is really meant to be just a helper for our CodePen demos, and probably shouldn't be used for anything "real".  We don't really have the bandwidth to create/maintain a real camera API, so we're likely not going to be meaningfully extending this anytime soon.

However, the Solutions themselves should allow you to very easily hook up whatever you end up using for webcam- or video-playing, since .send() accepts so many different types of input (HTMLVideoElement, ImageBitmap, HTMLImageElement, HTMLCanvasElement).

**Comment by delmohf** [comment]
ok, I get it !!!

Is there a chance at least to share your onFrame implementation from `@mediapipe/camera_utils`? I didn't find the non-obfuscated source code.
