### ISSUE TITLE
How to detect hand is front or back side

### ISSUE THREAD

**Issue by monxarat** [google/mediapipe#2997]
Hi guys,

How to detect the hand is front side or back side.

**Comment by sgowroji** [comment]
Hi @monxarat, Which platform or language or you preferring in the above ?

**Comment by monxarat** [comment]
@sgowroji 
I have used Android and Python.

**Comment by sgowroji** [comment]
For Android Refer [this](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/java/com/google/mediapipe/components/CameraHelper.java#:~:text=protected%20static%20final,%7D%3B) .

**Comment by monxarat** [comment]
@sgowroji 
No, I don't mean using the front or back camera, I'm talking about "How to detect palm/hand front or back"

![istockphoto-488159261-612x612](https://user-images.githubusercontent.com/4075787/149749245-a599d49d-b76e-480a-ae6c-2c52cb8e4983.jpeg)

**Comment by furkandindar** [comment]
@monxarat you can obtain which hand you're seeing from MULTI_HANDEDNESS label. It will return either "Left" or "Right". Depending on the hand, you can compare landmark locations. For example for the left hand, if THUMB_TIP (index 4)'s x value is smaller than PINKY_TIP (index 20)'s x value it means left hand palm, otherwise it's left hand back. Same thing but reverse calculation applies to right hand.
![](https://google.github.io/mediapipe/images/mobile/hand_landmarks.png)

**Comment by monxarat** [comment]
@furkandindar 
Thank you for your idea. But yeah✌️, rock✊ can detect? I will try it.

**Comment by sgowroji** [comment]
Thank you @furkandindar for sharing. may be @monxarat you can achieve by gesture recognition
