### ISSUE TITLE
Pose Estimation

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#3004]
I am using Facemesh and Holistic solution to extract head pose and body pose.
For example to extract the head pose I calculate the distance between nose tip and the outer corner of right and left eyes. while I am using the camera exactly at the origin (at the middle front of the face) everything is fine but when I change the position of the camera the head pose estimation gives wrong outputs. Actually I expected it, but when I change the thresholds in my script regarding to the new position of camera I still don't get accurate outputs. I am thinking that I might missed a detail or I made a mistake, so I have 3 questions:
1) Is there any other way to extract the head pose (right, left, up and down) except than the method that I use?
2) There is a pipeline named 'Face Pose', what is the output of it? can I directly use that to know what the head pose is?
3) In this [link](https://google.github.io/mediapipe/solutions/face_mesh) you explain about the 'Virtual Camera Parameters', how can I set it close to 'Real Physical Camera Parameter'? by setting it what will be changed?

Thank you

**Comment by lghasemzadeh** [comment]
Hello,
Isn't there any update?
Thx

**Comment by kostyaby** [comment]
Hey @lghasemzadeh,

> Is there any other way to extract the head pose (right, left, up and down) except than the method that I use?

I'd encourage you to take a look at the Face Geometry module ([code](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry), [docs](https://google.github.io/mediapipe/solutions/face_mesh#face-geometry-module))

> There is a pipeline named 'Face Pose', what is the output of it? can I directly use that to know what the head pose is?

Not sure I've seen this pipeline. Perhaps, you meant "Face Geometry" instead of "Face Pose"?

> In this link you explain about the 'Virtual Camera Parameters', how can I set it close to 'Real Physical Camera Parameter'? by setting it what will be changed?

"Virtual Camera Parameters" is a concept for the Face Geometry module, not the Face Mesh module. You can change the params through calculator options of `FaceGeometryEnvGeneratorCalculator` ([example](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_effect/face_effect_gpu.pbtxt#L54-L69)). Alternatively, you can form the `mediapipe.face_geometry.Environment` proto ([definition](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/environment.proto)) yourself client-side and pass it into the pipeline. It'd make sense to use your System OS API to extract physical camera params and them adopt those values into the Face Geometry's `Environment` proto

**Comment by cancan101** [comment]
@lghasemzadeh did end up finding what you were looking for as far as head / face pose estimation?
