### ISSUE TITLE
build MediaPipe Hands error

### ISSUE THREAD

**Issue by chauncey1213** [google/mediapipe#3085]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4)
- windows 10
- 
- Bazel version:
- Bazel 4.2.1

**Describe the problem**:
I ran the following command in cmd.exe
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu`

Then I got the following error message.

```
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/user/mediapipe/WORKSPACE:400:14: in <toplevel>
  C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/tensorflow/workspace2.bzl:876:19: in workspace
  C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/tensorflow/workspace2.bzl:89:27: in _tf_toolchains
  C:/users/user/_bazel_user/b7zs3pka/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/user/_bazel_user/b7zs3pka/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/py/python_configure.bzl:276:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/b7zs3pka/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Repository command failed

INFO: Elapsed time: 0.735s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (16 packages loaded, 11 targets `configured)`
```
Is there any way to fix this error?

**Comment by sgowroji** [comment]
Hi @chauncey1213, Please follow this steps mentioned in this https://github.com/google/mediapipe/issues/724.

**Comment by chauncey1213** [comment]
@sgowroji ,The error is resolved, thanks for your help!

**Comment by sambath-krian** [comment]
> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

@[chauncey1213](https://github.com/chauncey1213)  : hi, could you please send across me the files which are all used to run the hand tracking feature  in desktop\hand_tracking

**Comment by chauncey1213** [comment]
@sambath-krian 
Did you encounter any errors during the build process?

**Comment by sambath-krian** [comment]
yes
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (125 packages loaded, 5857 targets configured).
INFO: Found 1 target...
ERROR: C:/users/sambath.subbarayalu_/_bazel_sambath.subbarayalu_/3n7uzcn5/external/windows_opencv/BUILD.bazel:23:11: @windows_opencv//:opencv: missing input file 'external/windows_opencv/x64/vc15/bin/opencv_world3410.dll', owner: '@windows_opencv//:x64/vc15/bin/opencv_world3410.dll'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/sambath.subbarayalu_/_bazel_sambath.subbarayalu_/3n7uzcn5/external/windows_opencv/BUILD.bazel:23:11 1 input file(s) do not exist
INFO: Elapsed time: 22.851s, Critical Path: 2.58s
INFO: 287 processes: 287 internal.
FAILED: Build did NOT complete successfully

**Comment by sambath-krian** [comment]
but hello world is working

**Comment by sambath-krian** [comment]
it seems that i need some file like hello_world.cc, could you please send me the files

**Comment by chauncey1213** [comment]
Or you can modify 
 C:/users/sambath.subbarayalu_/bazel_sambath.subbarayalu/3n7uzcn5/external/windows_opencv/BUILD.bazel

```
":opt_build": [
            "x64/vc15/lib/opencv_world" + OPENCV_VERSION + ".lib",
            "x64/vc15/bin/opencv_world"+ OPENCV_VERSION + ".dll",
        ],
        ":dbg_build": [
            "x64/vc15/lib/opencv_world" + OPENCV_VERSION + "d.lib",
            "x64/vc15/bin/opencv_world"+ OPENCV_VERSION + "d.dll",
        ],
```
Revise the "OPENCV_VERSION" to your version.
Just like: 
```
"x64/vc15/lib/opencv_world" + "455" + ".lib",
"x64/vc15/bin/opencv_world" + "455" + ".dll"
```
 ```
"x64/vc15/lib/opencv_world" + "455" + "d.lib",
 "x64/vc15/bin/opencv_world"+ "455" + "d.dll"
```

**Comment by sambath-krian** [comment]
thanks for your help 

I have revised opencv as per my version 

# The following build rule assumes that the executable "opencv-3.4.10-vc14_vc15.exe"
# is downloaded and the files are extracted to local.
# If you install OpenCV separately, please modify the build rule accordingly.
cc_library(
    name = "opencv",
    srcs = select({
        ":opt_build": [
            "x64/vc15/lib/opencv_world" + "453" + ".lib",
            "x64/vc15/bin/opencv_world" + "453" + ".dll",
        ],
        ":dbg_build": [
            "x64/vc15/lib/opencv_world" + "453" + "d.lib",
            "x64/vc15/bin/opencv_world" + "453" + "d.dll",
        ],
    }),
    hdrs = glob(["include/opencv2/**/*.h*"]),
    includes = ["include/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],

currently i am getting following build issue 👍 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (1 packages loaded, 405 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/tool/text_to_binary_graph.cc [for host]:
C:\users\sambath.subbarayalu_\_bazel_sambath.subbarayalu_\3n7uzcn5\execroot\mediapipe\bazel-out\host\bin\external\com_github_glog_glog\_virtual_includes\windows_glog_headers\glog\logging.h(1660) : warning C4722: 'google::NullStreamFatal::~NullStreamFatal': destructor never returns, potential memory leak
ERROR: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/calculators/video/BUILD:198:11: C++ compilation of rule '//mediapipe/calculators/video:opencv_video_decoder_calculator' failed (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 46 argument(s) skipped)
.\mediapipe/framework/port/opencv_video_inc.h(88): fatal error C1083: Cannot open include file: 'opencv2/optflow.hpp': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.915s, Critical Path: 4.35s
INFO: 191 processes: 171 internal, 20 local.
FAILED: Build did NOT complete successfully
