### ISSUE TITLE
How to go about integrating mediapipe's pose tracking into an existing Visual Studio C++ project?

### ISSUE THREAD

**Issue by problemSolvingProgramming** [google/mediapipe#3141]
I must admit that I am quite a newb when it comes to build systems. So far I've managed to build the hello_word and the Pose Tracking examples on Windows (going through quite a few hoops along the way) https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

Of course, building those examples gives me an executable, which I can't integrate in another project.

What I'd like to do is have mediapipe as a dll or something similar so I can pass the framework an image and get joint coordinates in return, ideally. Can someone point me in the right direction?

I am going to use this Pose Tracking project

https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/pose_tracking

https://github.com/google/mediapipe written in C ++ language in Visual Studio 2019 for another project in C #. I built it through Bazel in Windows 10 according to the document instructions and output a file.exe gave me I can not use this source code in .cc format in Visual Studio 2019 I wanted to help me how can I compile projects that I compile through Bazel I can use in Visual Studio. I found the following links but unfortunately the output which is in the form of sln project 2019 file in C ++ did not give me output.

**Comment by Notheisz57** [comment]
Did you happen to read through some of the other issues, such as [this thread and it's comments] (https://github.com/google/mediapipe/issues/1162#issuecomment-916169732)?
The comments and links/samples provided by users in that thread helped me understand what/how I should be building.

**Comment by problemSolvingProgramming** [comment]
@Notheisz57 Thank you, yes, I read it, but unfortunately, every time I try to make it, unfortunately, I can not even read this link, but unfortunately, I do not know how it was made and how I should use it in Visual Studio 2019 in C # or C ++? 
https://github.com/HW140701/GoogleMediapipePackageDll
https://github.com/pavloMykhalevych/MediaPipe_pose_tracking_dll

**Comment by sureshdagooglecom** [comment]
Hi @problemSolvingProgramming , did you get a chance to check this issue https://github.com/google/mediapipe/issues/3141

**Comment by Notheisz57** [comment]
I don't represent MediaPipe in any way, but I see users complain about Bazel because they don't understand what it does or why this project uses it.
If you were to build MediaPipe in its entirety as a library, you would be forced to package a 150MB+ OpenCV+MediaPipe combo DLL with your software.
Bazel aims to produce the smallest possible artifact needed for your application, but to do that it needs to see your code.
If you want to utilize the example project as a DLL, you should write C source code yourself that wraps the functionality you need, then add a build rule to produce library output, which is explained with sample code in the link I included before.

**Comment by rigngsbase** [comment]
@Notheisz57 thank you . You can write a document or tutorial step by step or record a video. Explain these steps.
