### ISSUE TITLE
3288 development board is stuck in GPU mode！

### ISSUE THREAD

**Issue by rockygao123** [google/mediapipe#327]
The gesture tracking module runs very stuttered in the GPU mode of the 3288 development board, and has been unable to track it, and cannot get the correct drawing results. Is there an optimization solution?

**Comment by rockygao123** [comment]
Occasionally displayed messy block diagrams

**Comment by jiuqiant** [comment]
Hi, I am not familiar with the 3288 development board. Could you provide more information about the device? Due to the limited resources, MediaPipe team can't generate that our demos run perfectly on every device. Sometimes, the firmware as well as the GPU driver of a Dev board can cause problem as well. We worked with some users to solve a memory leak issue on RK3399 dev board: https://github.com/google/mediapipe/issues/205. Hope you can find something useful there.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
