### ISSUE TITLE
Not getting a packet with empty pose landmarks for a frame without a detection

### ISSUE THREAD

**Issue by tomerlevi444** [google/mediapipe#3350]
On Android pose tracking demo (bazel version 0.8.9):

When a detection is not found in input video's stream (human is outside of camera's frame), no output packet is received.
Expected behavior: receive a packet with landmark list of size 0.

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
Could you provide steps to reproduce this issue.

**Comment by tomerlevi444** [comment]
1. I followed the exact instructions here: `https://google.github.io/mediapipe/getting_started/android.html`
2. Installed via:
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`
and:
`adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk`
3. Made sure I was working against master branch (with no local changes).

When there is no detection in frame, no packet data is written to the log (MainActivity.java:44).
Further checks in debug mode have also shown that the processor's callback is not being triggered in this case.

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
Possibly the model produce "empty packet" instead of vector of zero detections. 
(please try ObserveTimestamps option, in FrameProcessor.  option is only available for AddMultiStreamCallback.  user would need to alter code locally to use AddMultiStreamCallback, and select the ObserveTimetampBounds parameter.  https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L213)
