### ISSUE TITLE
bazel build handtrackinggpu problem.

### ISSUE THREAD

**Issue by fimo719** [google/mediapipe#3365]
- ubuntu 20.04
- Bazel version: 5.0.0
- andriod studio:  SDK=31,  NDK= 21.4.7075529

Hi, I am a question. How can I fix this problem when I running following code

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

ERROR: /home/wen/.cache/bazel/_bazel_wen/740a4b00f4148ebeb0535284293c8bc2/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:13: Building external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar (15 source files) and running annotation processors (AutoValueProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:20: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;

**If this issue is resolved, I would very appreciate it.**

**Comment by sureshdagooglecom** [comment]
Hi @fimo719 ,
Could you provide steps to reproduce this issue.

**Comment by fimo719** [comment]
I completed the mediapipe Installation steps. 
When I run Mediapipe on andriod code, I added some code in WORKSPACE repositories .
The code is 

repositories = [
 "https://maven.aliyun.com/repository/google",
 "https://maven.aliyun.com/repository/central",
 "https://maven.aliyun.com/repository/public",
 ],

**Comment by fimo719** [comment]
Thank you for answering my question.

**Comment by badchewie** [comment]
Hi I am having the issue , I tried adding the above code to my WORKSPACE as repositories yet I am still getting the same error.

`repositories = [
        "https://maven.google.com",
        "https://dl.google.com/dl/android/maven2",
        "https://repo1.maven.org/maven2",
        "https://jcenter.bintray.com",
        "https://maven.aliyun.com/repository/google",
	"https://maven.aliyun.com/repository/central",
	"https://maven.aliyun.com/repository/public",
    ],`

`user@master:~/mediapipe$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --verbose_failures 
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /home/user/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/user/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (1 packages loaded, 1066 targets configured).
INFO: Found 1 target...
ERROR: /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:13: Building external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar (15 source files) and running annotation processors (AutoValueProcessor) failed: (Exit 1): java failed: error executing command 
  (cd /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/execroot/mediapipe && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
    PATH=/home/user/.cache/bazelisk/downloads/bazelbuild/bazel-5.2.0-linux-x86_64/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.resources=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-opens=java.base/java.nio=ALL-UNNAMED' '--add-opens=java.base/java.lang=ALL-UNNAMED' '--patch-module=java.compiler=external/remote_java_tools/java_tools/java_compiler.jar' '--patch-module=jdk.compiler=external/remote_java_tools/java_tools/jdk_compiler.jar' -jar external/remote_java_tools/java_tools/JavaBuilder_deploy.jar @bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar-0.params @bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar-1.params)
# Configuration: 47cfdde1bbfb6cf4a8cd0763fbc523ab11d5e5cb4db1c1385c6f2dc44738f04e
# Execution platform: @local_execution_config_platform//:platform
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:20: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:16: error: package com.android.dx.cf.direct does not exist
import com.android.dx.cf.direct.DirectClassFile;
                               ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:17: error: package com.android.dx.cf.direct does not exist
import com.android.dx.cf.direct.StdAttributeFactory;
                               ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:18: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:19: error: package com.android.dx.dex does not exist
import com.android.dx.dex.DexOptions;
                         ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:20: error: package com.android.dx.dex.cf does not exist
import com.android.dx.dex.cf.CfOptions;
                            ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:21: error: package com.android.dx.dex.cf does not exist
import com.android.dx.dex.cf.CfTranslator;
                            ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:22: error: package com.android.dx.dex.code does not exist
import com.android.dx.dex.code.PositionList;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:23: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.ClassDefItem;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:24: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:25: error: package com.android.dx.util does not exist
import com.android.dx.util.ByteArray;
                          ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:209: error: cannot find symbol
      DxContext context,
      ^
  symbol:   class DxContext
  location: class DexBuilder
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:187: error: cannot find symbol
  private final DxContext context;
                ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:188: error: cannot find symbol
  private final DexOptions dexOptions;
                ^
  symbol:   class DexOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:189: error: cannot find symbol
  private final CfOptions cfOptions;
                ^
  symbol:   class CfOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:195: error: cannot find symbol
  public Dexing(DxContext context, DexingOptions options) {
                ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
         ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
                            ^
  symbol:   class DexOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
                                                   ^
  symbol:   class CfOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:206: error: cannot find symbol
  public static DirectClassFile parseClassFile(byte[] classfile, String classfilePath) {
                ^
  symbol:   class DirectClassFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:214: error: cannot find symbol
  public DexFile newDexFile() {
         ^
  symbol:   class DexFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
                                   ^
  symbol:   class DexFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
                                                 ^
  symbol:   class DirectClassFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
         ^
  symbol:   class ClassDefItem
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:131: error: cannot find symbol
    public CfOptions toCfOptions(DxContext context) {
                                 ^
  symbol:   class DxContext
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:131: error: cannot find symbol
    public CfOptions toCfOptions(DxContext context) {
           ^
  symbol:   class CfOptions
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:145: error: cannot find symbol
    public DexOptions toDexOptions() {
           ^
  symbol:   class DexOptions
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexConverter.java:16: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexConverter.java:29: error: cannot find symbol
  public DexFile toDexFile(byte[] classfile, String classfilePath) {
         ^
  symbol:   class DexFile
  location: class DexConverter
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:19: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:20: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:21: error: package com.android.dx.merge does not exist
import com.android.dx.merge.CollisionPolicy;
                           ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:22: error: package com.android.dx.merge does not exist
import com.android.dx.merge.DexMerger;
                           ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:47: error: cannot find symbol
  private final ArrayList<Dex> currentShard = new ArrayList<>();
                          ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:51: error: cannot find symbol
  private final DxContext context;
                ^
  symbol:   class DxContext
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileArchive.java:18: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:16: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:17: error: package com.android.dex does not exist
import com.android.dex.FieldId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:18: error: package com.android.dex does not exist
import com.android.dex.MethodId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:19: error: package com.android.dex does not exist
import com.android.dex.ProtoId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:20: error: package com.android.dex does not exist
import com.android.dex.TypeList;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:61: error: cannot find symbol
      DxContext context,
      ^
  symbol:   class DxContext
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:79: error: cannot find symbol
  public DexFileAggregator add(Dex dexFile) {
                               ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:131: error: cannot find symbol
  private void writeMergedFile(Dex... dexes) {
                               ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:144: error: cannot find symbol
  private Dex merge(Dex... dexes) throws IOException {
                    ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:144: error: cannot find symbol
  private Dex merge(Dex... dexes) throws IOException {
          ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:47: error: cannot find symbol
  public boolean track(Dex dexFile) {
                       ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:58: error: cannot find symbol
  private void trackFieldsAndMethods(Dex dexFile) {
                                     ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:69: error: cannot find symbol
  private static String typeName(Dex dex, int typeIndex) {
                                 ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:94: error: cannot find symbol
    static MethodDescriptor fromDex(Dex dex, int methodIndex) {
                                    ^
  symbol:   class Dex
  location: class MethodDescriptor
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:75: error: cannot find symbol
    static FieldDescriptor fromDex(Dex dex, int fieldIndex) {
                                   ^
  symbol:   class Dex
  location: class FieldDescriptor
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileArchive.java:47: error: cannot find symbol
  public DexFileArchive addFile(ZipEntry entry, Dex dex) throws IOException {
                                                ^
  symbol:   class Dex
  location: class DexFileArchive
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:188: error: cannot find symbol
  private class RunDexMerger implements Callable<Dex> {
                                                 ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:190: error: cannot find symbol
    private final Dex[] dexes;
                  ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:192: error: cannot find symbol
    public RunDexMerger(Dex... dexes) {
                        ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:197: error: cannot find symbol
    public Dex call() throws IOException {
           ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:212: error: cannot find symbol
    private final ListenableFuture<Dex> dex;
                                   ^
  symbol:   class Dex
  location: class WriteFile
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:216: error: cannot find symbol
    public WriteFile(String filename, ListenableFuture<Dex> dex, DexFileArchive dest) {
                                                       ^
  symbol:   class Dex
  location: class WriteFile
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:21: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:22: error: package com.android.dex does not exist
import com.android.dex.DexFormat;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:23: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:20: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:21: error: package com.android.dex does not exist
import com.android.dex.DexFormat;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:16: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:17: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:28: error: cannot find symbol
  public static Dex toDex(DexFile dex) throws IOException {
                          ^
  symbol:   class DexFile
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:28: error: cannot find symbol
  public static Dex toDex(DexFile dex) throws IOException {
                ^
  symbol:   class Dex
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:35: error: cannot find symbol
  static byte[] encode(DexFile dex) throws IOException {
                       ^
  symbol:   class DexFile
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:164: error: cannot find symbol
      defaultValue = "" + DexFormat.MAX_MEMBER_IDX,
                          ^
  symbol:   variable DexFormat
  location: class Options
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:112: error: cannot find symbol
      defaultValue = "" + DexFormat.MAX_MEMBER_IDX,
                          ^
  symbol:   variable DexFormat
  location: class Options
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
INFO: Elapsed time: 63.808s, Critical Path: 11.04s
INFO: 48 processes: 48 internal.
FAILED: Build did NOT complete successfully
`
