### ISSUE TITLE
SyncSetInputStreamHandler with cc->SetOffset(TimestampDiff(0)); can not work together

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#343]
SyncSetInputStreamHandler sync set has seprate timestamp.

may be one is more less than anther.

if more large stream first arrived, and with SetOffset(TimestampDiff(0)), the calculator tiemstamp update the more large number, and the less timestamp arrived may corrupt.

how do I solution this?

sync set A: 9->10->11->12->13
sync set B: 1->2->3->4->5

calculator: SetOffset(TimestampDiff(0))

arrive order: 9->1->2->10

when 9 arrived, the next timestamp is 10, the 10 is update to the all outputstream, but the 1 is more less than 10, it may corrupt

**Comment by jiqimaogou** [comment]
![image](https://user-images.githubusercontent.com/1407040/71446815-9d721880-2762-11ea-8b41-dcc91d1b8b10.png)

I Think achieve an InputStreamHandler like DefaultInputStreamHandler would be better,
first, define a main inputstream, and the inputstream also be processed when it arrived.
and side inputstream, 
if side inputstream packet's timestamp is less than the current main packet timestamp, it will be processed with the main current packet.
if side inputstream packet's timestamp is larger than the current main packet tiemstamp, and it will be wait for the main bound is large than the side inputstream, and will be processed with the main packet in future.

**Comment by hadon** [comment]
Hi Jiqimaogou,

Yes, it's true that SetOffset(0) normally requires DefaultInputStreamHandler. 
SyncSetInputStreamHandler and ImmediateInputStreamHandler normally violate SetOffset(0).  

You suggest an InputStreamHandler that processes each "main-packet" as soon as it arrives, and couples it with a recent "auxiliary-packet".  Behavior similar to this can be arranged using the "PacketClonerCalculator".  The main-packet is used as the "tick input" to the "PacketClonerCalculator", while the auxiliary-packet is used as a "base input" to the "PacketClonerCalculator".  The "PacketClonerCalculator" can be configured with "ImmediateInputStreamHandler", so that it produces output immediately for each "tick input".  With this configuration, each main-packet is coupled with the most recent available "auxiliary-packet".  

Let me know if PacketClonerCalculator can address your use case.

**Comment by jiqimaogou** [comment]
> Hi Jiqimaogou,
> 
> Yes, it's true that SetOffset(0) normally requires DefaultInputStreamHandler.
> SyncSetInputStreamHandler and ImmediateInputStreamHandler normally violate SetOffset(0).
> 
> You suggest an InputStreamHandler that processes each "main-packet" as soon as it arrives, and couples it with a recent "auxiliary-packet". Behavior similar to this can be arranged using the "PacketClonerCalculator". The main-packet is used as the "tick input" to the "PacketClonerCalculator", while the auxiliary-packet is used as a "base input" to the "PacketClonerCalculator". The "PacketClonerCalculator" can be configured with "ImmediateInputStreamHandler", so that it produces output immediately for each "tick input". With this configuration, each main-packet is coupled with the most recent available "auxiliary-packet".
> 
> Let me know if PacketClonerCalculator can address your use case.

thank you, let me try, i have waiting for some days for your answer...

**Comment by jiqimaogou** [comment]
![image](https://user-images.githubusercontent.com/1407040/71728849-3696e280-2e79-11ea-91ad-634e63bad06d.png)

if I use PacketClonerCalculator everytime the option come everytime, I must store the lastImagePath to decide  wether to decode the image.

if I use SyncSetInputStreamHandler, I just decide weahter packet is empty, if not empty decode it.
and PacketClonerCalculator is more complicated if have a PacketClonerInputStreamHandler.

I think multi stream control should be in InputStreamHandler which is more flexible than in calculator.
