### ISSUE TITLE
Why classification related calculators have no GPU implementation?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#345]

**Comment by jiuqiant** [comment]
Can you make the question more specific? For example, which calculator are you referring to?

**Comment by yxchng** [comment]
https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/labels_to_render_data_calculator.cc

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_classification_calculator.cc

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/top_k_scores_calculator.cc

These 3 calculators are needed to run image classification pipeline and they all have no GPU implementations.

**Comment by jiuqiant** [comment]
@yxchng , you are right. Those calculators don't have GPU implementation. 

However, I don't see why those calculators need GPU implementation unless the entire pipeline needs everything running on GPU. Making those calculators work on GPU doesn't significantly improve the performance of our current use case since the model inference and rendering are already on GPU. Moreover, we need to make sure that the GPU implementation works across platforms when a GPU calculator is released officially.

Those three calculators are not hard to understand. Feel free to make the GPU version based on the CPU logic by yourself.

**Comment by yxchng** [comment]
@jiuqiant Yes but the problem is I need this https://github.com/google/mediapipe/issues/322#event-2895589439 in order to only run the TFLite part on GPU. Otherwise there is also no way to convert GPU tensors into CPU frame and then pass through these calculators. Or is there?

**Comment by mcclanahoochie** [comment]
As mentioned in https://github.com/google/mediapipe/issues/322#issuecomment-566834000 , you can still run inference on GPU and output directly to CPU tensors:
_TfLiteConverter(GPU)->TfLiteInference(GPU in / CPU out)->TensorsToClassifications(CPU)_

The  TensorsToX  calculators that _don't_ accept GPU input are done on purpose, as the GPU doesn't buy you anything perf wise, and it is also assumed that those calculators will be connected directly to the inference calculator anyway, which supports GPU->CPU conversion. 

More generally, I do agree that a generic GPU tensor to CPU calculator could be useful in some cases, and it may appear in the future, but for the meantime try using the inference calculator in this way (GPU -> CPU).

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
