### ISSUE TITLE
Box Tracking is broken on Windows 11

### ISSUE THREAD

**Issue by PZerua** [google/mediapipe#3523]
When executing the Box Tracking example demo with my webcam, on Windows it shows an increasing number (+150) of inexisting detections (not persons, but just random things) filling the whole screen. Looks completely broken.

**System information**
- Windows 11 (21996.1)
- MediaPipe version: v0.8.10.2
- Bazel version: 5.2.0
- Solution: Box Tracking
- Programming Language: C++

**Describe the expected behavior:**
On Linux it works with no problem, I compile and execute the object_tracking_cpu demo and Box Tracking works as expected.

**Standalone code you may have used to try to get what you need :**
```
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//GTI//AppData//Local//Programs//Python//Python310//python.exe" mediapipe/examples/desktop/object_tracking:object_tracking_cpu

set GLOG_logtostderr=1
bazel-bin\mediapipe\examples\desktop\object_tracking\object_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt
```

**Other info / Complete Logs :**
[log.txt](https://github.com/google/mediapipe/files/9128641/log.txt)

**Comment by PZerua** [comment]
For the record, I have tried Object Detection: ``object_detection_cpu.exe`` with ``object_detection_desktop_live.pbtxt``, and works with no problem.

**Comment by hadon** [comment]
I've tried to replicate this, starting on my home computer running windows 10.  I've gone through the mediapipe windows installation, and successfully compiled hello_world.exe.  I have found it necessary to avoid "optflow.hpp" in opencvx_video_inc.h, since "optflow.hpp" seems to be omitted from OpenCv 4.0.  I still need to correctly configure opencv on windows in order to compile "object_detection_cpu" and "object_detection_tensorflow".  I believe MediaPipe on windows is still "experimental".  

Anyway, I don't have access to a machine running windows 11 at the moment.  It looks like you are better positioned to diagnose this problem than I am.  If you or another community member can investigate what is different and failing between windows 10 and windows 11, and between "object_detection_cpu" and "object_detection_tensorflow", you can report your findings on this github issue, and your help will be appreciated.

**Comment by kuaashish** [comment]
Hi @PZerua,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3523#issuecomment-1238928698) and if you could report any of the findings that will be much appreciated. Thank you!
