### ISSUE TITLE
Extracting hands bounding boxes from sequence of frames

### ISSUE THREAD

**Issue by faresbs** [google/mediapipe#353]
hi, 

I am using mediapipe for hands tracking. I have a dataset of sequences of images and i want to use mediapipe to extract hand regions from the images and then save the hand regions in a destination folder.
Also, is there a way I can use a sequence of images (.png) as input instead of a video (.mp4). i tried converting the sequence to mp4 using ffmpeg but mediapipe produces an empty video output (it works fine for other mp4 videos).

i appreciate any feedback, thank you

**Comment by eknight7** [comment]
Are you trying to do this on desktop?

You can use the existing example code https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html#multi-hand-tracking-on-desktop and https://mediapipe.readthedocs.io/en/latest/hand_tracking_desktop.html#hand-tracking-on-desktop to run hand tracking on desktop. 

Similar to https://github.com/google/mediapipe/issues/266#issuecomment-558005653, modify your app for extracting the bounding boxes from the detections.

Reg. sequence of images - practically that is already what is happening in the desktop app. Instead of reading frames from a file, read each image PNG file and send that to the graph, and save the output from the graph.

**Comment by faresbs** [comment]
I successfully retrieved the hand bounding box location through the webcam. Instead of reading frames from the webcam, I tried passing the PNG frames from a file but i failed. could you please share the modifications needed in the demo_run_graph_main_gpu.cc? 
Yes, i am trying to do on desktop and on GPU.

**Comment by eknight7** [comment]
Can you share the code you tried for passing the frame from a PNG file and the modifications you made please? Thanks.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by dgrnd4** [comment]
@eknight7 hi, i want to extract the coordinates of the bounding boxe, do you have any codes to share?
if not, could you please help me doing it?

**Comment by eknight7** [comment]
Hi @dgrnd4 if you are still running into a problem, please open a new github issue. It will be easier for us to track and follow-up there. Thanks!

**Comment by dgrnd4** [comment]
@eknight7 already done, I’ve finished my final project/thesis and now I’m graduated already. MediaPipe was used to create a machine learning model to understand if an hand is wearing gloves or not!!
