### ISSUE TITLE
The need of Provisioning Profile for iOS project

### ISSUE THREAD

**Issue by yohanessatria** [google/mediapipe#3599]
Hello! I am a newbie in iOS programming so I beg your pardon if I might ask a stupid question. 

So in the documentation, it mentioned about the need for the provisioning profile if we want to develop it in the iOS device. so my question is whether the mediapipe can run on the simulator or not. because right now I still have some errors when building any example from the mediapipe.xcodeproj

thanks in advance!

**Comment by kuaashish** [comment]
Hi @yohanessatria, Have you looked at this closed issue #2132 and [#2132(comment)](https://github.com/google/mediapipe/issues/2132#issuecomment-926344776), shared the workaround to use mediapipe on iOS simulator. 
Meanwhile, Could you provide the complete error log to investigate further. Thank you!

**Comment by yohanessatria** [comment]
@kuaashish Hi, sorry for my late reply. Yes, I have seen this post after you mentioned it. But my problem is that I can't even build the iOS example project. 

Here's the screenshot of  the error I get whenever I try to run the project

<img width="922" alt="Screen Shot 2022-08-15 at 8 38 24 AM" src="https://user-images.githubusercontent.com/35787092/184561268-5900d60b-3020-4c9a-a16f-f5754a47c9fe.png">

**Comment by yohanessatria** [comment]
also,
<img width="789" alt="Screen Shot 2022-08-15 at 10 04 42 AM" src="https://user-images.githubusercontent.com/35787092/184565835-1c6b4fe0-b441-4d2e-a9ad-7c7953773b50.png">
 I got this error message(red highlight) mentioning about failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'. So is this the actual cause of my problem? if it is, is there any way for me to run MediaPipe without any provisioning profile since I am not subscribing to Apple Developer Program

**Comment by kuaashish** [comment]
Hi @yohanessatria, Yes, It looks like an error has occurred because of the missing provisioning profile. You could follow this closed issue #95 and [#95[Comment]](https://github.com/google/mediapipe/issues/95#issuecomment-529731141) to fix it.

Apple allows to deploy, run and test the application on iOS devices without subscribing to the Apple developer program. 
Please follow this [#SO](https://stackoverflow.com/questions/4952820/test-ios-app-on-device-without-apple-developer-program-or-jailbreak) issue for more information. 

Thank you!

**Comment by yohanessatria** [comment]
Alright, thanks for your answer! Problem solved.
Thanks once again!
