### ISSUE TITLE
What is the way to dependent mediapipe into my ios app?

### ISSUE THREAD

**Issue by noppefoxwolf** [google/mediapipe#364]
I want to use mediapipe for my app.
But it doesn't seem easy.
Is there the way to build to single binary?
(Preferably without bazel dependency.)

**Comment by mapleyuan** [comment]
I have the same problem, Any update?

**Comment by fenollp** [comment]
From https://github.com/bazelbuild/rules_apple/blob/master/doc/frameworks.md
Using Bazel one can do:
```python
MIN_IOS_VERSION = "10.0"

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_static_framework")

ios_static_framework(
    name = "MyFramework",
    # If `hdrs` isn't set Headers and Modules folders won't get generated
    hdrs = ["MyHeader.h"],
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        ":MyLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)
```
```
bazel build --config=ios_arm64 mediapipe/your/ios/project:MyFramework
unzip -l bazel-bin/mediapipe/your/ios/project/MyFramework.zip
```

Not sure which of `ios_static_framework` or `ios_framework` you'll want to use ;)

**Comment by noppefoxwolf** [comment]
Thank you!
I'll try it.

**Comment by noppefoxwolf** [comment]
@fenollp 
Thank you for your advice!
I tried build framework, But It's not linked calculators.

```
No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"
No registered object with name: PreviousLoopbackCalculator; Unable to find Calculator "PreviousLoopbackCalculator"
No registered object with name: GateCalculator; Unable to find Calculator "GateCalculator"
No registered object with name: HandDetectionSubgraph; Unable to find Calculator "HandDetectionSubgraph"
No registered object with name: HandLandmarkSubgraph; Unable to find Calculator "HandLandmarkSubgraph"
No registered object with name: PreviousLoopbackCalculator; Unable to find Calculator "PreviousLoopbackCalculator"
No registered object with name: MergeCalculator; Unable to find Calculator "MergeCalculator"
No registered object with name: RendererSubgraph; Unable to find Calculator "RendererSubgraph"" UserInfo={NSLocalizedDescription=ValidatedGraphConfig Initialization failed.
```

It seems like some developer had this issue.
https://github.com/google/mediapipe/issues/144
https://github.com/google/mediapipe/issues/294#issuecomment-574201789

Do you know how to way to fix this issue using bazel?

**Comment by fenollp** [comment]
@noppefoxwolf Sorry I missed your previous message somehow.

Was this with `ios_static_framework`? What do you get with `ios_framework`?
Maybe there's some linker flags to explore to force static linkage when building the iOS framework.

WRT duplicate symbols errors this should help: https://github.com/google/mediapipe/issues/144#issuecomment-560098009
Maybe it'll even unblock the other issue.

I'm quite interested in the results myself. Is there a place where you're sharing the code of your experiments somewhere? I could take a look.

**Comment by noppefoxwolf** [comment]
@fenollp 

I'm using `ios_framework `.
My build script and project are here.
https://github.com/noppefoxwolf/mediapipe/tree/develop/TrackerFramework

Makefile builds Framework and strip duplicate symbol.
```
$make framework
```

Some resources are bundle application directly.
Because for some reason framework cannot load bundle myself.

**Comment by noppefoxwolf** [comment]
I successfully load bundle and link calculator.
I should use `ios framework`.

If anyone had same issue. Please read my lesson code.
https://github.com/noppefoxwolf/mediapipe/tree/develop/TrackerFramework

I really appreciate for @fenollp 's advice.

**Comment by kulich-ua** [comment]
@noppefoxwolf, thank you very much for sharing your solution!
Based on it I was also able to build mediapipe hand tracking logic as a static framework.
And here https://github.com/google/mediapipe/issues/144#issuecomment-639434434 I described my workaround.

**Comment by fenollp** [comment]
Hopefully this helps you build an importable iOS framework: https://medium.com/@powderapp/mediapipe-tutorial-find-memes-that-match-your-facial-expression-9bf598da98c0

The whole process should be simpler and more robust when there are Bazel rules to build xcframeworks. In the meantime this works.

**Comment by weinixuehao** [comment]
@fenollp 
I can not open that page in 
![image](https://user-images.githubusercontent.com/17869361/85981095-2de12c80-ba16-11ea-8333-f82cbb353587.png)

**Comment by fenollp** [comment]
@weinixuehao Ah, Medium... Can you access the article through your browser's incognito mode?

I'll see if there's any way to disable all the paywalls. It seems I wasn't quite thorough the first time!

**Comment by weinixuehao** [comment]
```
ios_static_framework(
    name = "HedEdgeDetection_Framework",
    # If `hdrs` isn't set Headers and Modules folders won't get generated
    hdrs = [
        "//mediapipe/objc:MPPCameraInputSource.h",
        "//mediapipe/objc:MPPGraph.h",
        "//mediapipe/objc:MPPLayerRenderer.h",
        "//mediapipe/objc:MPPInputSource.h",
    ],
        
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        "@ios_opencv//:OpencvFramework",
        "HedEdgeDetectionLibrary"
    ]
)
```
@fenollp how to set hdrs with the same as original path? As xcode build error with following error.
![image](https://user-images.githubusercontent.com/17869361/86007937-b679c000-ba4a-11ea-9345-227ee399ae7f.png)

**Comment by slajar** [comment]
@noppefoxwolf I tied to upgrade your example to the latest mediapipe with bazel4. I builds a long time an then the linker fails :( 

Do you have an idea why this is failing?
ERROR: /Users/<mysecretpath>/TrackerExample/mediapipe/mediapipe/develop/BUILD:3:14: Linking of rule '//mediapipe/develop:MyFramework.__internal__.apple_binary' failed (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 273 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 273 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture arm64:
  "absl::lts_2020_09_23::InternalError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<mediapipe::NormalizedLandmarkList>() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
  "absl::lts_2020_09_23::strings_internal::CatPieces(std::initializer_list<absl::lts_2020_09_23::string_view>)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > absl::lts_2020_09_23::StrCat<>(absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
  "absl::lts_2020_09_23::InvalidArgumentError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<mediapipe::NormalizedLandmarkList>() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
      absl::lts_2020_09_23::StatusOr<std::__1::vector<google::protobuf::MessageLite const*, std::__1::allocator<google::protobuf::MessageLite const*> > > mediapipe::packet_internal::ConvertToVectorOfProtoMessageLitePtrs<mediapipe::NormalizedLandmarkList>(mediapipe::NormalizedLandmarkList const*, std::__1::integral_constant<bool, false>) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
  "absl::lts_2020_09_23::ByString::ByString(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::strings_internal::SelectDelimiter<char const*>::type, absl::lts_2020_09_23::AllowEmpty> absl::lts_2020_09_23::StrSplit<char const*>(absl::lts_2020_09_23::strings_internal::ConvertibleToStringView, char const*) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
  "absl::lts_2020_09_23::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, absl::lts_2020_09_23::string_view)", referenced from:
      mediapipe::NormalizedLandmarkList const& mediapipe::Packet::Get<mediapipe::NormalizedLandmarkList>() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
  "absl::lts_2020_09_23::ByString::Find(absl::lts_2020_09_23::string_view, unsigned long) const", referenced from:
      absl::lts_2020_09_23::strings_internal::SplitIterator<absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::ByString, absl::lts_2020_09_23::AllowEmpty> >::operator++() in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/develop:MyFramework failed to build
Use --verbose_failures to see the command lines of failed bui

**Comment by yuxiaohui78** [comment]
> @noppefoxwolf I tied to upgrade your example to the latest mediapipe with bazel4. I builds a long time an then the linker fails :(
> 
> Do you have an idea why this is failing?
> 
> `
> 
> > ERROR: /Users//TrackerExample/mediapipe/mediapipe/develop/BUILD:3:14: Linking of rule '//mediapipe/develop:MyFramework.**internal**.apple_binary' failed (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 273 argument(s) skipped)
> > Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 273 argument(s) skipped)
> > Use --sandbox_debug to see verbose messages from the sandbox
> > Undefined symbols for architecture arm64:
> > "absl::lts_2020_09_23::InternalError(absl::lts_2020_09_23::string_view)", referenced from:
> > absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsTypemediapipe::NormalizedLandmarkList() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > "absl::lts_2020_09_23::strings_internal::CatPieces(std::initializer_listabsl::lts_2020_09_23::string_view)", referenced from:
> > std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > absl::lts_2020_09_23::StrCat<>(absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&, absl::lts_2020_09_23::AlphaNum const&) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > "absl::lts_2020_09_23::InvalidArgumentError(absl::lts_2020_09_23::string_view)", referenced from:
> > absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsTypemediapipe::NormalizedLandmarkList() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > absl::lts_2020_09_23::StatusOr<std::__1::vector<google::protobuf::MessageLite const*, std::__1::allocator<google::protobuf::MessageLite const*> > > mediapipe::packet_internal::ConvertToVectorOfProtoMessageLitePtrsmediapipe::NormalizedLandmarkList(mediapipe::NormalizedLandmarkList const*, std::__1::integral_constant<bool, false>) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > "absl::lts_2020_09_23::ByString::ByString(absl::lts_2020_09_23::string_view)", referenced from:
> > absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::strings_internal::SelectDelimiter<char const*>::type, absl::lts_2020_09_23::AllowEmpty> absl::lts_2020_09_23::StrSplit<char const*>(absl::lts_2020_09_23::strings_internal::ConvertibleToStringView, char const*) in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > "absl::lts_2020_09_23::operator<<(std::__1::basic_ostream<char, std::__1::char_traits >&, absl::lts_2020_09_23::string_view)", referenced from:
> > mediapipe::NormalizedLandmarkList const& mediapipe::Packet::Getmediapipe::NormalizedLandmarkList() const in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > "absl::lts_2020_09_23::ByString::Find(absl::lts_2020_09_23::string_view, unsigned long) const", referenced from:
> > absl::lts_2020_09_23::strings_internal::SplitIterator<absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::ByString, absl::lts_2020_09_23::AllowEmpty> >::operator++() in libHandTrackingGpuAppLibrary.a(ObjcClass.o)
> > ld: symbol(s) not found for architecture arm64
> > clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > Error in child process '/usr/bin/xcrun'. 1
> > Target //mediapipe/develop:MyFramework failed to build
> > Use --verbose_failures to see the command lines of failed bui`

I got the same errors as you got. Have you got a solution to fix that? Thanks!

**Comment by nswdewy** [comment]
Hi,bros (@fenollp @noppefoxwolf @slajar @yuxiaohui78 @weinixuehao )!

I'm attempting to compile a posetracking framework to my project.

@noppefoxwolf's demo can run successfully, but is not a framework for whole pose tracking.

I can build and run the application successfully by tulsi or command lines.

But when I use the complied framework to a project, it occurs error "'absl/memory/memory.h' file not found"
![image](https://user-images.githubusercontent.com/26194478/124540104-5255bd00-de51-11eb-8e75-1f082ca3662b.png)

I have been stuck with this problems for couple of days….

Dose anybody have the solution to this problem?  
I will be very grateful for your suggestions.

**Comment by yuxiaohui78** [comment]
Hi @nswdewy,
I have built a full body pose tracking framework based on  @noppefoxwolf 's code.
You can check it out.
[Fullbody_pose_tracking_iOS.zip](https://github.com/google/mediapipe/files/6777174/Fullbody_pose_tracking_iOS.zip)

**Comment by tommypham** [comment]
Thanks @noppefoxwolf , I can build the framework with '**-std=c++17**' now.

**Comment by MenThu** [comment]
@yuxiaohui78

**Comment by MenThu** [comment]
@yuxiaohui78 
Hi, yuxiaohui, I'm also trying to compile posetracking's framework, but I've encountered several problems, since our goals are the same, I hope you can help solve them. thank you

my bazel version is 3.7.2 
my BUILD content is 
`MIN_IOS_VERSION = "10.0"

BUNDLE_ID_PREFIX = "org.douyu.vtuber.mediapipe"

load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_framework",
)

FRAMEWORK_HEADERS = [
    "DYMediaPipePoseTrakingManager.h",
]

FRAMEWORK_NAME = "DYPoseTraking"

ios_framework(
    name = FRAMEWORK_NAME,
    hdrs = FRAMEWORK_HEADERS,
    bundle_id = BUNDLE_ID_PREFIX + FRAMEWORK_NAME,
    bundle_name = FRAMEWORK_NAME,
    #bundle_id = "com.google.mediapipe.douyu.PoseTrackingGpuFramework",
    infoplists = [
        "//mediapipe/examples/ios/common:Info.plist",
        "Info.plist",
    ],
    families = [
        "iphone",
    ],
    #linkopts = ["-force_load"],
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        ":DYMediaPipePoseTrakingManager",
        "@ios_opencv//:OpencvFramework",
    ],
)


objc_library(
    name = "DYMediaPipePoseTrakingManager",
    srcs = [
        "DYMediaPipePoseTrakingManager.mm",
    ],
    hdrs = FRAMEWORK_HEADERS,
    copts = ["-std=c++17"],
    data = [
        "//mediapipe/graphs/pose_tracking:pose_tracking_gpu.binarypb",
        "//mediapipe/modules/pose_detection:pose_detection.tflite",
        "//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",
    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit",
    ],
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
)`

If I don't add `linkopts = ["-force_load"]` to BUILD file, the result framework is only 20M, and program failed at `- (BOOL)sendPacket:(const mediapipe::Packet&)packet
        intoStream:(const std::string&)streamName
             error:(NSError**)error {
  absl::Status status = _graph->AddPacketToInputStream(streamName, packet);
  if (!status.ok() && error) *error = [NSError gus_errorWithStatus:status];
  return status.ok();
}`  and status.message is NULL 

if i add force_load, then i failed at bazel compiled , the error is 'wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 323 argument(s) skipped)' 
I wonder if this has anything to do with my bazel version

Would you show me your BUILD? and i guess you are Chinese base on your name, it will be much more efficient if we can communicate in Chinese 😊

**Comment by MenThu** [comment]
@yuxiaohui78 

Hi, yuxiaohui, I'm also trying to compile posetracking's framework, but I've encountered several problems, since our goals are the same, I hope you can help solve them. thank you

my bazel version is 3.7.2
my BUILD content is
`'MIN_IOS_VERSION = "10.0"

BUNDLE_ID_PREFIX = "org.douyu.vtuber.mediapipe"

load(
"@build_bazel_rules_apple//apple:ios.bzl",
"ios_framework",
)

FRAMEWORK_HEADERS = [
"DYMediaPipePoseTrakingManager.h",
]

FRAMEWORK_NAME = "DYPoseTraking"

ios_framework(
name = FRAMEWORK_NAME,
hdrs = FRAMEWORK_HEADERS,
bundle_id = BUNDLE_ID_PREFIX + FRAMEWORK_NAME,
bundle_name = FRAMEWORK_NAME,
#bundle_id = "com.google.mediapipe.douyu.PoseTrackingGpuFramework",
infoplists = [
"//mediapipe/examples/ios/common:Info.plist",
"Info.plist",
],
families = [
"iphone",
],
#linkopts = ["-force_load"],
minimum_os_version = MIN_IOS_VERSION,
deps = [
":DYMediaPipePoseTrakingManager",
"@ios_opencv//:OpencvFramework",
],
)

objc_library(
name = "DYMediaPipePoseTrakingManager",
srcs = [
"DYMediaPipePoseTrakingManager.mm",
],
hdrs = FRAMEWORK_HEADERS,
copts = ["-std=c++17"],
data = [
"//mediapipe/graphs/pose_tracking:pose_tracking_gpu.binarypb",
"//mediapipe/modules/pose_detection:pose_detection.tflite",
"//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",
],
sdk_frameworks = [
"AVFoundation",
"CoreGraphics",
"CoreMedia",
"UIKit",
],
deps = [
"//mediapipe/objc:mediapipe_framework_ios",
] + select({
"//mediapipe:ios_i386": [],
"//mediapipe:ios_x86_64": [],
"//conditions:default": [
"//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
"//mediapipe/framework/formats:landmark_cc_proto",
],
}),
)'`

If I don't add linkopts = ["-force_load"] to BUILD file, the result framework is only 20M, and program failed at - (BOOL)sendPacket:(const mediapipe::Packet&)packet intoStream:(const std::string&)streamName error:(NSError**)error { absl::Status status = _graph->AddPacketToInputStream(streamName, packet); if (!status.ok() && error) *error = [NSError gus_errorWithStatus:status]; return status.ok(); } and status.message is NULL

if i add force_load, then i failed at bazel compiled , the error is 'wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 323 argument(s) skipped)'
I wonder if this has anything to do with my bazel version

Would you show me your BUILD? and i guess you are Chinese base on your name, it will be much more efficient if we can communicate in Chinese 😊

**Comment by MenThu** [comment]
@yuxiaohui78 

Hi, yuxiaohui, I'm also trying to compile posetracking's framework, but I've encountered several problems, since our goals are the same, I hope you can help solve them. thank you

my bazel version is 3.7.2
my BUILD content is
`'MIN_IOS_VERSION = "10.0"

BUNDLE_ID_PREFIX = "org.douyu.vtuber.mediapipe"

load(
"@build_bazel_rules_apple//apple:ios.bzl",
"ios_framework",
)

FRAMEWORK_HEADERS = [
"DYMediaPipePoseTrakingManager.h",
]

FRAMEWORK_NAME = "DYPoseTraking"

ios_framework(
name = FRAMEWORK_NAME,
hdrs = FRAMEWORK_HEADERS,
bundle_id = BUNDLE_ID_PREFIX + FRAMEWORK_NAME,
bundle_name = FRAMEWORK_NAME,
#bundle_id = "com.google.mediapipe.douyu.PoseTrackingGpuFramework",
infoplists = [
"//mediapipe/examples/ios/common:Info.plist",
"Info.plist",
],
families = [
"iphone",
],
#linkopts = ["-force_load"],
minimum_os_version = MIN_IOS_VERSION,
deps = [
":DYMediaPipePoseTrakingManager",
"@ios_opencv//:OpencvFramework",
],
)

objc_library(
name = "DYMediaPipePoseTrakingManager",
srcs = [
"DYMediaPipePoseTrakingManager.mm",
],
hdrs = FRAMEWORK_HEADERS,
copts = ["-std=c++17"],
data = [
"//mediapipe/graphs/pose_tracking:pose_tracking_gpu.binarypb",
"//mediapipe/modules/pose_detection:pose_detection.tflite",
"//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",
],
sdk_frameworks = [
"AVFoundation",
"CoreGraphics",
"CoreMedia",
"UIKit",
],
deps = [
"//mediapipe/objc:mediapipe_framework_ios",
] + select({
"//mediapipe:ios_i386": [],
"//mediapipe:ios_x86_64": [],
"//conditions:default": [
"//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
"//mediapipe/framework/formats:landmark_cc_proto",
],
}),
)'`

If I don't add linkopts = ["-force_load"] to BUILD file, the result framework is only 20M, and program failed at - (BOOL)sendPacket:(const mediapipe::Packet&)packet intoStream:(const std::string&)streamName error:(NSError**)error { absl::Status status = _graph->AddPacketToInputStream(streamName, packet); if (!status.ok() && error) *error = [NSError gus_errorWithStatus:status]; return status.ok(); } and status.message is NULL

if i add force_load, then i failed at bazel compiled , the error is 'wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 323 argument(s) skipped)'
I wonder if this has anything to do with my bazel version

Would you show me your BUILD? and i guess you are Chinese base on your name, it will be much more efficient if we can communicate in Chinese 😊

**Comment by yuxiaohui78** [comment]
@MenThu 
This is my BUILD file and the other related files. You can check to see if it can help you.
[posetracking_framework.zip](https://github.com/google/mediapipe/files/7137911/posetracking_framework.zip)

**Comment by Ankish** [comment]
@noppefoxwolf @yuxiaohui78 : It will be of great help, if you can you please explain the steps in creating the framework, the script and commands to run it from which folder.
I have successfully installed and got the example Pose app running. Need to create the framework to integrate in the app.

**Comment by viratQversity** [comment]
Hi @noppefoxwolf

**Comment by viratQversity** [comment]
Hi @yuxiaohui78 

The code you have posted [Fullbody_pose_tracking_iOS.zip](https://github.com/google/mediapipe/files/6777174/Fullbody_pose_tracking_iOS.zip) is working fine. But when i try to create framework using current mediapipe [version 0.10.9](https://github.com/google/mediapipe/releases/tag/v0.10.9)
and use that framework in your project , then i am not getting any landmarks. Actually 'didOutputLandmarks' and 'didOutputPixelBuffer' are not getting called. 
Here is a [link](https://www.dropbox.com/scl/fo/l3fwdsb2ksm49t6jx335v/h?rlkey=j49sy0t8lzn1zudcgypeiqjao&dl=0) to xcode project files and BUILD file and other related files in case anyone want to take a look at the files.
Bazel version is 6.1.1 , maybe that is the issue ?
