### ISSUE TITLE
Is graph compilation for Android and iOS necessary?

### ISSUE THREAD

**Issue by serrabii** [google/mediapipe#3743]
Hi,

On desktop creating and running graphs is possible through various ways without any compilation of the text configuration.
Meanwhile, on Android and iOS we must first compile the `.pbtxt` file to a `.binarybp` file. Why is this step necessary ?

Thanks in advance.

**Comment by kuaashish** [comment]
Hi @serrabii, 
Lite vs full protobuf library. On mobile platforms, MediaPipe is designed to work with the lite protobuf library and the lite protobuf library supports only binary serialization of protobufs (wire format). The Lite protobuf library has a smaller memory footprint, in part due to omitting the protobuf textual tag names from the lite probuf targets. Thank you!

**Comment by serrabii** [comment]
Thank you for this clarification!
