### ISSUE TITLE
Hello, I want to adjust the distance of the recognition gesture. When I stand at 1.5m, the camera can't recognize my hand. Is there any way to solve this problem

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#377]

**Comment by Sanerly** [comment]
@mgyong I hope to get your help. Thank you

**Comment by mgyong** [comment]
@Sanerly Can you provide images or video examples of how the hand model fails to recognize the hand?

**Comment by Sanerly** [comment]
[Screenrecorder-2020-01-07-18-19-51-343.zip](https://github.com/google/mediapipe/files/4030121/Screenrecorder-2020-01-07-18-19-51-343.zip)
Hello, this is the video I recorded. When my hand was far away, the model did not recognize my hand, and it was only recognized after walking about 1.5 meters. Is there any solution

**Comment by Sanerly** [comment]
Hello, this is the video I recorded. When my hand was far away, the model did not recognize my hand, and it was only recognized after walking about 1.5 meters. Is there any solution
[Screenrecorder-2020-01-07-18-19-51-343.zip](https://github.com/google/mediapipe/files/4033176/Screenrecorder-2020-01-07-18-19-51-343.zip)
@mgyong

**Comment by fanzhanggoogle** [comment]
Hi, we tried on our side and the detector should work better than 1.5 meters in usual cases. Maybe the mix of the lighting/background/hand color makes it perform poorly in your case. But anyway the detector has limitations on detecting small hands, we experimented before with larger model size and more number of anchors but it gives us a lot more false positive without much gain.

**Comment by fanzhanggoogle** [comment]
Feel free to re-open if you have further questions.

**Comment by Sanerly** [comment]
@fanzhanggoogle thank you

**Comment by ShrutheeshIR** [comment]
Hi @fanzhanggoogle 
Are there any parameters that could be potentially tuned to detect smaller hands? (To be more accurate, hands that are far away)
As in the issue here, I want to detect hands which are about 1.2m away, but I'm getting a lot of false positives. I want to reduce the number of false positives. I dont mind if the hand is missed in a few cases, but I wish to minimize false detections to a very low value. 
I've changed the confidence to a higher value, but I was wondering if any other parameters could be tuned.
Thanks!
