### ISSUE TITLE
mediapipe/holistic incorrect z-axis values for body pose landmarks

### ISSUE THREAD

**Issue by vladmandic** [google/mediapipe#3818]
@mediapipe/holistic returns normalized landmarks for body pose, left & right hand and face  
however, scale for z-axis values for body pose landmarks is double that of face or hands thus creating a very distorted image when viewed in 3d (since this scale issue only affects z-axis, it does not impact 2d visualizations)

by normalizing all body pose landmarks z-value by 0.5, pose looks sane

platform: this happens in `javascript` solution, although i have not checked other language ports and its likely same applies there
version: @mediapipe/holistic 0.5.1635989137
browser: chrome 107 on windows 11

**Comment by kuaashish** [comment]
Hello @vladmandic,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by vladmandic** [comment]
Is the issue addressed in the new solution?
It should not be up to user to upgrade and check.

**Comment by kuaashish** [comment]
@vladmandic,
Our new solutions are superset of the legacy solutions and major improvements have been done. However, For now we do not have specific documentation about the changes. Please check with upgraded solution and feel free to raise a new issue if you see the similar behaviour. Thank you

**Comment by kuaashish** [comment]
@vladmandic,

This is a legacy solution And We will be not able to fix this issue.

**Comment by ueihgnurt** [comment]
I might be wrong. in my case. Here is the annotation.

![Annotation 2024-10-03 173540](https://github.com/user-attachments/assets/97e274bd-2fa1-4e1f-bb5f-683d680be96a)
this is the result.
![Figure_1](https://github.com/user-attachments/assets/68895b2a-3103-446b-9f6e-215e7727386a)
this is after I processed data. with this theory:
![image](https://github.com/user-attachments/assets/7962265f-6671-4cfd-a022-c4be87bd2357)

![Figure_2](https://github.com/user-attachments/assets/cb8d1e9f-f155-4005-a605-38626d879204)

So I come to conclusion that because of the Camera Coordinates to NDC is wrong causing this problem.
The further object from the HIPS the more error z-index become.
