### ISSUE TITLE
How to directly obtain the original data in Iris Depth?

### ISSUE THREAD

**Issue by xxxneo000** [google/mediapipe#3880]
We need to build a project on the iPhone to enlarge and reduce the text displayed on the screen by using real-time iris depth data.

At present, Iris Depth DEMO has been successfully run on iOS, but the iris depth data is encapsulated in the rendering layer, and we cannot obtain it.

How can we get Left_iris_depth_mm/Right_iris_depth_mm values in real time in iOS projects?

**Comment by xxxneo000** [comment]
who can answer me?

**Comment by ayushgdev** [comment]
Hi @xxxneo000

`left_iris_depth_mm` and `right_iris_depth_mm` are values encapculated within mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt. To use access this stream outside, declare it as an output stream of graph, outside of all calculators. Like this:


```
type: "IrisAndDepthRendererGpu"
input_stream: "IMAGE:input_image"
...
output_stream: "IMAGE:output_image"
+ output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
+ output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"

````
Then in mediapipe/graphs/iris_tracking/iris_tracking_gpu.pbtxt, since it is importing IrisAndDepthRendererGpu as its calculator, declare same output streams as this calculator's output as well.

```
# Renders annotations and overlays them on top of the input images.
node {
  calculator: "IrisAndDepthRendererGpu"
  ...
  + output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
  + output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
}
```
Now the two streams can be accessed using CalculatorGraph::ObserveOutputStream. In order to use CalculatorGraph::ObserveOutputStream, the stream "Left_iris_depth_mm" must be a stream in the "top level graph" used to initialize the CalculatorGraph.
In the C++ API:, a sample snippet is below:
```
CalculatorGraph::ObserveOutputStream("Left_iris_depth_mm", 
      [](Packet p) { println(p.Get<double>());  myVar = p.Get<double>());});
```
In general, if a stream, such as "Left_iris_depth_mm", is inside a subgraph, then it needs to be declared as 
(1) an output stream of the subgraph, and 
(2) then listed as an output stream of the subgraph node for the subgraph in the containing graph.

**Comment by looninho** [comment]
> 
Hi @ayushgdev,
Could you give an example of using ObserveOutputStream:
here is my code and the returned error:
`double left, right;`
`m_graph.ObserveOutputStream("right_iris_depth_mm", [](mediapipe::Packet packet) {right = packet.Get<double>();});`

build error:
`no known conversion for argument 2 from 'mediapipe::ExampleImpl::Process(uint8_t*, int, int)::<lambda(mediapipe::Packet)>' to 'std::function<absl::lts_20230125::Status(const mediapipe::Packet&)>'`

Thanks,
