### ISSUE TITLE
How to reduce jittering in mediapipe face mesh ?

### ISSUE THREAD

**Issue by AyishwaryaM** [google/mediapipe#3926]
I am facing jittering issue in mediapipe face mesh.
Is anyone know solution for this?

**Comment by ayushgdev** [comment]
Hi @AyishwaryaM 
Can you please provide more details on the OS, the platform, the reproduction steps of the issue, etc. as per the applicable template [here](https://github.com/google/mediapipe/issues/new/choose)?

**Comment by AyishwaryaM** [comment]
Hi @ayushgdev , below are the my specifications of mediapipe , open3d and cv2
mediapipe - 0.8.11
open3d - 0.15.1
cv2 - 4.6.0
OS - windows 11

**Comment by ayushgdev** [comment]
Hi @AyishwaryaM 
Thanks for providing the details. The video was helpful to sense the issue. Unfortunately, this issue is known to us and being reported by other developers as well (such as #3495 ). However, since MediaPipe is focused on realtime detection and tracking, the image frames are processed by the calculator nodes fast and can cause variation in predicting landmark coordinates _within_ a tolerance level. 
That being said, we do realise this is an important area for improvement and we are working on enhancement at this front.
