### ISSUE TITLE
How to reduce the number of recognition points?

### ISSUE THREAD

**Issue by 459zyt** [google/mediapipe#3929]
How to reduce the number of recognition points? When I identify body nodes, I only want to get the elbow coordinates, not the leg nodes.Whether the number of frames can be increased by reducing the number of identification points

**Comment by ayushgdev** [comment]
Hi @459zyt 
Can you please provide details on the solution you are using, the technology/platform you are working on, mediapipe version, and any other detail you might feel relevant to your query?

**Comment by 459zyt** [comment]
I use  **mp_pose.Pose**，But I don't need to detect all the points in my body. How can I reduce the number of detection points

**Comment by ayushgdev** [comment]
Hi @459zyt Can you please use this template to provide the relevant information?

**Comment by ayushgdev** [comment]
Hello @459zyt 
The _recognition points_ cannot be reduced since they are coming from the model. However, what can be controlled instead is the _rendered landmarks_ . To do that, you can refer to the file [mediapipe/graphs/pose_tracking/subgraphs/pose_landmarks_to_render_data.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/subgraphs/pose_landmarks_to_render_data.pbtxt) and edit the landmark connections in `LandmarksToRenderDataCalculator`. Also refer to the file [mediapipe/calculators/util/landmarks_to_render_data_calculator.proto](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_render_data_calculator.proto) to understand the connections syntax. 

With the minimal information, we don't know the language you are using. However, it looks from the `mp_pose.Pose` that you are using Python. So after editing, you will need to build the MediaPipe Python package as instructed [here](https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package)
