### ISSUE TITLE
In Android face mesh solution , can I  change the fps of cameraInput ,    means that  the times of  cameraInput.setNewFrameListener called per second?

### ISSUE THREAD

**Issue by ngreedy** [google/mediapipe#3939]
just like     cam.set(cv2.CAP_PROP_FPS, 30)

**Comment by kuaashish** [comment]
Hi @ngreedy,
Would you let us know the support you are looking, steps followed to build the above scenario to address the issue better from our end.

**Comment by ngreedy** [comment]
> Hi @ngreedy, Would you let us know the support you are looking, steps followed to build the above scenario to address the issue better from our end.

in fact everything is working fine ,  but it cost too much and bad for my app's performance,   so I wonder if I can set the frequency of  face-detect , just for  lower cost

wish u can get what i mean...

**Comment by ngreedy** [comment]
![shot](https://user-images.githubusercontent.com/16276531/209037472-ceafde7e-4b8e-4d50-800c-5d772a832cef.jpg)

**Comment by kuaashish** [comment]
Hi @ngreedy,
Since the android solution of facemesh does not have the same parameter as python to adjust the fps rate. However, MediaPipe graphs will queue/drop frames when the input is faster than the system can handle if you have more powerful the device (or more simple the graph), the less frames dropped/queued, the higher fps can be achieved.

**Comment by ngreedy** [comment]
ok  I got it  ，3q
