### ISSUE TITLE
How to make models deterministic

### ISSUE THREAD

**Issue by adrianloy** [google/mediapipe#3945]
I am using the mediapipe Pose solution model, but the output seems to be non-deterministic. If I run inference on the same video multiple times, I do not get the same landmarks every time. What is the reason for this? How can I make the pipeline 100% deterministic?

**Comment by ayushgdev** [comment]
@adrianloy Before we can provide a conclusive remark, can you please let us know the following details:
1. The technology you are using (Python, JS, Android, etc)
2. The OS, it's version and it's architecture being used
3. Whether you are running CPU vs GPU based inference
4. Whether you are running the same video within the same program/application or across two different apps?

Also it will be great if you can provide a sample of landmarks that you get for different runs so that we can check the difference.

**Comment by adrianloy** [comment]
Thanks for the reply. I use Python on Linux, Ubuntu 22.04. I see this behaviour both on my local machine aswell as in a deployment on kubernetes within a docker container that is also based upon Ubuntu 22.04. I use CPU Inference. Same video running multiple times sequentially against the API serving the model does not seem to be deterministic, so one app getting the same video twice with nothing changed in between.

I can unfortunately not share the data that I use. Do I understand correctly from your reply, that the BlazeModel in general is expected to behave deterministically?

**Comment by ayushgdev** [comment]
Yes @adrianloy. The models should be giving deterministic outputs unless there is some change in the OS, CPU vs GPU inference, x64 vs x86 architecture, etc. across successive runs. 
We needed the outputs to check if the difference is very small or significant. Nevertheless, please allow us some time to revert back for any plausible explanation for different outputs.

**Comment by ziyadsheeba** [comment]
Are there any updates on this problem? @ayushgdev

**Comment by ayushgdev** [comment]
Hello @ziyadsheeba 
We don't have any update yet. Will update proactively once we know the plausible reason for the issue

**Comment by ziyadsheeba** [comment]
@ayushgdev Thanks for your prompt reply. Please let us know if any further information is required, since currently we are blocked by this issue for productionizing the model.

**Comment by ziyadsheeba** [comment]
We tried disabling the smoothing from the pose estimator and the results were still nondeterministic. Upon further investigations, we discovered that choosing "static_image_mode", the pose estimation results are deterministic.  It seems like in the computational graph of the solution, timestamp-dependant operations are performed on the key-points. We are suspecting the issue to be related to the following two nodes:
`# When the optional input side packet "use_prev_landmarks" is either absent or
# set to true, uses the landmarks on the previous image to help localize
# landmarks on the current image.
node {
  calculator: "GateCalculator"
  input_side_packet: "ALLOW:use_prev_landmarks"
  input_stream: "prev_pose_rect_from_landmarks"
  output_stream: "gated_prev_pose_rect_from_landmarks"
  options: {
    [mediapipe.GateCalculatorOptions.ext] {
      allow: true
    }
  }
}

# Caches pose rects calculated from landmarks, and upon the arrival of the next
# input image, sends out the cached rects with timestamps replaced by that of
# the input image, essentially generating a packet that carries the previous
# pose rects. Note that upon the arrival of the very first input image, a
# timestamp bound update occurs to jump start the feedback loop.
node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:image"
  input_stream: "LOOP:pose_rect_from_landmarks"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:prev_pose_rect_from_landmarks"
}`
@ayushgdev Could you please assign a googler to this issue?

**Comment by ayushgdev** [comment]
Hello @ziyadsheeba 
Thanks for the analysis. Since with static_image_mode being set to true makes the models deterministic, it indicates that the   video being sent into the graph is not having consistent video frames to process and hence the model output varies. 
This can happen if the video being processed is dropping a few frames, due to which subsequent frames are not able to use the previous detected landmarks to localise the pose. 

The GateCalculator will allow/disallow the prev pose landmarks depending upon the **use_prev_landmarks** input_side_packet. But this side packet will be constant once your solution is built. So probably this will not affect the outputs with subsequent runs.
You might want to look at FlowLimiterCalculator since the as per the [doc-string](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt#L25), 

> "All images that come in while waiting are dropped, limiting the number of in-flight images in most part of the graph to 1."

The `max_in_flight` arg is specified in the flow_limiter_calculator protobuf file [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/flow_limiter_calculator.proto#L31). Try to vary this along with the `max_in_queue` option to adjust the throughput-speed balance.

**Comment by adrianloy** [comment]
> Since with static_image_mode being set to true makes the models deterministic, it indicates that the video being sent into the graph is not having consistent video frames to process and hence the model output varies. This can happen if the video being processed is dropping a few frames, due to which subsequent frames are not able to use the previous detected landmarks to localise the pose.

I dont fully understand this part. I just iterate through a list of numpy arrays, and send the arrays to `pose_model.process` like this:

```
for image in data.frames:
    image.flags.writeable = False
    res = self.pose_model.process(image)
```

We checked that the array contains exactly the same arrays, yet `pose_model.process` is not deterministic with the static mode disabled. We do not drop any frames and the video fframes are consistent.
