### ISSUE TITLE
How change graph vertical_fov_degrees value with input_side_packet or other way

### ISSUE THREAD

**Issue by onuralpszr** [google/mediapipe#3953]
Hello, I was working FaceEffect and I wanted to change  vertical_fov_degrees value when I run on android, I already able to load graph and send input side packets. I already have an environment to test this. But problem is when change value "36" to variable value, it is literally giving me Type Error (asking for float value) and gives error when I compile the graph. 
I was looking into calculator part to modify this to make so I can send side packet but maybe there is a easier way to do it.

Any help would be great. 

```
# Generates an environment that describes the current virtual scene.
node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 36.0
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}
```

**Comment by ayushgdev** [comment]
@onuralpszr Can you please provide the steps to reproduce the error at our end?

**Comment by onuralpszr** [comment]
@ayushgdev  technically we can simplify this, for example I want to change use facemesh solution 

https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/facemesh/BUILD

And in that solution I want to modify related graph which is here 

https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_front_gpu_image.pbtxt#L51

` max_in_flight: 1`

In here we have max_in_flight value equal to 1 and that is constant value is there way to use something like this 

Let's say I added new variable 

`"output_stream: "max_in_flight_value"
`
and modify max_in_flight like this

` max_in_flight: "max_in_flight_value"`

If I do this change bazel error will literally say "I used string value instead of integer" and I have to revert this in order to make it work. I want to change that "constant" value and control via "variable" that is what I asking, mediapipe already have the code I am using it. so re-sharing all is kinda waste. I hope that will help.

**Comment by ayushgdev** [comment]
@onuralpszr Thanks for explaining the query.

You can take an example from the existing graph files for this case. 
Let's say we create face mesh from a video file rather than live desktop example in docs. To do that, we need the graph file of `face_mesh_desktop.pbtxt`, since it has two more arguments - `input_video_path` and `output_video_path`. Since these are constants for processing, these are provided as `input_side_packet` (refer theory [here](https://google.github.io/mediapipe/framework_concepts/framework_concepts.html#side-packets)). 

This `input_video_path` and `output_video_path` ARE infact the variables holding the values for video paths and these variables are used to give input to `OpenCvVideoDecoderCalculator` graph node as `INPUT_FILE_PATH` tag (refer the `face_mesh_desktop.pbtxt` file's first node). Now the question to _how_ to give the `input_video_path` to the face_mesh_desktop.pbtxt graph, it is given using `--input_side_packets` flag in the run command. Like in Autoflip example [here](https://google.github.io/mediapipe/solutions/autoflip.html#running).


In a similar fashion, you can alter any graph to include the variables. Please keep in mind that the node you want to pass the variable to can be a subgraph as well. For example, `FaceLandmarkFrontCpu` node is itself a subgraph located in mediapipe/modules/face_landmark/face_landmark_front_cpu.pbtxt. You will need to alter the subgraph as well to include any _new_ side packets and pass it to a calculator within this subgraph _as long as the calculator can accept such an argument_. 

In essence, you can give a variable value using the command line args while running the application, using input_side_packets
