### ISSUE TITLE
Generation of mediapipe as a whole framework for iOS

### ISSUE THREAD

**Issue by a-karthi** [google/mediapipe#3954]
I need to know how to generate media pipe as a singe framework for iOS
So that i can able to easily access by  importing mediapipe in my own xcode project

import Mediapipe

I working above topic for the past two days

you have any solution for above, or tell me if it is not possible

It is tough to customize or modify your framework depends on my use case

Or else tell me how to change lip color via your framework in iOS

Any answers, Thanks in advance!

**Comment by lxm1799** [comment]
maybe u should watch this: https://github.com/swittk/MediapipeFaceMeshIOSLibrary

**Comment by ayushgdev** [comment]
@a-karthi  The MediaPipe is segregated into several solutions so that the apps can be lightweight and only the solutions required for particular use-case can be included in the apps. The team is working on several aspects of MediaPipe, including improvement in the model performance and streamlining the MediaPipe solutions across the platforms. So it is not possible to merge all solutions and provide a ready to use library for iOS/Android at the moment.

Meanwhile, for the lip color change, you can explore the [FaceEffect](https://google.github.io/mediapipe/solutions/face_mesh.html#face-effect-example) and try building on the top of the example. FaceEffect is available on iOS and Android.

**Comment by a-karthi** [comment]
for lip colour change, what is the updates i want to be done in the calculator or which file i need to be modify ?
in default solution they render some sun glass and mask
Any reference or guidance how to do lip color change technically using ur face effect ?

**Comment by kuaashish** [comment]
@a-karthi,
We will shortly release MP Tasks to CocoaPods. You can then use our pre-built binaries. Thank you!!
