### ISSUE TITLE
About Youtube8M feature extractor. I tried on the Video that posted by Youtube8M challenge but it's different?

### ISSUE THREAD

**Issue by yw2278** [google/mediapipe#396]

**Comment by yw2278** [comment]
for video id fg6m. the feature I get from the feature extractor are flaots like 0.40838873, -0.66608351, -0.52097726, -0.60093373, -0.3703512, but the correspoding feature from the Chanllenge are 155.,  86., 106.,  82.,  97. so did I miss any data transformation?

**Comment by jiuqiant** [comment]
It's due to the quantization. Each float value in the YT8M dataset is quantized to a byte in the [0, 255] range. But, what you get from the feature extractor is the original float values.

You can find the simple quantization/dequantization algorithm in [QuantizeFloatVectorCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/quantize_float_vector_calculator.cc) and [DequantizeByteArrayCalculator ](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/dequantize_byte_array_calculator.cc). For example, we get the float value 0.408 from the feature extractor and the original value range is from -2 to 2. Then,  we apply (value - min_quantized_value) * (255.0 / range)) to get the quantized value, we will get 155 by (0.408 - (-2))*(255/4).

**Comment by yw2278** [comment]
Hi, sorry I have to ask, why for some value, after quantize the differences are so big? for example, -0.60093373 quantized to 89, but corresponding value is 82?
