### ISSUE TITLE
AttributeError: type object 'SolutionOutputs' has no attribute 'hand_rect'

### ISSUE THREAD

**Issue by yasminhannahza** [google/mediapipe#3962]
Hello, I'm trying to deploy my webcam for hand recognition through Flask.

When I'm running my server.py, my Flask web will come through but there is no webcam appeared because it said that:
AttributeError: type object 'SolutionOutputs' has no attribute 'hand_rect'.

Here's my code for it: 

                if results.hand_rects:
                for rect in results.hand_rects:
                ## Bouding box:
                    x_cen = rect.x_center*h
                    y_cen = rect.y_center*w
                    scale_w = rect.width * h
                    scale_h = rect.height * w
                
                    cv2.rectangle(image, (int(x_cen - scale_w/2),int( y_cen - scale_h/2)),(int(x_cen + scale_w/2), int(y_cen + scale_h/2)), (0, 255, 0), 2)
                    
                    img = image[int(y_cen - scale_w/2): int(y_cen + scale_w/2), int(x_cen - scale_h/2): int( x_cen + scale_h/2)]
                    if(np.array(img).size != 0):
                        cv2.imwrite('crop.jpg', img)
                        img = cv2.resize(img,(224,224))
                        img = img/255
                        img = tf.expand_dims(img, axis=0)
                        t = to_label(model.predict(img))[0]
                        print(t)
                cv2.rectangle(image, (0,0), (h,40), (255,0,0),-1)
                cv2.putText(image, t, (int(h/2-4),30), fontFace=cv2.FONT_HERSHEY_SIMPLEX , fontScale=1, color=(255,255,255),lineType=cv2.LINE_AA)

                cv2.imwrite('demo.jpg', image)
                yield (b'--image\r\n'
                    b'Content-Type: image/jpeg\r\n\r\n' + open('demo.jpg', 'rb').read() + b'\r\n')`

**Comment by ayushgdev** [comment]
Hello @yasminhannahza 
1. Which solution are you using?
2. Which documentation are you referring for Python API? Can you point out the documentation with `hand_rects`?

**Comment by MrGranddy** [comment]
Having the same issue with face mesh, I amn using the exact same code given here: https://google.github.io/mediapipe/solutions/face_mesh.html for the webcam. I am also trying other things but it seems to behave the same. face_mesh.process(image) returns <class 'mediapipe.python.solution_base.SolutionOutputs'> which is a Type object.

**Comment by ayushgdev** [comment]
@MrGranddy 
What is the error or issue you are facing? We are able to run the sample code without any issue.

**Comment by MrGranddy** [comment]
@ayushgdev 
I found out what the issue is, sorry for not making an update here. The problem was mediapipe was not able to detect anything on frame so it returned <class 'mediapipe.python.solution_base.SolutionOutputs'>, yet I still do not think this kind of behaviour is very intuitive, you see if there was an indication that Mediapipe is not able to detect faces I would act on it but with the current behaviour it returns <class 'mediapipe.python.solution_base.SolutionOutputs'> which makes you think there is a bug with the framework, even a simple "None" return would be more intuitive. 

Further I don't know if this is expected behaviour for face mesh module but, when I fed a 1920x1080 frame with single person and maybe about 150x150 face, the framework did not detect any faces, which yield the respective problem. But when I crop the video without any resizing it worked perfectly, so from a CNN side of view I don't understand how this behaviour makes sense, maybe something to look at.

Anyway thanks for the great framework, it works suprisingly accurate and fast.

**Comment by RyanPaulMcKenna** [comment]
> @MrGranddy What is the error or issue you are facing? We are able to run the sample code without any issue.

Which version of mediapipe are you using?

**Comment by MrGranddy** [comment]
> > @MrGranddy What is the error or issue you are facing? We are able to run the sample code without any issue.
> 
> Which version of mediapipe are you using?

Hello, I engineered away the problem long time ago, if a related issue comes up, please inform me so I can try and replicate the same problem again, but I am not sure if it still, it maybe has been a year.
