### ISSUE TITLE
I use mediapipe holistic,I need using medepipe to extract the lines of human bones of video ,including hand ,face,arm.In order to train a classifier for sign language recognition

### ISSUE THREAD

**Issue by stonecropa** [google/mediapipe#3989]
<em>now ,I find a image and the code,but what I do is video.I need help,thankyou.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):no 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): windows10 
- MediaPipe Tasks SDK version:
- Task name (e.g. Object detection, Gesture recognition etc.):sign language recognition
- Programming Language and version ( e.g. C++, Python, Java): python

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab, GitHub repo link or anything that we can use to reproduce the problem: the image and code is this.I don't know how to change it to the skeleton output of the video, only the skeleton including  face,hand and arm .
# Run MediaPipe Holistic and plot 3d pose world landmarks.
with  mp_holistic.Holistic(static_image_mode=True) as holistic:
  for name, image in images.items():
    results = holistic.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Print the real-world 3D coordinates of nose in meters with the origin at
    # the center between hips.
    print('Nose world landmark:'),
    print(results.pose_world_landmarks.landmark[mp_holistic.PoseLandmark.NOSE])
    
    # Plot pose world landmarks.
    print(f'Pose world landmarks of {name}:')
    mp_drawing.plot_landmarks(
        results.pose_world_landmarks, mp_holistic.POSE_CONNECTIONS)
![image](https://user-images.githubusercontent.com/114655828/211959202-a119f68f-ae59-46f4-80ff-624409c04dcb.png)

**Comment by ayushgdev** [comment]
Hello @stonecropa 
Please refer to [this file](https://github.com/ayushgdev/MediaPipeCodeSamples/blob/main/samples.ipynb) for example on running holistic solution in python using video file. `static_image_mode` is the parameter which helps differentiate between temporally dependent (like in a video) and independent frames (like in separate image files) in a sequence.
**Note**: The `plot_landmarks()` in drawing_utils package does not return anything; rather calls `plt.show()` within the function. Hence, if you would like to create a _video_ sequence of the plotted 3D graphs for each frame, you will need to write custom `plot_landmarks()`. You can probably copy the whole function from [here](https://github.com/google/mediapipe/blob/9cbb76939dd069eacecae103c5c27b6e07c7e9c7/mediapipe/python/solutions/drawing_utils.py#L254) and then edit the last part, i.e. after you are ready with the axes plot3D. 

1. Store the plot as a numpy array so that it can be writable to a file on disk.
2. Use VideoWriter class to instatiate a new video object, as in the example gist.
3. Write the numpy array to the VideoWriter object
4. **IMP:** release the VideoWriter object

**Comment by stonecropa** [comment]
Hello@ayushgdev 
First of all, thank you for your answer.What you said is very good, but I don't understand how to revise this code.Could you tell how to Specific modifications ?I use mediapipe holistic then the final generated video includes the original video and additional lines. Can you tell me how to extract only the lines. I just want a video of line.My expression may not be clear. If you don't understand, please tell me.I look forward to your reply. Thank you.

**Comment by ayushgdev** [comment]
Hello @stonecropa 

I have modified the code to create a video with only detected pose lines. Please check it out.
One sample frame of the video output is attached here.
<img width="1392" alt="Screenshot 2023-01-16 at 12 37 21 PM" src="https://user-images.githubusercontent.com/118424249/212618032-5ff65914-a99b-47b3-b3da-00120790255c.png">

**Comment by stonecropa** [comment]
@ayushgdev 
Thanks for your help. I'm very grateful.Please check my code.Hands in holistic.
I have four videos in total, but one of them has no hands in a few seconds.Everything else is normal.




if results.left_hand_landmarks:
            mp_drawing.draw_landmarks(
                annotated_frame,
                results.left_hand_landmarks,
                mp_holistic.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())
        if results.right_hand_landmarks:
            mp_drawing.draw_landmarks(
                annotated_frame,
                results.right_hand_landmarks,
                mp_holistic.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())
![image](https://user-images.githubusercontent.com/114655828/213152004-01e0992a-cb48-49b6-ab83-08d8b9e971f7.png)
![image](https://user-images.githubusercontent.com/114655828/213152199-f06b40af-cde4-4993-8fbd-c9ffcb39f250.png)

**Comment by ayushgdev** [comment]
Hello @stonecropa 
Always happy to help. However, this issue seems to be related to model predictions. To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one? 
This helps community and us to search the issues better in concise manner.

**Comment by stonecropa** [comment]
@ayushgdev 
Thank you. I will open a new question now.
