### ISSUE TITLE
Using the video last generated by mediapipe holistic, how to extract the video with only lines instead of the original person?（The language is Python and the system is win10.）

### ISSUE THREAD

**Issue by zjkafasf** [google/mediapipe#3997]
import os
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_holistic = mp.solutions.holistic

path = 'E:/test'
file_list = os.listdir(path)
for file_name in file_list:
    print(file_name)
    cap = cv2.VideoCapture(path + '/' + file_name)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) 
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    file_name_prefix, file_extension = file_name.split('.')
    out = cv2.VideoWriter('E:/test1/' + file_name_prefix + '.mp4' , fourcc, 20, (width, height))
    with mp_holistic.Holistic(
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as holistic:
      
      while cap.isOpened():
        success, image = cap.read()
        if not success:
          print("Ignoring empty camera frame.")
        # If loading a video, use 'break' instead of 'continue'.
          break

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = holistic.process(image)

        # Draw landmark annotation on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        mp_drawing.draw_landmarks(
        image,
        results.face_landmarks,
        mp_holistic.FACEMESH_CONTOURS,
        landmark_drawing_spec=None,
        connection_drawing_spec=mp_drawing_styles
        .get_default_face_mesh_contours_style())
        mp_drawing.draw_landmarks(
        image,
        results.left_hand_landmarks,
        mp_holistic.HAND_CONNECTIONS,
        mp_drawing_styles.get_default_hand_landmarks_style(),
        mp_drawing_styles.get_default_hand_connections_style())
        mp_drawing.draw_landmarks(
        image,
        results.right_hand_landmarks,
        mp_holistic.HAND_CONNECTIONS,
        mp_drawing_styles.get_default_hand_landmarks_style(),
        mp_drawing_styles.get_default_hand_connections_style())
        mp_drawing.draw_landmarks(
        image,
        results.pose_landmarks,
        mp_holistic.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles
        .get_default_pose_landmarks_style())
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Holistic', image)
        out.write(image)
        if cv2.waitKey(5) & 0xFF == 27:
          break
    cap.release()

**Comment by ayushgdev** [comment]
Hello @zjkafasf 
Using the last video generated by MediaPipe to extract the lines would not be possible since the original frames and the output detections are already merged.
Instead, you need to process the original video with MP Holistic  and while processing phase only for each frame, write the output into a new video file.

Please refer to [this file](https://github.com/ayushgdev/MediaPipeCodeSamples/blob/main/samples.ipynb) for example on running holistic solution in python using video file. Also, I see when you are creating the MP Holistic object, 
```
with mp_holistic.Holistic(
min_detection_confidence=0.5,
min_tracking_confidence=0.5) as holistic:
```
`static_image_mode: false` should be set for video input. `static_image_mode` is the parameter which helps differentiate between temporally dependent (like in a video) and independent frames (like in separate image files) in a sequence.
