### ISSUE TITLE
Future of Mediapipe in iOS, OpenGL deprecated. 

### ISSUE THREAD

**Issue by afsaredrisy** [google/mediapipe#400]
Hey I am bit confuse to use Mediapipe in our product. As we  know that apple has already deprecated OpenGL and OpenCL & will be completely remove in upcoming iOS OS,   but mediapipe is using OpenGL & OpenCL then what will be the future of Mediapipe in term of iOS applications.  Is there any plan to update Mediapipe from OpenGL to Metal for iSO applications? 
Should we use mediapipe for iOS product or not.

**Comment by fenollp** [comment]
From the code I'd say Mediapipe uses Metal on iOS, not OpenGL.

I'd like to piggyback on this question to ask whether Mediapipe has on the roadmap support for [Apple Neural Engine](https://en.wikipedia.org/wiki/Apple_A11#Neural_Engine) a.k.a the dedicated iPhone chip that can do inference faster than Metal GPUs, or is it a Tensorflow question?

**Comment by afsaredrisy** [comment]
Hi @fenollp I am still seeing OpenGL in iOS mediapipe but could not find metal code any where,  neither in framework nor in calculators. This  [MPPGLViewRendere](https://github.com/google/mediapipe/blob/master/mediapipe/objc/MPPGLViewRenderer.mm)  which is being used to render camera pixelBuffer to OpenGL texture & this openGL texture is input stream to mediapipe graph. I did not see metal texture anywhere, am I finding something wrong ?

**Comment by fenollp** [comment]
Maybe OpenGL is only used for rendering then?
Metal is used for inference: https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/calculators/tflite/tflite_inference_calculator.cc#L186

**Comment by mcclanahoochie** [comment]
@afsaredrisy you can find metal performance shader code in these calculators: 
[converter](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/calculators/tflite/tflite_converter_calculator.cc) , [inference](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/calculators/tflite/tflite_inference_calculator.cc) , [tensors_to_detections](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc) , 
and for more metal support, see [here ](https://github.com/google/mediapipe/search?q=metal.h&unscoped_q=metal.h) , and more is to come. 

OpenGL is used for some basic rendering and image manipulation, because at the time of MediaPipe creation (years ago internally), this was an easy way to be cross platform.  Removing OpenGL entirely, is up to Apple, and we will adapt when necessary. 

@fenollp thanks for the pointer, but this would be a tensorflow question (the guts of the tflite calculator).

**Comment by afsaredrisy** [comment]
Hey Thanks @mcclanahoochie  and @fenollp
