### ISSUE TITLE
There is no 0.9.0.1 tag in the repository

### ISSUE THREAD

**Issue by yurivict** [google/mediapipe#4002]
PYPI [has](https://pypi.org/project/mediapipe/) this version.

**Comment by schmidt-sebastian** [comment]
I will try to fix this shortly.

**Comment by schmidt-sebastian** [comment]
@ayushgdev is working a the next release.

**Comment by ayushgdev** [comment]
@yurivict Unfortunately, releasing the unsynced version (0.9.0.1) in GitHub repository would not be possible now as there have been lots of changes since then and it is intractable to consolidate them back in time. 
Instead, a new version, v0.9.1, has been released. Now the PyPi repository and the GitHub repository are in sync. 
Can you please check and close the issue if it is resolved for you?

**Comment by yurivict** [comment]
Thank you.
