### ISSUE TITLE
Rotate camera picture in 'hands' of 'mediapipe-solutions-examples'

### ISSUE THREAD

**Issue by drink2** [google/mediapipe#4006]
**System information** 
- I use this example code: https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands
- I changed a line in the AndroidManifest.xml to `<activity android:name=".MainActivity" android:screenOrientation="landscape">`
- I added `setRequestedOrientation (ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);` in `@Override protected void onCreate(Bundle savedInstanceState) {} ` inside MainActivity.java
- In MainActivity.java I changed in `private void startCamera(){}` to `CameraInput.CameraFacing.FRONT`

- Developer Machine: Ubuntu 22.04.1 LTS, 
- Target: Android Tablet (Android 12), Samsung Tab A7  same issue is reproducible on Google Pixel 6 (Android 13)

**Describe the expected behavior:**
As expected, the app uses the front camera and launches in landcape mode. All buttons and text are displayed in landscape, but the **camera stream** with the landmark overlay is **incorrectly rotated by 90 degrees CW.** When using the static picture mode, the picture is displayed with correct orientation.

Related issue: https://github.com/google/mediapipe/issues/3877

Thank you for your help,
drink2

**Comment by ayushgdev** [comment]
Hello @drink2 
We see you have already tried a few possible fixes. Please allow us sometime to replicate the issue at our end and provide solution to you.

**Comment by ayushgdev** [comment]
Hello @drink2 
Thanks for raising this issue. Unfortunately, this is not possible since you are using the example of maven prebuilt binaries available for hand-tracking. The CameraInput internally uses CameraXPreviewHelper, but the code is prebuilt. So, it is advised to [build Android AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) for hand tracking manually which will allow for more customisation. 
**Tip:** The `startCamera()` in `CameraXPreviewHelper` can be used to give rotated image height and width into the `targetSize` argument.
Further, we would mark this as a feature request to evolve our maven APIs.

**Comment by drink2** [comment]
Hi @ayushgdev,
thank you for the explanation. That is information enough for me to close this issue.

**Comment by vietnt-uet** [comment]
I'm facing the same problem and there is a comment here could be useful for everyone:
https://github.com/google/mediapipe/issues/568#issuecomment-975439977
