### ISSUE TITLE
build successfully but it doesn't print # Hello World

### ISSUE THREAD

**Issue by Hyun-Jegal** [google/mediapipe#4015]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS 13.1

$ export GLOG_logtostderr=1
$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world

…
…

INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/mediapipe/examples/desktop/hello_world/helINFO: Build completed successfully, 1 total action
dyld[3859]: symbol not found in flat namespace '__ZN6google8protobuf8internal14ArenaStringPtr3SetEONSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_5ArenaE'
zsh: abort      bazel run --define MEDIAPIPE_DISABLE_GPU=1

**Comment by kuaashish** [comment]
Hi @Hyun-Jegal,
As from the description I see that build has completed successfully but as mentioned [here ](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos) it does not printing the Hello World! right?

**Comment by kuaashish** [comment]
@Hyun-Jegal,
Thanks for reporting out this bug! We are forwarding this internally and will let us know if there will be any specific update about the bug.

**Comment by kuaashish** [comment]
@Hyun-Jegal,
This issue has been fixed in the latest release of the mediapipe version [v0.9.1](https://github.com/google/mediapipe/tree/v0.9.1). I could successfully reproduce the issue in `Xcode 14.2`, `macOS Ventura 13.2` with no errors. Please try with this latest release and feel free to close this as issue has been resolved. Thank you!
<img width="1728" alt="3415" src="https://user-images.githubusercontent.com/98159216/218062623-2215f78c-eb8b-489c-be02-41d5fef2a717.png">
