### ISSUE TITLE
Why is M1 performance so different on iOS and Mac OS X?

### ISSUE THREAD

**Issue by juanmaxon** [google/mediapipe#4022]
My javascript app runs at 18 fps on a M1 mac mini, but goes at 2 or 3 fps on an Ipad Air with the same M1. Is it the difference between Mac OS X and iOS? Thanks

**Comment by ayushgdev** [comment]
Hello @juanmaxon 
- Would you please let us know which MediaPipe solution you are using?
- Which browser and version are you testing the solution on?
- Are you using the default example or custom code?

**Comment by juanmaxon** [comment]
Hello,

* Holistic
* Latest versions in Mac OS X and iOS. Safari 16.2 and Chrome 109.0.5414.119
* Yes, for example, demo Holistic.  

Thanks

**Comment by ayushgdev** [comment]
Hello @juanmaxon 
Apple has an experimental setting "GPU Process: WebGL" which is enabled by default (as of iOS 16). We believe it tries to kick WebGL calls to a separate GPU process rather than rendering them in the usual one. This currently completely hoses our iOS web performance.
Would you please try going to Settings --> Safari --> Advanced --> Experimental Features, and disabling GPU Process: WebGL, then trying the MediaPipe solution?

**Comment by juanmaxon** [comment]
> Hello @juanmaxon
> Apple has an experimental setting "GPU Process: WebGL" which is enabled by default (as of iOS 16). We believe it tries to kick WebGL calls to a separate GPU process rather than rendering them in the usual one. This currently completely hoses our iOS web performance.
> Would you please try going to Settings --> Safari --> Advanced --> Experimental Features, and disabling GPU Process: WebGL, then trying the MediaPipe solution?

I've done that and I'm still getting very low fps. Ipad air with M1 goes at 4 fps while macbook air or mini or imac with m1 goes at 15 fps. I don't understand.
Thanks
