### ISSUE TITLE
about CameraXPreview

### ISSUE THREAD

**Issue by MakeMeCookie** [google/mediapipe#4039]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):  android 11, ubuntu 22.04
- Bazel version: 5.1
- Solution (e.g. FaceMesh, Pose, Holistic): hand tracking
- Programming Language and version ( e.g. C++, Python, Java): Java

I would like to modify the cameraaxpreview in the aar file and insert the zoom function of the camera.
I know how to extract the aar file.
What should I do with java if I want to change the code in cameraaxpreview and enlarge it?

**Comment by ayushgdev** [comment]
Hello @MakeMeCookie To modify the CameraXPreview from mediapipe library, you will need to use AAR package building approach, since prebuilt maven binaries won't allow modifications. 
Refer to the file [CameraXPreviewHelper](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java) which contains code for starting the camera, utils for camera frame size, etc. Then build AAR package for hands solutions and include the AAR file in your application as lib, as guided [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html).
