### ISSUE TITLE
Accessing the mediapipe's different solutions

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#4041]
Hello,

I want to start from a basic question and then descend to my main question.
By installing MediaPipe (python version), will we have access to all the solutions (iris, object detection, ...) provided by mediapipe library?
I mean I want to install mediapipe and use all the solutions listed on the main page, is it possible?
Thx

**Comment by ayushgdev** [comment]
Hello @lghasemzadeh Yes. The Python MediaPipe installation from pip will give you access to all solutions listed on the MediaPipe documentation.

**Comment by lghasemzadeh** [comment]
I have installed **python** mediapipe 0.8.3 in ubuntu about 2 years ago, following the instruction in this [link](https://google.github.io/mediapipe/getting_started/install.html) (the instruction doesn't use pip!). But I can not access all the solutions like iris and object detection.

I have  questions:
1) Is the installation instruction in the link above updated? or it is old and useless?
2) to install python mediapipe can I use that instruction (ubuntu) step by step without making any changes? since I saw different installation method in forums/pages.
3) by the answer above you mean 'The Python MediaPipe installation from pip will give us access to all  **READY TO USE** solutions listed on the MediaPipe documentation.' right?
4) if yes why the table in this [link](https://google.github.io/mediapipe/) shows that iris solution is not available for python?
5) in my case, not having the access to iris and object detection solution causes by having old version of mediapipe or causes by the installation method I used (I didn't use pip)?
6) to get access to iris and object detection solution what should I do?
7) How can I find the compatible python version of specific mediapie version? for example, what is the compatible python version for mediapipe 0.8.11?

I need the answer to all the questions above, please.
Thank you so much

**Comment by ayushgdev** [comment]
Hello @lghasemzadeh 
Please find your questions answered below:
1. The installation instructions are correct and up to date.
2. Yes you can use the instructions available on documentation [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) without any changes. **But this will only install deps like OpenCV and Bazelisk into the OS so that the _operating system_ can leverage the hardware when asked by user using any Python, C++, or Java APIs. Corresponding APIs should be installed via their respective tutorials. For example in your case, you should follow the Python instructions [here](https://google.github.io/mediapipe/getting_started/python.html)**
3. Yes, they are ready to use solutions. Ready to use in the sense that the APIs can be leveraged to use the internal Graphs and machine learning models without any training required beforehand.
4. Yes, the Iris solution is not available for Python. The solution availability table is up to date so you can rely on it.
5. Iris and object detection are not available in Python APIs. So it is not an installation issue.
6. It looks like you will be building desktop apps with Python. So you can use C++ solution which is having the highest range of solutions available. 
7. To find a compatibility for Python and MP versions, you will need to check the release notes to find which versions are supported. For example, Python v3.10 support was released with MediaPipe v0.8.9 as documented [here](https://github.com/google/mediapipe/releases/tag/v0.8.9). We are aware it is not the most convenient method, but we are working on improving documentation of MediaPipe.

**Comment by lghasemzadeh** [comment]
Thank you.
I don't have further questions about this issue right now.

**Comment by lghasemzadeh** [comment]
I updated my last comment above and waiting for your response.

**Comment by ayushgdev** [comment]
Thanks for the update @lghasemzadeh . Apologies that your reply was missed amid other issues since this was already closed. 
The observations are interesting. Will get back to you on this after checking.

**Comment by ayushgdev** [comment]
Hello @lghasemzadeh 
1. There is no Python solution for Iris detection independently, however, since FaceMesh solution supports [an option](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_front_cpu.pbtxt#L42) to _include_ Iris Landmarks as well, you are able to get those landmarks. The input_side_packet "WITH_ATTENTION" is provided via the argument [`refine_landmarks`](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_mesh.py#L98) of the `FaceMesh()` constructor.
2. Although the visual representation is not available, the whole facial landmark indices can be found in [face_mesh_connections.py](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_mesh_connections.py) file

**Comment by lghasemzadeh** [comment]
Hello,

From which version of 'mediapipe python' version the 8 irises landmarks were included?
