### ISSUE TITLE
How and where the surfaceview is drawn after procesing by frame processor

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#407]
How and where the rendering of modified frames(frames which has landmark ponts and lines) are done on the surfaceview after frame processor processes the camera inputs and is it possible to do our custom rendering.

**Comment by eknight7** [comment]
The rendering happens inside the MediaPipe graph via the `AnnotationOverlayCalculator` (see https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt#L94 for example). The `output_video` frame is then displayed via `videoSurfaceOutput` declared in `FrameProcessor` https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L115.

Do do custom rendering, there are at least two ways:

1. Define a custom calculator (or subgraph) and use it instead of `AnnotationOverlayCalculator` to draw some data on the output frame. 
2. Define a custom utility function that takes an output frame (or the corresponding input frame), adds rendering to that frame and then sends it to the `videoSurfaceOutput` and display the result.

**Comment by VaishakVN** [comment]
**I found the following in the FrameProcessor. 
What exactly does the following code snippet do and Will it add an external image to a specific landmark point(e.g. Landmark [13]) in the Mediapipe rendering -**

/**
   * Accepts a Bitmap to be sent to main input stream at the given timestamp.
   *
   * <p>Note: This requires a graph that takes an ImageFrame instead of a mediapipe::GpuBuffer. An
   * instance of FrameProcessor should only ever use this or the other variant for onNewFrame().
   */
  public void onNewFrame(final Bitmap bitmap, long timestamp) {
    if (!maybeAcceptNewFrame()) {
      return;
    }

**Comment by eknight7** [comment]
@VaishakVN you can use that function to send a Bitmap object to an input stream in a MediaPipe graph. 
To render an object to a specific landmark point, you will need to write a custom rendering function. This may be helpful: https://github.com/google/mediapipe/issues/397#issuecomment-576145283
