### ISSUE TITLE
Objectron javascript library doesn't work after building the app

### ISSUE THREAD

**Issue by thisisrishabh22** [google/mediapipe#4086]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

WSL Ubuntu 20.04.5

### Browser and version if the issue happens on browser

Google Chrome 109.0.5414.120

### Programming Language and version

JavaScript

### Solution

Objectron

### Describe the actual behavior

```shell
Objectron is able to initialize in development but doesn't work after building the javascript application.
```

### Describe the expected behaviour

```shell
Objectron should initialize in development and work after building the javascript application.
```

### Standalone code/steps you may have used to try to get what you need

```shell
I'm using @mediapipe/objectron javascript package in my ViteJS application using ReactJS as template.
You can find a reproducible repository here: https://github.com/thisisrishabh22/mediapipe-threejs

Steps to reproduce:
1. Clone the repository
2. Install packages using: yarn install
3. Run in the development environment using: yarn dev
4. Create a production build using: yarn build
5. Run in the production environment using: yarn preview
```

### Other info / Complete Logs

```shell
Unexpected Application Error!
sl.Objectron is not a constructor

Vg/<@http://localhost:4173/assets/index-d3345c5a.js:84:17875
Xl@http://localhost:4173/assets/index-d3345c5a.js:40:24263
Kr@http://localhost:4173/assets/index-d3345c5a.js:40:42317
iy@http://localhost:4173/assets/index-d3345c5a.js:40:41163
tr@http://localhost:4173/assets/index-d3345c5a.js:40:40212
Wf@http://localhost:4173/assets/index-d3345c5a.js:40:36824
Xn@http://localhost:4173/assets/index-d3345c5a.js:38:3274
dt/<@http://localhost:4173/assets/index-d3345c5a.js:40:34207
```

**Comment by ayushgdev** [comment]
Hello @thisisrishabh22 
Thanks for raising this issue. We are aware of the issue and working on a solution. 
This seems to be happening due to the Rollup CommonJS plugin, since this plugin can't work with obfuscated packages and the JS source code for MediaPipe is not public. Rollup uses static analysis to determine its exports.

We are working on a solution to unveal the JS code. Meanwhile, can you refer to [this workaround](https://github.com/google/mediapipe/issues/2883#issuecomment-1060454290) and let us know if this works for you? 
PS: The link by the author has changed to [this link](https://github.com/shiguredo/media-processors/blob/develop/packages/virtual-background/rollup.config.mjs#L73)

**Comment by thisisrishabh22** [comment]
Hi @ayushgdev 
I've referred to the workaround you've shared and tried to implement it in my application but it's actually not working.
Thanks

**Comment by ayushgdev** [comment]
Hello @thisisrishabh22 
We are refreshing our solutions into new Tasks API. They should not have this issue, as they are built using ESM. However, they are not mature enough to be used in production yet, but you can explore the new APIs [here](https://developers.google.com/mediapipe/solutions/examples)

Due to our existing infrastructure, it is difficult for us to release the existing libraries using ESM.
