### ISSUE TITLE
RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL

### ISSUE THREAD

**Issue by lhray** [google/mediapipe#4091]
mediapipe v0.9.1
ubuntu: 18.0.04
nvidia Driver Version: 465.19.01    CUDA Version: 11.3
docker build image and start it.
1. [nvidia-docker] to run it, the mediapipe process can run in container.
2. docker run --runtime=nvidia to run image, the process could run too.
3. docker run --gpus all to run image, the process could not run and get error:  (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL.

I don't know why i could not run it using --gpus all parameter!

![image](https://user-images.githubusercontent.com/14047988/218393781-c106a976-3e55-4535-bf66-7af890f934e0.png)

**Comment by ayushgdev** [comment]
@lhray 
1. When you use `docker run --runtime=nvidia`, you are using nvidia-cotainer-runtime to access the host GPUs so that you don't have to install all drivers into the docker as well. This is required if you don't have nvidia-runtime specified in the docker's `daemon.json` config file as default runtime.
2. When you use `nvidia docker` command, this is essentially a script which adds backward compatibility with nvidia-docker v1. In v2, both commands are equivalent. So essentially this command also does the same since you are using 11.3.
3. When you use `docker run --gpus all`, it is specifiying that you want to expose all the available GPUs in your host machine to docker container. But you **also** need to specify the runtime as nvidia along with the `--gpus all` arg, since it does not know if it needs to expose the nvidia runtime to docker or not.

So just add `--runtime=nvidia` with `--gpus all`. That should solve the issue.

**Comment by mixiazhiyang** [comment]
> 2\. runtime=nvidia

@ayushgdev I can only access docker because I am using HPC. I cannot go outside the docker and run docker. Is there any way to solve this issue in the docker?

I0000 00:00:1708958024.457143 2343 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
I0000 00:00:1708958025.256465 2343 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1708958025.257329 2343 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
batch 0 | loss_lan: 0.40, loss_reg_id: 0.27,loss_reg_exp: 0.97
| To extract pose from static
{'src_image_name': 'infer_out/tmp/cropped_src_img.png', 'drv_audio_name': '/tmp/gradio/89f924df8f6ba2a90f4ff1ad4f4f3ec670ba241f/audio.wav', 'drv_pose_name': 'static', 'bg_image_name': '/tmp/gradio/77e40a84169eb20cd5632ed343840895826c8a11/bg.png', 'blink_mode': 'period', 'temperature': 0.2, 'mouth_amp': 0.45, 'out_mode': 'concat_debug', 'map_to_init_pose': True, 'low_memory_usage': False, 'hold_eye_opened': False, 'a2m_ckpt': '/hpc2hdd/home/yyang937/digital_human/video/Real3DPortrait/checkpoints/240210_real3dportrait_orig/audio2secc_vae/model_ckpt_steps_400000.ckpt', 'head_ckpt': None, 'torso_ckpt': '/hpc2hdd/home/yyang937/digital_human/video/Real3DPortrait/checkpoints/240210_real3dportrait_orig/secc2plane_torso_orig/model_ckpt_steps_100000.ckpt', 'min_face_area_percent': 0.2, 'out_name': '', 'seed': 42}
| audio-to-motion finished
rendering drv secc: 0%| | 0/5 [00:00<?, ?it/s]create rasterizer on device cuda:0
rendering drv secc: 0%| | 0/5 [00:00<?, ?it/s]
Inference ERROR: Not compiled with GPU support?

I installed everything correctly, including mediapipe. I tried bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \ mediapipe/examples/desktop/hello_world:hello_world and it works under cloned mediapipe folder.
But when I run python inference/app_real3dportrait.py , it will raise errors above.

uname -a Linux 4c2a87d133e3 4.18.0-305.el8.x86_64 https://github.com/yerfor/Real3DPortrait/issues/1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
mediapipe.__version__  0.10.10
Ubuntu 22.04.4 LTS
 NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2

I can run nvidia-smi, and model can be loaded to GPU without errors with pytorch. But it has some problem with mediapipe/gpu maybe. I can only access docker because I am using HPC. I cannot go outside the docker and run docker. Is there any way to solve this issue in the docker?

**Comment by pfagomez** [comment]
I was having the same issue and this solved it for me:
https://stackoverflow.com/a/79692238/7673180
os.environ['PYOPENGL_PLATFORM'] = 'egl'
os.environ['EGL_PLATFORM'] = 'surfaceless'

(well, I did:
```
export PYOPENGL_PLATFORM=egl
export EGL_PLATFORM=surfaceless
```
