### ISSUE TITLE
How to get Confidence/Score of face detection while using FaceMesh through MediaPipe?

### ISSUE THREAD

**Issue by FaizanAhmadPF** [google/mediapipe#4102]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android

### MediaPipe version

latest-release

### Bazel version

latest-release

### Solution

FaceMesh

### Describe the actual behavior

```shell
Using FaceMesh solution, I am unable to get detected face' Confidence/score.
```

### Describe the expected behaviour

```shell
Using FaceMesh solution, I am unable to get detected face' Confidence/score.
```

### Standalone code/steps you may have used to try to get what you need

```shell
facemesh.setResultListener(
                    faceMeshResult -> {
                       //I tried to get confidence/score from this faceMeshResult variable but unable to do so.
                    });
```

### Other info / Complete Logs

```shell
I want to get confidence/score of detected face. I am using FaceMesh feature. I want to know detected face' confidence.
Is it possible in android or not, if yes then please explain.
```

**Comment by ayushgdev** [comment]
Hello @FaizanAhmadPF 
MediaPipe Face Mesh solution does not support querying the confidence score for the face. If you check the [model card](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview), you will notice it does not return any confidence score, unlike [face detection](https://drive.google.com/file/d/1d4-xJP9PVzOvMBDgIjz6NhvpnlG9_i0S/preview). Since the platform APIs depend on the model to return the confidence score, this is not possible as of now.

**Comment by FaizanAhmadPF** [comment]
Okay, thank you so much for your response.
