### ISSUE TITLE
Broken Link for tensorflow models

### ISSUE THREAD

**Issue by lucifertrj** [google/mediapipe#4124]
### Description of issue (what needs changing)

[Object Detection](https://google.github.io/mediapipe/solutions/object_detection.html) documentation fix

### Clear description

[Object Detection](https://google.github.io/mediapipe/solutions/object_detection.html) documentation contains three broken link. Since the code solution is implementing `graphs` saved model. I hope I have used a correct link in replacement to the broken link

### Correct links

Yes

### Parameters defined

Yes

**Comment by ayushgdev** [comment]
Hello @lucifertrj 
- Would you please let us know which links are not working in the documentation? Or point us to the section in the page where  the links are located?
- Also, have you submitted any PR for the fix?

**Comment by lucifertrj** [comment]
Hi @ayushgdev, 

- Documentation that contains the broken link: [Object Detection](https://google.github.io/mediapipe/solutions/object_detection.html). TensorFlow model and more info URL redirecting to Page not found. 
- Yes, I have raised a PR #4123

**Comment by ayushgdev** [comment]
Hello @lucifertrj 
Thanks for interest in MediaPipe and your enthusiasm for active contribution. However, I checked the code in the PR:
1. The issue occurs because the original path does not exist anymore. You can check the original path [here](https://github.com/google/mediapipe/tree/v0.8.10/mediapipe/models/object_detection_saved_model) in the old versions. This path was removed in v0.8.11 since we favour TFLite models and do not encourage usage of the Tensorflow Models(check a sample [here](https://github.com/google/mediapipe/commit/dcd2adad532f3f65703a7c387f182090a1229c51)). The Tensorflow model link in the PR is updated to point to ".../graphs/object_detection" page, which is not a correct place to point to.
2. For the model info link, the new link is pointing to the "objectron" solution instead of the "object detection". These are two separate solution offerings by MediaPipe and thus cannot be interchanged. 

So the changes are not valid changes.

**Comment by lucifertrj** [comment]
I have updated the link in PR #4123 , so check it out @ayushgdev

**Comment by kuaashish** [comment]
Closing this issue as PR has been merged in commit [38ec8ae](https://github.com/google/mediapipe/commit/38ec8ae842ceb4083129a4da325a56e41799bd08).
