### ISSUE TITLE
How to detect foward kick more accurately

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4126]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android 11

### MediaPipe version

0.9.1

### Bazel version

5.2

### Solution

Pose

### Programming Language and version

Java

### Describe the actual behavior

```shell
Please refer to the video:
https://drive.google.com/file/d/11f7ej1YFuzaAyxbAEl62ipQHcOqpQ8td/view?usp=share_link

Is there any way to track the forward kick more accurately?
```

### Describe the expected behaviour

```shell
The feet should overlap the position of the shoe.
```

**Comment by ayushgdev** [comment]
Hello @fchen09 
Is it possible if you can provide the video/screenshot of the video _without_ the pose detection results? Due to the landmark and connection drawings, is it difficult to check the original input.

**Comment by fchen09** [comment]
Here is the original input:
<img width="400" alt="me3" src="https://user-images.githubusercontent.com/84703080/221563157-2104f5af-7488-4849-9355-e0803b2b89df.png">

**Comment by ayushgdev** [comment]
There are two things you can try to deal with this issue:
1. You can try altering the colors of the image by preproessing since [skintones are accounted](https://openaccess.thecvf.com/content_CVPR_2020/papers/Xu_GHUM__GHUML_Generative_3D_Human_Shape_and_Articulated_Pose_CVPR_2020_paper.pdf) when detecting the pose of the subjects.
2. You can use a heavier model for Pose detection. The model complexity for Pose solution can be changed in the [`PoseLandmarkCpu`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L20) calculator. The Calculator accepts `MODEL_COMPLEXITY` as a input_side_packet. This calculator is used in [pose_tracking_cpu.pbtxt](https://github.com/google/mediapipe/blob/4a1ba11e3f014f0ecfde6108971a0b649df42fa5/mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt#L47) file. Hence, you can add input_side_packet as input to this graph node. And in the MainActivity.java, you can give the complexity as:
```
 AndroidPacketCreator packetCreator = processor.getPacketCreator();
 Map<String, Packet> inputSidePackets = new HashMap<>();
 inputSidePackets.put("MODEL_COMPLEXITY", packetCreator.createInt32(COMPLEXITY));
 processor.setInputSidePackets(inputSidePackets);
```
