### ISSUE TITLE
For the value of the depth mm of iris.

### ISSUE THREAD

**Issue by MakeMeCookie** [google/mediapipe#4131]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### MediaPipe Tasks SDK version

master

### Task name (e.g. Image classification, Gesture recognition etc.)

Gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

Java

### Describe the actual behavior

```shell
The app crashes completely.
```

### Describe the expected behaviour

```shell
In my opinion, if you build iris "depth_MM" code into handtracking, you should get a z value for hands. But that's not the case.

I want to build the code of "depth_MM" of iris to show the z-value by building the hand tracking.
Can't the iris code be set to the z-value of the hand? I'm curious.
https://github.com/google/mediapipe/issues/742#issuecomment-639104199 
I looked at the question of #742. However, I did not saw a perfect z-value output.
thank you,. It if you could tell me if the code for iris tracking can show the z-value of hand tracking or not.
```

### Standalone code/steps you may have used to try to get what you need

```shell
try {
            ByteArrayOutputStream handLandmarksPacket = null;
            byte[] lanndmarksRaw = handLandmarksPacket.toByteArray();
            LandmarkProto.NormalizedLandmarkList landmarks = LandmarkProto.NormalizedLandmarkList.parseFrom(lanndmarksRaw);
            double depthMM = landmarks.getLandmark(0).getZ();
            double depthCM = depthMM / 10.0;
            System.out.println("Depth of landmark 0: " + depthCM + " cm");
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
```

**Comment by ayushgdev** [comment]
Hello @MakeMeCookie
Getting hands' depth value in Iris solution is not possible, since this will internally use the [Iris depth renderer subgraph ](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt). This graph uses [IrisToDepthCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt#L226) which outputs the Iris Depths. Thus, one solution would be to edit this graph file and include the [HandLandMarkCPU](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt) subgraph . However, we would not advise so since it would be very difficult to manage the customization.

Another solution is to run the Iris and Hands solution simultaneously and get the Hands Z-coordinates. However, they will be based on the GHUM model so the center will not be hand. Check the model card [here](https://drive.google.com/file/d/1-rmIgTfuCbBPW_IFHkh3f0-U_lnGrWpg/preview).
