### ISSUE TITLE
MP Holistic and MP Hands generate different hand_landmarks result

### ISSUE THREAD

**Issue by tuotuoshao** [google/mediapipe#4163]
refer to #4014 .
I captured a image, then run with holistic and hand solutions respectively，here is the partial code in python:
![u75ghkACbw](https://user-images.githubusercontent.com/51219602/224238708-ae197f18-e24b-427b-8a4f-5b33580dfb9a.jpg)
![hPkrevN9ka](https://user-images.githubusercontent.com/51219602/224238860-717cbdd7-886b-4982-a0e2-7efb75ea67c2.jpg)
Then get different hand result, holistic solution indicates there is no hand, hand solution indicates there is a right hand.Here is my debug view:
![qy6ZIvVBTJ](https://user-images.githubusercontent.com/51219602/224241335-a3cd7121-865e-4fb1-8c4d-1734a7920b84.jpg)
![mOMpzLzxLU](https://user-images.githubusercontent.com/51219602/224240880-e1cf81bd-3bf0-42b7-bc4c-369ad5b4b5bd.jpg)
Here is the captured image for test:
![b](https://user-images.githubusercontent.com/51219602/224241681-f1b4c473-0154-4948-b9ee-3630c560caa2.JPG)

**Comment by ayushgdev** [comment]
@tuotuoshao Thanks for bringing this to our attention. This seems to be of an interesting case. We shall investigate this issue and update our findings soon.
However, to replicate the issue,we shall need few inputs from your end:
- The OS being used. 
- The Python version used
- MediaPipe version used

**Comment by tuotuoshao** [comment]
The OS is windows, python 3.7.15, mediaipe 0.9.0.1.
I used c++ with tag v0.9.1 at the beginning than observed the hands were undetected frequently with holistic, but solution hand detected well.Than I tried several tag and get same result, the same behavior to python mediaipe 0.9.0.1.

**Comment by ayushgdev** [comment]
Hello @tuotuoshao 
On investigating the issue, it is found that the issue is by design. The hand tracking solution uses different graph than the holistic solution and as a result it outputs different result.

1. In holistic solution, holistic_landmark_cpu.pbtxt graph is used. In this graph, [HandLandmarksLeftAndRightCpu](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L120) node is designated to provide left and right hand landmarks. This node is itself a [subgraph](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/holistic_landmark/hand_landmarks_left_and_right_cpu.pbtxt). Within this subgraph, [`HandLandmarksFromPoseCpu`](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/holistic_landmark/hand_landmarks_left_and_right_cpu.pbtxt#L68) is the node to output the right hand landmarks. As clear by name, this subgraph uses the pose landmark to detect if there are any hand landmarks or not.

2. Within this subgraph, [`HandVisibilityFromHandLandmarksFromPose`](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/holistic_landmark/hand_landmarks_from_pose_cpu.pbtxt#L25) is the node which determines if there is a hand visible or not. 

3. If we further go into this subgraph, we shall find [LandmarkVisibilityCalculator](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/holistic_landmark/hand_visibility_from_hand_landmarks_from_pose.pbtxt#L28) which determines if the  hand is visible or not _based on wrist landmark visibility from pose landmarks_. The visibility of the wrist landmark comes from the TFlite model.

Comparing this to [`hand_landmark_tracking_cpu.pbtxt`](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.pbtxt) used in Hand solution, there is no such LandmarkVisibilityCalculator used based on which the hands are determined. Rather, [NormalizedRectVectorHasMinSizeCalculator](https://github.com/google/mediapipe/blob/131be2169ae417ead964ad17a46900034479c3d8/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.pbtxt#L82) determines if the `PalmDetectionCpu` should run or not based on whether the minimum number of hands to be detected are detected.

**Comment by tuotuoshao** [comment]
Okay. Thank you for your answer.
