### ISSUE TITLE
[ ⭐] How to change lip color using Mediapipe?

### ISSUE THREAD

**Issue by techy-keeda** [google/mediapipe#4179]
Hi all, I need help with changing the lip color of a person in a video using Mediapipe. I've used Mediapipe for facial landmark detection and tracking, but I'm not sure how to proceed with changing the lip color. I couldn't find any resources on how to achieve this in the Mediapipe documentation. Can someone please provide me with some guidance on how to do this? Thank you!

**Comment by techy-keeda** [comment]
I can outline lips using facemesh, but I need assistance to fill in color with controllable transparency in them. Plus no bold lines for outlining also.

**Comment by fadiaburaid** [comment]
This has to do more with OpenCV than Mediapipe. You might want to search for how to fill a polygon using [cv2.fillPoly](http://docs.opencv.org/modules/core/doc/drawing_functions.html#fillpoly).  You will need the landmarks to define the contour you can refer to this image [here](https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png) to find which landmarks.

**Comment by kuaashish** [comment]
@techy-keeda,
Would you please let us know the platform using such as Python, Android, JavaScript or other available? Thank you!

**Comment by techy-keeda** [comment]
@kuaashish any suggestions?

**Comment by kuaashish** [comment]
Hi @kostyaby,
Could you please look into this issue. Thank you!

**Comment by kostyaby** [comment]
Hey @techy-keeda,

Generating the lip mask from the landmarks is an important step that you've already taken, so that's good. It looks like you've gotten pretty far already! To enhance the quality, I'd recommend doing the following:

- Smooth the segmentation mask using OpenCV gaussian blur filter ([tutorial](https://docs.opencv.org/4.x/d4/d13/tutorial_py_filtering.html)). This should help to avoid sharp edges of the segmentation mask
- When blending, avoid using the sharp mask and/or any bitwise operations on the mask  - instead, use the blurred mask and treat it as if it has continuous values from 0 to 1, not just {0, 1}. This means using alpha-blending (`A * (1 - alpha) + B * alpha`) instead of bitwise operator like `bitwise_and`
- As for the virtual makeup rendering itself, it's a very complex area so don't expect to have an easy perfect solution. However, for darker colors (like red or blue) a decent blending function is "multiply" ([CSS spec](https://www.w3.org/TR/compositing-1/#blendingmultiply)). In other words, if the original image pixel color is `(R_i, G_i, B_i)` and the color of the makeup is `(R_m, G_m, B_m)` then the "multiply" result would be `(R_i * R_m, G_i * G_m, B_i * B_m)`. 
- If you're looking to build a more advanced solution, there's a paper that we wrote together with my colleagues back in the days: [PDF](https://static1.squarespace.com/static/5c3f69e1cc8fedbc039ea739/t/5d01686862182d0001b776a2/1560373362585/12_Lipstick_Simulation_Paper_For_Submission.pdf)

Hopefully this reply helps you to proceed forward!

**Comment by techy-keeda** [comment]
Thanks @kostyaby
will work on the recommendations and post results here

**Comment by kuaashish** [comment]
@techy-keeda,
Could you please update the result here if you have succeeded to archive the mentioned use case?
