### ISSUE TITLE
GPU Acceleration Python Module

### ISSUE THREAD

**Issue by matteoturini** [google/mediapipe#4182]
### MediaPipe Solution (you are using)

pose

### Programming language

Python

### Are you willing to contribute it

No

### Describe the feature and the current behaviour/state

```shell
Currently, the module uses CPU with Windows and AMD GPUs, but other APIs such as OpenCL or DirectML could be used instead.
```

### Will this change the current API? How?

```shell
It will not.
```

### Who will benefit with this feature?

Users of AMD GPUs.

### Please specify the use cases for this feature

```shell
Accelerate drastically all estimations on Windows and GPUs
```

**Comment by ayushgdev** [comment]
Hello @matteoturini 
Thanks for raising this issue. This is indeed an improvement we expect to be present in the MediaPipe solutions for Python. We shall take this feature request and prfioritize it internally to make it available by default/by using some config options.

In the meantime, please look at [this comment](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007) to enable GPU acceleration in Python. Since Python can understand Image Frame and there is a requirement of GPU Buffer for GPU processing, this change should help.

**Comment by matteoturini** [comment]
Does this work with AMD GPUs?

**Comment by ayushgdev** [comment]
MediaPipe GPU works with the OpenGL library. If your AMD GPU model supports OpenGL, this will work in AMD GPU as well.

**Comment by matteoturini** [comment]
How do I build my own version?

**Comment by matteoturini** [comment]
I don't have the coding skills to make it, but I can compile it if it exists, or can be done with minor changes.

**Comment by matteoturini** [comment]
Also, OpenGL is (probably) good enough for me.

**Comment by ayushgdev** [comment]
The integration with DirectML does not exist as of now. Since the complexity is very high for such integration, it is advised to wait for an official release. OpenGL is already available for use in MediaPipe so it should serve the purpose.
