### ISSUE TITLE
how can make python transform C++，in order to make me use gpu to speed

### ISSUE THREAD

**Issue by stonecropa** [google/mediapipe#4185]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

win10

### Solution

holistic

### Programming Language and version

python and C++

### Describe the actual behavior

```shell
Mediapipe have not gpu edition in python but I don't konw C++,how can make python transform C++，in order to make me use gpu to speed.Converting Python code to C++.Besides,I want to know how fast in C++ edition in gpu compared with python edition in cpu
```

### Describe the expected behaviour

```shell
Converting Python code to C++.and use gpu edition in C++.I would appreciate it if you could tell me how to do it.Thank you for your guidance
```

**Comment by kuaashish** [comment]
Hi @stonecropa,
Could you please elaborate your query with complete details. Thank you!

**Comment by ayushgdev** [comment]
Hello @stonecropa 
From the provided description, it seems that you want to use GPU in Python, but are unfamiliar with C++ which supports GPU. To provide a context to the GPU usage in Python, most popular libraries rely on the C++ to make computations faster internally (_numpy_ (not a GPU reference) is such an example). C++ will be required since it provides a native device management API to interact with GPU. In order to use C++ with Python, wrappers such as pybind11 are used to call C++ functions within the Python code. (MediaPipe also uses this when you can see such imports `from mediapipe.python._framework_bindings import ...`). 

To use GPU in Python, there are certain transforms need to be applied to the Python **_build_** to help it supply the inputs to GPU buffers instead of CPU. Please look at https://github.com/google/mediapipe/issues/1042#issuecomment-683506007 to enable GPU acceleration in Python. Since Python can understand Image Frame and there is a requirement of GPU Buffer for GPU processing, this change should help.

**Comment by stonecropa** [comment]
Thank you ,I have seen the #1042,but I don't know how to improve it and this detail

**Comment by ayushgdev** [comment]
@stonecropa Please look this [this particular comment ](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007)and make the changes to the holistic solution graph (holistic_tracking_gpu.pbtxt) since it is the entry point for holistic solution. 
Essentially, before feeding the `input_video` stream to FlowLimiterCalculator, conversion to GPUBuffer is required with ImageFrameToGpuBufferCalculator so that the image frames are in processed in GPU rather than CPU. At last, the reverse conversion is needed so that the exit is of ImageFrame and not GPUBuffer.
