### ISSUE TITLE
Help please with landmark coordinates

### ISSUE THREAD

**Issue by Michael89** [google/mediapipe#422]
I have tried your pretrained model for hand tracking on my laptop with tflite.
Using hand_landmark_3d.tflite I was able to get response with 93 float values, but I don't know how to interpret them. If I guess correctly it should be like this [x, y, z, x, y, z, x, y, z, ......]
In another issues I found that instead x, y, there is u, v coordinates. Can someone help me figure out how to map this coordinates back to image. Or share some links where I can learn something how to work with this coordinates.

Here is example of output
[[ 5.73803955e+02  1.13868750e+03 -5.46218395e-01  5.12194763e+02
   5.26353577e+02 -1.75876827e+01  3.95716187e+02  3.61917419e+02
  -6.36454277e+01  2.47399094e+02  4.43307892e+02 -1.11231621e+02
   3.95803040e+02  2.40306549e+02 -1.26765953e+02  3.38830536e+02
  -2.76079865e+02  2.41141205e+01  2.83156219e+02 -1.70654221e+02
  -6.85159779e+00  2.28728485e+02 -2.76015808e+02  4.23018265e+01
   3.32072327e+02 -4.60349854e+02  7.72872162e+01  4.22068481e+02
   5.75553589e+01 -5.78513641e+01  6.83203506e+01  2.89094452e+02
  -2.13282196e+02  1.12702522e+02  4.30184937e+02 -3.22525116e+02
   4.39910492e+02  9.63115768e+01 -3.96457275e+02  4.50602661e+02
   3.00958435e+02 -1.23822266e+02  6.66966431e+02  4.33050293e+02
  -2.13000671e+02  7.11620422e+02  5.44539368e+02  2.39527969e+02
   5.37973145e+02  5.62555664e+02  5.77881592e+02  3.24635773e+02
   3.63354736e+02 -2.22293304e+02  5.68385254e+02  6.90362366e+02
  -2.63504822e+02  6.28268127e+02  5.53707825e+02 -3.67202225e+01
   6.08915894e+02  3.19211914e+02  2.04959793e+02]]

**Comment by Delicate-Kim** [comment]
hey did you work in desktop? How did you manage to extract this array of coordinates???

**Comment by alexgoft** [comment]
what did you do? @Michael89

**Comment by eknight7** [comment]
Code for extracting coordinates on desktop: https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f.

**Comment by alexgoft** [comment]
> Code for extracting coordinates on desktop: https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f.

I don't understand what PreProcess/ PostProcess on images/keypoints was performed (i am writing a simple python inference script).
Could you please help me with this?

**Comment by pruntoff** [comment]
> I don't understand what PreProcess/ PostProcess on images/keypoints was performed (i am writing a simple python inference script).
> Could you please help me with this?

Sorry for necrocomment.
I can feel your pain, case mp is not very friendly with newcommers (especially with only scripting languages background).
So if you'd like to get landmark pozition in python, you should do some things:
output landmarks are normalized, and returned in class NormalizedLandmarkList (which is list :) ). So you can access landmark (which is NormalizedLandmark class) by it index, as usual list.
If so, you get something like this: 
```
x: 0.3427850008010864
y: 0.5966814756393433
z: 0.04402058944106102
```
It is protobuf message with normalized x,y and z coord. As I know there is somewhere methods like .x() or .y() to get corresponding value, but not in python. To access x or y you should use any protobuf parser (the best one is google.protobuf.json_format IMHO). So just parse message to dict (or json, as you wish)(https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html) and you get dict with coordinates for landmark.

As I think to get corresponding pixel on image, you can just multiply x on width and y on height of image in pixels, because as I understand normalization is get by [0,1] with input image (but i'm not shure I do not need this, just test it).
