### ISSUE TITLE
Face Detection does not work if I move to different tab in the browser

### ISSUE THREAD

**Issue by krisalay** [google/mediapipe#4244]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Mac OS

### Browser and version if the issue happens on browser

Google Chrome Version 111.0.5563.146 (Official Build) (arm64)

### Programming Language and version

Javascript (react.js)

### MediaPipe version

"@mediapipe/camera_utils": "^0.3.1675466862",     "@mediapipe/drawing_utils": "^0.3.1675466124",     "@mediapipe/face_mesh": "^0.4.1633559619",

### Solution

FaceMesh

### Describe the actual behavior

```shell
The face mesh work fine if I am on the same tab where the facemesh logic is written, but if I move to the another tab, then I do not get the data from facemesh.
```

### Describe the expected behaviour

```shell
It should work irrespective of which tab I am on.
```

### Standalone code/steps you may have used to try to get what you need

```shell
const facemesh = new FaceMesh({ locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}` });
facemesh.setOptions({
  maxNumFaces: 2,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5,
  enableFaceGeometry: false
});
facemesh.onResults((result) => {
      console.log("########", new Date().toISOString());
    });
const camera = new Camera(videoElement, {
      facingMode: "user",
      onFrame: async () => {
        await facemesh.send({ image: videoElement });
      },
      width: 120,
      height: 90
    });
    camera.start();
```

### Other info / Complete Logs

```shell
######## 2023-04-05T11:15:12.519Z
######## 2023-04-05T11:15:12.554Z
######## 2023-04-05T11:23:54.553Z
######## 2023-04-05T11:23:54.570Z
######## 2023-04-05T11:23:54.595Z
######## 2023-04-05T11:23:54.629Z
######## 2023-04-05T11:23:54.664Z
```

**Comment by ayushgdev** [comment]
Hello @krisalay 
This is not a bug. This works as per the standard Web APIs because it uses `requestAnimationFrame()` which is called frequently (60FPS) but it is paused if the tab is not in focus to save resources in the browsers. Please check the comment [here] (https://github.com/google/mediapipe/issues/3977#issuecomment-1377034643) where a user asked for a similar issue.

**Comment by krisalay** [comment]
@ayushgdev If I want to not pause, then is there a way that it can be done?

**Comment by ayushgdev** [comment]
I don't think so @krisalay . The main motivation for pausing the background activities is to restrict background usage of resources. So not even web workers are allowed to continue running. 
In typical scenarios, like if you want to make HTTP calls continuously, developers use a trick. They push dummy notifications which can be listened to by a service worker in the browser and as soon as the notification arrives, they call HTTP APIs. 

However, this trick cannot work in the case of webcam since for processing each frame, the call has to be made 60 times per second (or 30 atleast to get a 30FPS output), which is very fast compared to the push notifications the browser can receive.

**Comment by krisalay** [comment]
@ayushgdev So you are saying that it can noway be done?

**Comment by ayushgdev** [comment]
Yes @krisalay . The trick used is already shared. But it cannot be done in an ideal way.
