### ISSUE TITLE
using opencv android sdk and mediapipe aar

### ISSUE THREAD

**Issue by jimwinkpresage** [google/mediapipe#4273]
I am trying to use opencv android SDK in an android studio project with mediapipe graph using aar. After I import the the opencv module into my project I get the following error "More than one file was found with OS independent path 'lib/armeabi-v7a/libopencv_java3.so....' I guess my opencv module import is conflicting with the stuff imported by the aar. Any ideas how I can modify the aar build so that I can do things like "import.org.opencv.core.Mat'?

**Comment by jimwinkpresage** [comment]
I was able to resolve this by building the aar file with MEDIPAPIE_DISABLE_OPENCV=1. Using this aar I was able to import the opencv module and no issues using opencv functions and graph running fine.

**Comment by jimwinkpresage** [comment]
Yes please close. Thank you.

**Comment by rgm-22** [comment]
Hey, @jimwinkpresage and @ayushgdev !

I would like to integrate the awesome MediaPipe hand tracking into my OpenCV onCameraFrame method (Android).

I think it is possible.
Any idea about how to start with it?

Thank you in advance!

**Comment by ayushgdev** [comment]
@rgm-22 This issue seems to be related to the original issue. To keep the context of the issue as relevant to the original issue as possible, we request you to open a separate issue. 
This helps community and us to search the issues better in concise manner.
Closing this issue since original query has been resolved.
