### ISSUE TITLE
Holistic as .tflite

### ISSUE THREAD

**Issue by charlieforward9** [google/mediapipe#4277]
### MediaPipe Solution (you are using)

Pose, Hands, Face

### Programming language

Flutter

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
In search of the `Holistic landmarks detection` model in `.tflite` format

I am attempting to create a product using this extraordinary repository and have been having to hack around a lot due to my decision to build with Flutter. I am now at the point where I would like to replace the independent *Pose*, *Hands*, and *Face Landmark* models with the *Holistic* model, but I notice that there is no .tflite format for the model in the [docs](https://github.com/google/mediapipe/blob/master/docs/solutions/holistic.md).
```

### Will this change the current API? How?

```shell
It will not change in any way, only expanded to more developers
```

### Who will benefit with this feature?

1. Flutter developers.
2. Anyone else who uses .tflite files.
3. The physical therapists I am building this application for.
4. The clinic owners who depend on the physical therapist work efficiently
5. The patients' insurance providers who pay for the clinic visits and assessment administration.

### Please specify the use cases for this feature

```shell
Detecting the pose and balance variation of patients performing assessments in a physical therapy clinic. Using the face and hands as references for assessment starting conditions.
```

### Any Other info

```shell
I see that there is a comment about a new version coming out, but I am perfectly fine with the legacy version for my MVP. I am willing to contribute to this effort with my limited ML expertise to: 
1. Accelerate the timeline
2. Learn about a foundational piece of the product I am trying to build. 

Please let me know what I can do to help make this happen.

The long-term plan is to create an inference pipeline in the cloud, which will take some extra learning. If this request cannot be met in the next few days, please let me know ASAP so I can work on creating that instead with the Python Solution API.
```

**Comment by ayushgdev** [comment]
Hello @charlieforward9 
Having holistic solution's dedicated .tflite model is a good to have item, but a redundant one as well because holistic solution is defined as a solution which can detect all major body landmarks including face and hands. Since we offer the other solutions independently, we can simply reuse the existing models to create such an exhaustive solution.

To create a new holistic dedicated model, we shall need to perform annotations of the images for hands, face points and body, all in the same image. Preparation of such a dataset can take considerable time. Adding to it is the training time and resources for such a model. Having holistic solution as a combination of preexisting modular solution makes sense due to these reasons.

**Comment by charlieforward9** [comment]
@ayushgdev To clarify, you are implying that to achieve the holistic model, I should manually implement this? 

![image](https://user-images.githubusercontent.com/62311337/231884543-053e6804-ddf7-4c1e-9954-309cf3f1ddf5.png)

Also, I cannot find the *face recrop* model in the [list of model offerings](https://github.com/google/mediapipe/blob/master/docs/solutions/models.md). Should I calculate the image bounds from the *face detection* model?
