### ISSUE TITLE
replacing foot landmarks by object

### ISSUE THREAD

**Issue by SinaDavid** [google/mediapipe#4281]
The feet in my videos are covered by an object and therefore are not detected properly. However, I know that they don't move. Is there a way to tell the model that the feet are e.g. the center of the object that covers them?

Thanks in advance!

**Comment by ayushgdev** [comment]
Hello @SinaDavid Would you please elaborate your issue with details like 
- the platform you are using, 
- the mediapipe solution along with it's version, 
- are you using tasks api or the legacy solution,
- any image sample that you can provide for the query

**Comment by SinaDavid** [comment]
Hey, sorry for my late reply!

this is our actual code:


# Importing mediapipe and opencv 
import cv2
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_pose = mp.solutions.pose

# Specify the video filename
file = 'Ollie_Zeidler_6_48_67.mp4'

# Loading in the video
cap = cv2.VideoCapture(file)

# Check if camera opened successfully
if (cap.isOpened()== False):
    print("Error opening video file")

antwoord = []

# Read until video is completed
with mp_pose.Pose(min_detection_confidence=0.5, 
                  min_tracking_confidence=0.5) as pose:
    while(cap.isOpened()):
      
        # Capture frame-by-frame
        ret, frame = cap.read()
        if ret == True:
            # Create the pose estimation for this frame
            # Recolor image to RGB
            image = image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image.flags.writeable = False
   
        # Make detection
            results = pose.process(image)
   
        # Color back to BGR
            image.flags.writeable = True
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    
        # Drawing the landmarks
            mp_drawing.draw_landmarks(
                image,
                results.pose_landmarks,
                mp_pose.POSE_CONNECTIONS)
            # Show the video
            cv2.imshow('Mediapipe Feed', image)
          
            # Press Q on keyboard to exit
            if cv2.waitKey(25) & 0xFF == ord('q'):
                break
  
# Break the loop
        else:
            break
# When everything done, release
# the video capture object
cap.release()
  
# Closes all the frames
cv2.destroyAllWindows()

We would like to fix to position of the foot at the intersection between the shank and the boat. I added an example video.
Any input is highly appreciated!

Sina

[](url)

https://user-images.githubusercontent.com/9551718/234217559-06af6545-b3f0-4d21-807e-2ebb36121b08.mp4

**Comment by ayushgdev** [comment]
Hello @SinaDavid 
Apologies for the late reply. However, the brainstorming took sometime. 
The best alternative would be to use a custom model fit for your purpose but that is not possible since MediaPipe pose solution does not allow fine tuning.  Hence the other alternative is to use algorithmic approach.

If we notice the pattern, the issue is that the mediapipe detects feet at right angle of the legs. Thus the foot index fingers are detected at right angles. Since in your application, you stated that you know the feet are hidden in the boat, we can use this to alter the landmarks manually. Hence, the red dot corresponding to the toes can be moved down in `y-coordinate` so that the connections with the ankle and heel landmarks are created with an obtuse angle. This will give a perception that the feet are touching the boat base rather than being shown lifted upwards. 

To achieve this, a code can be before `mp_drawing.draw_landmarks()`. Sample code is given below:
```
results.pose_landmarks.landmark[31].y += 0.05
results.pose_landmarks.landmark[32].y += 0.05
```
Indices of the landmarks can be found in [pose_landmark_gpu.pbtxt.](https://github.com/google/mediapipe/blob/48cc96cf3c9d7e1eee20c36f90e7e2dcc497a6fb/mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt#L86).
