### ISSUE TITLE
Uncaught (in promise) TypeError: m is not a function     at oa.h (holistic.js:61:1)

### ISSUE THREAD

**Issue by guibeutler** [google/mediapipe#4290]
My project is showing this error when trying to use some screens. I don't know how to solve it.

**Comment by ayushgdev** [comment]
Hello @guibeutler 
Please elaborate your query with complete details on the following:
- the mediapipe solution you are using along with its version
- browser and its version you are encountering this issue
- whether you are using vanilla JS or some JS framework (reactJs or Angular)
- steps to reproduce the issue consistently at our end
- a minimal example code to reproduce the issue

Also, we will request you to use [new issue template](https://github.com/google/mediapipe/issues/new/choose) while filing for new issue since it gives better understanding of the query in the first go.
