### ISSUE TITLE
PacketGetter.getProtoBytes(packet) on Pose detection

### ISSUE THREAD

**Issue by pavelatmotivision** [google/mediapipe#4298]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

macos/android

### Programming Language and version

kotlin

### Solution

Pose

### Android Studio, NDK, SDK versions (if issue is related to building in Android environment)

Electric EEL

### Describe the actual behavior

```shell
HI everyone

I'm running the pose detection on android and trying to convert Packet object into the landmark object, it crashes on `PacketGetter.getProtoBytes(packet)`. 
It disconnects and throws this in output
`A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xb400007312f810e0 in tid 27883 (DefaultDispatch), pid 27817`

May you provide assistance?
```

### Describe the expected behaviour

```shell
should not be crashing
```

### Standalone code/steps you may have used to try to get what you need

```shell
Tried to isolate the issue
```

### Other info / Complete Logs

```shell
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xb400007312f810e0 in tid 27883 (DefaultDispatch), pid 27817
```

**Comment by ayushgdev** [comment]
Hello @pavelatmotivision Would you please provide few more details:
- Are you using the new MediaPipe tasks API or the legacy solution?
- Which version of MediaPipe are you using?
- The version of Android SDK and NDK being used
- Is it possible to provide a minimal code example in any github repo so that we can reproduce the issue at our end and look at it in detail?

**Comment by pavelatmotivision** [comment]
@ayushgdev 

Is there anything else that I'm missing on my end so that you'd be able to help out with this issue?

**Comment by ayushgdev** [comment]
Hello @pavelatmotivision 
1. Would you please try using [`geProtoVector()`](https://github.com/google/mediapipe/blob/cf101e62a9d49a51be76836b2b8e5ba5c06b5da0/mediapipe/java/com/google/mediapipe/solutioncore/SolutionBase.java#L106) instead of `getProtoBytes()`? This is because landmarks in pose contain a vector of normalized landmarks so querying for protobytes would be raise issue. 
2. Also, the packet could be empty as well. Hence, add a check for if the packet is empty or not.

**Comment by pavelatmotivision** [comment]
@ayushgdev 

I tried the suggested implementation

`if (!packet.isEmpty) {
                    val landmarksRaw =
                        PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser())
......
                }`

Does not seem to solve the issue. Still crashes on "PacketGetter.getProtoVector".

What else can be a possible solution? 
Thanks

**Comment by ayushgdev** [comment]
Would you please let us know your Android SDK and NDK versions? We test solutions extensively on SDK 30.0.3 andd NDK 21.1.6352462 so we would advice testing your code with this combination first.
