### ISSUE TITLE
Slow Initialization of Holistic in Chrome

### ISSUE THREAD

**Issue by nskaiser** [google/mediapipe#4348]
Hello, when initializing Holistic in Chrome, it can freeze Chrome for about 30 seconds while loading. On a Mac M2, it is quite fast, under 3 seconds.   But slightly older computers can be drastically slower.  Here's the params:

async initialize() {
    if (!this.holistic) {
      this.holistic = new Holistic({locateFile: (file) => new URL(`holistic/${file}`, globalThis.location.origin).toString()});
    }
    
    this.holistic.setOptions({
      modelComplexity: 0,
      smoothLandmarks: true,
      enableSegmentation: false,
      smoothSegmentation: false,
      refineFaceLandmarks: true,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5
    });
    this.holistic.onResults(this.onResults);
    this.model = await load();
  }

 Here are the specs of the computer that takes 30 seconds:

Lenovo Yoga C940
Processor: 10th Generation Intel® Core™ i7-1065G7 Processor (1.30 GHz, up to 3.90 GHz with Turbo Boost, 4 Cores, 8 Threads, 8 MB Cache)
RAM: 16.0 GB (15.7 GB usable)

Is there anything we can do to load Holistic w/o locking/chopping up the Chrome browser?  

Also I am wondering if work is being done to boost performance?

Thank you.

**Comment by ayushgdev** [comment]
Hello @nskaiser 
From the specifications of the intel based system, the holistic model loading should work just fine. The system is powerful enough to load it. It can be network issue with the system. 
- What is the OS that you are running?
- Would you please try with other chromium based browser such as Edge/Chromium on Intel system so that the issue can be narrowed down?
- Try on Safari on Mac M2 as well as other browsers. Essentially, the secondary browser testing on both the systems should be able to provide a better view at the issue

**Comment by nskaiser** [comment]
Thanks. It's Windows 11 and it doesn't matter if it's Edge or Chrome, the load time is the same.  Even using the simple code pen demo, https://codepen.io/mediapipe/full/LYRRYEw, will take a good 15 seconds to load.  It's not the network, which is fast, and we get similar results even w/ local models.  Mac M1/M2 is very fast, under 3 seconds to load.  A colleague has an older MacBook Air (~2019) and it takes a good 15 seconds to load on that too.  Are there any specs on hardware vs average load times? Or anything else we can be doing to fine-tune and increase the load time on the older hardware?

**Comment by ayushgdev** [comment]
Hello @nskaiser 
We have replicated the issue at our end. We did not find any difference among the Mac M1 and Windows 11 Intel i7-8th gen CPU, but we did find the model takes sometime (~15s) to load before the webcam starts on the codepen demo on both the systems. 
However, the loading is not due to the network call. The model files are downloaded within 2seconds. The issue lies with the initialisation of the model. Loading through web workers so as not to suspend foreground process on the page seems to be a solution, but it also has its flaws at this point (#2506). 
> When .send() is called the first time, we potentially initialize the graph. This means loading the models (which are in the packed assets) and starting up the wasm. For holistic, the models are... a bit large... there are three of them, in fact, and each are several megabytes in size.

This issue has already been reported in the past (refer  #1918 and #2506 ), however, we don't have any timeline for it yet since we are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), and upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

We would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications.

**Comment by nskaiser** [comment]
Thanks for the info. Are there any migration guides for people using the current Holistic model? The documentation on the new MP seems to be a bit light still. Thanks.

**Comment by ayushgdev** [comment]
@nskaiser The new APIs are complete independent from the older ones. Hence _migration_ would not be possible, rather re-coding will be required. Further, the holistic solution is yet to be released.
