### ISSUE TITLE
Couldn't find pb.h files

### ISSUE THREAD

**Issue by ChuyiZhong** [google/mediapipe#436]
//Take stream from /mediapipe/graphs/hand_tracking/hand_detection_desktop_live.pbtxt
// RendererSubgraph - LANDMARKS:hand_landmarks
#include "mediapipe/calculators/util/landmarks_to_render_data_calculator.pb.h"
#include "mediapipe/framework/formats/landmark.pb.h"

Couldn't find the two pb.h files. Are they been deleted or adapted to other existing files?

**Comment by kodosexe** [comment]
Any news on this? Having the same problem

**Comment by dgrnd4** [comment]
I am having the same problem as well

**Comment by dgrnd4** [comment]
@ChuyiZhong  have you solved it??

**Comment by Nvelu048** [comment]
@dgrnd4 @ChuyiZhong  @kodosexe 
Any update on this ?

**Comment by dgrnd4** [comment]
I had the same problem and if I’m not wrong I was wrong because I didn’t add the libraries in the build. 
If you want to compile a project, you must add all the libraries in the BUILD file. 
So: #include “.../AllFilesThatYouWantToAdd.pb.h” in the BUILD FILE
Let me know if you can solve in this way.

**Comment by ianni67** [comment]
It worked in my case. I had to add `"//mediapipe/framework/formats:landmark_cc_proto",` in the BUILD file.
Thank you!

**Comment by johnboiles** [comment]
In case anyone else ends up here who has the same issue as I did:

For me, the problem was that I was trying to run an iOS example in the iOS simulator, and it [looks like](https://github.com/google/mediapipe/blob/2b58cceec9953f0d97059934f0de85dd60adbe9b/mediapipe/examples/ios/iristrackinggpu/BUILD#L73) `//mediapipe/framework/formats:landmark_cc_proto` isn't included for simulator builds for the `iristrackinggpu` example. Just add `--ios_multi_cpus=arm64` to the build parameters:

```bazel run mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp --ios_multi_cpus=arm64```
