### ISSUE TITLE
FileNotFoundError: The path does not exist.

### ISSUE THREAD

**Issue by MHM-Rajpoot** [google/mediapipe#4364]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

windows

### MediaPipe Tasks SDK version

mediapipe 0.9.3.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand-Poses Recognition

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

```shell
when the app is build with pyinstaller it does not start just gives an error 

pyinstaller --onefile --noconsole --name=VirtualMouse --icon=mouse.ico mouse.py

when app is started it shows following error::

Traceback (most recent call last):
  File "mouse.py", line 107, in <module>
  File "mediapipe\python\solutions\hands.py", line 114, in __init__
  File "mediapipe\python\solution_base.py", line 264, in __init__
FileNotFoundError: The path does not exist.
```

### Describe the expected behaviour

```shell
The app should start working as invoked a camera open and start capturing hands gestures to move mouse on screen.
```

### Standalone code/steps you may have used to try to get what you need

```shell
capturing hands gestures to move mouse on screen.
```

**Comment by ayushgdev** [comment]
Hello @MHM-Rajpoot 
Would you please try the solution given in [this comment](https://github.com/google/mediapipe/issues/2677#issuecomment-1030701521).  Essentially the issue occurs if the path contains any Unicode characters not in ASCII. So if you can alter the path to a path which does not include the Unicode characters, this issue will not happen.

**Comment by MHM-Rajpoot** [comment]
Solution :: 

First I make copy of the folder  site-pakages to sitepackages ::
C:\Users\ali\AppData\Local\Programs\Python\Python310\Lib\sitepackages

Secondly I changed the path in file solution_base.py (line 261)

    # MediaPipe package root path
    
    #root_path = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-3])
    root_path = "C:/Users/ali/AppData/Local/Programs/Python/Python310/Lib/sitepackages"

    resource_util.set_resource_dir(root_path)
    validated_graph = validated_graph_config.ValidatedGraphConfig()

All Done !

**Comment by Yembot31013** [comment]
> I got it working with:
> 
> pyinstaller --add-data "C:\Users\USER\AppData\Local\Programs\Python\Python310\Lib\site-packages\mediapipe;mediapipe/" YOURSCRIPT.py
> 
> so just trace back your mediapipe module path and modify the command above.. you can also add "--onefile" if you want to just deploy one .exe

please @wulf11 did you added **;mediapipe/** at the end by intention ?

**Comment by wulf11** [comment]
@Yembot31013  Yeah in my case it is! 

For windows the format is:

`--add-data "<src>;.<dest>"`

For Unix, it is:

`--add-data "<src>:<dest>"`

So when I do:

`pyinstaller --add-data "C:\Users\USER\AppData\Local\Programs\Python\Python310\Lib\site-packages\mediapipe;mediapipe/" YOURSCRIPT.py`

The ; is used to separate the source and destination directories on Windows. The source is the path to the MediaPipe package on my system. The destination is the directory inside the distribution folder where you want these files to go. In my case, I've chosen mediapipe/ as the destination directory.

So, if your system is Windows, you should be able to use the command like that. It tells PyInstaller to take the MediaPipe files from the specified source directory and place them in a mediapipe directory inside your application's distribution folder. This might be necessary, because MediaPipe might have non-Python files that need to be included in the bundled application.
