### ISSUE TITLE
Where is mediapipe's pose key smoothing code? I want to know the implementation principle and code of this pose key point

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#4369]
Where is mediapipe's pose key smoothing code? I want to know the implementation principle and code of this pose key point

```
with mp_pose.Pose(
    static_image_mode=False,
    model_complexity=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as pose:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      # continue
      break

    image = cv2.flip(image, 1)

    start_time = time.time()

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = pose.process(image)

    # Draw the pose annotation on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    mp_drawing.draw_landmarks(
        image,
        results.pose_landmarks,
        mp_pose.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
```

pose_landmarks How do smooth_landmarks work? What smoothing algorithm was used?
Can you tell me how smooth handles the code?

**Comment by ayushgdev** [comment]
Hello @LMR2018 
The LandmarkSmoothingCalculator is used to reduce jitter in pose solution. The usage can be found in [pose_landmark_filtering.pbtxt file](https://github.com/google/mediapipe/blob/48cc96cf3c9d7e1eee20c36f90e7e2dcc497a6fb/mediapipe/modules/pose_landmark/pose_landmark_filtering.pbtxt#L94). Internally,  `process()` of solution_base.py is called from every mediapipe solution python implementation since it it the base class.  Once the [`add_packet_to_input_stream()`](https://github.com/google/mediapipe/blob/48cc96cf3c9d7e1eee20c36f90e7e2dcc497a6fb/mediapipe/python/solution_base.py#L355) is called, the control is transferred to C++ which processes these graphs and returns result to the python implementation.

**Comment by LMR2018** [comment]
@ayushgdev  LandmarkSmoothingCalculator is the use of EMA smoothing algorithm to deal with the key? If not, what smoothing algorithm is used?

**Comment by ayushgdev** [comment]
You can take a look at [landmark_smoothing_calculator.proto](https://github.com/google/mediapipe/blob/48cc96cf3c9d7e1eee20c36f90e7e2dcc497a6fb/mediapipe/calculators/util/landmarks_smoothing_calculator.proto) file. There are two algorithms available for smoothing- VelocityFilter and OneEuroFilter. OneEuroFilter is extensively used in MediaPipe solutions, for example in the upcoming Face Landmarker APIs.

**Comment by LMR2018** [comment]
@ayushgdev  I see a lot of platform keypoint smoothing only for single pose. What do I do if I want to achieve multiple keypoints smoothing on a single image?

**Comment by ayushgdev** [comment]
For using multiple smoothing algorithms, you will need to alter landmark_smoothing_calculator.cc file. The [`Open()`](https://github.com/google/mediapipe/blob/48cc96cf3c9d7e1eee20c36f90e7e2dcc497a6fb/mediapipe/calculators/util/landmarks_smoothing_calculator.cc#L389) of the calculator has mutually exclusive conditions for the supported calculators hence you cannot use multiple of them simultaneously. 
However, we would advice against altering the solutions to this extent since it brings a lot of instability and issues around the compilation and runtime errors like segmentation faults. 
Also, we are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), and upgrading the others.  You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by LMR2018** [comment]
@ayushgdev  I mean how to do One Euro key smoothing for multiple human key points on the same frame picture?

**Comment by ayushgdev** [comment]
Capturing multiple humans are not supported in our pose solution @LMR2018 . Out of scope applications in Page 2 in [Pose solution model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview) explicitly states that. 
Also, smoothing landmarks of multiple targets it is not supported by the landmarks smoothing calculator.  we do multiple pose landmarks detection by a for loop. However, the landmarks smoothing calculator utilises the timestamp to do the smoothing, so the for loop mess up the smoothing calculator. Hence, the calculator is not designed to work for multiple objects at all.

**Comment by LMR2018** [comment]
@ayushgdev  I tried to use yolov8 to detect the boxes of multiple people respectively, and then cut them out for loop to estimate mp keypoints, but the effect was poor. I don't know how to deal with the key points of multiple people and smooth the processing

**Comment by LMR2018** [comment]
> 嗨，landmarks_smoothing_calculator。请告诉我 python 如何使用

I also do not know the specific use, can not find the specific implementation of the code

**Comment by Joker789** [comment]
thank you，Have you resolved your shaking problem?

**Comment by LMR2018** [comment]
> 谢谢，你的抖动问题解决了吗？

not yet

**Comment by ayushgdev** [comment]
Hello @LMR2018 Would you please provide a minimal code of yolov8 usage with MediaPipe so that we can investigate more on the issue? The code provided does not include yolov8. So it is difficult to understand the problem. 
Also, if you can attach an output video of what you are getting, it would be great.

**Comment by mcdonasd1212** [comment]
@Joker789 did you find python solution to the shaking problem?
