### ISSUE TITLE
Importing DetectionResult throws error 

### ISSUE THREAD

**Issue by ayushgdev** [google/mediapipe#4377]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Mac OS 13 (Ventura)

### MediaPipe Tasks SDK version

0.9.3.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Object Detection

### Programming Language and version (e.g. C++, Python, Java)

Python 3.10.10

### Describe the actual behavior

In Object detection [python guide](https://developers.google.com/mediapipe/solutions/vision/object_detector/python#create_the_task), DetectionResult is imported as 
```python
DetectionResult = mp.tasks.components.containers.detections.DetectionResult
```
However, this throws error in Runtime
```shell
Traceback (most recent call last):
  File "/Users/username/obj_detector_livestream.py", line 6, in <module>
    DetectionResult = mp.tasks.components.containers.detections.DetectionResult
AttributeError: module 'mediapipe.tasks.python.components.containers' has no attribute 'detections'. Did you mean: 'Detection'?
```

### Describe the expected behaviour

The import should be successful

### Standalone code/steps you may have used to try to get what you need

```python
import mediapipe as mp
import cv2
from typing import List

DetectionResult = mp.tasks.components.containers.detections.DetectionResult
ObjectDetector = mp.tasks.vision.ObjectDetector
```

**Comment by pdg916** [comment]
Hi @ayushgdev. I had a lot of trouble with that issue too, but I've solved it! As far as I can tell, the error occurs in mediapipe 0.9.3, but not since mediapipe 0.10.0. Also, instead of "mp.tasks.components.containers.detections.DetectionResult", it should be "mp.tasks.components.containers.DetectionResult". 

Here are my settings
MacBook: M1 MacBook Air
MacOS: Monterey 12.6.4
Python Version: 3.10.11

`Python 3.10.11 (main, Apr  7 2023, 07:24:47) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe as mp
>>> mp.__version__
'0.10.0'
>>> mp.tasks.components.containers.detections.DetectionResult
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mediapipe.tasks.python.components.containers' has no attribute 'detections'. Did you mean: 'Detection'?
>>> mp.tasks.components.containers.DetectionResult
<class 'mediapipe.tasks.python.components.containers.detections.DetectionResult'>`

**Comment by kuaashish** [comment]
@pdg916,
Thank you for the confirmation. Could you please let us know if we can move the issue to close status as the issue has been resolved from your end.

**Comment by pdg916** [comment]
@kuaashish 
Yes, you can move the issue to close status as the issue has been resolved from my end.
Additionally, I found about 2~3 errors in the Mediapipe development documentation, where should I report them?
How can I become a Mediapipe contributor? Thank you!
