### ISSUE TITLE
example parameters for starting face_mesg

### ISSUE THREAD

**Issue by clogwog** [google/mediapipe#4407]
### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Compiler version

g++8

### Programming Language and version

c++

### MediaPipe version

current master branch

### Bazel version

6.1.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.1.1

### Describe the problem

```shell
I've been able to compile face_mesh_cpu and now i'm trying to run it.
It looks like i'm missing the parameters for supplying an image

    Failed to run the graph: ; Can't find file:

I tried:

 CC=gcc-8 CXX=g++-8 bazel run -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/face_mesh:face_mesh_cpu -- --input_image_path=/data/images/2023y05m10d_03h22m00s_1.jpg

but it replies with 

    ...
    INFO: Running command line: bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu '--input_image_path=/data/images/2023y05m10d_03h22m00s_1.jpg'
    ERROR: Unknown command line flag 'input_image_path'

is the example for face_mesh supposed to work ? how do i specify an image ?
```

### Complete Logs

```shell
$ CC=gcc-8 CXX=g++-8 bazel run -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11  mediapipe/examples/desktop/face_mesh:face_mesh_cpu
WARNING: /data/src/mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /data/src/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu
INFO: Elapsed time: 1.015s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu
E20230514 22:54:18.518496 13070 demo_run_graph_main.cc:155] Failed to run the graph: ; Can't find file:
```

**Comment by ayushgdev** [comment]
Hello @clogwog 
Face Mesh desktop solution does not support `input_image_path` as an argument. If you check the target `face_mesh_cpu` in [BUILD](https://github.com/google/mediapipe/blob/12ba644393fecf676c8d9f16ce7cc93cd762049a/mediapipe/examples/desktop/face_mesh/BUILD#L32) file, it includes demo_run_graph_main.cc. This file takes only [3 arguments](https://github.com/google/mediapipe/blob/12ba644393fecf676c8d9f16ce7cc93cd762049a/mediapipe/examples/desktop/demo_run_graph_main.cc#L37) at runtime- `calculator_graph_config_file`, `input_video_path` and `output_video_path`. 
In contrast, if you check the _now unsupported_ [autoflip solution](https://github.com/google/mediapipe/blob/master/docs/solutions/autoflip.md#running), its run command included `input_side_packets`. The autoflip solution uses [simple_run_graph_main.cc](https://github.com/google/mediapipe/blob/12ba644393fecf676c8d9f16ce7cc93cd762049a/mediapipe/examples/desktop/autoflip/BUILD#L44), which accepts [`input_side_packets`](https://github.com/google/mediapipe/blob/12ba644393fecf676c8d9f16ce7cc93cd762049a/mediapipe/examples/desktop/simple_run_graph_main.cc#L39) rather than `input_video_path`. There lies a distinction.

So you will need to modify `demo_run_graph_main.cc` in such a way that it accepts the input_image_path argument and then passes the supplied image to the graph. Or use simple_run_graph_main in face_mesh BUILD file. But it is suspected that will also require some modification in simple_run_graph_main.cc.

**Comment by clogwog** [comment]
Thank you @ayushgdev for showing where i can find the parameters. I think i understand now. So i adjusted the call to:

```
CC=gcc-8 CXX=g++-8 bazel run -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/face_mesh:face_mesh_cpu --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt  --input_video_path=/data/videos/event/sent/usb-046d_0825_1A0D6A40-video-index0_inf_20230508070637.mp4 --output_video_path=/data/bla.mp4
ERROR: --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt :: Unrecognized option: --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt
```

**Comment by ayushgdev** [comment]
I suspect this is because there is a prebuilt version of face_mesh_cpu in your local. Hence, run command is picking it up and throwing error with respect to the calculator_graph_config_file. It is a valid option.
Please try the following:
1. Clean the prebuilt binaries with `bazel clean --expunge`
2. Build and run the face mesh solution separately. Also, if you choose to use MESA_EGL_X11_HEADERS and similar macros, these are only valid with face_mesh_gpu, since they are GPU specific macros. I would suggest try. building and running the CPU version first since it eradicates lots of issues with the setup.
Please follow [this section](https://github.com/google/mediapipe/blob/master/docs/getting_started/cpp.md#option-1-running-on-cpu) of CPP installation first

**Comment by clogwog** [comment]
@ayushgdev thank you ! the cpu based version is working. 

it takes about 1 minute and 3 seconds to process a 30 second mp4 file. does the inference run on a scaled down version of the input video ? or does it just run slower when it has to run on larger video files ?
