### ISSUE TITLE
Landmarks Presence vs Visibility

### ISSUE THREAD

**Issue by DehTop** [google/mediapipe#4411]
### Description of issue (what needs changing)

Unclear description of Landmarks "presence" output

### Clear description

in https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python, we found the keywork "presence" in the landmark list at the end of the page, but there's no mention to its meaning anywhere. What this output is supposed to represent? Thanks!

**Comment by ayushgdev** [comment]
Hello @DehTop 
The documentation about the models can be found in the [model cards page](https://github.com/google/mediapipe/blob/master/docs/solutions/models.md). pose solution model card is available [here](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview). However, there is a caveat. Though presence is given as output in the landmark, it is not used anywhere in MediaPIpe. Please check [this comment](https://github.com/google/mediapipe/issues/1790#issuecomment-974957042) for more context.

**Comment by ButzYung** [comment]
Instead of visibility, can there be a `score` for each landmark telling the confidence of the prediction?

**Comment by ayushgdev** [comment]
@ButzYung score for each landmark will not be possible since it is not given as output by the model itself. When a model is trained by anyone, a dataset annotated with the landmarks of the human body's prominent feature/joints would be used. Hence the locations (x/y/z coordinates) are available as desired outputs for model to learn. If score for each landmark were to be given, it would require a complete new dataset where annotation will need to be done for each landmark with a confidence score. This seems infeasible as of now, however, provided we find enough traction from the community and a use case which specifically can leverage this effort to its potential, we shall include this feature as well.

**Comment by DBertazioli** [comment]
@ayushgdev thanks for your kind reply,  Couldn't find the model card myself. Now it makes sense.

**Comment by DehTop** [comment]
hello @ayushgdev ,

thanks for the kind reply, I must've missed the model card :) now it makes sense.
