### ISSUE TITLE
How to access BlazePose Full model

### ISSUE THREAD

**Issue by kylekam** [google/mediapipe#4431]
The BlazePose paper on arxiv.org states that there is a BlazePose Full model and a BlazePose Lite model. Is there a way to specify using the BlazePose Full model when using mediapipe? Also, which model is it implicitly? I'm trying to do this in python.

**Comment by ayushgdev** [comment]
Hello @kylekam 
The model can be downloaded from [here](https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task) and used as below or as suggested in the [docs](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python):
```python
model_path = '/absolute/path/to/downloaded/pose_landmarker_full.task'
options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.LIVE_STREAM,
    result_callback=print_result)

```

**Comment by kylekam** [comment]
Thanks for the quick response! Does this mean the model called by mediapipe.solutions.pose is the BlazePose Lite model?

**Comment by ayushgdev** [comment]
@kylekam By default, the **legacy solutions** load the full model. This can be inferred from the SwitchCalculator [here](https://github.com/google/mediapipe/blob/7c28c5d58ffbcb72043cbe8c9cc32b40aaebac41/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt#L22) since the default value of the model_complexity is 1 as passed from the [pose_landmark_cpu.pbtxt](https://github.com/google/mediapipe/blob/7c28c5d58ffbcb72043cbe8c9cc32b40aaebac41/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L47). (Notice PoseLandmarkCpu being used in [pose_tracking_cpu.pbtxt](https://github.com/google/mediapipe/blob/7c28c5d58ffbcb72043cbe8c9cc32b40aaebac41/mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt#L45) does not pass model_complexity. So pose_landmark_cpu calculator sets model_complexity to 1 by default and then passes on to the pose_landmark_model_loader.pbtxt).
In new Task APIs, you are free to provide any *.tflite file to be loaded.
