### ISSUE TITLE
How to build face_landmarks.tflite from mediapipe graph?

### ISSUE THREAD

**Issue by nguyennyssf** [google/mediapipe#4454]
### OS Platform and Distribution

macOS Ventura 13.2.1

### Programming Language and version

TFLite

### MediaPipe version

Newest from source with branch master

### Bazel version

5.2.0

### Android AAR (if android)

None

### Describe the problem

```shell
I just want to build model .tflite from the graph of face landmark.
Please help me or give me the instruction how to do that. Really appreciate for your helps
```

### Complete Logs

```shell
(Don't know how to build .tflite from .pbtxt of face_landmark)
```

**Comment by ayushgdev** [comment]
Hello @nguyennyssf 
TfLite models are artifacts which cannot be created from MediaPipe graphs. They can only be _used in_ MediaPipe graph like [here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmarks_model_loader.pbtxt) in face landmarks. These can be downloaded from the [Model cards page](https://github.com/google/mediapipe/blob/master/docs/solutions/models.md)/documentation page of the corresponding solution. For face landmark, the model can be found in [this section](https://developers.google.com/mediapipe/solutions/vision/face_landmarker#models).

**Comment by nguyencse** [comment]
Yes, thanks for your response @ayushgdev. In fact that I really really need to build an ios framework use the latest model of facemesh. I cannot build it on macOS Ventura with XCode 14.3 (macOS Ventura only supports XCode 14 and so I cannot downgrade version).
Really need help or could you give me an example of facemesh xcodeproj? I cannot install Tusi app as well due to macOS version.

**Comment by ayushgdev** [comment]
@nguyencse We are using MacOS Ventura 13.4 with Xcode 14.1. You can build the legacy solutions in Tulsi with this version setup. However, iOS APIs are getting _major_ upgrades since we are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), and upgrading the others. 
We are yet to release the iOS MediaPipe Task APIs and we would request you to wait for sometime. These APIs will be much simpler to use.

**Comment by nguyencse** [comment]
ok thanks @ayushgdev , I built a temp framework of my own in ios and waiting for your task api. Thank you
