### ISSUE TITLE
Train Palm Detector

### ISSUE THREAD

**Issue by yyqgood** [google/mediapipe#447]
Hello, I have a few questions:
1. I use mobilenet-ssd to train my palm detector and convert it to tflite format. Does the mediapipe framework support it?
2. Will there be a comprehensive calculators wiki instead of source code or examples?

**Comment by fanzhanggoogle** [comment]
Hi, thank you for the questions.
1. We currently don't provide the palm detector training pipeline in MediaPipe.
2. Great questions! We always have that on our roadmap, we'll prioritize this task as examples/calculators grows.

**Comment by yyqgood** [comment]
@fanzhanggoogle 
 Regarding the first question, I mean: I trained the palm detector myself. The mobilenet-ssd network I use. Does the mediapipe framework support it? Do calculators support it?

Should mediapipe give: the network structure currently officially supported, such as: commonly used classification networks and detection networks? This is good for developers' early decisions.

**Comment by mgyong** [comment]
@yyqgood  The calculators for the [hand tracking example](https://mediapipe.readthedocs.io/en/latest/hand_tracking_mobile_gpu.html) are written for SSD based detector system. If you are using mobilenet-ssd, it should technically work.

**Comment by fanzhanggoogle** [comment]
Hi @yyqgood ,
1) It should work, but you need to be careful about the [SSD anchor generation calculator](https://github.com/google/mediapipe/blob/de4fbc10e62001795741cb6d0200a17a94a29b0f/mediapipe/graphs/object_detection/object_detection_mobile_gpu.pbtxt#L76) and [converting output tensors to detections](https://github.com/google/mediapipe/blob/de4fbc10e62001795741cb6d0200a17a94a29b0f/mediapipe/graphs/object_detection/object_detection_mobile_gpu.pbtxt#L106) if you don't embed the post processing of anchors within the model (which is suggested for better performance because this part of ops will not be supported on GPU yet). 
2) That's very good suggestions! @mgyong We should provide the model architectures that we officially support, e.g. detector/classifier/segmentations. Ideally we tend to provide Mediapipe as an infrastructure that you can freely build on top of it for any models. For example, you can reuse all the inference calculators but add your customized calculator for decoding output tensors from new models/tasks. With the existing example/graphs/calculators, hopefully it can provide enough reference to create your own pipeline.
