### ISSUE TITLE
Bazel 6.1.1 doesn't build ios mediapipe 0.10.3 examples ( handtracking )  

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4742]
### OS Platform and Distribution

iOS

### Programming Language and version

oc

### MediaPipe version

0.10.3

### Bazel version

6.1.1

### XCode and Tulsi versions (if iOS)

14.3.1

### Android AAR (if android)

None

### Describe the problem

```shell
A bug happened! bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
```
 brew config 
HOMEBREW_VERSION: 4.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: d4444b563e24ac7c05a93121c464c02dfa04d44f
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d793577b4ad83222bb580364ff66b1c5fede26a6
Core tap last commit: 32 hours ago
Core tap branch: master
Core tap JSON: 30 Aug 08:57 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.3 build 1403
Git: 2.33.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1

### Complete Logs

```shell
ERROR: /Users/zhiyun/work/mediapipe_work/ios/mediapipe_gitee/mediapipe/graphs/hand_tracking/BUILD:69:23: Linking mediapipe/graphs/hand_tracking/hand_tracking_mobile_gpu_binary_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418-ST-9facee45ddd0/bin/mediapipe/graphs/hand_tracking/hand_tracking_mobile_gpu_binary_graph_text_to_binary_graph-2.params
```

**Comment by kuaashish** [comment]
@chensisi0730,

This issue is already known to us, And We are actively pursuing a solution to rectify the issue at hand. 
As a potential solution, I kindly request that you clone the Bazel repository and implement the fix that the community has identified, as outlined [here](https://github.com/Evizero/bazel). 

For a more comprehensive grasp of the matter, I advise you to consult this ongoing discussion [thread](https://github.com/google/mediapipe/issues/4296#issuecomment-1694920439). Thank you
