### ISSUE TITLE
How do I learn?

### ISSUE THREAD

**Issue by Zumbalamambo** [google/mediapipe#484]
The entire framework remains like a BlackBox. There is not a definite guideline, a path which defines how to make use of the functions that Mediapipe offers. Please improvise the documentation.

**Comment by Cubbee** [comment]
As a fellow user, I would recommend reading comments preceding every Calculator class and also test cases. They contain a lot more info compared to documentation.

**Comment by eknight7** [comment]
Hi! We would be happy to know more about how we can improve the documentation. In the meantime, please see if the following resources are useful:

* [Videos](https://www.youtube.com/channel/UCObqmpuSMx-usADtL_qdMAw) giving an overview of MediaPipe.
* Try it out on the web before installing, [see web demos](https://mediapipe.readthedocs.io/en/latest/install.html).
* [Installing](https://mediapipe.readthedocs.io/en/latest/install.html) MediaPipe.
* [Tutorials](https://mediapipe.readthedocs.io/en/latest/examples.html) to build a MediaPipe application from scratch for different platforms. This also has links to all demo applications.
* [Concepts](https://mediapipe.readthedocs.io/en/latest/concepts.html) in MediaPipe. More details are also available in this [paper](https://arxiv.org/abs/1906.08172).

Feel free to open an issue for any specific questions. Existing issues tagged [good first issue](https://github.com/google/mediapipe/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22good+first+issue%22+) and [general](https://github.com/google/mediapipe/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ageneral+) are good ones to check out as well.

**Comment by bhack** [comment]
I think that what Is required It Is really more documentation about customize/finetune or plug your own trained model and how to consume/handle intermediate results for your custom app (keypoints, bboxs etc..)

**Comment by mgyong** [comment]
@bhack Pls check some of the tutorials in [awesome-mediapipe](https://mediapipe.org)

**Comment by 5310** [comment]
This issue was just closed and all, but as someone who wants to try and use Mediapipe inside web apps, I   must confess that I still have no clues as to where to start learning. 

[awesome-mediapipe](https://github.com/mgyong/awesome-mediapipe/) doesn't even have any links to tutorials to run Mediapipe on the web; there is one [web example link under TFLite](https://github.com/Mach1Studios/m1-web-spatialaudioplayer), and while [impressive](https://demos.mach1.tech/#Facetracking-SpatialPlayer), it doesn't really help abate my confusion at all. 

Even the [Google Dev article](https://developers.googleblog.com/2020/01/mediapipe-on-web.html) that previewed Mediapipe running on the web doesn't help much. It has a bunch of similarly impressive demoes and a brief overview on how they were compiled to WebAssembly which I can only assume is helpful to people who already have an idea of how these things work. These too only run on viz.mediapipe.org, and not standalone like even the Mach1 demoes do. And of course, nothing instructional.

Are there any tutorials for running Mediapipe in web app? Or is the WASM pipeline too new to expect them right now?

**Comment by Zumbalamambo** [comment]
@5310 very bad documentation
