### ISSUE TITLE
Hand tracking with gloves, would like to offer data. 

### ISSUE THREAD

**Issue by brvanvoo** [google/mediapipe#4870]
I noticed that the hand tracking does not work well when the hands are wearing gloves, specifically the kinds of gloves used by healthcare professionals which often come in a variety of colors.  

Is there a software fix for this, or is this a data training and labeling problem?

I have considerable use for the hand tracker in the presence of gloves and would like to work with you to address this issue.  Please let me know if we can collaborate on this.

**Comment by kuaashish** [comment]
Hi @brvanvoo,

This aspect is beyond the scope of the **Hand Landmark** as explicitly outlined in the [model card](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20Hand%20Tracking%20(Lite_Full)%20with%20Fairness%20Oct%202021.pdf) on **page 2** under the section titled "**Out-of-Scope Applications.**":

_- Predicting hand landmarks with gloves or occlusions. For example when the hand is holding objects or there is decoration on the hand including jewelry, tattoo and henna._

Because, our **Hand Landmark** model is trained specifically for detecting exposed hands. We think **MediaPipe Model Maker** is a tool that can modify existing machine learning (ML) models to fit your data and applications as guided [here](https://developers.google.com/mediapipe/solutions/model_maker) and can be adjusted to meet your specific needs. 

Right now, you can use MediaPipe Model Maker to train customised models for **Object detection, Image classification, Gesture recognition, and Text Classification** not for **Hand Landmark** as outlined [here](https://developers.google.com/mediapipe/solutions/guide#available_solutions). For now, we think you'll need to train a similar machine learning model to meet your specific needs. Thank you
