### ISSUE TITLE
hair segmentation using webcam on cpu

### ISSUE THREAD

**Issue by ashwath98** [google/mediapipe#489]
what changes do you suggest to make the hair segmentation graph compatible with cpu?

**Comment by mcclanahoochie** [comment]
Ideally, you simply get rid of all the '_GPU' from stream tags in the **graph** 
( i.e.  IMAGE_GPU-->IMAGE  &  TENSORS_GPU-->TENSORS ).

Once you do this, all streams will be on CPU, and run in CPU path through each calculator... except for the [RecolorCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/recolor_calculator.cc), which has no CPU path.

Everything is setup inside the recolor calculator, but the RenderCPU isn't implemented, so that is what you would have to add yourself. 
We have this as a TODO as well, so it will eventually happen, but in the meantime, you are welcome to try (just follow what the gpu does, except with opencv).

**Comment by ashwath98** [comment]
Okay. Will try out your solution.
Also If I wanted to change the input format from live webcam to a static video for the Desktop GPU implementation. What should I change?

Thanks

**Comment by mcclanahoochie** [comment]
please use the extra flags
[here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc#L40) and [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc#L36)

`--input_video_path=/full/path/to/movie.mp4`

**Comment by ashwath98** [comment]
Thank you

**Comment by mcclanahoochie** [comment]
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt
