### ISSUE TITLE
Unable to install MediaPipe on Mac pip install -q mediapipe==0.10.0

### ISSUE THREAD

**Issue by jeff-orthober** [google/mediapipe#4936]
### OS Platform and Distribution

MAC Ventura 13.5 Intel Core 8

### Compiler version

pip --version 20.3.4

### Programming Language and version

python3 --version 3.12.0

### MediaPipe version

20.3.4

### Bazel version

bazel 6.4.0-homebrew

### Android AAR (if android)

None

### Describe the problem

Can not install 0.10.0 Python

### Complete Logs

```shell
pip install -q mediapipe==0.10.0

ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: none)
ERROR: No matching distribution found for mediapipe==0.10.0
```

**Comment by jeff-orthober** [comment]
This also fails, saw that there are a few new releases up to 0.10.7, etc

python3 -m pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

**Comment by jeff-orthober** [comment]
Ok had to downgrade python3 to 3.11.6 using pyenv.  wow. Hope this helps others.

**Comment by kuaashish** [comment]
Hi @jeff-orthober,

The build has failed due to the current lack of support for Python Version 3.12.*. Please note that MediaPipe supports Python versions 3.9 to 3.11 across all platforms, as outlined in the provided [guide](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). We recommend ensuring the compatibility of Python, Bazel, and other dependencies before proceeding with the MediaPipe build.

For now, We are closing this issue as it has been resolved on your end. Thank you
