### ISSUE TITLE
when i build handtracking:handtracking-cpu ,some errors occur . error code:c2664

### ISSUE THREAD

**Issue by lneverd** [google/mediapipe#4994]
### OS Platform and Distribution

Windows10

### Compiler version

vc++15

### Programming Language and version

c++15

### Installed using virtualenv? pip? Conda?(if python)

miniconda 3 python 3.8.16

### MediaPipe version

v0.10.8

### Bazel version

6.4.0

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.10

### Describe the problem

helloworld.exe have normally ouput.but can not build handtracking-cpu

### Complete Logs

```shell
when i run this command bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://miniconda3//envs//hand//python.exe" mediapipe/examples/desktop/hello_world  it builds successfully and run it successfully.
But when i run this command bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\miniconda3\\envs\\hand\\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu 
i can not build successfully,and then output information of erors are  
mediapipe/calculators/core/previous_loopback_calculator.cc(128): error C2664: “void 
mediapipe::api2::OutputShardAccess<ValueT>::Send(std::unique_ptr<T,std::default_delete<_Ty>>)”: can not 
convert parameter 1 from “mediapipe::api2::PacketBase” to “mediapipe::api2::Packet<T> &&”
```

**Comment by kuaashish** [comment]
Hi @lneverd,

Based on the provided descriptions, it seems that the build failure may be due to the use of unsupported versions of dependencies. Kindly refer to the Windows installation [guide](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows) and ensure that you are using the recommended version of Microsoft Visual C++ 2019, as the current version in use is Visual C++ 15.

Furthermore, please make sure to use the supported version of Bazel, specifically version 6.1.1 as indicated [here](https://github.com/google/mediapipe/blob/master/.bazelversion). The current version in use is 6.4.0, which is not yet supported. Kindly implement these changes, consult the documentation for installing MediaPipe on Windows, and verify if the issue persists.

Additionally, you could inform us of any similar errors encountered after applying these recommendation.

Thank you
