### ISSUE TITLE
Mediapipe hand tracking, get individual landmarks for each frame

### ISSUE THREAD

**Issue by pranayagra** [google/mediapipe#502]
Currently, I have mediapipe set up to where I can pass it a bunch of frames and it will use multi-hand-tracking to create a .data file with the bounding box and 21 landmarks for each hand. However, I currently only get either all the landmarks or none of the landmarks (if any 1 landmark feature is not generated by mediapipe, I get no landmarks from mediapipe). Wondering where I can see the landmark information for each frame in mediapipe, as I would like to save the % of times I get a certain landmark feature from a sample video. 

This is a snippet of the code that I believe is getting landmarks from mediapipe:

```
LOG(INFO) << "Saving Features and Landmarks";
  mediapipe::Packet multi_hand_rects_packet;
  mediapipe::Packet multi_hand_landmarks_packet;
  if (multi_hand_rects_poller.Next(&multi_hand_rects_packet) && multi_hand_landmarks_poller.Next(&multi_hand_landmarks_packet)) {
    //LOG(INFO) << "Processing frame: " << counter;
    if (!multi_hand_rects_packet.IsEmpty() && !multi_hand_landmarks_packet.IsEmpty()) {
      std::vector<mediapipe::NormalizedRect> multi_hand_rects = multi_hand_rects_packet.Get<std::vector<mediapipe::NormalizedRect>>();
      std::vector<::mediapipe::NormalizedLandmarkList> multi_hand_landmarks = multi_hand_landmarks_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();

...
}}
```

**Comment by eknight7** [comment]
> However, I currently only get either all the landmarks or none of the landmarks (if any 1 landmark feature is not generated by mediapipe, I get no landmarks from mediapipe). 

Actually, this is by design in the [multi-hand landmark graph](https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_mobile_gpu.html#multi-hand-landmark-subgraph). The subgraph contains a `FilterLandmarksCollection` node which outputs a set of landmarks for a hand instance if and only if hand presence for that hand detection is `true`.

The fact that the set of the landmarks either contains all 21 or none is because of the design of the [hand landmark subgraph](https://mediapipe.readthedocs.io/en/latest/hand_tracking_mobile_gpu.html#hand-landmark-subgraph) which outputs a collection of landmarks for the hand.
@fanzhanggoogle can explain more about why only all or none of the landmarks are available (probably due to the model).

> Wondering where I can see the landmark information for each frame in mediapipe, as I would like to save the % of times I get a certain landmark feature from a sample video.

If I understand correctly, you want to save the % of times one of the 21 landmark features is missing from a sample video. That depends on whether getting a partial set of landmarks is possible.
