### ISSUE TITLE
how does z define the depth information of the key point?

### ISSUE THREAD

**Issue by lucker26** [google/mediapipe#5075]
The output coordinates of hand key points are x,y,z y and z, where x and y can be multiplied by the width and height of the image to get the position of the key point in the image, so how does z define the depth information of the key point? Is it the distance between the key point and the camera or the distance between the key point and the wrist?

**Comment by kuaashish** [comment]
Hi @lucker26,

The hand model uses a method called "scaled orthographic projection," which combines orthographic projection with scaling to imitate perspective. This assumes that all points on a 3D object are approximately at the same distance from the camera.

The reason for using this method is that it closely approximates perspective, especially when the depth variation along the line of sight is small compared to the fixed average depth. This helps prevent distortion of objects at a distance due to perspective, allowing for uniform scaling instead.

The model predicts a relative depth (z) based on the average depth of a "typical hand" (in scenarios like holding a phone with one hand). The range of z is not limited, but it scales proportionally with x and y through weak projection and uses the same units as x and y.

There is a central landmark point (wrist) to which all other landmark depths are relative. These depths are normalized using weak projection with respect to x and y coordinates.

Additionally, we recommend that you please read through [this](https://github.com/google/mediapipe/issues/742) thread for a better understanding.

Thank you
