### ISSUE TITLE
Facemesh for mobile devices

### ISSUE THREAD

**Issue by tttzof351** [google/mediapipe#508]
Yesterday google released new facemesh model as part of mediapipe, but for mobile devices it is not available. Will it be added later?

https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html
> These packages are also available as part of MediaPipe, a library for building multimodal perception pipelines:

**Comment by mgyong** [comment]
@tttzof351 We [released a version of the face mesh for TF.js](https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html). What's your use case for the mobile version? 

We are looking to release this. Timeline is undecided

**Comment by bhack** [comment]
@mgyong I have a more general question. Is there any planned activity in the roadmap to enable more cross platform examples instead of having to reimpl for TPU, JS, Mobile and Desktop?

**Comment by mgyong** [comment]
@bhack Most of our main examples like Multi hand tracking, object detection is cross platform: mobile (iOS, android), desktop (C++). TPU(Coral) & TF.js  face mesh/handpose examples are not cross platform due to implementation reasons and are the exception. For example, TPU(Coral) requires quantized model for Coral EdgeTPU and the TF.js face mesh/handpose examples are pure js for pre-processing and post processing. 

Our general plan has always been to enable MediaPipe for cross platform on-device inference pipelines
