### ISSUE TITLE
Is there any stable version of python and pip to train common object detection model?

### ISSUE THREAD

**Issue by ly15927086342** [google/mediapipe#5080]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows10

### Solution

Object Detector

### Programming Language and version

Python3.11

### Describe the actual behavior

install mediapipe-model-maker fail

### Describe the expected behaviour

install mediapipe-model-maker success

### Standalone code/steps you may have used to try to get what you need

```shell
Recently, I try to train my own object detection model as the example in https://developers.google.com/mediapipe/solutions/customization/object_detector. I tried it with M1, Python3.10 and Python3.9, neithor of them success, with the problem of mediapipe-model-maker installation. And then, I tries it with windows10, Python3.11, but still failed. I searched related issue in this repo, which can not solve my problem.
I just want to know is there any officially suggested  version about Python, pip and the mediapipe-model-maker and so on, which has been proved to be working. Windows10 and M1 will help me a lot.
Expect for your apply!
```

**Comment by kuaashish** [comment]
Hi @ly15927086342,

Unfortunately, you won't be able to install the latest version of MediaPipe model maker (0.2.1.3) because tensorflow-text stopped supporting Windows, Aarch64, and Apple Macs since version 2.11 (refer to https://github.com/tensorflow/text/issues/1140 and https://github.com/tensorflow/text#a-note-about-different-operating-system-packages).

To install the latest version, you can try building the tensorflow-text package from their Github if you are using Windows. If you are not using the text_classifier task in Model Maker (which requires tensorflow-text), you can attempt to install it using pip with the "--no-deps" parameter. You would need to install each requirement independently, excluding tensorflow-text. Note that this is a workaround suggested by a user here: https://github.com/tensorflow/text/issues/1206.

Alternatively, you can consider using Windows Subsystem for Linux (WSL) or the Colab cloud environment to install these packages in a Linux environment.

However, based on our analysis, you can install mediapipe-model-maker-0.1.0.2, which is based on an older version of MediaPipe (0.9.0.1) without any issues but this is not our recommended approach.

Thank you

**Comment by ly15927086342** [comment]
I have train my model by Colab, it works will, thank you!
There is another question. After export my model.tflite, the connect is closed. So is there any approach for me to import the model, and contine to do the model quantization step? 
Hope for your apply!

**Comment by kuaashish** [comment]
@ly15927086342,

Thank you for confirming. Kindly grant us some time to internally review the matter. We will inform you of the feasibility from our perspective.

**Comment by kuaashish** [comment]
Hi @ly15927086342,

I attempted to replicate the scenario in Colab. It appears that running the demo with a smaller dataset was successful. After importing the customized TensorFlow Lite model, the quantization example codes executed smoothly without runtime interruptions. 

In your situation, if you aim to train the model with a larger dataset without encountering timeouts, you may consider extending the runtime duration by implementing the following suggestions:

**Run the following code in the console and it will prevent you from disconnecting.**

**Ctrl + Shift + I to open the inspector view. Then go to the console.**

```
function ClickConnect(){
    console.log("Working");
    document.querySelector("colab-toolbar-button#connect").click()
}
setInterval(ClickConnect,60000)
```

 Reference: [[How can I prevent Google Colab from disconnecting?](https://stackoverflow.com/questions/57113226/how-can-i-prevent-google-colab-from-disconnecting)](https://stackoverflow.com/questions/57113226/how-can-i-prevent-google-colab-from-disconnecting).


Thank you!!
