### ISSUE TITLE
Forecast for the update of the 'Holistic Solution' in the new versions

### ISSUE THREAD

**Issue by ThiruSS** [google/mediapipe#5101]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu

### Task name (e.g. Image classification, Gesture recognition etc.)

Holistic

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Holistic solution 

### Describe the expected behaviour

Holistic solution updated in the short term

### Standalone code/steps you may have used to try to get what you need

```shell
```

### Other info / Complete Logs

First of all, congratulations on this remarkable project.

Regarding the 'holistic' solution, I noted on your website the announcement: "An upgraded version of this MediaPipe Solution is coming soon!" 
It appears this message has been displayed for several months now. I am eager to learn whether there are plans to launch an enhanced, GPU-compatible version of 'holistic'. 
While I understand precise timelines might be challenging, could you provide a general indication of whether any progress in this area is anticipated in either the first or second quarter of the year?

Thank you for your time and consideration.

**Comment by kuaashish** [comment]
Hi @ThiruSS,

The newly upgraded Holistic code has been completed. Primarily, it will be included in the upcoming release, initially planned for mid-January. However, due to a pipeline issue, the release has been rescheduled for, or within, the second week of February. Unfortunately, We are unable to provide an exact date at this time. Nevertheless, we anticipate that it will support GPU, similar to our other Python Task APIs.

Thank you!!

**Comment by florianbaer** [comment]
Any updates on this? Further delay expected, if I may ask ;)

**Comment by Winton-Long** [comment]
Any further news on this model update?
