### ISSUE TITLE
Segfault ( EXC_BAD_ACCESS(code=1) ) on apple silicon with -c dbg

### ISSUE THREAD

**Issue by tonystratum** [google/mediapipe#5163]
I need to debug my code (specifically [demo_run_graph_main.cc](https://github.com/google/mediapipe/blob/v0.10.9/mediapipe/examples/desktop/demo_run_graph_main.cc)), therefore building with `bazel build -c dbg`. The app segfaults on [ParseTextProto](https://github.com/google/mediapipe/blob/4237b765ce95af0813de4094ed1e21a67bad2a5f/mediapipe/framework/port/parse_text_proto.h#L27). With `-c opt` no segfault.

Why does it happen?
How to properly build for debug?
Why do we always need `-c opt` and how is it different to `-c dbg`?

Sonoma 14.3.1 on M2 max
Apple clang 15.0.0
bazel 6.1.1 (bazelisk)

**Comment by ayushgdev** [comment]
Hello @tonystratum 
Which desktop app are you trying to build and debug? We have tried to reproduce the issue with an example app  that includes demo_run_graph_main.cc in its deps (the face detection cpu app). But the app did indeed build successfully at our end. 
Though we could not test on M2 Max due to device unavailability, we did testing on Mac M1 Pro which has silicon ARM based architecture. So we expect similar performance and libary support. 

Could you please try running the following command for face detection and see if that builds successfully?
```shell
bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_detection/face_detection_cpu
```

**Comment by tonystratum** [comment]
@ayushgdev thanks for the support, fixed it. It was a version mismatch with protobuf, I had a newer version installed.
