### ISSUE TITLE
Removal of Mediapipe 0.8.9.1 from pypi

### ISSUE THREAD

**Issue by JeyandranathSO** [google/mediapipe#5224]
Removal of Mediapipe 0.8.9.1 creates issue with legacy systems. Can we please restore it ?

**Comment by kuaashish** [comment]
Hi @JeyandranathSO,

Please grant us some time to gather information on this matter. We will inform you whether it is possible or not shortly.

Thank you!!

**Comment by kuaashish** [comment]
Hi @JeyandranathSO,

Following internal discussions, we are gradually removing older versions containing legacy solutions due to storage limitations on PyPi. Consequently, restoring removed versions isn't feasible. However, you can still construct the MediaPipe Python package from its source using the guide provided [here](https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md#building-mediapipe-python-package). Please note that the nearest upgraded version available is v0.8.10.

Thank you!!

**Comment by schmidt-sebastian** [comment]
Sorry - we do not keep an archive of the files and we are hitting our storage quota constantly, so we have to purge old releases. I am afraid we cannot help at this point.
