### ISSUE TITLE
aarch64 wheels are missing from PyPI starting with 0.10.10

### ISSUE THREAD

**Issue by ddelange** [google/mediapipe#5239]
### OS Platform and Distribution

linux aarch64 (arm processors)

### Programming Language and version

cpython

### MediaPipe version

0.10.10+

### Android AAR (if android)

None

### Describe the problem

0.10.9 had aarch64 wheels on PyPI - 0.10.10 and 0.10.11 do not

search for `aarch64.whl` on these pages:

https://pypi.org/project/mediapipe/0.10.9/#files ✅
https://pypi.org/project/mediapipe/0.10.10/#files ❌
https://pypi.org/project/mediapipe/0.10.11/#files ❌

this has consequences for all linux boxes running on aarch64 processors, and for building linux docker images on arm macs

### Complete Logs

```shell
```

**Comment by kuaashish** [comment]
Hi @ddelange,

Due to testing failure on Aarch64, particularly on Raspberry Pi, we have postponed the release of the Aarch64 wheel since version 0.10.10 and 0.10.11. However, once the issues are resolved, we intend to release the Aarch64 wheel files. Currently, we are assigning this matter to our team for more updates. We will keep you informed of any updates as they arise.

Thank you!!

**Comment by ddelange** [comment]
shouldn't such issues be a release blocker?

**Comment by schmidt-sebastian** [comment]
Yes - but we had to release new features on our other platforms unfortunately.

**Comment by schmidt-sebastian** [comment]
This will be resolved in our next release.
