### ISSUE TITLE
MediaPipe GPU support in PyPi package

### ISSUE THREAD

**Issue by JC3** [google/mediapipe#5263]
### MediaPipe Solution (you are using)

Pose Landmarker

### Programming language

python

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

Enabling GPU support seems *possible* (I think?) e.g. https://github.com/google/mediapipe/issues/4410 but exceedingly cumbersome. Can the version of mediapipe on PyPi be made to have GPU support some day?

### Who will benefit with this feature?

Everybody

### Please specify the use cases for this feature

Pose landmarking

**Comment by kuaashish** [comment]
Hi @JC3,

Could you kindly inform us of the platform you require GPU support for? GPU support has been available since version 0.10.8 through our pip package, but currently it's only compatible with macOS and regular Linux operating systems. You can activate GPU support for Pose Landmarker by using the following code snippet(See [#4988](https://github.com/google/mediapipe/issues/4988)):

`base_options = python.BaseOptions(model_asset_path='pose_landmarker_lite.task', delegate=python.BaseOptions.Delegate.GPU)`

This ensures that the example runs smoothly on the GPU. If you need support for other operating systems such as Windows, we kindly ask you to submit a new [feature request](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml), and Once you raise the request, we will share it with our team for further evaluation and discussion. Based on the demand and deliberation, we will proceed with implementing the feature.

Thank you!!

**Comment by JC3** [comment]
Awesome, this works for me. Thank you very much.

**Comment by JC3** [comment]
Btw, docs should probably be updated: https://developers.google.com/mediapipe/api/solutions/python/mp/tasks/BaseOptions states GPU only works on Ubuntu.

**Comment by jordanmuraskin** [comment]
I have tried to get working on a Google Colab Notebook with GPU support, but receive the following error: 
`RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL`

Here is the task setup:
```
def get_detector():
  base_options = python.BaseOptions(model_asset_path='pose_landmarker.task',
                                    delegate = python.BaseOptions.Delegate.GPU)
  options = vision.PoseLandmarkerOptions(
      base_options=base_options,
      output_segmentation_masks=False,
      running_mode=VisionRunningMode.VIDEO)
  detector = vision.PoseLandmarker.create_from_options(options)
  return detector
```

Has anyone else been able to get GPU to work on colab?

**Comment by hunter2009pf** [comment]
> Btw, docs should probably be updated: https://developers.google.com/mediapipe/api/solutions/python/mp/tasks/BaseOptions states GPU only works on Ubuntu.

so how to make mediapipe support windows10 on GPU calculation?

**Comment by Gnoot01** [comment]
Hi, @kuaashish is GPU for Mediapipe Pose supported on WSL2 Ubuntu then?

**Comment by davimedio01** [comment]
> I have tried to get working on a Google Colab Notebook with GPU support, but receive the following error: `RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL`
> 
> Here is the task setup:
> 
> ```
> def get_detector():
>   base_options = python.BaseOptions(model_asset_path='pose_landmarker.task',
>                                     delegate = python.BaseOptions.Delegate.GPU)
>   options = vision.PoseLandmarkerOptions(
>       base_options=base_options,
>       output_segmentation_masks=False,
>       running_mode=VisionRunningMode.VIDEO)
>   detector = vision.PoseLandmarker.create_from_options(options)
>   return detector
> ```
> 
> Has anyone else been able to get GPU to work on colab?

Have same problem here!!
