### ISSUE TITLE
Selfie Segmentation vs Image Segmentation

### ISSUE THREAD

**Issue by Honya2000** [google/mediapipe#5312]
I’m wondering what the difference in quality and performance between Selfie Segmentation and Image Segmentation solutions. As far as i understood last one is using new Tasks Api. But how is this better? Problem is i didn’t find any documentation or examples related to new c++ vision tasks. So not sure what the difference, and what will be changed when i switch to hew api.

**Comment by kuaashish** [comment]
Hi @Honya2000,

Regarding the difference between the legacy and new versions, we currently lack concrete data to provide you with a comparison. Due to limited bandwidth, this is not our top priority at the moment.

As for your second query, we regret to inform you that we do not have documentation available for the new C++ vision feature yet, as it is still in progress. It may take additional time before it becomes available to the public. Unfortunately, we cannot commit to a specific timeline for its release.

Thank you!!
