### ISSUE TITLE
When I set max_vec_size=2 in Multi-Hand Detection Subgraph and min_size = 2 in multi_hand_tracking_mobile_graph, I get 3hands results.

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#555]
https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_mobile_gpu.html
It says if max_vec_size = 2, the Multi-Hand Detection Subgraph will clips the size of the input vector to the provided max_vec_size. It means if the scene has 5 hands, the Multi-Hand Detection Subgraph will only output 2 hands.
Also if min_size = 2, the multi_hand_tracking main graph will run the Multi-Hand Detection Subgraph only when NormalizedRect's size fewer than 2.
But when I set max_vec_size = 2 and min_size = 2, and the scene has about 5 hands, I will get 3 hands  results.
I don't know why. It will cause exception in my project.

**Comment by eknight7** [comment]
Hi @Sara533, thank you for sharing this issue, this is unintended behavior. Let's investigate further to understand if this is an artifact of the graph configuration or a bug in the app.

> But when I set max_vec_size = 2 and min_size = 2, and the scene has about 5 hands, I will get 3 hands results.

If I understand correctly, the app is tracking 3 hands instead of 2 hands, even though the `max_vec_size = 2`, i.e. the maximum number of hands detected is supposed to be `2`. Can you tell us more about when this happens? Specifically:
1. Are the 3 results overlapping in any way?
2. What happens if you tweak `min_similarity_threshold` in the `AssociationNormRectCalculator` in the [multi_hand_tracking_mobile.pbtxt](https://github.com/google/mediapipe/tree/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt) file? Does that improve the results?
3. Does tweaking `min_suppression_threshold` in the `NonMaxSuppressionCalculator` in the [multi_hand_detection.pbtxt](https://github.com/google/mediapipe/tree/master/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_detection_gpu.pbtxt) improve the results?
4. Could you please share a screenshot or a video to reproduce and debug this issue? We can debug it on [desktop](https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html) using a pre-recorded video.

**Comment by MitchDtown** [comment]
Hi we are experiencing this behaviour as well.
In some cases the Handtracking detects 3 even though it is limited to 2 Hands maximum.

![3Hands](https://user-images.githubusercontent.com/58523261/90783311-306a4f00-e300-11ea-9d94-da4fd3861ff4.jpeg)

In this case we use the X and Y Coordinates for the two hands (21 *2 * 2 = 84) plus  the X and Y coordinate for the Lip Landmark (in total 86 Landmarks). But somehow it detects a third hand and we get 128 Landmarks (86+42 from the third hand).

**Comment by eknight7** [comment]
Hi @MitchDtown Thank you for reporting the error. Can you share a video on which this error occurs to help us debug the issue? Thanks.

**Comment by eknight7** [comment]
Hi @MitchDtown,
Can you please check if the latest release of MediaPipe still causes this issue for you? Thank you.

**Comment by eknight7** [comment]
Hi @MitchDtown, since the issue has been inactive, we will close it. Please feel free to reopen it for further quesitions. Thank you!
