### ISSUE TITLE
Is GPU support planned for other Desktop targets?

### ISSUE THREAD

**Issue by samsieber** [google/mediapipe#574]
Is GPU support planned for other desktop targets (ie. OSX and Windows)? I'd love to use this in an app I'm working on for some extra features, but CPU only makes it a little too slow for my needs.

On a more general note, is there a roadmap for features that'll be added before version 1.0?

**Comment by pablovela5620** [comment]
I'd love to know this as well, especially for windows since being limited to just linux for gpu support is less than ideal

**Comment by mcclanahoochie** [comment]
GPU support for OSX is indeed planned and will be released eventually, but unfortunately no date soon is set yet. 
One upside is the gap between current iOS GPU support and desktop OSX CPU support isn't huge, and could be solved by determined users.
Native Windows support is being considered as well, but is also not a priority at the moment.

**Comment by pablovela5620** [comment]
Thanks for clarifying @mcclanahoochie. I think an assumption I had made is that mediapipe for desktop targets is only supported by Nvidia GPUs which is why I assumed OSX support would be later in the pipeline compared to Windows. Does this mean that Mediapipe supports AMD GPUs commonly found in macs? or is it external GPU's that are being targeted. I would assume it to be the former

**Comment by mcclanahoochie** [comment]
Currently the only requirement is OpenGL ES 3.1+ support on Android/Linux, and 'Metal' support on Apple [iOS] devices.  There is no check for AMD or Nvidia. 

On Linux, I expect if your AMD machine can pass this test then it would work:
https://mediapipe.readthedocs.io/en/latest/gpu.html#desktop-gpu-linux

On OSX, this is hindered by the fact Apple has deprecated OpenGL in favor of their Metal api, so the Apple desktop support would likely be very similar to iOS, because we can't rely on OpenGL ES being available.

**Comment by pablovela5620** [comment]
Great, thank you for the response!

**Comment by time4Wiley** [comment]
So the closing means macOS Metal support is done? If not, is there a planned date?

**Comment by jfdream** [comment]
So the closing means macOS Metal support is done? If not, is there a planned date?

**Comment by ROBYER1** [comment]
> GPU support for OSX is indeed planned and will be released eventually, but unfortunately no date soon is set yet. One upside is the gap between current iOS GPU support and desktop OSX CPU support isn't huge, and could be solved by determined users. Native Windows support is being considered as well, but is also not a priority at the moment.

As a developer using Mediapipe on a range of platforms both desktop MacOS/Windows and Android/IOS, I am very interested in seeing GPU support get added for Windows and MacOS.

Is there a public roadmap or anywhere to see the status of these features being added? Desktop GPU support for Mediapipe is something that our clients have been asking about for many months. Thanks for your hard work on this fantastic ML tool set.
