### ISSUE TITLE
can not crop well in my video

### ISSUE THREAD

**Issue by ai1361720220000** [google/mediapipe#586]
Hi,
I run the project to test my own video, but it can not achieve the cropped video i wanted. The original video is simple scene that only one actress dance in front of the camera. However, in my cropped video, that person does not exist.
my video is in 
https://drive.google.com/file/d/1DC1AyOyExcXXUGs1osmBRO6r8OcRz9eQ/view?usp=sharing
The running code 
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \ --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \ --input_side_packets=input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/absolute/path/to/save/the/output/video/file,aspect_ratio=9:16`
thank you

**Comment by ndimension** [comment]
Hi, thank you for filing this issue with us.  We agree that the autoflip result is not ideal on the video sample you provided.  We have internally done some testing and have discovered the low-quality result is due to a false positive face detection on your video. 

We have updated the internal version of autoflip to use a new face detection model.  We hope to release this update next week that will improve the autoflip results on your video.  Thank you for your patients.

**Comment by sgowroji** [comment]
We are closing this issue as we see the above resolution answered your query. Thanks!
