### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by adwaitsharma** [google/mediapipe#59]
Sorry if I missed it, but can someone help me to find the documentation for setting up the 3D hand-tracking? More specifically, I am interested in joint coordinates.

**Comment by jiuqiant** [comment]
You can build the 3D hand tracking Android demo by 
```
bazel build -c opt --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu
```

[The hand landmark graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_landmark_gpu.pbtxt) provides a "hand_landmarks" stream, which contains the coordinates. However, since we don't have desktop demos yet, you probably only can get them on Android and iOS.
