### ISSUE TITLE
Realtime FPS with PacketCloner

### ISSUE THREAD

**Issue by mb-14** [google/mediapipe#598]
I'm trying to run the hair segmentation graph  (`hair_segmentation_desktop_live.pbtxt`) with my webcamera as the video source. To maintain the FPS rate of my input video stream (~30FPS), I've added a `PacketClonerCalculator` node at the end of my graph:
![Screenshot from 2020-04-10 08-17-31](https://user-images.githubusercontent.com/1137632/78957761-dcef2580-7b03-11ea-8cbb-2d6b803f44c6.png)

The `PacketClonerCalculator` node should emit frames at the rate of the tick input stream but actually has a rate of **5 FPS** . Is there something wrong with my graph or my understanding of the packet cloner calculator?

**Comment by eknight7** [comment]
How did you measure the rate of the `PacketClonerCalculator`?

**Comment by mb-14** [comment]
I added a very simple FPS caluclator in the main loop:
```
    bool grab_frames = true;
    long frameCounter = 0;
    std::time_t timeBegin = std::time(0);
    int tick = 0;
    while (grab_frames)
    {
        cv::Mat camera_frame_raw;
        capture >> camera_frame_raw;
       
        // process graph
      
       frameCounter++;
        std::time_t timeNow = std::time(0) - timeBegin;
        if (timeNow - tick >= 1)
        {
            tick++;
            LOG(INFO) << "FPS: " << frameCounter;
            frameCounter = 0;
        }
    }
```

This same program gives a an output of ~28FPS when using the face detection graph

**Comment by hadon** [comment]
This low FPS may result from how PacketClonerCalculator works with "DefaultInputStreamHandler".  PacketClonerCalculator will clone the most recent "image" from RecolorCalculator, but it will not produce those "image" packet clones until it is sure that another "image" will not arrive with a timestamp preceding the "tick" packet timestamp.  As a result, the several "tick" packets may queue up at the PacketClonerCalculator waiting to see what the next "image" timestamp will be.  Then when the next "image" packet arrives from RecolorCalculator, PacketClonerCalculator will release the clones all at once.  The result will look like one batch of clones "image" packets with different timestamps released at the end of each a low FPS interval.  

One workaround for this problem is to configure the PacketClonerCalculator with an "ImmediateInputStreamHandler".  This allows the "tick" packets to be processed and produce their clone "image" packets before the next "image" timestamp is revealed.  

A more elegant solution for this problem is to arrange the RecolorCalculator deliver frequent indications about the range of possible timestamps for the next "image" packet.  This can be arranged using the calculator attributes "SetTimestampOffset" and "SetProcessTimestamps", and it must be arranged for every calculator upstream of the RecolorCalculator.  In future MediaPipe releases, MediaPipe maintainers will try to ensure that every calculator is able to propagate this "timestamp bounds" information.
