### ISSUE TITLE
Is it possible that we can train our own model and do the inference with tensorflow?

### ISSUE THREAD

**Issue by yw2278** [google/mediapipe#6]

**Comment by mgyong** [comment]
@yw2278 We provide the Android mobile & desktop examples (graph, calculators & TF/TFlite models) as guidance. You can modify the Android mobile example and change the preprocessing and post-processing calculators as well as the model when you do inference

**Comment by mgyong** [comment]
@yw2278 Closing out issue for now since there has not been any further replies

**Comment by chenyuZha** [comment]
@mgyong  Thanks for your replay. Recently I would like to replace model ``ssdlite_object_detection.tflite`` by my custom model, which is training with ``ssd_mobilenetv2_coco``. To get the file tflite, I use the script ``export_ssdlite_graph.py`` and set the flag ``add_postprocessing_op=False`` as mentioned in the tutorial. I also replace the ``label_map_path``,``num class``,``num_boxes``(for my case is 1917 instead of 2034)  in the ``object_detection_android_gpu.pbtxt``. Besides, I replace the models and file txt in objectdetctiongpu/BUILD file. Then I build and install apk, no errors during the process. But when I run inference with my mobile, no bounding boxes were detected.. Did I miss something ? Thanks for your help!

**Comment by CharlesShang** [comment]
Hi @chenyuZha, how is your custom training going now? 
I find this repo is awesome to learn a full-stack DL+Android workflow. I want to dig more about it. 
could you post more recent results/works for your custom training? 
thanks
