### ISSUE TITLE
Why does the timestamp not equal to TimeNow ?

### ISSUE THREAD

**Issue by cjf445144540** [google/mediapipe#600]
There is one thing confuse me when I run the objectdetection3d.
ToUnixMicros(clock_->TimeNow()) = some thing like 1586515301123634.
But cc->InputTimestamp().Microseconds() = some thing like 56607865952.
What is the relationship between them ?

**Comment by hadon** [comment]
When Mediapipe runs over video frames, often the video "presentation timestamp" is used as the Mediapipe Packet timestamp.  The video presentation timestamp is often defined as "microseconds since the start of the video", while ToUnixMicros(clock_->TimeNow()) is "microseconds since the unix epoch".  

For interactive applications, with input from a camera or microphone, Mediapipe normally uses "microseconds since the unix epoch" for each Mediapipe Packet timestamp.  In this case, cc->InputTimestamp().Microseconds() will be close to ToUnixMicros(clock_->TimeNow()).
