### ISSUE TITLE
Ios - multihand tracker crashes after dealloc

### ISSUE THREAD

**Issue by SvyatHoly** [google/mediapipe#651]
Hi! I compiled framework for ios with multihand tracker. And faced an issue that app crashes after deallocation

Dealloc method is the same as in examples:

```
- (void)dealloc {
         NSLog(@"dealloc");
 self.mediapipeGraph.delegate = nil;
 [self.mediapipeGraph cancel];
 // Ignore errors since we're cleaning up.
 [self.mediapipeGraph closeAllInputStreamsWithError:nil];
 [self.mediapipeGraph waitUntilDoneWithError:nil];
}
```

After it's called i see this two logs:

```
2020-04-25 09:57:09.310544+0300 ARMA[1791:443685] dealloc
2020-04-25 09:57:09.310772+0300 ARMA[1791:443685] *** Assertion failure in -[MPPGraph waitUntilDoneWithError:](), mediapipe/objc/MPPGraph.mm:273
```

And then 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x100000001)`

**Comment by NikolayChirkov** [comment]
Hi @SvyatHoly, please provide the build instructions you used.

**Comment by kolibaba-ams** [comment]
Hi! This line `*** Assertion failure in -[MPPGraph waitUntilDoneWithError:](), mediapipe/objc/MPPGraph.mm:273` means that this code ` [self.mediapipeGraph waitUntilDoneWithError:nil];` was called on the main thread.
And based on the comments in code, it should be avoided.
`waitUntilDoneWithError: should not be called on the main thread`
But it also means that the code in all the iOS examples is wrong because the UIViewController's dealloc method is always called on main thread.

But my problem is that even if I call ` [self.mediapipeGraph waitUntilDoneWithError:nil];`  on a background thread it doesn't works properly and I get the following error:
`mediapipe/-1 (16): EXC_BAD_ACCESS (code=1, address=0x10000000001)`
`#1	0x0000000100bef488 in mediapipe::GPUData::~GPUData() at mediapipe/mediapipe/calculators/tflite/tflite_converter_calculator.cc:81`

Can please someone tell me how to stop and destroy the graph properly?

**Comment by mcclanahoochie** [comment]
I believe this issue may be resolved in the next release. 
It has to do with needing to add a private namespace around the declaration of GPUData in both tflite_converter_calculator.cc and tflite_inference_calculator.cc
You can try adding that, or wait until the next push, likely early next week.

**Comment by kolibaba-ams** [comment]
@mcclanahoochie, thank you very much for the feedback!

**Comment by kulich-ua** [comment]
Hi @Ankish , at the moment I don't work actively with mediapipe. But I found a change in source code I made back then related to this issue. I hope it will help.

Here is the diff:

```diff
diff --git a/mediapipe/calculators/tflite/tflite_converter_calculator.cc b/mediapipe/calculators/tflite/tflite_converter_calculator.cc
index 8f3af1c..dad2f0b 100644
--- a/mediapipe/calculators/tflite/tflite_converter_calculator.cc
+++ b/mediapipe/calculators/tflite/tflite_converter_calculator.cc
@@ -78,11 +78,13 @@ struct GPUData {
   GlProgram program;
 };
 #elif defined(MEDIAPIPE_IOS)
+namespace { // fix based on:https://github.com/google/mediapipe/issues/651
 struct GPUData {
   int elements = 1;
   GpuTensor buffer;
   id<MTLComputePipelineState> pipeline_state;
 };
+}
 #endif
 
 // Calculator for normalizing and converting an ImageFrame or Matrix
```

**Comment by BTLDXX-x** [comment]
hello, i met this issue also.

i did [this](https://github.com/google/mediapipe/issues/2730#issuecomment-954690529), but still failed.

thanks for your help!
