### ISSUE TITLE
model inference time

### ISSUE THREAD

**Issue by xuchengggg** [google/mediapipe#657]
I test the palm_detection.tflite and hand_landmark_3d.tflite model in pixel 2. The inference time of the two models combined is about 100ms. But when I use multi-hand tracking, it is almost real time. In addition, I test the multi-hand tracking with only one hand which means palm detection is always called. How could that be or the inference time I tested is wrong?

**Comment by fanzhanggoogle** [comment]
Combined 100ms is probably reasonable on Pixel 2, but I would say it should be faster than that.
When you say `real-time`, it might be hard to visually tell the difference, e.g. 100ms is ~10fps which seems to be real-time but actually 3x slower than real real-time.
But you are right: assume you are running multi-hand for 2 hands, then only 1 hand is present meaning it's running both models.
When you test the app, did you build it with `--define 3D=true` to make sure it's running the 3D model? Because the 2D model could 1.5x - 2x faster than the 3D model.

**Comment by xuchengggg** [comment]
Thank you for your reply. Yes, i define 3D=true. I think those two models(palm_detection, hand_landmark_3d) are serial, which means the app should be slower than the inference time of those two models. Is that correct? Or is there a distributed or parallel strategy? And  how can I test the inference time of those two models in app?

**Comment by fanzhanggoogle** [comment]
Yes, you are right when detection is triggered, the two models will run sequentially for that particular timestamp. How did you measure the performance of the model separately? Could you also measure the end to end inference time of case that 1 hand is present in 2 hands tracking? It's a bit hard to tell what's happening without both numbers to compare.

**Comment by xuchengggg** [comment]
I just use android studio to test the model inference time. And two models are tested separately.
```
final long startTime = SystemClock.uptimeMillis();
Trace.beginSection("run");
tfLite.runForMultipleInputsOutputs(inputArray, outputMap);
Trace.endSection();
long costTime = SystemClock.uptimeMillis() - startTime;
Log.i("inference_palm_time", String.value0f(costTime) + "\n*****\n");
```
For multi-hand tracking app, i just use bazel to build the apk. So i have no idea how to test that end to end inferrence time.

**Comment by fanzhanggoogle** [comment]
You can definitely try [ TFLite's benchmarking tool](https://www.tensorflow.org/lite/performance/benchmarks).
