### ISSUE TITLE
Models on Tenserflow hub are not updated and different results for  Facemesh web demo vs android apk.

### ISSUE THREAD

**Issue by ankitcsr** [google/mediapipe#740]
Tf.js models on the TensorFlow hub are not updated. Web demo is pulling models form [Tenserflow hub](https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1) and it seems to be outdated, also there is a big difference is the accuracy (in web demo even for little head roll it's giving inaccurate result but on android and it's working fine) of facemesh on [android](https://github.com/google/mediapipe/blob/master/mediapipe/docs/face_mesh_mobile_gpu.md#android) vs facemesh on the [web](https://storage.googleapis.com/tfjs-models/demos/facemesh/index.html), are they using different models or its due to different versions?

**Comment by mgyong** [comment]
@ankitcsr The [hand model hosted on MediaPipe](https://github.com/google/mediapipe/blob/master/mediapipe/models/README.md#hand-detection-and-tracking) is the latest. Yes the tf.js model is older. 

The face mesh model on MediaPipe and tfjs model as of 1 Jun 2020 is the same version. The difference in accuracy between the web demo and the android version for face mesh is likely not because of the model but the pre-processing and post-processing implementations (tj.js example is a reimplementation of the MediaPipe C++ pipeline). The accuracy differences for the hand examples for the web and android is due to the newer  hand version available for mobile and not the web

**Comment by ankitcsr** [comment]
Any plan for applying the same pre/post-processing step in tf.js as of media pipe C++ pipeline, can we convert c++ code to WebAssembly and use it?
