### ISSUE TITLE
Custom Models based on hand detection/tracking

### ISSUE THREAD

**Issue by anilsrik** [google/mediapipe#754]
This is not an issue but more a documentation help.
I'm trying to train a custom gesture recognition model and use that along with hand detection model to annotate video. 

I'm having trouble getting thru the mediasequence example to extract data for custom training. Here is what I plan to do, use hand detection model and extract just the red box data as an input for training custom model.  Is it possible to do this if so please share any helpful documentation. 

Here is what I plan to do, since the only relevant data is from the detected red box, I plan to train a model based of this and create a tflite model to generate appropriate gesture annotation.

**Comment by bryanseybold** [comment]
I'm not fully sure what questions you're asking here because there seem to be multiple parts. I'll try and help regarding mediasequence, but others may need to chime in for parts related to the models.

Can you tell me a little more about your input data and how you're trying to transform it? I have a guess, but I'm sure I'm wrong about something. My guess:
You have videos as input.
You want to run a detection model on every frame of the input videos.
Given the output of the detector, you want to crop out that portion of the video frame.
You want to store the crops in the SequenceExample.

There are two steps to get this working:
Creating the metadata MediaSequence examples listing where the videos and timespans to process.
Running the MediaPipe graph to extract the data.

Is that everything you want to do? What steps am I missing? Which step are you stuck at?

(If you also have labels for what the videos should be, the kinetics_dataset.py example should be a good place to start for setting up the metadata for the sequence example. After that, you may need to create a new MediaPipe graph to run the hand detector and do the cropping, but we'll talk through that step when we get there.)

**Comment by anilsrik** [comment]
Thank you for responding. The input data is a video dataset with labels and I want to run detection model across frames. thanks for pointing me to the kinetics_dataset.py example. This is helpful.
