### ISSUE TITLE
Cannot setup android through setup_android_sdk_and_ndk.sh in Windows Docker environment

### ISSUE THREAD

**Issue by RicoSuaveGuapo** [google/mediapipe#76]
Installing Mediapipe with Docker in Windows 10 pro 1903 host, 
trying to set up Android SDK and NDK without Android Studio.

In the container, in the meidapipe root, typing
```
 bash ./setup_android_sdk_and_ndk.sh ~Sdk ~/Android/Ndk r18b
```
I get the following error message:
```
./setup_android_sdk_and_ndk.sh: line 22: $'\r': command not found
: invalid optionsdk_and_ndk.sh: line 23: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./setup_android_sdk_and_ndk.sh: line 24: $'\r': command not found
./setup_android_sdk_and_ndk.sh: line 27: syntax error near unexpected token `elif'
./setup_android_sdk_and_ndk.sh: line 27: `elif [ "$(expr substr $(uname -s) ' 5)" == "Linux" ]; then
```
suspect that the format of ``setup_android_sdk_and_ndk.sh`` is not correct.

**Comment by jiuqiant** [comment]
I am able to install Android SDK and NDK in a Docker container on Ubuntu. 

To do that, I modify the Dockerfile to
- Install OpenJDK8 instead of OpenJDK11
- Install curl

I am going to update the Dockerfile soon to reflect those changes. I apologize that our current Dockerfile is very basic and the container is mainly for reproducing the desktop examples. 

We haven't supported and tested MediaPipe on Windows. All contributions are welcome.

**Comment by RicoSuaveGuapo** [comment]
Thanks for the reply and testing, I may change to WSL as you suggested for now. If the update is complete, please notify us~
