### ISSUE TITLE
Issue with pixel coordinates

### ISSUE THREAD

**Issue by iverdr17** [google/mediapipe#774]
Hi,
From corner 1 to 2 in the fig the coordinate x is varying from .2 to .8 only instead of 0-1 like the y coordinate. Is there any possible way to rectify this. And I wanted to know whether this will have any impact on calculating vertical and horizontal angle of view using sensor width, sensor height or will it change.
https://user-images.githubusercontent.com/23277899/83963095-ea851980-a8c0-11ea-8d23-66d5f762ea2c.jpeg

**Comment by chuoling** [comment]
This is because the aspect ratio of the camera preview frames (returned from the OS camera API) can be different from that of the [display SurfaceView](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L69). In those cases, to not distort the camera frames, MediaPipe fits the output to the display along one axis while having it cropped (on both sides) along the other axis.

You should be able to derive such cropping from the aspect ratio of the display view ([width and height here](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L170)) and that of the camera preview frames (essentially from [this size](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L170)).

Note that to minimize such cropping in general the app should request preview frames (using the OS camera API) with the closest aspect ratio to the display view. However, our Android example app currently doesn't always do that, partly due to some incorrect setup and partly the version of the CameraX we use. We are working on a fix.

**Comment by iverdr17** [comment]
So. I am getting 1080*1969 as viewSize, 720*720 as displaySize. How will the cropping occur in this case. I mean could you explain me how to derive from this.

**Comment by chuoling** [comment]
In this case, the output image from the graph is 720x720, which is rendered onto the 1080x1969 view with the left and right side cropped. You could consider the rendering process as the output image first being enlarged to 1969x1969 and with its center aligned with the 1080x1969 view. As a result, the left and right (1969-1080)/2 ~= 444 pixels are cropped. Consequently, about 444/1080 ~= 23% of the image is cropped horizontally from each side, aligned with your 0.2~0.8 observation.

**Comment by iverdr17** [comment]
Hi @chuoling,
Basically I am trying to get the real world coordinates from the normalized pixel coordinates by incorporating mediapipe along with a depth sensor. Post my calculations using camera matrix I am getting values of maximum field of view in x and y(when seen in portrait view x is along horizontal and y is vertical and the origin is at the top left corner) directions which agrees with the normal front camera for a particalar depth. But the view which the mediapipe is showing appears to be be zoomed in both the directions. As mentioned by you earlier one of the side is cropped I agree to that which is x in our case but even y appears to be zoomed though it gives me values from 0-1. For example with my calculations at a depth of 30cm the X and Y(max field of view) is 30cm and 38.88cm which is correct when tested with the normal selfie camera. But when in mediapipe the values X and Y is arround 14-15cm and 26-27cm. Could you please get me through this.

**Comment by tyrmullen** [comment]
This was an issue we ran into when trying to determine the click locations on-image from click-locations on screen, since we needed to map touch presses (sometimes with coordinates on a constrained range like [.2, .8]) back to normalized image coordinates [0, 1].  Perhaps the solution there can help you with your calculations?

See the "recordClick" function in mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/MainActivity.java for more details.

**Comment by sgowroji** [comment]
Hi @iverdr17, We are closing this issue now, We assume you are resolved from the above comments. Feel free to reach us if you still have any further queries on the above. Thanks!
