### ISSUE TITLE
New hand_landmark.tflite model worse than previous

### ISSUE THREAD

**Issue by tuvolon** [google/mediapipe#806]
The new hand_landmark.tflite model is considerably worse than the previous one.
On my PC, i3-8100K, the old hand_landmark.tflite gives 8-9 FPS, whereas the current one only gives 6 FPS.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for testing the model performance! I wonder for previous model, are you comparing with the hand_landmark_3d or hand_landmark?
We expect the new model (3D) to be faster than previous 3D version, but slightly slower than the 2D version.

**Comment by tuvolon** [comment]
Hi,
I was comparing 3D to 2D. Is there an updated 2D version, or it now only 2D?

**Comment by fanzhanggoogle** [comment]
We don't have a standalone 2D version anymore since the 3D has comparable quality on x,y. Sorry that it's slower than the previous 2D version and causes trouble. We have speed up the model internally (2.5x faster on GPU, 3x faster on CPU) with minimum quality change, but haven't determined the plan to release it yet. We'll consider prioritize releasing the light model.

**Comment by tuvolon** [comment]
OK. Is the speed up in the 2D model or the 3D model?

**Comment by fanzhanggoogle** [comment]
Hi, have you tried our latest model? the 3D model should be ~2.5x faster than before.
