### ISSUE TITLE
how to run two graph at the same time?

### ISSUE THREAD

**Issue by mapleyuan** [google/mediapipe#830]
hi guys,
I would run the face mesh and the hand detect graphs at the same time, but I can not find the official ways to do it. Could you provides it? thx

**Comment by chuoling** [comment]
Running two graphs at the same time, although feasible, is not recommended because the two graphs then run independently and is not best for resource utilization and scheduling efficiency etc.

Instead, we recommend merging them into a single graph. For instance, you can merge the [face mesh graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/face_mesh_mobile.pbtxt) and [hand detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_detection_mobile.pbtxt) by having them as two branches in a graph, sharing the same input stream "input_video". Note that you may need to rename some streams in one branch to avoid duplicate stream names.

**Comment by mapleyuan** [comment]
hi @chuoling , thanks for your reply. I have two question.
1. I need to run two graphs but don't need to run two graphs continuously, I just need one graph and stop another graph some time. So the mediapipe can't do it?
2.what's your "two branches in a graph" meaning? could you give some examples?
thanks a lot.

**Comment by chuoling** [comment]
You could follow the class comment in [RoundRobinDemuxCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/round_robin_demux_calculator.cc) as an example. The RoundRobinDemuxCalculator there dispatches the input to one of the two branches, each branch consisting of a single "SlowCalculator" node in this case. 

What you'll need to do is to make a new calculator (e.g., DemuxCalculator) that selects one of the two outputs using another input stream for selection (similar to the [MuxCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/mux_calculator.cc) but with the roles of input and output switched). You'll also need to replace the two "SlowCalculator" nodes with, in your case, the [face mesh graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/face_mesh_mobile.pbtxt) and [hand detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_detection_mobile.pbtxt).

**Comment by sgowroji** [comment]
As we see the Main query was answered  in the above [comment](https://github.com/google/mediapipe/issues/830#issuecomment-655225656). We are closing this issue now.
