### ISSUE TITLE
Resetting CalculatorGraph internal state?

### ISSUE THREAD

**Issue by RaphiePS** [google/mediapipe#832]
Hello MediaPipe team! I'm running the FaceMesh model on desktop, processing a bunch of short video clips.

If I understand correctly, the FaceMesh model keeps some internal state in between frames: a list of regions of interest from the previous frame, which it uses to speed up inference on the next frame.

This feature is fantastic, but I want to reset the ROI state (and any other state it's keeping around) each time I process a new video clip, so the first frame of video clip `N` is not affected by the results from the last frame of clip `N - 1`.

I can't find any obvious way to reset internal state, and when I try calling `StartRun()` multiple times on the same graph, I get an `SetExecutor must be called only once for the executor` error.

The only solution I've found is to completely re-initialize the graph for each video clip, but this is quite an expensive operation and I'm wondering if there's a cleaner or more idiomatic way.

Thanks so much!

**Comment by chuoling** [comment]
There is no existing mechanism to reset a graph other than closing the graph and creating a new one. This is because not only the graph can hold memory (e.g., via packets), internal implementation of the nodes (calculators) and sometimes even the ML models can also have memory. 

That being said, MediaPipe Face Mesh (and several other MediaPipe solutions) does come with an [static_image_mode](https://google.github.io/mediapipe/solutions/face_mesh.html#static_image_mode) option that configures the graph in a way to not use information from the previous image (essentially by setting this [bool_value](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/modules/face_landmark/face_landmark_front_cpu.pbtxt#L55) to false). However, I understand this is different from your use case where you want to use that information until starting a new video.

**Comment by sgowroji** [comment]
Hi @RaphiePS, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/832#issuecomment-877988977). Thanks!
