### ISSUE TITLE
Build error when building gpu target on Win10

### ISSUE THREAD

**Issue by zengvain** [google/mediapipe#836]
When I build a GPU target of face detection as follows:
bazel build -c opt --action_env PYTHON_BIN_PATH="C:\\Users\\Leon\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe" mediapipe/examples/desktop/face_detection:face_detection_gpu

It displays error:
.\mediapipe/gpu/gl_base.h(57): fatal error C1083: cannot open include file: “EGL/egl.h”: No such file or directory
Target //mediapipe/examples/desktop/face_detection:face_detection_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.747s, Critical Path: 1.51s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

The cpu target is ok.

So is there any solution to build gpu target on windows 10? And how to implement it?

**Comment by jiuqiant** [comment]
MediaPipe doesn't support GPU on native Windows yet.

In order to support this, we need to refactor [the core gl_context component](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/gl_context.h#L18) to replace `pthread` on Windows. We don't have a plan to do this in the near future due to the other high priority tasks.

**Comment by Thaina** [comment]
@jiuqiant Now 2025 are there any consideration on windows gpu?
