### ISSUE TITLE
Autoflip cannot rapidly switch between two faces in scene. 

### ISSUE THREAD

**Issue by darkrider87** [google/mediapipe#844]
I was attempting to run autoflip on a scene like the one below which rapidly switches between two faces to autocrop to portrait 9:16. 
https://www.youtube.com/watch?v=VlSkPA60ujQ

However, I can't seem to tweak the advanced settings to get it to switch to between the two faces. It ends up slow panning or ending up somewhere in the middle of the scene with no faces. 
Setting FACE_CORE_LANDMARKS is_required: TRUE will solve the issue but results in padding. 

Is there anyway to get the scene_camera_motion_analyzer to rapidly switch between two faces without padding or forcing it to a different aspect ratio. Would like it to crop it as 9:16. 

Thanks!

**Comment by ndimension** [comment]
Hi @darkrider87,

Thank you for sharing this issue with us.  I did some testing on your example video and I believe the root problem is autoflip is not detecting shot boundaries in this dark pub scene.  Specifically, when the camera switches focus back and forth (between Jesse Eisenberg and Rooney Mara) you may notice the scenes color and brightness are very similar and the ShotBoundaryDetection calculator fails to tell a shot change occurred.

I'd recommend adjusting your ShotBoundaryCalculatorOptions to be a bit more aggressive for this clip.  The specific settings I used were:
```
window_size: 3
min_shot_measure: 0.95
min_motion_with_shot_measure: 0.0001
```
Also, because this scene is pretty focused on faces, I disabled object detection into the SignalFusingCalculator (you could also just reduce their weights closer to zero):
```
  input_stream: "shot_change"
  input_stream: "face_regions"
#  input_stream: "object_regions"
  output_stream: "salient_regions"
```
With those changes, the results look much improved:
https://photos.app.goo.gl/SVe4baL5jwRf5gDP7

In the long term, we hope to develop more reliable ways to detect shot boundaries across all scene types. In the mean time, let me know if I can provide anymore guidance on this video.

-Nathan Frey

**Comment by darkrider87** [comment]
This is awesome! Thanks a lot.

**Comment by darkrider87** [comment]
Our team did come across a few more issues. Would it be possible to set up a quick call to discuss this in more detail? You can find me on LinkedIn...
http://linkedin.com/in/muskan-srivastava

**Comment by ndimension** [comment]
Hi @darkrider87, we would now recommend using a new shot detection calculator based on the TransNetV2 deep model.  You can find that calculator and example code here:

https://github.com/googleinterns/intern-for-design/tree/master/autoflip_integrated_calculators

-Nathan Frey
