### ISSUE TITLE
Unable to build Android AAR

### ISSUE THREAD

**Issue by Tectu** [google/mediapipe#881]
# Environment
- Ubuntu 20.04 64-bit
- Bazel 3.2.0
- GCC 9.3.0
- OpenJDK 1.8.0_252
- `ANDROID_SDK`, `ANDROID_NDK_HOME` and `JAVA_HOME` are set correctly
- MediaPipe current `master` branch (commit `67bd8a2bf04072b853142e7739466dea218ae007`)

# Noteworthy
- I am able to build & run the Android examples that ship with MediaPipe successfully.

# Issue
I have a custom library/application based on the MediaPipe hand tracking example. I'm able to build this application either as a standalone executable or as a shared library on an Ubuntu machine and run it on the desktop without problems. Next my goal is to build an Android AAR to get the library functionality into an Android project. To do so, I've added the `mediapipe_aar` section to the bazel `BUILD` file as instructed by [the official documentation](https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-build-with-bazel-in-command-line):
```
package(default_visibility = [
    "//visibility:public",
])

cc_binary(
    name = "libmediapipe.so",
    srcs = ["hand_tracker.cpp",
            "hand_tracker.hpp", 
            "hand_tracker_impl.cpp", 
            "hand_tracker_impl.hpp", 
            "landmarks.hpp"],
    deps = [
        "@mediapipe//mediapipe/framework:calculator_framework",
        "@mediapipe//mediapipe/framework/formats:image_frame",
        "@mediapipe//mediapipe/framework/formats:image_frame_opencv",
        "@mediapipe//mediapipe/framework/formats:landmark_cc_proto",
        "@mediapipe//mediapipe/framework/port:commandlineflags",
        "@mediapipe//mediapipe/framework/port:file_helpers",
        "@mediapipe//mediapipe/framework/port:opencv_highgui",
        "@mediapipe//mediapipe/framework/port:opencv_imgproc",
        "@mediapipe//mediapipe/framework/port:opencv_video",
        "@mediapipe//mediapipe/framework/port:parse_text_proto",
        "@mediapipe//mediapipe/framework/port:status",
        "@mediapipe//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",
    ],
    linkshared=True,
)

cc_binary(
    name = "libmediapipe_gpu.so",
    srcs = ["hand_tracker.cpp",
            "hand_tracker.hpp", 
            "hand_tracker_impl.cpp", 
            "hand_tracker_impl.hpp", 
            "landmarks.hpp"],
    local_defines = ["MEDIAPIPE_GPU"],
    deps = [
        "@mediapipe//mediapipe/framework:calculator_framework",
        "@mediapipe//mediapipe/framework/formats:image_frame",
        "@mediapipe//mediapipe/framework/formats:image_frame_opencv",
        "@mediapipe//mediapipe/framework/formats:landmark_cc_proto",
        "@mediapipe//mediapipe/framework/port:file_helpers",
        "@mediapipe//mediapipe/framework/port:opencv_highgui",
        "@mediapipe//mediapipe/framework/port:opencv_imgproc",
        "@mediapipe//mediapipe/framework/port:opencv_video",
        "@mediapipe//mediapipe/framework/port:parse_text_proto",
        "@mediapipe//mediapipe/framework/port:status",
        "@mediapipe//mediapipe/gpu:gl_calculator_helper",
        "@mediapipe//mediapipe/gpu:gpu_buffer",
        "@mediapipe//mediapipe/gpu:gpu_shared_data_internal",
        "@mediapipe//mediapipe/graphs/hand_tracking:mobile_calculators",
    ],
    linkshared=True,
)

load("@mediapipe//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_hand_tracking_aar",
    calculators = ["@mediapipe//mediapipe/graphs/hand_tracking:mobile_calculators"],
)
```
However, the build process yields a visibility error upon trying to compile to an Android AAR:
```
joel@joel-ubuntu:~/projects/mediapipe_latest/my_custom_project/library$ bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a :mp_hand_tracking_aar
ERROR: /home/joel/projects/mediapipe_latest/my_custom_project/library/BUILD:74:14: in genrule rule //my_custom_project/library:rasterization_proto_proto_java_src_generator: target '//mediapipe/framework/formats/annotation:protos_src' is not visible from target '//my_custom_project/library:rasterization_proto_proto_java_src_generator'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//my_custom_project/library:mp_hand_tracking_aar' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.170s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
joel@joel-ubuntu:~/projects/mediapipe_latest/my_custom_project/library$ 
``` 
What exactly causes this issue and what's the intended way to make this build work?

**Comment by jiuqiant** [comment]
We don't plan to expose the proto source code because that's some implementation details we may change later. So, we set [the protos_src file_group](https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/annotation/BUILD#L40) to be only visible within the MediaPipe repo. Moreover, MediaPipe AAR rule was designed for packaging existing MediaPipe solutions such as face detection, hand tracking, and etc. So, we was expecting the users to use the aar rule within the MediaPipe repo.

For your case, you can change https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/annotation/BUILD#L43 to be `visibility = ["//visibility:public"],` to solve this issue.

**Comment by brianm-sra** [comment]
The other thing you can try is to move the lines at the end of that BUILD file
(load and mediapipe_aar) from the existing mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD file
to a **brand new (otherwise empty) file** 
mediapipe/examples/android/src/java/com/google/mediapipe/apps/**aar_example**/BUILD

as mentioned in the documentation at
https://google.github.io/mediapipe/getting_started/android_archive_library.html

and then build with

bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/**aar_example**:mp_hand_tracking_aar
