### ISSUE TITLE
use tflite_convert error

### ISSUE THREAD

**Issue by teafff** [google/mediapipe#917]
hi！
I have a problem when i try to convert the object detection saved model.

my tensorflow version is 2.2.0

I refer to this document：
https://www.tensorflow.org/lite/convert/cmdline#usage

my command:
tflite_convert \
--saved_model_dir=mediapipe/models/object_detection_saved_model \
--output_file=mediapipe/models/object_detection_saved_model/model.tflite

output:
  %236 = "tf.TensorArrayGatherV3"(%handle_213, %235, %223#5) {device = "", element_shape = #tf.shape<>} : (tensor<2x!tf.resource<tensor<*xi32>>>, tensor<?xi32>, tensor<f32>) -> tensor<?xi32>
  %237 = "tfl.cast"(%236) : (tensor<?xi32>) -> tensor<?xf32>
  "std.return"(%226, %233, %229, %237, %198, %203) : (tensor<?x100x4xf32>, tensor<?x100xf32>, tensor<?x100xf32>, tensor<?xf32>, tensor<?x?x4xf32>, tensor<?x?x91xf32>) -> ()
}) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "image_tensor", outputs = "detection_boxes,detection_classes,detection_scores,num_detections,raw_detection_boxes,raw_detection_scores"}, type = (tensor<?x?x?x3x!tf.quint8>) -> (tensor<?x100x4xf32>, tensor<?x100xf32>, tensor<?x100xf32>, tensor<?xf32>, tensor<?x?x4xf32>, tensor<?x?x91xf32>)} : () -> ()

I don't know how to solve it.
Can you give me a code to convert tflite model?
Please!

**Comment by eknight7** [comment]
Can you please copy the conversion command from https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_saved_model/README.md and try?

**Comment by teafff** [comment]
> Can you please copy the conversion command from https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_saved_model/README.md and try?

the tensorflow version > 2.0 , it doesn't support --graph_def_file

so i will set a low version to try it.

**Comment by teafff** [comment]
Thank you！
I success to convert it~

**Comment by architjaiswal** [comment]
I am still confused on how to convert the model such that it gets the same 4 outputs I was initially giving. I also saved the model using model.export_model(model.export_model(model_name=model_out, quantization_config=quantization_config)

Can someone tell me how to convert the trained model to obtain the 4 output (locations, classes, scores, detections)?

I was trying to run inference in C++ using the following code but it failed due to output mismatch:
`    
// https://www.tensorflow.org/lite/models/object_detection/overview#starter_model

TfLiteTensor *output_locations =  interpreter->tensor(interpreter->outputs()[0]);
TfLiteTensor *output_classes = interpreter->tensor(interpreter->outputs()[1]);
TfLiteTensor *output_scores =  interpreter->tensor(interpreter->outputs()[2]);
TfLiteTensor *output_detections =  interpreter->tensor(interpreter->outputs()[3]);
`
