### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by JsBlueCat** [google/mediapipe#970]
In file included from mediapipe/examples/desktop/demo_run_graph_main_gpu.cc:26:
./mediapipe/framework/port/opencv_video_inc.h:88:10: fatal error: opencv2/optflow.hpp: No such file or directory
   88 | #include <opencv2/optflow.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/face_detection:face_detection_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by jiuqiant** [comment]
Seems like you use opencv4 and hit this issue. I barely remember that opencv4 removed opencv2/optflow.hpp after 4.1.0. 
Since MediaPipe recommends using opencv 3 for all platforms, we don't pay too much attention to supporting opencv 4 anymore.

You probably can rewrite line 88 of /mediapipe/framework/port/opencv_video_inc.h as the following to see if that solves the problem. Otherwise, switching back to opencv3 should just work.

```
#include <opencv2/video/tracking.hpp>
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by Parth-Shah-Tool-Kit** [comment]
Hi I am facing a similar issue can you pls help..
In one program..

I have these includes..

#include "opencv2\face\facerec.hpp"				
#include "opencv2\face.hpp"						
#include "opencv2\optflow.hpp"

and these are said as not found.. can you pls help.. i have installed opencv3.1.0 so that i dont face this but am still having this issue.

thank you..

**Comment by matanster** [comment]
Just a quick note about OpenCV version support, coming from the above ticket that refers here. 

![image](https://user-images.githubusercontent.com/4996067/142925689-95dd792a-1fb2-46fe-bd11-a68a5c8d5958.png)

If OpenCV 3 is the endorsed version, then the OpenCV version recommendations here must mean something else than what they may seem to mean to my small mind.

**Comment by gx1989mao** [comment]
> Hi, sorry to bother you. But after I commented line 89 and replaced it with `#include <opencv2/video/tracking.hpp>` , and build hand_tracking_gpu, it says
> 
> ```
> ./mediapipe/framework/port/opencv_video_inc.h:94:10: error: 'optflow' has not been declared
>    94 |   return optflow::createOptFlow_DualTVL1();
> ```
> 
> I'm on Ubuntu 20.04 and using opencv 4.1.2 (I've also tried opencv 4.2 and opencv 3.4, and none worked)
> 
> Should I build opencv 3.2 from source code?
> 
> Thank you :)

one should common those lines in ...../mediapipe/mediapipe/framework/port/opencv_video_inc.h:
`
// namespace cv {
// inline Ptr<DenseOpticalFlow> createOptFlow_DualTVL1() {
//   return optflow::createOptFlow_DualTVL1();
// }
// }  // namespace cv`

**Comment by 199ChenNuo** [comment]
> 

thanks!

**Comment by 19920716** [comment]
Very good, solved the problem of switching to Opencv4。

**Comment by james365** [comment]
install libopencv-contrib-dev library can solve this problem
