### ISSUE TITLE
//external:android/crosstool depends on @androidndk//:default_crosstool in repository @androidndk which failed to fetch. no such package '@androidndk//': Could not read RELEASE.TXT in Android NDK: /home/nd/Android/Sdk/ndk/RELEASE.TXT (No such file or directory) 

### ISSUE THREAD

**Issue by JimReno** [google/mediapipe#98]
I followed the instruction to set up Android Studio with MediaPipe. When I import the build file with bazel, error occured.
![图片](https://user-images.githubusercontent.com/28293145/64619143-25cae880-d414-11e9-81c7-b82855def9b3.png)

I opened the ndk folder but can't find `RELEASE.TXT`. But I did installed ndk in the Adroid Studio. Please give me some hint about this problem. Thanks anyway. :)

**Comment by jiuqiant** [comment]
Can you report the following system information to help us understand your issue:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04)
- Bazel version
- Android Studio, NDK, SDK versions (if issue is related to building in mobile dev environment
- Your environment variables: $ANDROID_HOME  and $ANDROID_NDK_HOME 

Moreover, do you install NDK by yourself? If it's installed by Android Studio, it's likely to be put into `Android/Sdk/ndk-bundle/` instead of `Android/Sdk/ndk/`. Have you modified WORKSAPCE file?

**Comment by JimReno** [comment]
Thanks for reply. Sure. The system information are listed below:
- OS Platform and Distribution : Linux Ubuntu 16.04
- Bazel version:0.29.0
- Android Studio SDK version: 29  NDK version: 20.0.5594570
-  environment variables: $ANDROID_HOME:/home/nd/Android/Sdk  $ANDROID_NDK_HOME:/home/nd/Android/Sdk/ndk.
![图片](https://user-images.githubusercontent.com/28293145/64662872-8261ee00-d47c-11e9-801c-4703078c2aa6.png)

I follow the instruction and installed the NDK in Android Studio. And I didn't modified the workspace file.
![图片](https://user-images.githubusercontent.com/28293145/64662930-b76e4080-d47c-11e9-8b7c-04c1aca01f32.png)

**Comment by jiuqiant** [comment]
I can reproduce this issue with Android Studio 3.5 on Linux now.
The latest Android Studio  (3.5) puts the ndk libraries into `Android/Sdk/ndk/<version number>` instead of `Android/Sdk/ndk-bundle/ `. For your case, the `$ANDROID_NDK_HOME` should be `/home/nd/Android/Sdk/ndk/20.0.5594570`.

We will update install.md soon to mention this change. Thanks.

**Comment by jiuqiant** [comment]
The instruction of setting up MediaPipe with Android Studio is updated. See [install.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-studio-with-mediapipe).

**Comment by dizcza** [comment]
> The instruction of setting up MediaPipe with Android Studio is updated. See [install.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-studio-with-mediapipe).

Dead link.

I must note that the official documentation at https://developers.google.com/mediapipe/framework/getting_started/android still does not note the correct way to determine the ANDROID_NDK_HOME. Had I not read this conversation, I wouldn't have known what to do either.
