### ISSUE TITLE
How to distinguish between landmarks data?

### ISSUE THREAD

**Issue by tonywang531** [google/mediapipe#981]
I have modified the source so it outputs landmarks. Then I directed the outputs to a txt file. This is a video that is about 10 seconds long. This is just an example, I believe any other videos would output the similar results as well. As you can see, it is almost impossible to tell which is which with the current data only.

My question is in what order are the landmarks being saved? Also how to distinguish between frames?
[hand1.txt](https://github.com/google/mediapipe/files/5026237/hand1.txt)

**Comment by eknight7** [comment]
There should be a timestamp associated with the landmarks packet that you can use to identify landmarks per frame.

**Comment by tonywang531** [comment]
> There should be a timestamp associated with the landmarks packet that you can use to identify landmarks per frame.

Thanks for the pointer. I hardly know any c++ so I am still trying hard to figure out how the structure is laid out. I have found where the message is being defined, which is in landmark.proto. So I added another element below. I will try to trace down how the values are being defined tomorrow.

```
message NormalizedLandmark {
  optional float x = 1;
  optional float y = 2;
  optional float z = 3;
  optional float visibility = 4;
  optional float timestamp = 5;
}
```

**Comment by eknight7** [comment]
You don't need to add the timestamp field to the proto.
Please see information about MediaPipe packets here: https://google.github.io/mediapipe/framework_concepts/packets.html and how calculators process packets here: https://google.github.io/mediapipe/framework_concepts/calculators.html

Since the graph is outputting packets of information at every timestamp, and it is the packet that contains the landmark data, you can output the packet timestamp along with the landmark data. For example, in the [desktop C++ code](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L111-L129) for outputting timestamps and landmark data, you can access the timestamp using:

```
multi_hand_landmarks_packet.Timestamp();
```

**Comment by tonywang531** [comment]
> You don't need to add the timestamp field to the proto.
> Please see information about MediaPipe packets here: https://google.github.io/mediapipe/framework_concepts/packets.html and how calculators process packets here: https://google.github.io/mediapipe/framework_concepts/calculators.html
> 
> Since the graph is outputting packets of information at every timestamp, and it is the packet that contains the landmark data, you can output the packet timestamp along with the landmark data. For example, in the [desktop C++ code](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L111-L129) for outputting timestamps and landmark data, you can access the timestamp using:
> 
> ```
> multi_hand_landmarks_packet.Timestamp();
> ```

Thanks again for the clear explanation. I have got it working by adding Timestamp() to the LOG. Any chance you will be doing this for the gpu multihand as well? If not feel free to close the issue.

**Comment by eknight7** [comment]
The code for landmarks and timestamp should be the same for multihand gpu.

**Comment by xxiMiaxx** [comment]
> There should be a timestamp associated with the landmarks packet that you can use to identify landmarks per frame.

can you elaborate on how to get the frame along with its landmarks
